package-lock.json
package.json

COMPASS-3804: Pass app registry to few() in all cases

---

package-lock.json
package.json

Update host and port when select connection.

fix: update host and port when select connection

---

package-lock.json
package.json

Handles a number of recent issues:
COMPASS-3805
COMPASS-3709
COMPASS-3879
COMPASS-3886
COMPASS-3843
COMPASS-3584

Adding missing stage operators and fixing grammar

---

README.md

Updated README with UserVoice link

Added link to UserVoice forum

---

package-lock.json
package.json

mongodb-extended-json needed to support both new and old binary code in from the BSON library.

COMPASS-3836: Handle Binary properly in Query History

---

package-lock.json
package.json

- COMPASS-3868: Handle long namespaces in collection header.
- COMPASS-3819: Refresh documents on CMD+R
- COMPASS-3834: Refresh indexes on CMD+R

Compass Iteration "Newt" Bug Fixes, Part I

---

package-lock.json
package.json

* Bumped compass-connect ver to 5.0.6

bump compass-connect ver to 5.0.6

---

package-lock.json
package.json
src/main/window-manager.js

COMPASS-3811: Zoom works with CMD/CTRL+=

---

package-lock.json
package.json

COMPASS-3909: Fixing stage operator snippets
COMPASS-3903: Fix double scrollbar in table view.

1 20 fixes

---

package-lock.json
package.json

Bumped compass-connect ver to 5.2.5

Bumped compass-connect ver to 5.2.5

---

package-lock.json
package.json

Refreshes data after import is either partially finished or fully finished. Based off work in [compass-import-export#10](https://github.com/mongodb-js/compass-import-export/pull/10)
Adds button states to import modal based on state of import completion. Based off work in [compass-imoport-export#13](https://github.com/mongodb-js/compass-import-export/pull/13)

COMPASS-3948: import-export@4.1.5, refresh data after import

---

package-lock.json
package.json

Fix explain plan layout problem, when d3 is hidden behind a sidebar and node lines are missing.

COMPASS-3885 Explain plan layout

---

package-lock.json
package.json

Updates to favourites from @alenakhineika's work in [compass-connect#75](https://github.com/mongodb-js/compass-connect/pull/75).

COMPASS-3946: compass-connect@5.2.5: updates to bugs in favourites

---

package-lock.json
package.json

Do not update a tree if it is an initial state.

COMPASS-3885 do not update a tree if it is an initial state

---

package-lock.json
package.json

Bump @mongodb-js/compass-schema to 2.0.3 to fix COMPASS-3928

COMPASS-3928: Schema Analysis leaves UI artifacts on completion

---

package-lock.json
package.json

Switch to a new version of the schema validation plugin that replaces `active-tab-changed` event with `subtab-changed` event to continue sending metrics.

COMPASS-3945 subtab changed event

---

package-lock.json
package.json

Use a new version of agg pipeline with a confirmation modal that appears before creating a new pipeline.

COMPASS-3940 is new pipeline confirm

---

package-lock.json
package.json

Fixes wrong link for wildcard indexes doc.

COMPASS-3952: Bumped version of compass-indexes

---

package-lock.json
package.json

Compass 3979: Now the + button to create database is centered

---

package-lock.json
src/app/migrations/1.20.0-beta.0.js
src/app/migrations/connection-disk.js
src/app/migrations/connection-indexeddb.js
src/main/window-manager.js

- Simplify migration to not use async module, ampersand callbacks only.
- Don't load from secure storage, no need to access it twice.

COMPASS-3967: Fixing segfault error on migrations

---

package-lock.json
package.json

Use a new version of the crud plugin with JSON doc highlighting and better comment block handling.

COMPASS-3983 JSON mode improvements

---

.evergreen.yml
package-lock.json

Small refreshes found in the course of fixing COMPASS-3996 that were causing the Windows build boxes to fail (warnings about dependency statuses, out of date package-lock cache tree, etc.)

chore(evergreen): small tweaks to keep windows up to date

---

package-lock.json
package.json

Bump @mongodb-js/compass-metrics to version 2.1.0

COMPASS-3968: AWS/GCP/Azure telemetry

---

src/app/index.html

In the intercom widget, we need to add a module to point users to UserVoice for feedback. The image is hosted on webassets.mongodb.com so we need to whitelist it in the Content Security Policy.

COMPASS-4061: Whitelisted webassets.mongodb.com

---

src/app/index.html

Whitelist ip-ranges.amazonaws.com

---

package-lock.json
package.json

Use `compass-crud@8.2.0` that shows a different message when a collection is empty and when a query has no results.

COMPASS-4037: Zero state when query has no results

---

package-lock.json
package.json

Handle password while swithcing views:
When switching to the connection form view do not display edit/hide buttons
When a connection string is not editable when switching to the connection form view, use the real password to populate the input, do not use ***** value form the safe connection string.

COMPASS-4150: handle password when switching views

---

package-lock.json
package.json

Instead of showing a blank screen on a maxTimeMS related timeout, shows the banner and tells the user to increase the value.

COMPASS-4145: Show banner on maxTimeMS timeout

---

package-lock.json
package.json

(wasn't handling `Date` properly in example @mmarcon had on COMPASS-4164)
From mongodb-js/compass-import-export#120
> - chore: Upgrade to javascript-stringify@2 b5bdc7b Fixes #56
> - fix(import): Preview table values always strings 29148cd Fixes COMPASS-4164
> - fix(import): Hard limit reading fs for preview to first 20kb so preview always shows as fast as possible.
> 
> ![Screenshot 2020-03-09 12 18 44](https://user-images.githubusercontent.com/23074/76234690-6f985e00-6200-11ea-86a7-e902b2d0510f.png)
As a reminder, because we're now using a streaming backend, the total number of documents is likely to be off, especially for very large imports. So, 100% progress but still running is expected behavior. Devtools will log not only the input options that user chose but the estimator details …

fix(import): COMPASS-4164: Preview table values always strings

---

package-lock.json
package.json

Adds a custom drag layer to the agg pipeline builder.

COMPASS-4152: Add custom drag layer to agg

---

package-lock.json
package.json

https://github.com/mongodb-js/compass-import-export/commit/8390bcbc03154e79b8fff134157eaff97e729626

fix(import): Transforms to Double retain precision

---

package-lock.json
package.json

COMPASS-4205 I found some export edge cases where the resulting JSON would be malformed so I fixed and added a bunch of tests.
https://github.com/mongodb-js/compass-import-export/pull/128

fix(export): COMPASS-4205: fixup JSON output formatter

---

package-lock.json
package.json

Adds all the new agg pipeline stage operators and expressions, and updates autocomplete filtering to be fully env aware and not just version aware.

4.4 features

---

package-lock.json
package.json

See https://github.com/mongodb-js/compass-import-export/pull/137

fix(import): COMPASS-4025: Make CSV casting work

---

README.md

The README.md lists outdated `node` and `npm` version requirements - this PR updates it to the values found in `package.json`.
I was trying to get this project to run locally and installed node 10 according to the `README.md` only to find out that `npm install` is failing because my node version is outdated.
none
none

update node and npm requirements in README.md

---

package-lock.json
package.json

Fixes the table view interactions. Pinned right columns now always visible.

COMPASS-4243: Fixing table view interactions

---

src/app/index.js
src/app/loading/loading.js
src/main/window-manager.js

This catches all global errors in Compass and then does an IPC broadcast of the error and stack trace to all windows. This is so errors caught in the main Compass window while loading can have the messages logged in the console of the loading screen.

Handle all errors globally and broadcast

---

.evergreen.yml
package-lock.json
package.json

Notarize Compass

---

package-lock.json
package.json

This removes the hardened runtime required for notarisation and trying to sign all resources.

Pin electron-installer-codesign at 0.3.0

---

package-lock.json
package.json

Display import preview only for csv files, and do not display it for json files.
Related issues:
https://jira.mongodb.org/browse/COMPASS-4298
https://jira.mongodb.org/browse/COMPASS-4248

COMPASS-4298: Display import preview only for csv files

---

package-lock.json
package.json

Display import preview only for csv files, and do not display it for json files.
Related issues:
https://jira.mongodb.org/browse/COMPASS-4298
https://jira.mongodb.org/browse/COMPASS-4248

COMPASS-4298: Merge import fix to 1.22

---

package-lock.json
package.json

Fix reset not working in query bar

COMPASS-4245: fix reset not working in query bar

---

package-lock.json
package.json

https://jira.mongodb.org/browse/COMPASS-4346
This pulls in the reference tag fixes from connection-model.

Bump compass connect to version 5.4.12

---

.evergreen.yml
package-lock.json
package.json
src/app/index.js
src/app/network-optin/index.jade
src/app/network-optin/index.js
src/app/tour/features.js
src/app/tour/index.js
src/main/application.js
src/setup-hadron-distribution.js

How do I test it? Should I change the documentation somewhere?

COMPASS-4131: remove compass community

---

package.json

Remove shell from readonly

---

package-lock.json
package.json

Bump compass metrics to 3.0.8 to bring in compass-shell events

---

package-lock.json
package.json

https://github.com/mongodb-js/data-service/pull/242

Bump data service to 16.9.1 for datalake telemetry fix

---

package-lock.json
package.json

COMPASS-4389
Pulls in resizable query bar plugin

COMPASS-4389: Update compass-query-bar dependency

---

package-lock.json
package.json

https://github.com/mongodb-js/compass-import-export/pull/192
https://github.com/mongodb-js/compass-aggregations/pull/279

Update compass-aggregations to 7.1.6 and compass-import-export to 5.1.20

---

package-lock.json
package.json

https://github.com/mongodb-js/mongosh/commit/9a0125f2a5fea54dca3166496574c8157baad0ad
This pulls in a number of new mongosh functionality and compass-shell ux improvements.

Bump mongosh compass-shell to 0.2.1

---

package-lock.json
package.json

https://github.com/mongodb-js/mongosh/commit/4e188a4336bb5f57bc2431811e54b90bf83b1cdf

Bump mongosh compass-shell to 0.2.2

---

.evergreen.yml
package-lock.json
package.json
src/app/index.js
src/app/network-optin/index.jade
src/app/network-optin/index.js
src/app/tour/features.js
src/app/tour/index.js
src/main/application.js
src/setup-hadron-distribution.js

Pulls in:
- Bumped compass-shell
- Removing shell from readonly
- Removal of compass-community

Cherry pick for ga 1.22.0

---

package-lock.json
package.json

COMPASS-4401 - Prevent drop in readonly mode

---

package-lock.json
package.json

→ https://github.com/mongodb-js/compass-query-bar/pull/157

COMPASS-4296 Do not let map filter override other filters

---

package-lock.json
package.json

→ https://github.com/mongodb-js/compass-indexes/pull/130

COMPASS-4371 - Account for missing 'ns' field

---

package-lock.json
package.json

→ https://github.com/mongodb-js/compass-import-export/pull/205

COMPASS-4426 - Work around bson package bugs

---

package-lock.json
package.json

Pulls in https://github.com/mongodb-js/compass-collection/pull/129

Bump compass-collection to 2.1.0 to bring in ux improvements

---

package-lock.json
package.json

Bumps `hadron-build` to a version that doesn't leak env var with debug logging.

COMPASS-4437: Fix leak of env vars in compass build

---

package-lock.json
package.json

MONGOSH-237 - Support print()

---

package-lock.json
package.json

https://github.com/mongodb-js/compass-crud/pull/301

COMPASS-4427 - Allow non-editable fields to be deleted

---

package-lock.json
package.json

COMPASS-4125 - Clean up d3-tip nodes after component unmount

---

package-lock.json
package.json

COMPASS-4434 - Preserve components for individual tabs

---

src/main/application.js

Removed duplicate menu setup code that might be a left-over from a previous merge. The removed function is the same as still located in [Line 122](https://github.com/mongodb-js/compass/blob/master/src/main/application.js#L122)

Remove duplicate menu setup code

---

package-lock.json
package.json

COMPASS-4487: update mongodb@3.6.3, fixes: COMPASS-4487, COMPASS-4203, COMPASS-4324

---

package.json
release/commands.js
release/git.js
release/github.js
release/index.spec.js
release/publish.js
release/publish.spec.js
release/ux.js

Fixes some issues I've noticed while using the scripts for the first time: 
- `npm run release checkout` logs the push command if the branch is not existing.
- `npm run release wait` also outputs the evergreen link for the build
- Fix press any key not waiting
- Waiting for a draft release to be created is impossible without login: we just log the general releases url and wait for the release to be published.
- Cleaner logging of manual actions.
- Output links for final verifications.

build: fix release scripts

---

package-lock.json
package.json

Pulls in https://github.com/mongodb-js/compass-crud/pull/309

fix(compass-crud): field row number styling

---

package-lock.json
package.json

COMPASS-4499
Pulls in https://github.com/mongodb-js/compass-aggregations/pull/309

feat(COMPASS-4499): Add tooltip to stage operator select with stage description

---

package-lock.json
package.json

Brings in:
- https://github.com/mongodb-js/compass-crud/pull/314
- https://github.com/mongodb-js/compass-crud/pull/313

fix(compass-crud): do not explicitly sort by _id COMPASS-4435

---

.github/PULL_REQUEST_TEMPLATE.md
release/changelog.js
release/commands.js
release/index.spec.js

chore: generate release notes with the new commit format

---

release/changelog.js
release/commands.js
release/github.js
release/publish.js
release/publish.spec.js
release/ux.js

Updates the release helper scripts to also automatically generate the changelog directly.

chore: improve release scripts

---

package-lock.json
package.json

See https://github.com/mongodb-js/compass-crud/pull/315 and corresponding release https://github.com/mongodb-js/compass-crud/releases/tag/v10.1.3.

fix(compass-crud): ensure add field in table view works as expected COMPASS-4455, COMPASS-4340

---

package-lock.json
package.json

fix(data-service): parseBuildInfo causing Blank UI with ADL COMPASS-4522

---

.npmrc
package-lock.json
package.json

feat(compass-shell): bump shell version to 0.6.1 COMPASS-4531

---

package-lock.json
package.json

Reverts mongodb-js/compass#2080

Revert "fix(deps): pin antlr4 dependency at 4.7.2"

---

package-lock.json
package.json

Pulls in https://github.com/mongodb-js/connection-model/pull/339

fix(connection-model): do not default directConnection to true with srv records

---

package-lock.json
package.json

Replaces the loading spinner with a new one designed in house.

chore(loading): replace loading spinner COMPASS-4532 (#241)

---

package-lock.json
package.json

fix: use native node js functions to track osName COMPASS-4510

---

package-lock.json
package.json

COMPASS-4202
pulls in https://github.com/mongodb-js/compass-connect/pull/251

fix: Hide progress bar on invalid connection string connect attempt COMPASS-4202

---

package-lock.json
package.json

COMPASS-4488 
Pulls in https://github.com/mongodb-js/compass-status/pull/7

fix: remove 700ms delay on each loading indicator COMPASS-4488 

---

package-lock.json
package.json

→ https://github.com/mongodb-js/compass-import-export/pull/235
→ https://github.com/mongodb-js/compass-import-export/pull/234

fix(compass-import-export): bump compass-import-export to 5.2.5

---

package-lock.json
package.json

COMPASS-4393
Pulls in https://github.com/mongodb-js/compass-connect/pull/257
https://user-images.githubusercontent.com/1791149/106895576-b0d70d80-66f0-11eb-9392-99afd82eb49f.mp4

feat(compass-connect): Enable cancelling connection attempt COMPASS-4393

---

package-lock.json
package.json

COMPASS-4628
pulls in https://github.com/mongodb-js/connection-model/pull/349

fix(connection-model): use correct connection title for connection form connections COMPASS-4628

---

package-lock.json
package.json

feat(compass-query-bar): add placeholders for fields COMPASS-4616

---

package-lock.json
package.json

pulls in https://github.com/mongodb-js/compass-connect/pull/265

chore(compass-connect): debounce showing connecting modal when connecting

---

package-lock.json
package.json

→ https://github.com/mongodb-js/compass-crud/pull/344

fix(compass-crud): fix empty ‘insert document’ view COMPASS-4511

---

package-lock.json
package.json

COMPASS-4636
Pulls in https://github.com/mongodb-js/compass-sidebar/pull/158

fix: editing favorite connectionModel prop misnaming COMPASS-4636

---

package-lock.json
package.json

https://github.com/mongodb-js/compass-connect/pull/267

fix(compass-connect): ensure styles are properly namespaced and not impacting other plugins

---

package-lock.json
package.json

COMPASS-4489
Pulls in https://github.com/mongodb-js/compass-indexes/pull/156

feat(compass-indexes): Add ability to create text indexes COMPASS-4489

---

package-lock.json
package.json

→ https://github.com/mongodb-js/compass-explain-plan/pull/186

feat(compass-explain-plan): support SBE explain plan COMPASS-4606

---

package-lock.json
package.json

COMPASS-4653
Pulls in https://github.com/mongodb-js/compass-connect/pull/268

chore(compass-connect): Sort favorites by name alphabetic, recents by most recently at the top COMPASS-4653

---

package-lock.json
package.json

→ https://github.com/mongodb-js/compass-explain-plan/pull/187

fix(compass-explain-plan): update to 4.2.2

---

package-lock.json
package.json

bump compass-schema

---

package-lock.json
package.json

COMPASS-4413
Pulls in https://github.com/mongodb-js/compass-aggregations/pull/338

feat(compass-aggregations): Add handling and showing of updating view source errors COMPASS-4413

---

package-lock.json
package.json

COMPASS-4509
Pulls in https://github.com/mongodb-js/compass-crud/pull/346

fix(compass-crud): Show updated value for updated fields in table view COMPASS-4509

---

package-lock.json
package.json

Fixes COMPASS-4661
|Before|After|
|---|---|
|![Kapture 2021-03-09 at 10 49 41](https://user-images.githubusercontent.com/5036933/110452326-5ea95380-80c5-11eb-97f5-41a4797c536f.gif)|![Kapture 2021-03-09 at 10 56 34](https://user-images.githubusercontent.com/5036933/110453338-5bfb2e00-80c6-11eb-80d8-1e2d3910c041.gif)|

fix: Update compass-schema version to latest COMPASS-4661

---

package-lock.json
package.json

COMPASS-4412
Pulls in https://github.com/mongodb-js/compass-sidebar/pull/162

feat(compass-sidebar): show active state for home, clear database state when home clicked COMPASS-4412

---

package-lock.json
package.json

feat: Update compass-shell to latest with new async runtime COMPASS-4678

---

package-lock.json
package.json

COMPASS-4717
Pulls in https://github.com/mongodb-js/compass-connect/pull/273

feat(compass-connect): add double click to connect to connection COMPASS-4717

---

package-lock.json
package.json

COMPASS-4716
Pulls in https://github.com/mongodb-js/compass-query-bar/pull/195

feat(compass-query-bar): add button for toggle query history COMPASS-4716

---

package-lock.json
package.json

COMPASS-4660
Pulls in https://github.com/mongodb-js/compass-query-history/pull/214

fix(compass-query-history): Make height overflow scroll COMPASS-4660

---

package-lock.json
package.json

See https://github.com/mongodb-js/compass-import-export/pull/243 for details

fix(import-export): Update plugin to latest to include import progress fixes COMPASS-4571

---

package-lock.json
package.json

bump metrics

---

package-lock.json
package.json

COMPASS-2890
Pulls in https://github.com/mongodb-js/compass-aggregations/pull/348

feat(compass-aggregations): Allow resizing aggregation stage editors horizontally, improve drag source COMPASS-2890

---

package-lock.json
package.json

Pulls in https://github.com/mongodb-js/connection-model/pull/361

fix(connection-model): don't cache title and use port as title dep

---

package-lock.json
package.json

fix(compass-connect): update port input when a different connection is selected

---

package-lock.json
package.json

Pulls in https://github.com/mongodb-js/compass-aggregations/pull/361

fix(compass-aggregations): hide empty documents state when loading

---

packages/compass-schema/package-lock.json
packages/compass-schema/package.json
packages/compass-schema/src/components/value-bubble/value-bubble.jsx

fix(compass-schema): fix dependencies and compile

---

packages/compass-aggregations/package-lock.json
packages/compass-app-stores/package-lock.json
packages/compass-collection/package-lock.json
packages/compass-connect/test/renderer/stores/index.spec.js
packages/compass-deployment-awareness/package-lock.json
packages/compass-explain-plan/package-lock.json
packages/compass-home/package-lock.json
packages/compass-import-export/package-lock.json
packages/compass-instance/package-lock.json
packages/compass-metrics/package-lock.json
packages/compass-query-history/package-lock.json
packages/compass-schema-validation/package-lock.json
packages/compass-serverstats/package-lock.json
packages/compass/package-lock.json
packages/hadron-build/package-lock.json

chore: Fix diverged package-lock.json files everywhere

---

packages/compass-indexes/src/components/create-index-field/create-index-field.jsx

Clarifies that if a field to index by isn't in the dropdown, it's also possible to type its name.

ux: more clear index placeholder

---

packages/compass-shell/src/components/compass-shell/compass-shell.jsx
packages/compass-shell/src/stores/store.js

Fixes #2215
https://user-images.githubusercontent.com/5036933/121522605-9346e700-c9f5-11eb-9fff-6660aa7be427.mp4

fix(@mongodb-js/compass-shell): Terminate shell runtime when dataService disconnects or Compass is closed COMPASS-4830

---

packages/compass-shell/package-lock.json
packages/compass-shell/package.json

Doesn't seems to break anything so let's update it

chore(@mongodb-js/compass-shell): Bump mongosh to latest

---

.github/workflows/authors-and-third-party-notices.yaml

chore(monorepo): install missing deps in CI

---

.evergreen.yml

Forgot to change that in the initial workspaces implementation

ci(evergreen): Update npm version and install script in evergreen config

---

.github/workflows/check-test.yaml

Missed those windows failures in #2260

ci(github): Explicitly set bash shell so that env variables are correctly processed in windows environment

---

packages/databases-collections/src/components/collections/collections-table/collection-properties.jsx

style(databases-collections): Add icon for time series collection badges in collections table COMPASS-4842

---

packages/ace-mode/package.json
packages/ace-theme-query/package.json
packages/ace-theme/package.json

Missed `depcheck` in few packages that does not have scripts

chore(monorepo): add depcheck where missing

---

packages/compass-serverstats/src/d3/real-time-mouse-overlay.js

Pulling over from https://github.com/mongodb-js/compass-serverstats/pull/35
https://user-images.githubusercontent.com/1791149/111316294-0c36dc80-865b-11eb-988e-b20d886e8389.mp4

fix(compass-serverstats): prevent mouse cursor jumping COMPASS-4432

---

packages/compass-aggregations/package.json
packages/compass-connect/package.json
packages/compass-shell/package.json
packages/compass-sidebar/package.json

Updates our https://github.com/mongodb/leafygreen-ui deps and aligns them. Some slight style updates, but looked good on a run through.

deps: align leafygreen-ui deps

---

packages/compass-aggregations/src/components/stage-editor-toolbar/stage-operator-select.jsx
packages/compass-aggregations/src/utils/stage.js
packages/compass-aggregations/src/utils/stage.spec.js

Compare versions including prerelease options to display agg stages.

feat: check prerelease server version to display stages COMPASS-4783

---

packages/compass-collection-stats/src/stores/store.js
packages/compass-query-bar/test/renderer/query-changed-store.spec.js

Clean up some names and comments.

refactor: clean up some names and comments COMPASS-4878

---

packages/compass-collection-stats/src/stores/store.js
packages/compass-query-bar/test/renderer/query-changed-store.spec.js

Reverts mongodb-js/compass#2315

Revert "refactor: clean up some names and comments COMPASS-4878"

---

packages/compass-indexes/package.json
packages/compass-schema/package.json
packages/compass-shell/package.json
packages/compass/package.json
packages/connection-model/package.json
packages/data-service/package.json
packages/databases-collections/package.json
packages/index-model/package.json

chore(deps): bump mongosh and driver to latest COMPASS-4893

---

packages/compass-aggregations/package.json
packages/compass-crud/package.json
packages/compass-indexes/package.json
packages/compass-query-history/package.json
packages/compass-schema-validation/package.json
packages/compass/package.json

fix(deps): bump mongodb-extended-json to 1.11.1

---

packages/compass-shell/src/components/shell-header/shell-header.jsx

feat(compass-shell): remove “beta” from mongosh header

---

packages/compass/package.json

fix(deps): bump kerberos to 1.1.6 COMPASS-4961

---

packages/compass-shell/package.json

chore(deps): bump mongosh to 1.0.1 COMPASS-4966

---

packages/compass-indexes/package.json
packages/compass-schema/package.json
packages/compass-shell/package.json
packages/compass/package.json
packages/connection-model/package.json
packages/data-service/package.json
packages/databases-collections/package.json
packages/index-model/package.json

feat: bump driver to 4.1.0/mongosh to 1.0.4 COMPASS-4898

---

.github/workflows/build.yaml

fix(ci): Lock npm version to the one that works as expected

---

packages/data-service/src/connection-options.ts

Adds the new `ConnectionOptions` and related interfaces. No further code changes.
PR is a Draft as it is based on #2395 and targets this branch. Once #2395 is merged this PR can be adapted and opened correctly.

chore(data-service): add ConnectionOptions interfaces COMPASS-5008

---

packages/compass-components/.depcheckrc
packages/compass-components/.eslintrc.js
packages/compass-components/.prettierrc.json
packages/compass-components/package.json
packages/compass-components/src/components/confirmation-modal.spec.tsx
packages/compass-components/src/components/confirmation-modal.tsx
packages/compass-components/src/index.ts
packages/compass-components/test-setup.ts
packages/data-service/package.json
packages/tsconfig-compass/package.json

Updates `compass-components` to latest `prettier` configuration.

chore: align prettier formatting for compass-components

---

scripts/generate-package-lock.js

Immediately fail if the workspace name arg is missing.

chore(scripts): improve error message for gen-package-lock

---

.github/workflows/authors-and-third-party-notices.yaml
.github/workflows/build.yaml
.github/workflows/check-test.yaml

Let's see if it makes things faster

ci(github): Activate npm cache for GitHub actions

---

packages/compass-sidebar/src/components/sidebar-collection/sidebar-collection.jsx

fix(compass-sidebar): update modify source text to modify view COMPASS-4650

---

packages/compass-connect/package.json
packages/compass-connect/src/modules/connection-attempt.js
packages/compass-logging/.depcheckrc
packages/compass-logging/.eslintignore
packages/compass-logging/.eslintrc.js
packages/compass-logging/.mocharc.js
packages/compass-logging/.prettierignore
packages/compass-logging/.prettierrc.json
packages/compass-logging/package.json
packages/compass-logging/src/index.spec.ts
packages/compass-logging/src/index.ts
packages/compass-logging/tsconfig-lint.json
packages/compass-logging/tsconfig.json
packages/compass/package.json
packages/compass/src/main/index.js
packages/compass/src/main/logging.js
packages/compass/src/main/window-manager.js
packages/data-service/package.json
packages/data-service/src/legacy-connect.ts
packages/hadron-ipc/index.d.ts
packages/hadron-ipc/index.js

Set up main-process logging, add a `@mongodb-js/compass-logging`
package and use it to log basic information about connection attempts.
Example result:
```js
$ zcat ~/.mongodb/compass/6132154a13a16a1815e33f5a_log.gz
{"t":{"$date":"2021-09-03T12:30:02.381Z"},"s":"I","c":"COMPASS-MAIN","id":1001000001,"ctx":"logging","msg":"Starting logging","attr":{"version":"0.0.0-dev.0","platform":"linux","arch":"x64"}}
{"t":{"$date":"2021-09-03T12:30:09.134Z"},"s":"I","c":"COMPASS-CONNECT-UI","id":1001000004,"ctx":"Connection UI","msg":"Initiating connection attempt"}
{"t":{"$date":"2021-09-03T12:30:09.136Z"},"s":"I","c":"COMPASS-DS-CONNECT","id":1001000009,"ctx":"Connect","msg":"Initiating connection","attr":{"url":"mongodb+srv://<credentials>@cluster0.ucdwm.mongodb.net/admin?authSource=admin&replicaSet …
```

feat(compass-logging): add initial log infrastructure COMPASS-5031

---

packages/compass-e2e-tests/helpers/compass.js
packages/compass-e2e-tests/tests/logging.test.js
packages/compass-logging/package.json
packages/compass/package.json
packages/compass/src/app/index.js
packages/compass/src/main/logging.js

Also make a minor adjustment to the `compass:error:fatal`
handler to handle the case where `error` is not set on the
`ErrorEvent` (this happens e.g. when an asynchronous exception
comes from the built-in inspect because that is considered
a cross-context operation).

chore(compass-e2e-tests): add logging tests COMPASS-5038

---

packages/compass-e2e-tests/tests/logging.test.js
packages/compass-logging/src/index.spec.ts
packages/compass-logging/src/index.ts
packages/data-service/src/data-service.ts
packages/data-service/src/legacy-connection-model.ts
packages/data-service/src/types.ts

Fill out everything that we definitely want to log regarding
connectivity.
Also:
- Fix a bug in the compass-logging package where log statements
from different components could have ended up being printed
out of order
- Make sure that the dataService `_collectionNames` helper
uses `nameOnly: true`
- Use `import type` in a few places where it is appropiate

feat: fill out connectivity logging COMPASS-5032

---

packages/compass-shell/src/components/info-modal/info-modal.jsx

Fix wording Ctrl+L to Ctrl/Cmd+L in shortcut table doc of mongosh

---

configs/eslint-config-compass/index.js
packages/data-service/package.json
packages/data-service/test/connectivity.spec.ts

Add connectivity tests

---

packages/compass-query-bar/src/components/query-bar/query-bar.jsx

Will be nice to remove the lint `react/sort-comp` I reckon.

chore(compass-query-bar): fix check react/sort-comp issue

---

packages/compass/webpack.config.js

Spotted by @Anemy. I somehow messed up the source path to the main.js so security storage was not set up correctly 🤦

fix(mongodb-compass): Fix Compass app main import path

---

packages/compass/src/main/index.js

fix: set electron app version explicitly like app name

---

packages/compass-connect/src/stores/index.js
packages/compass-e2e-tests/tests/logging.test.js
packages/compass/src/main/logging.js
packages/data-service/src/data-service.spec.ts
packages/data-service/src/data-service.ts
packages/data-service/src/instance-detail-helper.ts
packages/data-service/src/legacy-connect.ts
packages/data-service/src/types.ts

chore(logging): expand log info with TSE-requested features COMPASS-5072

---

packages/compass-e2e-tests/tests/logging.test.js
packages/compass-logging/package.json
packages/compass/package.json
packages/data-service/src/data-service.ts
packages/data-service/src/legacy-connect.spec.ts
packages/data-service/src/legacy-connect.ts

chore(data-service): expand logging for individual calls COMPASS-5104

---

packages/compass-connect/package.json
packages/compass-connect/src/modules/connection-attempt.js
packages/compass-logging/package.json
packages/compass-logging/src/index.ts
packages/compass-shell/package.json
packages/compass-shell/src/stores/store.js
packages/compass/package.json
packages/data-service/src/data-service.ts
packages/data-service/src/legacy-connect.ts
packages/hadron-ipc/lib/renderer.js

chore(compass-logging): also emit debug() calls implicitly COMPASS-5107

---

packages/app-migrations/lib/index.js
packages/app-migrations/package.json
packages/compass-crud/package.json
packages/compass-crud/src/stores/crud-store.js
packages/compass-e2e-tests/tests/logging.test.js
packages/compass-import-export/package.json
packages/compass-import-export/src/modules/export.js
packages/compass-import-export/src/modules/import.js
packages/compass-import-export/src/modules/load-fields.js
packages/compass-logging/package.json
packages/compass-logging/src/index.ts
packages/compass-logging/src/is-electron-renderer.d.ts
packages/compass-schema/package.json
packages/compass-schema/src/modules/schema-analysis.js
packages/compass/package.json
packages/compass/src/app/index.js
packages/data-service/src/data-service.ts

This is the result of auditing `debug()` calls for potentially
interesting log sites. This adds logging for:
- App migrations that we run
- CRUD plugin refreshes
- Import/Export events
- Schema analysis events
- When the main window is displayed

chore: add logging in various places COMPASS-5106

---

packages/data-service/src/data-service.spec.ts
packages/data-service/src/data-service.ts

Only log heartbeat events for significant changes in status.

chore(data-service): reduce heartbeat event noisiness COMPASS-5118

---

packages/compass/src/main/logging.js

chore(compass): include Electron/Node.js versions in log

---

packages/compass-crud/src/components/toolbar.jsx
packages/compass-e2e-tests/tests/smoke.test.js
packages/compass-export-to-language/src/components/export-modal/export-modal.jsx
packages/compass-export-to-language/src/modules/count-aggregation-stages-in-string.js
packages/compass-query-bar/package.json
packages/compass-query-bar/src/modules/utils.js
packages/compass-query-bar/src/stores/query-bar-store.js
packages/compass-query-bar/test/modules/utils.spec.js
packages/compass-query-bar/test/renderer/query-bar-store.spec.js
packages/compass-query-history/package.json
packages/compass-query-history/src/stores/favorite-list-store.js
packages/compass-query-history/src/stores/query-history-store.js
packages/compass-query-history/src/stores/recent-list-store.js

chore: add query tracking COMPASS-5196

---

scripts/logserver.js

This was missed in 5f43eb66694eb0 because the script was
being introduced at the same time.

fix(scripts): fix typo in telemetry log server script

---

packages/compass/src/main/telemetry.ts

Emit one last tracking event for these cases.

chore(compass-main): track telemetry disabling COMPASS-5241

---

packages/compass-crud/src/stores/crud-store.js

chore(compass-crud): track document editing operations COMPASS-5197

---

packages/compass-aggregations/src/modules/create-view/index.js
packages/compass-aggregations/src/modules/index.js
packages/compass-aggregations/src/modules/saved-pipeline.js
packages/compass-aggregations/src/modules/update-view.js

chore(compass-aggregations): add agg builder tracking COMPASS-5195

---

packages/compass-shell/package.json
packages/compass/package.json

chore(mongodb-compass, compass-shell): Update mongosh dependencies

---

packages/collection-model/lib/model.js

This is fix for a regression I accidentally introduced in #2558, before this change instance fetching will always fetch collections with `collectionInfo` if possible, after it we started to fetch collections with `nameOnly` option, and this leads to collection list and collection workspace not having required information from collection options like `view_on` or `readonly` or whether collection is a timeseries or a view. The fix copies over relevant parts of the implementation from #2574 that allows to optionally `fetchInfo` when fetching collection list, with one change that makes `fetchInfo` `true` by default to preserve current GA behavior

fix(collection-model): Try to fetch collection info when listing collections for a database COMPASS-5272

---

packages/data-service/.depcheckrc
packages/data-service/package.json

This should fix kerberos tests that are currently failing in CI

test(data-service): Add kerberos as a dependency so the kerberos tests can run

---

packages/data-service/src/instance-detail-helper.spec.ts
packages/data-service/src/instance-detail-helper.ts
packages/data-service/src/run-command.ts

fix: remove empty db and collection from privileges

---

.evergreen.yml
packages/compass/src/main/telemetry.ts

chore: enable telemetry reporting COMPASS-5225

---

packages/compass/src/main/menu.ts

COMPASS-5290
Fixes https://github.com/mongodb-js/compass/issues/2587 - showing the collection menu when viewing a collection.
Also fixes a couple of the generic menu items which were using the wrong roles/sectors.
https://user-images.githubusercontent.com/1791149/141661722-f13cb1f2-e0dd-4a3d-860c-fb34d28d7426.mp4

fix(menu): Fix collection menu not showing COMPASS-5290

---

packages/compass-components/src/components/cancel-loader.spec.tsx
packages/compass-components/src/components/spin-loader.spec.tsx
packages/compass-components/src/components/spin-loader.tsx
packages/compass-components/src/index.ts
packages/compass-crud/src/components/document-list.jsx
packages/compass-crud/src/components/toolbar.jsx
packages/compass-crud/src/stores/crud-store.js
packages/compass-crud/src/stores/crud-store.spec.js
packages/compass-crud/src/utils/index.js
packages/compass-e2e-tests/tests/smoke.test.js
packages/compass-shell/src/components/shell-header/shell-header.jsx

Quite proud of my little `waitForStates()` test helper.

Don't await the countDocuments() promise COMPASS-5279

---

packages/compass-connect/src/stores/index.js

chore(compass-connect): fix server_version telemetry field

---

scripts/bump-private-dependencies.js

Took a me a second during publish to understand why package-lock update breaks and to remember that we already ran into this before so added a check in the script as a reminder (this npm bug doesn't affect anything but the packages publish process so I'm not locking our engines field to this particular version)

chore(scripts): Throw an error with an explanation when using npm version that will fail during package-lock update

---

packages/connections/src/components/connection-list/connection-list.spec.tsx
packages/connections/src/components/connection-list/connection-list.tsx
packages/connections/src/components/connection-list/connection.tsx

Adds sorts to the connections list.
Favorites alphabetical, most recent connections will be at the top of the list.

feat(connections): Sort favorites alphabetically, sort recents by date

---

packages/hadron-build/commands/upload.js

Both evergreen stable and testing are currently picking up the changes
in the x.x-releases branches and basically racing to release Compass
disregarding if they should. This checks the project against the release
channel to make sure that stable doesn't publish beta releases and vice
versa

chore(hadron-build): Check if evergreen channels are matching the expectation before uploading the release

---

packages/connection-model/package.json
packages/data-service/package.json

chore(deps): bump resolve-mongodb-srv to 1.1.1 COMPASS-5324

---

packages/compass-e2e-tests/package.json
packages/compass-schema/package.json
packages/compass-shell/package.json
packages/compass/package.json
packages/connection-model/package.json
packages/data-service/package.json
packages/index-model/package.json

chore(deps): bump driver to 4.2.1, mongosh to 1.1.6 COMPASS-5340

---

packages/hadron-build/commands/release.js
packages/hadron-build/lib/target.js

See https://jira.mongodb.org/browse/COMPASS-5333

fix: remove expired link from license COMPASS-5333

---

lerna.json
package.json
scripts/.depcheckrc
scripts/.eslintignore
scripts/.eslintrc.js
scripts/.prettierignore
scripts/.prettierrc.json
scripts/bump-private-dependencies.js
scripts/changed.js
scripts/check-logids.js
scripts/create-workspace.js
scripts/depalign.js
scripts/gather-licenses.js
scripts/generate-authors.js
scripts/import-test-connections.js
scripts/logserver.js
scripts/monorepo/where.js
scripts/monorepo/with-progress.js
scripts/package.json
scripts/rebuild.js
scripts/run-in-dir.js
scripts/semver-helpers.js
scripts/workspace-dependencies.js

```
electron scripts/import-test-connections.js beta
``` 
Note also moved scripts to a package to avoid adding too many dependencies to the root

chore: add script to import test connections

---

packages/data-service/src/data-service.ts

This is what was causing this:

don't go looking for a port if we're not going to need it

---

packages/compass-e2e-tests/package.json
packages/compass-schema/package.json
packages/compass-shell/package.json
packages/compass/package.json
packages/connection-model/package.json
packages/data-service/package.json
packages/index-model/package.json

chore(deps): bump mongosh to 1.1.7 and driver to 4.2.2 COMPASS-5308

---

packages/data-service/src/connection-secrets.spec.ts
packages/data-service/src/connection-secrets.ts

chore(data-service): handle proxyPassword in connection-secrets

---

packages/compass-connect/package.json
packages/compass-metrics/package.json
packages/connect-form/package.json
packages/connect-form/src/components/advanced-options-tabs/general/direct-connection-input.tsx
packages/connect-form/src/components/advanced-options-tabs/general/host-input.tsx
packages/connect-form/src/hooks/use-connect-form.ts
packages/connect-form/src/utils/connection-string-schema.ts
packages/connection-model/package.json
packages/connections/package.json
packages/data-service/package.json
packages/data-service/src/connect-mongo-client.ts
packages/data-service/src/connect.spec.ts
packages/data-service/src/connection-secrets.ts
packages/data-service/src/legacy/legacy-connection-model.ts
scripts/package.json

Follow-up to https://github.com/mongodb-js/compass/pull/2647#discussion_r772468351

chore: use typed connection string search params

---

packages/compass-shell/src/components/compass-shell/compass-shell.jsx
packages/compass-shell/src/components/info-modal/info-modal.jsx
packages/compass-shell/src/components/info-modal/info-model.spec.js
packages/compass-shell/src/components/shell-header/shell-header.jsx

feat(shell-toggle): enable keyboard toggle for shell COMPASS-5385

feature(toggle-shell): use keyboard to toggle mongosh COMPASS-5385

---

packages/connect-form/src/components/advanced-options-tabs/ssh-tunnel-tab/ssh-tunnel-tab.tsx

fix(connections): add ssh tab label

fix(connections): add ssh label

---

packages/compass-aggregations/src/constants.js
packages/data-service/src/legacy/legacy-connection-model.ts

Add a link to the official documentation for the $documents stage (5.1 support): https://docs.mongodb.com/v5.1/reference/operator/aggregation/documents/#mongodb-pipeline-pipe.-documents
Change the incorrect `kerberosCanonicalizeHostname` string type to proper boolean: https://github.com/mongodb-js/vscode/blob/VSCODE-312-switch-to-new-data-service-and-model-v2/src/views/webview-app/connection-model/legacy-connection-model.ts#L40

feat: add link and descriptions for the $documents stage COMPASS-5170

---

packages/connect-form/package.json

Remove `compass-components` from prod dependencies, since it exists in peer and fails packages publishing.

fix: remove compass-components from prod dependencies

---

packages/connect-form/src/components/advanced-options-tabs/ssh-tunnel-tab/ssh-tunnel-tab.spec.tsx
packages/connect-form/src/components/advanced-options-tabs/ssh-tunnel-tab/ssh-tunnel-tab.tsx

fix(connections): hide socks tab on ssh form

---

packages/compass-shell/package.json
packages/compass/package.json

For the driver bump in COMPASS-5399

chore(compass-shell): bump mongosh to 1.1.8

---

packages/ssh-tunnel/src/index.spec.ts

chore(ssh-tunnel): remove unused var import
after merging [2676](https://github.com/mongodb-js/compass/pull/2676), the evergreen check failed for the release. this pr fixes that check.

fix(ssh-tunnel): remove unused import

---

packages/compass-crud/src/components/editable-value.jsx
packages/connect-form/src/components/advanced-options-tabs/advanced-tab/advanced-tab.tsx
packages/connect-form/src/components/advanced-options-tabs/ssh-tunnel-tab/ssh-tunnel-identity.tsx
packages/connect-form/src/components/advanced-options-tabs/ssh-tunnel-tab/ssh-tunnel-password.tsx
packages/connect-form/src/components/connection-string-input.tsx
packages/databases-collections/src/components/collection-fields/capped-collection-fields.jsx
packages/databases-collections/src/components/collection-fields/collection-name.jsx
packages/databases-collections/src/components/collection-fields/database-name.jsx
packages/databases-collections/src/components/collection-fields/time-series-fields.jsx

adds `spellCheck=false` to all TextInput and TextArea elements

(chore): adds spellCheck=false to all TextInput and TextArea elements

---

packages/connect-form/package.json
packages/connect-form/src/components/advanced-connection-options.tsx
packages/connect-form/src/components/advanced-options-tabs/advanced-options-tabs.tsx
packages/connect-form/src/components/advanced-options-tabs/tls-ssl-tab/tls-ssl-tab.tsx
packages/connect-form/src/components/connect-form.spec.tsx
packages/connect-form/src/components/connect-form.tsx
packages/connect-form/src/components/connection-string-input.spec.tsx
packages/connect-form/src/components/connection-string-input.tsx
packages/connect-form/src/constants/default-connection.ts
packages/connect-form/src/constants/ssl-tls-options.ts
packages/connect-form/src/hooks/use-connect-form.spec.ts
packages/connect-form/src/hooks/use-connect-form.ts
packages/connect-form/src/utils/connection-ssh-handler.spec.ts
packages/connect-form/src/utils/connection-ssh-handler.ts
packages/connect-form/src/utils/connection-string-schema.spec.ts
packages/connect-form/src/utils/tls-options.spec.ts
packages/connect-form/src/utils/tls-options.ts
packages/connect-form/src/utils/validation.ts

unify connect hooks handlers and integrate warning validations on changes

chore(connect-form): unify connect hooks handlers and integrate validations on change

---

packages/connections/src/components/connection-list/connection-list.spec.tsx
packages/connections/src/components/connection-list/connection-list.tsx
packages/connections/src/components/connections.tsx
packages/connections/src/components/resizeable-sidebar.tsx
packages/connections/src/stores/connections-store.ts

Adds "Clear All" button to recents list

feat(connections): Adds "Clear All" button to recents list COMPASS-5294

---

packages/connect-form/src/utils/validation.spec.ts
packages/connect-form/src/utils/validation.ts

The password is not ignored, and can be used as a workaround by some customer https://jira.mongodb.org/browse/MONGOSH-1059

fix(compass-connect): remove password warning with kerberos

---

packages/connect-form/src/components/connect-form.tsx

align the favorite icon to design

---

packages/connections/src/stores/connections-store.spec.ts

There were some tests missing for the `connection-store` file.
- createNewConnection
- duplicateConnection
- removeConnection
- removeAllRecentsConnections
-

chore(connections): Adds tests for missing functions COMPASS-5433

---

packages/connections/src/modules/telemetry.spec.ts

mini PR for intentionally testing `DEFAULT` as `authMechanism` in telemetry since we are using it rn

test(telemetry): add test for authMechanism=DEFAULT

---

packages/compass-e2e-tests/tests/connection.test.js
packages/compass-home/package.json
packages/compass/package.json
packages/connection-model/package.json
packages/data-service/package.json

~~Debugging PR because I couldn’t get this to fail locally~~
Now with an actual fix! Mostly just https://github.com/mongodb-js/os-dns-native/pull/3

test(e2e): unskip SRV resolution test on Windows

---

packages/connections/src/components/connection-list/connection-list.tsx

style(connect-form): fix clear button color

---

packages/data-service/src/data-service.ts

Fixes an issue reported [in this slack thread](https://mongodb.slack.com/archives/C0U7K0MC3/p1643331979076600). Not sure it's the best approach to take, but at least it guarantees for now that we will not run into weird cases when passing `filter` to the `listCollections` method. Worth noting that we only do this in one place, in `collectionInfo` method, and only filter by collection `name`, so we might also consider doing some special handling for the `collectionInfo` method as falling back to privileges in its context doesn't make sense anyway.

fix(data-service): Do not use privileges as a fallback when listCollections is called with a filter

---

packages/connect-form/src/components/advanced-options-tabs/advanced-tab/url-options-table.spec.tsx
packages/connect-form/src/components/advanced-options-tabs/advanced-tab/url-options-table.tsx

chore(connect-form): fix advanced option warning

---

packages/connections/src/components/connections.tsx

before:
https://user-images.githubusercontent.com/1791149/152229316-122f6bca-9b53-49ae-880f-f23549799f12.mp4
after:
https://user-images.githubusercontent.com/1791149/152229322-52bbc50f-f3da-4923-a1fd-f60690415b5a.mp4

chore(connect-form): reset connection form on connection change

---

packages/connection-model/lib/model.js

Try/catch requiring `os-dns-native` so it won't fail in vscode where native addons are not allowed.

fix(connection-model): try catch os dns native MONGOSH-1080

---

packages/data-service/src/connection-storage.spec.ts
packages/data-service/src/legacy/legacy-connection-model.ts

Allows saving connections that would have been invalid with the old connection model. Still attempts a best effort to preserve backward compatibility as much as possible to allow downgrades.

fix(connection-storage): disable legacy validation on save COMPASS-5476

---

packages/compass-e2e-tests/helpers/commands/set-ace-value.ts

setAceValue's been not pasting on ubuntu and hopefully it is just this.

ctrl-v for ubuntu/windows again

---

packages/compass-e2e-tests/helpers/commands/add-collection.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/collection-indexes-tab.test.ts
packages/compass-indexes/src/components/index-component/index-component.jsx

Just this one basic test for indexes for now. We can probably test out the options and multi-key indexes when we redo that screen.

chore(e2e): Create an index and drop it COMPASS-5469

---

packages/compass-e2e-tests/helpers/commands/get-query-id.ts
packages/compass-e2e-tests/helpers/commands/index.ts
packages/compass-e2e-tests/helpers/commands/run-find-operation.ts
packages/compass-e2e-tests/helpers/commands/run-find.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
packages/compass-explain-plan/src/components/explain-summary/explain-summary.jsx
packages/compass-explain-plan/src/components/summary-stat/summary-stat.jsx
packages/compass-export-to-language/src/components/editor/editor.jsx
packages/compass-export-to-language/src/components/editor/editor.spec.js
packages/compass-export-to-language/src/components/export-form/export-form.jsx

Leaving the ones that test the list/json/table view editors and their context buttons for a separate PR.

chore(e2e): More E2E tests for the Documents tab COMPASS-5469

---

packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/collection-export.test.ts

One of them is currently skipped because exporting to JSON doesn't currently do what you ask for.

chore(e2e) Add E2E tests for export COMPASS-5467

---

packages/compass-import-export/src/modules/export.js
packages/compass-import-export/src/modules/export.spec.js

When exporting to CSV, if the user add a field in the dialog box, it is not included in the output.

bug(compass-import-export): Include manually added fields in CSV output COMPASS-4971

---

packages/compass-aggregations/src/components/pipeline/modals/restore-pipeline-modal.jsx
packages/compass-aggregations/src/components/save-pipeline/save-pipeline-card/save-pipeline-card.jsx
packages/compass-aggregations/src/modules/index.js
packages/compass-aggregations/src/modules/saved-pipeline.js
packages/compass-aggregations/src/utils/pipelineStorage.js
packages/compass-query-history/src/stores/favorite-list-store.js
packages/compass-saved-aggregations-queries/package.json
packages/compass-saved-aggregations-queries/src/components/aggregations-queries-list.tsx
packages/compass-saved-aggregations-queries/src/hooks/use-grid-filters.tsx
packages/compass-saved-aggregations-queries/src/stores/copy-to-clipboard.ts
packages/compass-saved-aggregations-queries/src/stores/delete-item.ts
packages/compass-saved-aggregations-queries/src/stores/open-item.ts

Adds new tracking events and modifies existing ones for the new feature

chore(saved-aggregations-queries): Add tracking for the new feature COMPASS-5508

---

packages/compass-connections/package.json
packages/compass-e2e-tests/package.json
packages/compass-schema/package.json
packages/compass-shell/package.json
packages/compass/package.json
packages/connection-form/package.json
packages/connection-model/package.json
packages/data-service/package.json
packages/index-model/package.json

Driver release notes: https://github.com/mongodb/node-mongodb-native/releases/tag/v4.4.0

chore: Bump driver to latest

---

packages/connection-model/lib/extended-model.js

fix(connections): hide ssl tunnel password in ampersand

fix(connections): hide sslPass in ampersand COMPASS-5239

---

packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-aws.tsx

chore(connect-form): rename label Aws -> AWS

---

packages/connection-model/README.md

chore(packages-publish): change readme to trigger package version

---

packages/compass-sidebar/src/components/sidebar/navigation-items.jsx

Claudia asked to switch the icon to `{}`

chore(saved-aggregations-queries): Change icon for the navigation item

---

.depcheckrc
.evergreen.yml
.github/workflows/authors-and-third-party-notices.yaml
.github/workflows/build.yaml
.github/workflows/check-test.yaml
.github/workflows/connectivity-tests.yaml
package.json
packages/compass-e2e-tests/package.json
packages/compass-e2e-tests/tests/database-collections-tab.test.ts
packages/compass-shell/package.json
packages/compass-shell/src/stores/store.js
packages/compass/.depcheckrc
packages/compass/package.json
packages/connection-model/package.json
packages/data-service/package.json
packages/hadron-build/package.json
scripts/check-leafygreen-dep-usage.js

Currently fails with:
```js
@mongodb-js/compass-shell: ERROR in /home/addaleax/src/compass/node_modules/@mongosh/browser-repl/lib/mongosh-browser-repl.js
@mongodb-js/compass-shell: Module not found: Error: Can't resolve '@leafygreen-ui/code' in '/home/addaleax/src/compass/node_modules/@mongosh/browser-repl/lib'
@mongodb-js/compass-shell:  @ /home/addaleax/src/compass/node_modules/@mongosh/browser-repl/lib/mongosh-browser-repl.js 33:13712-13742
@mongodb-js/compass-shell:  @ ./src/components/compass-shell/compass-shell.jsx
@mongodb-js/compass-shell:  @ ./src/components/compass-shell/index.js
@mongodb-js/compass-shell:  @ ./src/plugin.js
@mongodb-js/compass-shell:  @ ./src/index.js
lerna ERR! npm run bootstrap exited 2 in '@mongodb-js/compass-shell'
```

chore(deps): bump mongosh, kerberos, devtools-connect, etc

---

packages/compass-aggregations/src/components/saving-pipeline-modal/saving-pipeline-modal.jsx
packages/compass-e2e-tests/helpers/commands/do-connect.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/instance-my-queries-tab.test.ts
packages/compass-query-history/src/components/recent/recent-list-item.jsx
packages/compass-saved-aggregations-queries/src/components/aggregations-queries-list.tsx

e2e tests for saved queries and aggregations.

test(compass-saved-aggregations-queries): e2e tests COMPASS-5516

---

packages/compass-aggregations/package.json
packages/compass-query-bar/package.json
packages/compass-schema-validation/package.json

chore: bump ace autocompleter to 0.11.0 COMPASS-5556

---

packages/compass-shell/package.json
packages/compass/package.json

chore: bump mongosh packages

---

packages/compass-e2e-tests/helpers/commands/scroll-to-virtual-item.ts
packages/compass-e2e-tests/helpers/commands/set-connect-form-state.ts

Trying to fix/debug this flake:

attempt at fixing the CI flake and at least get better debug output

---

packages/data-service/package.json

chore(deps): bump devtools-connect to 1.3.0

---

packages/connection-form/src/components/advanced-options-tabs/csfle-tab/kms-provider-fields.tsx

As an editing leftover, this said 'gcp' instead of referring
to the actual KMS provider in question.

fix(connection-form): properly configure CSFLE KMS TLS options

---

packages/data-service/package.json

chore(deps): bump devtools-connect to 1.3.1 COMPASS-5729

---

packages/compass-e2e-tests/tests/logging.test.ts
packages/data-service/src/data-service.spec.ts
packages/data-service/src/data-service.ts
packages/data-service/src/instance-detail-helper.ts

chore(data-service): log csfle connection options COMPASS-5719

---

packages/compass-explain-plan/src/modules/explain.js
packages/data-service/src/data-service.ts

COMPASS-4662
Before:
https://user-images.githubusercontent.com/1791149/163860807-7daadd02-0f85-4caf-8d0d-ccff4c5837ab.mp4
After:
https://user-images.githubusercontent.com/1791149/163860818-ff1c99a1-e24d-49bc-a708-0404b78f563d.mp4
One drive by typing fix in data-service as well (happy to move out if preferred).

fix(compass-explain-plan): Reset error on explain success COMPASS-4662

---

packages/compass-aggregations/src/modules/aggregation.ts
packages/compass-aggregations/src/modules/pipeline.spec.js
packages/compass-aggregations/src/modules/pipeline.ts
packages/compass-e2e-tests/tests/collection-export.test.ts
packages/compass-import-export/src/modules/export.js

This patch adds new telemetry events for running, editing, and exporting aggregations

chore(compass-aggregations): Add new telemetry for aggregations COMPASS-5425 COMPASS-5740

---

.evergreen/functions.yml
.evergreen/tasks.yml
.evergreen/template-yml.js
packages/compass-crud/package.json
packages/compass-e2e-tests/package.json
packages/compass-e2e-tests/tests/instance-sidebar.test.ts
packages/compass-e2e-tests/tests/logging.test.ts
packages/connection-model/package.json
packages/data-service/package.json
packages/index-model/package.json

fix(ci): run e2e tests against enterprise when requested COMPASS-5761

---

packages/databases-collections/src/modules/create-collection/index.js
packages/databases-collections/src/modules/create-database/index.js
packages/databases-collections/src/modules/create-database/index.spec.js

This is otherwise prone to unnecessary divergence between
the two modules.

chore(databases-collections): merge db/coll creation code

---

packages/compass-crud/src/components/insert-csfle-warning-banner.jsx
packages/compass-crud/src/components/insert-document-dialog.jsx
packages/compass-crud/src/stores/crud-store.js
packages/compass-crud/src/stores/crud-store.spec.js
packages/data-service/src/csfle-collection-tracker.spec.ts
packages/data-service/src/csfle-collection-tracker.ts

feat(compass-crud): list encrypted fields in insert dialogue COMPASS-5783

---

packages/compass/package.json
packages/compass/release/branch.spec.js
packages/compass/release/bump.spec.js
packages/compass/release/download-center.spec.js
packages/compass/release/index.spec.js
packages/compass/release/publish.spec.js
packages/compass/release/version.spec.js
packages/compass/release/wait-for-assets.spec.js
packages/compass/scripts/download-akzidenz.js
packages/compass/src/app/tour/index.js
packages/compass/src/main/application.ts
packages/compass/src/main/index.ts
packages/compass/src/main/logging.ts

chore: run linting in compass package

---

configs/webpack-config-compass/src/index.ts
configs/webpack-config-compass/src/loaders.ts
packages/compass-e2e-tests/tests/logging.test.ts
packages/compass/LICENSE
packages/compass/package.json
packages/compass/scripts/download-akzidenz.js
packages/compass/scripts/download-csfle.js
packages/compass/src/deps/csfle/.gitignore
packages/compass/src/main/application.ts
packages/compass/src/main/index.ts
packages/compass/src/main/setup-csfle-library.ts
packages/data-service/src/connect-mongo-client.ts

With a huge thanks to @gribnoysup for showing me how to do this :slightly_smiling_face:

feat: include csfle shared library COMPASS-5618

---

packages/compass-e2e-tests/tests/collection-export.test.ts
packages/compass-home/src/components/home.spec.tsx

chore: unskip home tests for electron env, unskip e2e export test

---

packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.tsx
packages/connection-form/src/components/advanced-options-tabs/csfle-tab/kms-provider-status-indicator.tsx

chore(connection-form): use proper icons for KMS provider list COMPASS-5651

---

packages/compass-connections/src/modules/telemetry.spec.ts
packages/compass-connections/src/modules/telemetry.ts
packages/compass-e2e-tests/tests/logging.test.ts
packages/data-service/src/index.ts
packages/data-service/src/instance-detail-helper.ts
packages/databases-collections/src/modules/create-collection/index.js

chore(telemetry): add fle2 telemetry COMPASS-5658

---

packages/data-service/src/data-service.ts

`command not supported for auto encryption: collStats`

fix(data-service): use non-csfle client for fetching indexes COMPASS-5807

---

packages/connection-form/src/components/advanced-options-tabs/csfle-tab/kms-tls-options.tsx
packages/connection-form/src/components/advanced-options-tabs/tls-ssl-tab/tls-certificate-authority.tsx

This is dependent on not-yet-existent driver support,
so for now disable the checkbox and revisit this later.

chore(connection-form): hide useSystemCA checkbox for KMS TLS COMPASS-5804

---

packages/databases-collections/src/components/collection-fields/collection-fields.jsx
packages/databases-collections/src/components/collection-fields/has-fle2-support.js
packages/databases-collections/src/components/collection-fields/has-fle2-support.spec.js

fix(databases-collections): hide FLE2 options on non-CSFLE connections COMPASS-5812

---

packages/data-service/src/connect-mongo-client.ts

chore(data-service): do not modify options passed to connectMongoClient

---

.evergreen/tasks.in.yml
.evergreen/tasks.yml

I accidentally changed macos to macos_package, forgetting that mac is special.

fix: macos, not macos_package

---

packages/compass-crud/src/components/insert-csfle-warning-banner.jsx

Smol change to fix the React proptype validation warning in dev mode

chore(compass-crud): Fix proptype type

---

packages/compass-collection/src/components/collection-header/fle-badge.tsx
packages/databases-collections-list/src/collections.tsx
packages/databases-collections/src/components/collection-fields/fle2-fields.jsx

chore: replace FLE2 with proper names in UI COMPASS-5626

---

packages/compass-components/src/components/document-list/document.spec.tsx
packages/compass-components/src/components/document-list/element.tsx
packages/compass-crud/src/components/insert-csfle-warning-banner.jsx
packages/compass-crud/src/components/table-view/cell-renderer.jsx
packages/compass-sidebar/src/components/csfle-connection-modal/csfle-connection-modal.jsx
packages/compass-sidebar/src/components/csfle-marker/csfle-marker.jsx
packages/connection-form/src/components/advanced-options-tabs/advanced-options-tabs.tsx
packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.tsx
packages/connection-form/src/components/connect-form.tsx
packages/connection-form/src/utils/validation.ts

Product promises that this is what everyone will call the shared FLE1/FLE2 parts. :slightly_smiling_face:

chore: replace references to CSFLE with “In-Use Encryption” COMPASS-5829

---

packages/compass-shell/package.json
packages/compass/package.json

chore(deps): bump mongosh to 1.4.2 COMPASS-5647

---

packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.tsx

This pr makes
have a pointer cursor on hover.

chore(compass-aggregations): make saved aggregation button hover cursor pointer

---

packages/data-service/src/connection-storage.spec.ts

test(connection-storage): test csfle secrets storage COMPASS-5839

---

packages/connection-form/src/components/connect-form.tsx

chore(connection-form): fix CSS width typo

---

packages/compass/src/app/index.js

fix for handling setTimeout error from driver.  follow [this conversation](https://mongodb.slack.com/archives/G2L10JAV7/p1653901171129569) on slack for more.

fix(compass): handle settimeout error COMPASS-5867

---

packages/compass-aggregations/src/components/pipeline-explain/explain-query-performance.tsx
packages/compass-aggregations/src/components/pipeline-explain/index.tsx

This PR aligns Query Performance Summary items correctly and sets the title of explain modal to Explain Plan.

fix(explain-aggregation): title and alignment

---

.evergreen/functions.yml
.gitignore
packages/compass/LICENSE
packages/compass/package.json
packages/compass/scripts/download-csfle.js
packages/compass/src/main/setup-csfle-library.ts
packages/data-service/src/connect-mongo-client.ts
packages/data-service/src/csfle-collection-tracker.spec.ts

chore: replace references to csfle shared library COMPASS-5859

---

packages/compass-e2e-tests/tests/connection-form.test.ts

chore(compass-e2e-tests): run prettier reformat

---

packages/compass-sidebar/src/components/csfle-connection-modal/csfle-connection-modal.jsx
packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.tsx
packages/databases-collections/src/components/collection-fields/fle2-fields.jsx

Update QE doc links to be properly working permalinks.
We’ll still want to update the links again once there are permalinks
for the In-Use Encryption umbrella docs (left to COMPASS-5925).

chore: update QE docs links COMPASS-5777 COMPASS-5912

---

packages/connection-form/src/components/connect-form.tsx

chore(connection-form): spacing fix for connection string error banner

---

packages/compass-nlp-query/ai-training-input.txt

Add some more training data

---

packages/compass-collection/package.json
packages/compass-connections/package.json
packages/compass-e2e-tests/package.json
packages/connection-form/package.json
packages/connection-model/package.json
packages/data-service/package.json
packages/data-service/src/connection-secrets.spec.ts
packages/data-service/src/connection-secrets.ts
scripts/package.json

fix(connection-storage): allow extract/merge secrets for cosmos connection string COMPASS-5958

---

packages/hadron-document/src/utils.ts
packages/hadron-document/test/document.test.ts

Bug introduced by yours truly in 47e5bfae7ee7b.

fix(hadron-document): handle oddball fp numbers well in `.toEJSON()` COMPASS-5974

---

packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-workspace.module.less

Reveals a shadow when the user starts scrolling. We'll use this with the new toolbars once they're ready to be published.
https://user-images.githubusercontent.com/1791149/180892688-2d6a8384-e462-4209-9f76-63d93a053303.mp4

chore(compass-aggregations): add shadow on scroll to aggregations workspace

---

configs/mocha-config-compass/register/resolve-from-source-register.js

chore(mocha-config-compass): Warn about non-workspace dirs in packages folder

---

packages/compass-collection/package.json
packages/compass-connections/package.json
packages/compass-e2e-tests/package.json
packages/compass-import-export/package.json
packages/compass-schema/package.json
packages/compass-shell/package.json
packages/compass/package.json
packages/connection-form/package.json
packages/connection-model/package.json
packages/data-service/package.json
packages/data-service/src/connect-mongo-client.ts
packages/index-model/package.json

Re-do of https://github.com/mongodb-js/compass/pull/3266 with the latest versions of driver, mongosh and mongodb-client-encryption. Resolves COMPASS-5767 and prepares us for the next driver release expected to drop early next week.

chore(deps): bump driver, shell, libmongocrypt

---

packages/compass-shell/package.json
packages/compass/package.json
packages/data-service/package.json

Fixes a critical bug in libmongocrypt (MONGOCRYPT-464).

chore(deps): bump mongosh/libmongocrypt to latest versions

---

package.json

chore: use conventional bump commit message

---

THIRD-PARTY-NOTICES.md
packages/compass-components/src/components/icon-button.tsx
packages/compass-components/src/components/item-action-controls.tsx
packages/compass-components/src/components/resizeable-sidebar.tsx
packages/compass-databases-navigation/src/collection-item.tsx
packages/compass-databases-navigation/src/database-item.tsx
packages/compass-databases-navigation/src/tree-item.tsx
packages/compass-home/src/index.less
packages/compass-instance/package.json
packages/compass-instance/src/plugin.jsx
packages/compass-instance/src/stores/index.js
packages/compass-sidebar/src/components-legacy/sidebar/navigation-items.jsx
packages/compass-sidebar/src/components-legacy/sidebar/sidebar.module.less
packages/compass-sidebar/src/components/database-collection-filter.tsx
packages/compass-sidebar/src/components/navigation-items.tsx
packages/compass-sidebar/src/components/sidebar-title.tsx
packages/compass-sidebar/src/components/sidebar.tsx
packages/compass-sidebar/src/modules/index.js
packages/compass-sidebar/src/modules/location.ts
packages/compass-sidebar/src/stores/store.js

feat(sidebar): New sidebar nav items, add database button, filter COMPASS-5963 COMPASS-5964 COMPASS-5965

---

packages/compass-crud/src/components/document-list.jsx
packages/compass-e2e-tests/tests/collection-documents-tab.test.ts

feat(compass-crud): Add error message hint for crud timeout message COMPASS-4638

---

packages/compass-explain-plan/src/components/explain-toolbar/explain-toolbar.tsx
packages/compass-query-bar/src/components/query-bar.tsx
packages/compass-query-bar/src/components/query-option.tsx

Styling tweaks for the feature flagged toolbars. Will likely be another follow up pr following sync with Claudia as well.
Before:
After:
Before:
After:

chore(query-bar, explain-plan): remove shadow on new explain toolbar, dark theme border on query

---

packages/compass-sidebar/src/components/db-stats.tsx
packages/compass-sidebar/src/components/sidebar.tsx

feat(sidebar): new sidebar db stats COMPASS-5962

---

packages/compass-components/src/constants/mongodb-ace-theme-query.ts
packages/compass-query-bar/src/components/option-editor.tsx
packages/compass-query-bar/src/components/query-bar.tsx
packages/compass-query-bar/src/components/query-option.tsx

chore(query-bar): styling updates, white background on query bar area, no borders on inputs

---

packages/compass/scripts/download-csfle.js

fix(compass): adjust crypt shared library download script for M1 builds

---

.evergreen/buildvariants.in.yml
.evergreen/buildvariants.yml

For testing out [BUILD-14120](https://jira.mongodb.org/browse/BUILD-14120) / getting started with COMPASS-5214

chore(ci): use macos-1100-gui hosts

---

packages/hadron-build/lib/target.js

This allows installing and (successfully) running Compass on RHEL 9.
Similar change for Atom: https://github.com/atom/atom/pull/25541

fix(hadron-build): drop lsb-core-noarch from rpm deps COMPASS-6025

---

packages/index-model/lib/model.js
packages/index-model/test/index.test.js

fix(index-model): when expireAfterSeconds is 0 COMPASS-3073

fix(index-model): when expireAfterSeconds is 0 COMPASS-3073

---

packages/compass-sidebar/src/components/connection-info-modal.tsx
packages/compass-sidebar/src/components/csfle-marker.tsx
packages/compass-sidebar/src/components/db-stats.tsx
packages/compass-sidebar/src/components/non-genuine-marker.tsx
packages/compass-sidebar/src/components/sidebar.tsx
packages/compass-sidebar/src/stores/store.js
packages/database-model/lib/model.js
packages/instance-model/index.d.ts

feat(sidebar): move db stats to the connection modal COMPASS-6079

---

packages/compass-databases-navigation/src/tree-item.tsx

chore: fix prettier formatting

---

packages/compass-query-bar/src/components/query-bar.tsx
packages/compass-query-bar/src/components/query-history-button-popover.tsx
packages/compass-query-bar/src/components/query-option.tsx
packages/compass-query-bar/src/components/query-options-grid.tsx

Part of COMPASS-6088
Mocks: https://www.figma.com/file/vbjoD4dcisPYRYJ5RRu72k/Compass-LG?node-id=3325%3A104508

styles(compass-query-bar): Update filter label placement and spacing styles COMPASS-6088

---

.github/PULL_REQUEST_TEMPLATE.md

COMPASS-5094
The Contributor License Agreement (CLA) is already mentioned clearly in the `CONTRIBUTING.md`.

chore: Add Contributor License Agreement checklist item to pull request template COMPASS-5094

---

packages/compass-sidebar/src/components-legacy/sidebar/navigation-items.jsx
packages/compass-sidebar/src/components-legacy/sidebar/sidebar.module.less

https://user-images.githubusercontent.com/69737/189307077-20b0592c-29d5-4fea-9e3f-49e94416fa03.mov

revert the bold effect on the old sidebar

---

packages/compass-e2e-tests/helpers/commands/index.ts
packages/compass-e2e-tests/helpers/commands/save-favorite.ts
packages/compass-e2e-tests/helpers/commands/select-connection-menu-item.ts
packages/compass-e2e-tests/helpers/commands/select-favorite.ts
packages/compass-e2e-tests/tests/connection-form.test.ts

chore(compass-e2e-tests): refactor out common favorite operations

---

packages/compass-components/src/components/bson-value.spec.tsx
packages/compass-components/src/components/bson-value.tsx

Also open to not doing this at all is this seems too verbose:

feat(compass-components): link to Compass FLE docs for encrypted values COMPASS-5633

---

packages/compass-components/src/components/placeholder.tsx
packages/compass/src/app/index.html
packages/compass/src/app/styles/index.less

* updates the colours on the loading placeholder to match the new light mode sidebar.
* picks new colours for the light/dark mode placeholder images that contrast better

feat(sidebar): New sidebar placeholders COMPASS-6098

---

packages/compass-preferences-model/src/index.ts
packages/compass-preferences-model/src/preferences.ts
packages/compass-preferences-model/src/renderer-ipc.ts
packages/compass-settings/src/components/settings/privacy.tsx
packages/compass-settings/src/stores/settings.ts
packages/compass-settings/src/stores/updated-fields.ts

Make sure that types match what they are expected to match, and make sure that the Ampersand props definition contains exactly what it is supposed to contain.

chore: user stricter types for Compass preferences

---

packages/compass-e2e-tests/helpers/insert-data.ts
packages/compass-e2e-tests/tests/collection-schema-tab.test.ts
packages/compass-schema/src/components/field/field.jsx

fix(compass-schema): fix map rendering + add e2e tests COMPASS-6131

---

packages/compass-preferences-model/package.json
packages/compass-preferences-model/src/preferences.spec.ts
packages/compass-preferences-model/src/renderer-ipc.spec.ts
packages/compass-preferences-model/src/renderer-ipc.ts

… so that they can be extended in COMPASS-6070 / COMPASS-6071.

chore(compass-preferences-model): add tests

---

packages/compass/src/app/index.js
packages/compass/src/app/migrations/index.js
packages/compass/src/app/setup-plugin-manager.js
packages/compass/src/main/window-manager.ts

This was not being consumed anywhere since 5485446eb4b17.

chore(compass): remove compass:loading:change-status event

---

packages/compass/src/main/application.ts

chore(compass): fix `MONGODB_COMPASS_TEST_LOG_DIR` access

---

packages/compass-e2e-tests/helpers/compass.ts

chore(compass-e2e-tests): resolve TODO about `any` type

---

configs/mocha-config-compass/package.json
configs/tsconfig-compass/package.json
configs/webpack-config-compass/package.json
packages/compass-components/package.json
packages/compass-components/src/components/leafy-green/combobox/combobox.tsx
packages/compass-databases-navigation/package.json
packages/compass-e2e-tests/index.ts
packages/compass-e2e-tests/package.json
packages/compass-logging/package.json
packages/compass-utils/package.json
packages/data-service/package.json
packages/databases-collections-list/package.json
packages/explain-plan-helper/package.json
packages/hadron-app-registry/package.json
packages/ssh-tunnel/package.json

chore: bump typescript and ts-node to latest

---

configs/webpack-config-compass/src/loaders.ts
packages/compass/package.json
packages/compass/src/app/index.js

Replaces https://github.com/mongodb-js/compass/pull/3498

chore(typography): Add Source Code Pro COMPASS-6096

---

packages/compass-connections/src/components/connection-list/connection.tsx

chore(compass-connections): run prettier

---

CONTRIBUTING.md
README.md

This PR updates the base [README](https://github.com/mongodb-js/compass/blob/main/README.md) and [CONTRIBUTING](https://github.com/mongodb-js/compass/blob/main/CONTRIBUTING.md) documentation to hopefully get newer folks into the project quicker.
Open to opinions and thoughts.

docs: Move contributing section up in readme, rearrange section in contributing

---

.evergreen/buildvariants.in.yml
.evergreen/buildvariants.yml
.evergreen/functions.yml
.evergreen/tasks.in.yml
.evergreen/tasks.yml

ci: publish next tagged packages on main merge

---

packages/compass-collection/package.json
packages/compass-connections/package.json
packages/compass-e2e-tests/package.json
packages/connection-form/package.json
packages/connection-model/package.json
packages/data-service/package.json
scripts/package.json

chore(deps): bump mongodb-connection-string-url to 2.5.4 COMPASS-5738

---

packages/compass-home/src/components/home.spec.tsx
packages/compass-home/src/components/home.tsx
packages/compass-home/src/plugin.tsx
packages/compass-preferences-model/src/preferences.ts
packages/compass-welcome/src/components/modal.spec.tsx
packages/compass-welcome/src/components/modal.tsx
packages/compass/src/app/index.js

Follow-up to https://github.com/mongodb-js/compass/pull/3535
See also https://mongodb.slack.com/archives/GDTJXPHD0/p1664869640286469

chore: hide the disclaimer if networkTraffic is false COMPASS-6150

---

packages/compass-aggregations/src/modules/index.ts
packages/compass-aggregations/src/modules/pipeline-builder/index.spec.ts
packages/compass-aggregations/src/modules/pipeline-builder/index.ts
packages/compass-aggregations/src/modules/pipeline-builder/pipeline-mode.ts
packages/compass-aggregations/src/stores/store.spec.js

chore(text-aggregation): setup pipeline builder slice

---

packages/compass-schema/src/components/compass-schema/compass-schema.jsx

chore: re-center the schema analysis loader

---

packages/compass-aggregations/src/components/pipeline/pipeline.jsx
packages/compass-aggregations/src/components/settings/settings.jsx

chore: move aggregation settings and replace buttons COMPASS-6184

---

packages/compass-explain-plan/src/components/summary-index-stat/summary-index-stat.jsx
packages/compass-explain-plan/src/components/summary-stat/summary-stat.jsx

fix(query-explain): open info links in browser COMPASS-6193

---

packages/compass-aggregations/package.json
packages/compass-aggregations/src/modules/pipeline-builder/pipeline-builder.ts
packages/compass-aggregations/src/typings.d.ts

chore(pipeline-builder): use ejson types COMPASS-6204

---

packages/compass-sidebar/src/components/navigation-items.spec.tsx
packages/compass-sidebar/src/components/navigation-items.tsx
packages/compass-sidebar/src/modules/databases.js

fix(sidebar): hide create database button on readonly

---

packages/compass-editor/src/ace/theme.ts

COMPASS-6225
| Before | After |
| - | - |
| ![Screen Shot 2022-10-24 at 7 31 16 PM](https://user-images.githubusercontent.com/1791149/197649291-30afa60e-b431-4c87-8854-e003db73d8d9.png) | ![Screen Shot 2022-10-24 at 7 29 07 PM](https://user-images.githubusercontent.com/1791149/197649302-da572d5f-fd93-46bf-ae46-c07bd739409f.png) |
| ![Screen Shot 2022-10-24 at 7 31 28 PM](https://user-images.githubusercontent.com/1791149/197649310-84bf6364-6a46-41eb-8314-a96421849715.png) | ![Screen Shot 2022-10-24 at 7 29 46 PM](https://user-images.githubusercontent.com/1791149/197649326-30361bd1-6147-4f5c-aa8b-071e363db24d.png) |

chore(editor): remove ace-editor left shadow on scroll COMPASS-6225

---

packages/compass-connections/src/components/form-help/form-help.tsx
packages/connection-form/src/components/connect-form.tsx

COMPASS-6231
|before|after|
|-|-|
|![Screen Shot 2022-10-24 at 9 50 17 PM](https://user-images.githubusercontent.com/1791149/197663600-834b0e34-54fc-4c17-b131-e7b5d358566f.png)|![Screen Shot 2022-10-24 at 9 48 11 PM](https://user-images.githubusercontent.com/1791149/197663613-bf360ad7-8747-4f9a-babf-500fd39509ea.png)|

styles: style with theme in atlas help panel COMPASS-6231

---

packages/compass-shell/src/components/shell-info-modal/shell-info-modal.jsx

Fixes clicking this close button to close modal

fix: close on click info modal close button

---

packages/compass-preferences-model/.mocharc.js
packages/compass-preferences-model/package.json
packages/compass-preferences-model/src/index.ts
packages/compass-preferences-model/src/react.spec.tsx
packages/compass-preferences-model/src/react.ts
packages/compass-schema/src/components/field/field.jsx

chore(compass-preferences-model): add react integration utils

---

packages/compass-collection/src/components/collection-header/collection-header.tsx
packages/compass-collection/src/components/collection-stats-item/collection-stats-item.tsx
packages/compass-saved-aggregations-queries/src/components/saved-item-card.tsx
packages/compass-schema/src/components/compass-schema/compass-schema.module.less
packages/compass-sidebar/src/components/db-stats.tsx
packages/databases-collections-list/src/namespace-card.tsx

chore: small contrast fixes

---

packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-preview.tsx

removes extra $s from pipeline preview text

fix(pipeline-text): remove $s from text

---

.gitignore
scripts/generate-snyk-reports.sh

chore: add script to generate snyk reports

---

packages/connection-form/src/components/advanced-options-tabs/ssh-tunnel-tab/ssh-tunnel-identity.tsx
packages/connection-form/src/components/advanced-options-tabs/ssh-tunnel-tab/ssh-tunnel-password.tsx

chore(connection-form): minor type improvements in ssh tunnel forms

---

packages/compass-connections/src/components/connections.tsx

| - | - |
| no scroll <img width="735" alt="Screen Shot 2022-11-07 at 4 32 10 PM" src="https://user-images.githubusercontent.com/1791149/200420242-0061d17b-6e3c-45a2-8473-5175d348c2d6.png"> | <img width="792" alt="Screen Shot 2022-11-07 at 4 30 21 PM" src="https://user-images.githubusercontent.com/1791149/200420278-98f93ef5-7553-4a2c-901d-50aaa6858ace.png"> |
|  | <img width="432" alt="Screen Shot 2022-11-07 at 4 30 31 PM" src="https://user-images.githubusercontent.com/1791149/200420355-d240b059-8a52-4a10-b300-172a8ee6a2d8.png"> |

chore(connections): make connection form and info panel area scroll

---

packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.spec.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-menus.tsx

Reverts mongodb-js/compass#3709

Revert "chore(compass-aggregations): do not show pipeline as text option when text editor enabled COMPASS-6170"

---

packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-preview.tsx

fix(pipeline-text): use correct stage operators

---

packages/compass-e2e-tests/helpers/compass.ts

Previously, default options were only set if a Compass instance had previously run where the welcome modal was displayed, which makes tests interdependent on each other. Now, the welcome modal is shown by default, which ensures that default settings are in effect.

fix(compass-e2e-tests): ensure default settings are set

---

packages/compass-connections/src/stores/connections-store.spec.ts
packages/compass-connections/src/stores/connections-store.ts
packages/compass-e2e-tests/tests/auto-connect.test.ts

fix(compass-connections): do not save auto-connection in recents COMPASS-6290

---

packages/compass-e2e-tests/tests/auto-connect.test.ts
packages/compass-preferences-model/src/preferences.ts
packages/compass/package.json
packages/compass/src/app/auto-connect.spec.ts
packages/compass/src/app/auto-connect.ts
packages/connection-form/src/utils/force-connection-options.spec.ts
packages/connection-form/src/utils/force-connection-options.ts

feat: add --username and --password for auto-connect COMPASS-6216

---

packages/compass-preferences-model/src/preferences.spec.ts
packages/compass-preferences-model/src/preferences.ts

fix(compass-preferences-model): default enableShell to true

---

packages/compass-preferences-model/src/preferences.ts
packages/compass-settings/src/components/settings/features.spec.tsx
packages/compass-settings/src/components/settings/features.tsx
packages/compass-settings/src/components/settings/privacy.spec.tsx
packages/compass-settings/src/components/settings/privacy.tsx
packages/compass-settings/src/components/settings/settings-list.tsx
packages/compass-settings/src/utils/pick.ts

feat(compass-settings): add support for numeric inputs

---

packages/compass-connections/src/components/connections.spec.tsx
packages/compass-connections/src/components/form-help/form-help.tsx

Not sure what to do about this one https://github.com/mongodb-js/compass/blob/99d5978b1ac67e7d6e8e39d29db203f2dbec4e23/packages/compass-aggregations/src/components/atlas-stage-preview.tsx#L13

chore(connect): update Create Free Cluster link COMPASS-6287

---

packages/compass/src/app/index.js
packages/compass/src/main/application.ts
packages/compass/src/main/window-manager.ts

Add Application Launched telemetry event.

feat: track application launched telemetry COMPASS-6077

---

packages/compass-preferences-model/src/global-config.spec.ts
packages/compass-preferences-model/src/global-config.ts

fix(compass-preferences-model): ignore squirrel options

---

packages/compass-components/src/components/document-list/element-actions.tsx
packages/compass-components/src/components/document-list/element-editors.tsx
packages/compass-components/src/components/document-list/element.tsx
packages/compass-components/src/components/item-action-controls.tsx
packages/compass-components/src/components/leafygreen.tsx
packages/compass-crud/src/components/table-view/add-field-button.jsx
packages/compass-crud/src/components/table-view/ag-grid.less
packages/compass-crud/src/components/table-view/breadcrumb.jsx
packages/compass-crud/src/components/table-view/cell-editor.jsx
packages/compass-crud/src/components/table-view/cell-renderer.jsx

chore(compass-components): add xsmall icon size COMPASS-6306

---

packages/compass-aggregations/src/components/saved-pipelines/saved-pipelines.tsx

fix(aggregations): fix the saved pipelines popover's scrolling COMPASS-6277

---

packages/compass-e2e-tests/tests/global-preferences.test.ts
packages/compass/src/main/application.ts
packages/compass/src/main/disable-node-deprecations.ts

fix(compass): disable deprecation warnings in production COMPASS-6322

---

packages/compass-settings/src/components/modal.tsx
packages/compass-settings/src/components/sidebar.tsx

Make a contrast of settings' categories names that is readable in dark mode.

fix: apply settings categories dark styles COMPASS-6327

---

packages/compass-settings/src/components/settings/settings-list.tsx

fix(compass-settings): ignore non-digits in number input COMPASS-6326

---

packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/index.tsx

fixes UI glitches when editor is resized [COMPASS-6320](https://jira.mongodb.org/browse/COMPASS-6320)

fix(pipeline-preview): do not overflow the preview container COMPASS-6320

---

THIRD-PARTY-NOTICES.md
packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-editor.spec.tsx
packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-editor.tsx

chore(telemetry): track aggregation changes in text mode [COMPASS-6328](https://jira.mongodb.org/browse/COMPASS-6328)

chore(telemetry): track aggregation changes in text mode COMPASS-6328

---

packages/compass/src/main/window-manager.ts

fix(compass): fix macOS protocol handler connection string passing

---

packages/compass-import-export/src/components/import-modal.tsx
packages/compass-import-export/src/components/import-options.tsx

chore(compass-import-export): fix “delimeter” typo

---

packages/compass-crud/src/components/insert-document-dialog.tsx

| - | - |
| ![Screen Shot 2022-11-30 at 5 55 43 PM](https://user-images.githubusercontent.com/1791149/204926118-fa1b097c-c04a-4291-9532-e4c23defc6e6.png) | ![Screen Shot 2022-11-30 at 5 56 48 PM](https://user-images.githubusercontent.com/1791149/204926128-3fec5009-74dd-4ff2-ac0f-73e08289f04e.png) |

chore(compass-crud): show namespace in modal form subtitle, not title

---

packages/compass-connections/src/components/connection-list/connections-title.tsx
packages/compass/scripts/download-fonts.js
packages/compass/src/app/styles/fonts.less

Chatted with Claudia a week or two back, we were thinking this might be a better move for now. Will double check with design before merging. 
| - | - |
| ![Screen Shot 2022-11-30 at 4 58 42 PM](https://user-images.githubusercontent.com/1791149/204917413-01e6a998-0c6c-42dc-954a-7624e59fe882.png) | ![Screen Shot 2022-11-30 at 4 58 30 PM](https://user-images.githubusercontent.com/1791149/204917425-20ae098e-663a-4415-b95c-4f11a4198373.png) |

styles(connections): update connection title, remove mongodb font

---

packages/compass-aggregations/src/components/pipeline-results-workspace/pipeline-results-header.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.spec.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-menus.tsx
packages/compass-aggregations/src/modules/pipeline-builder/pipeline-mode.ts
packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
packages/compass-preferences-model/src/preferences.ts
packages/compass-preferences-model/src/renderer-ipc.ts
packages/compass-settings/src/components/modal.tsx
packages/compass-settings/src/components/settings/featureflags.tsx
packages/compass/src/app/theme.ts
packages/compass/src/index.d.ts
packages/compass/src/main/index.ts
packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.tsx

~~[draft since this depends on #3826]~~

feat: expose feature flags as settings COMPASS-6336

---

packages/compass-components/src/components/spin-loader.tsx
packages/compass-shell/src/components/shell-header/shell-header.jsx

This addresses a review comment on b09f4d5f0a:
https://github.com/mongodb-js/compass/pull/3867#discussion_r1042656113

chore(compass-shell): pass className directly to SpinLoader

---

packages/compass-indexes/src/utils/index-link-helper.ts
packages/databases-collections/src/components/collection-fields/clustered-collection-fields.jsx

chore(docs): add clustered collection index docs COMPASS-5760

---

packages/compass-crud/src/components/json-editor.tsx

COMPASS-6059
I'd like to add a regression test, but there isn't really much testing anything near here so I'm thinking it's not worth the time.
**Before**
https://user-images.githubusercontent.com/1791149/206559963-f87a21f0-a464-4626-92c6-253f350ede6c.mp4
**After**
https://user-images.githubusercontent.com/1791149/206559974-d747c6b9-eec4-4153-aa6c-f8b4e534b236.mp4

fix(compass-crud): reset contains error check on document json view edit cancel COMPASS-6059

---

packages/compass-schema/src/components/field/field.jsx

We should probably have a test for nested fields.

fix(schema): pass the preference as a prop when nesting Field COMPASS-6363

---

packages/compass-databases-navigation/src/collection-item.tsx
packages/compass-databases-navigation/src/placeholder-item.tsx

chore(sidebar): indent collections in the sidebar COMPASS-6380

---

packages/compass-sidebar/src/components/sidebar-title.tsx

More context: https://mongodb.slack.com/archives/GDTJXPHD0/p1671045581185539

chore(compass-sidebar): rename refresh menu action to reload data

---

packages/compass-aggregations/src/components/focus-mode.tsx
packages/compass-aggregations/src/components/focus-mode/focus-mode.spec.tsx
packages/compass-aggregations/src/components/focus-mode/focus-mode.tsx
packages/compass-aggregations/src/components/pipeline/pipeline.jsx
packages/compass-aggregations/src/components/stage-preview-toolbar/stage-preview-toolbar.tsx
packages/compass-aggregations/src/modules/focus-mode.ts
packages/compass-aggregations/src/modules/index.ts
packages/compass-aggregations/src/stores/store.spec.js
packages/compass-preferences-model/src/preferences.ts
packages/compass-settings/src/components/settings/featureflags.tsx

feat(focus-mode): setup focus mode COMPASS-6386

feat(focus-mode): setup focus mode COMPASS-6386

---

packages/compass-aggregations/src/utils/stage.js
packages/compass-aggregations/src/utils/stage.spec.js

fix(aggregations): output stage destination name COMPASS-6407

fix(aggregations): output stage destination name COMPASS-6407 

---

packages/compass-app-stores/src/stores/instance-store.js
packages/compass-e2e-tests/tests/database-collections-tab.test.ts
packages/compass-e2e-tests/tests/in-use-encryption.test.ts
packages/compass-e2e-tests/tests/instance-databases-tab.test.ts
packages/compass-e2e-tests/tests/instance-sidebar.test.ts

This affects adding a collection from the sidebar and from the collections list.
Checking in e2e tests that the redirect happens.

feat(collections): redirect to the new collection after creating it COMPASS-6019

---

packages/compass-crud/src/components/table-view/document-table-view.tsx

Remove UNSAFE_componentWillReceiveProps in the document table.

refactor: remove unsafe method in document table COMPASS-6137

---

packages/compass-aggregations/src/components/focus-mode/focus-mode-modal-header.spec.tsx
packages/compass-aggregations/src/components/focus-mode/focus-mode-modal-header.tsx

Just adding some tests as promised (I'll wait for a prettier PR to land first before merging this)

chore(compass-aggregations): add tests for focus-mode header component

---

packages/compass-aggregations/src/components/saved-pipelines/saved-pipelines.tsx
packages/compass-aggregations/src/components/stage-editor/stage-editor.jsx
packages/compass-aggregations/src/modules/aggregation.ts
packages/compass-aggregations/src/modules/explain.ts
packages/compass-aggregations/src/modules/focus-mode.ts
packages/compass-aggregations/src/modules/pipeline-builder/builder-helpers.ts
packages/compass-aggregations/src/modules/pipeline-builder/pipeline-mode.ts
packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
packages/compass-aggregations/src/modules/saved-pipeline.ts
packages/compass-aggregations/src/modules/update-view.js
packages/compass-aggregations/src/modules/update-view.spec.js
packages/compass-editor/src/multiline-editor.tsx

New telemetry for Focus Mode feature

chore(compass-aggregations): add telemetry for focus mode modal COMPASS-6392

---

packages/compass/package.json
packages/data-service/package.json
packages/data-service/src/csfle-collection-tracker.ts

… and update our monkey-patching to be async/await-based rather than callback-based to match the corresponding upstream changes.

chore(deps): bump mongodb-client-encryption to 2.4.0 COMPASS-6484

---

packages/compass-sidebar/src/components/sidebar-title.tsx
packages/compass/src/main/menu.ts

| - | - |
| <img width="249" alt="Screen Shot 2023-02-05 at 7 17 52 AM" src="https://user-images.githubusercontent.com/1791149/216818295-bfdff15d-0032-47f4-b4c4-5ef3ba82e79e.png"> | <img width="262" alt="Screen Shot 2023-02-05 at 7 19 03 AM" src="https://user-images.githubusercontent.com/1791149/216818301-4e0e748a-fe42-4958-a232-ebdda927c4d9.png"> |
| <img width="234" alt="Screen Shot 2023-02-05 at 7 20 48 AM" src="https://user-images.githubusercontent.com/1791149/216818342-c85fdd46-8aec-45bc-9d8b-7c08ff59ed4e.png"> | <img width="242" alt="Screen Shot 2023-02-05 at 7 19 13 AM" src="https://user-images.githubusercontent.com/1791149/216818346-c797b7ef-5022-45e6-b871-e6b8dc994130.png"> |

chore: standardize menu option capitalization

---

packages/compass-aggregations/src/components/focus-mode/focus-mode.tsx

Dark mode fixes for Focus Mode

feat(focus-mode): dark mode COMPASS-6472

---

packages/compass-serverstats/src/components/chart-component.jsx
packages/compass/src/app/index.jsx

Originally planned to use this to enable the v5 upgrade to BSON, doesn’t look like that’s going to be possible but still seems worth creating a PR for

chore: migrate more code from CJS to (JSX-style) ESM

---

packages/compass-e2e-tests/tests/in-use-encryption.test.ts
packages/compass/package.json
packages/compass/scripts/download-csfle.js
packages/data-service/src/csfle-collection-tracker.ts

feat: upgrade crypt_shared lib to 6.2.0, test range QE COMPASS-6485

---

packages/compass-components/src/components/collapsible-field-set.tsx
packages/compass-components/src/components/list-editor.tsx
packages/compass-e2e-tests/tests/collection-indexes-tab.test.ts
packages/compass-indexes/src/components/create-index-fields.tsx
packages/compass-indexes/src/components/create-index-form/collapsible-input.tsx
packages/compass-indexes/src/modules/create-index/options.tsx
packages/connection-form/src/components/advanced-options-tabs/general-tab/host-input.tsx

chore(compass-indexes): add preview badge to the column store index options COMPASS-6488

---

packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-shell/package.json
packages/compass/package.json

feat(deps): upgrade mongosh to 1.7.0

---

packages/compass-e2e-tests/helpers/selectors.ts
packages/databases-collections/src/components/collection-fields/collection-fields.jsx
packages/databases-collections/src/components/collection-fields/collection-fields.spec.jsx

COMPASS-4981
--
This PR moves Timeseries collection creation to a more visible place - out of our collapsible advanced options, right underneath the collection name.

chore(databases-collections): make Time-Series more visible

---

packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-preview.tsx

fix(focus-mode): plain object for redux connect

---

packages/compass-aggregations/src/components/stage.tsx

fix(focus-mode): feature flagged guide cue COMPASS-6524

---

scripts/precommit.js

Pre-commit run prettier when files are changed.

fix(pre-commit): ignore prettier when no files are changed

---

packages/compass-import-export/src/import/import-csv.spec.ts
packages/compass-import-export/src/utils/utf8-validator.ts

Forgot to add that to the validator code in #4075 :)

fix(compass-import-export): also reject truncated UTF-8

---

packages/compass-settings/src/components/settings/theme.tsx
packages/compass-settings/src/components/sidebar.tsx

feat(settings): dark theme improvements in the settings modal COMPASS-6552

---

packages/compass-aggregations/package.json
packages/compass-collection/package.json
packages/compass-connections/package.json
packages/compass-e2e-tests/package.json
packages/compass-import-export/package.json
packages/compass-indexes/package.json
packages/compass-schema/package.json
packages/compass/package.json
packages/connection-form/package.json
packages/connection-form/src/utils/csfle-kms-fields.ts
packages/connection-model/package.json
packages/data-service/package.json
packages/databases-collections/package.json
packages/index-model/package.json

chore(deps): bump driver to 5.1.0, mongodb-client-encryption to 2.6.0

---

packages/compass-aggregations/src/plugin.jsx

fix(aggregations): wrap aggregations plugin in confirmation modal

---

packages/compass-import-export/src/import/import-csv.spec.ts
packages/compass-import-export/src/import/import-json.spec.ts
packages/compass-import-export/src/modules/export.spec.js
packages/data-service/src/index.ts

Other packages should rely on the interface, not the implementation.

chore(data-service): remove DataServiceImpl usage outside of package

---

packages/compass-e2e-tests/helpers/commands/show-shell.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/in-use-encryption.test.ts
packages/compass-e2e-tests/tests/instance-my-queries-tab.test.ts
packages/compass-e2e-tests/tests/instance-sidebar.test.ts
packages/compass-sidebar/src/components/navigation-items.spec.tsx
packages/compass-sidebar/src/components/navigation-items.tsx
packages/compass-sidebar/src/components/sidebar-title.tsx

Closes
--
COMPASS-6431
Moves the refresh CTA from options menu to an easily accessible location in sidebar.
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img width="265" alt="image" src="https://user-images.githubusercontent.com/10037761/221826240-770f2b92-430b-4078-85b0-c4c92a16fefa.png">
<td><img width="265" alt="image" src="https://user-images.githubusercontent.com/10037761/221826091-61816073-e8e9-4b15-92d9-1e7f4d9245de.png">
<tr>
<td><img width="265" alt="image" src="https://user-images.githubusercontent.com/10037761/221826385-ee058161-d539-4fdf-9955-c24e60636735.png">
<td><img width="265" alt="image" src="https://user-images.githubusercontent.com/10037761/221826454-bac7a1ec-89a2-4053-849c-4508a5c7374f.png">
</table>

feat(compass-sidebar): adds the refresh CTA to sidebar

---

packages/compass-shell/package.json

This is a followup of [this PR](https://github.com/mongodb-js/mongosh/pull/1420).

chore(compass-shell): dependency update for browser-repl - COMPASS-6534

---

packages/compass-editor/src/codemirror/query-autocompleter.test.ts
packages/compass-editor/src/codemirror/query-autocompleter.ts
packages/compass-editor/src/index.ts

Basic autocopmletions for queries to match current ace editor behavior

chore(compass-editor): add codemirror query autocompleter matching ace editor COMPASS-6573

---

packages/compass-import-export/src/components/import-preview.tsx

fix(import): add dark mode colours for the mixed warning

---

packages/compass-aggregations/src/components/focus-mode/focus-mode.tsx
packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-editor.tsx
packages/compass-aggregations/src/components/stage-editor/stage-editor.tsx

Small fix for the dark mode colors as highlighted in https://github.com/mongodb-js/compass/pull/4187#issuecomment-1484227524

chore(compass-aggregations): disable default background color in editor

---

packages/compass-preferences-model/src/preferences.ts
packages/compass-settings/src/components/settings/featureflags.tsx

chore(stage-wizard): setup feature flag COMPASS-6652

---

packages/compass-schema-validation/src/modules/validation.js
packages/data-service/src/data-service.ts

chore(data-service, schema-validation): change order for logging and fix dispatch order

---

packages/compass-aggregations/src/components/stage-toolbar/index.tsx
packages/compass-aggregations/src/components/stage-toolbar/option-menu.tsx

feat(aggregations): button titles in stage toolbar COMPASS-6686

---

packages/compass-preferences-model/src/global-config.ts

fix(config): fix loading configuration file on windows, remove arg check COMPASS-6527

---

packages/compass-crud/src/components/add-data-menu.tsx

COMPASS-6494
https://mongodb.slack.com/archives/GDTJXPHD0/p1680535352473779
| - | - |
| <img width="409" alt="Screenshot 2023-04-03 at 12 14 53 PM" src="https://user-images.githubusercontent.com/1791149/229568323-9d37b6d0-6848-4619-9d21-7da84b19768b.png"> | <img width="405" alt="Screenshot 2023-04-03 at 12 15 52 PM" src="https://user-images.githubusercontent.com/1791149/229568347-4ea1261d-f110-403b-9de1-557c51b2d5fd.png"> |

feat(compass-crud): update add data icon to plus with circle from download COMPASS-6494

---

packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/index.ts
packages/compass-aggregations/src/components/stage-wizard/index.spec.tsx
packages/compass-aggregations/src/components/stage-wizard/index.tsx

In this PR, added Stage Wizard Card where we will render the form elements of the aggregation use case.

feat(stage-wizard): stage wizard card COMPASS-6654

---

packages/compass-import-export/src/components/import-toast.tsx
packages/compass-import-export/src/csv/csv-utils.spec.ts
packages/compass-import-export/src/csv/csv-utils.ts
packages/compass-import-export/src/modules/import.ts

https://user-images.githubusercontent.com/69737/231783601-01c09ed3-e0e6-4b64-b521-de3b2508a53f.mov

feat(import): Import progress COMPASS-6721

---

packages/data-service/src/csfle-collection-tracker.spec.ts
packages/data-service/src/data-service.spec.ts
packages/data-service/src/data-service.ts
packages/databases-collections/src/modules/drop-database/drop-database.ts
packages/databases-collections/src/stores/drop-database.js

Small one changing the only callback database method to promises

chore(data-service): promisify database methods COMPASS-6620

---

packages/compass-crud/src/stores/crud-store.spec.ts
packages/compass-crud/src/stores/crud-store.ts
packages/compass-crud/src/utils/cancellable-queries.spec.ts
packages/data-service/src/data-service.spec.ts
packages/data-service/src/data-service.ts

Last batch of methods converted. Same deal as before, base is previous PR, will update when it lands

chore(data-service): promisify delete* methods COMPASS-6620

---

packages/compass-crud/src/stores/crud-store.spec.ts
packages/compass-crud/src/stores/crud-store.ts
packages/compass-crud/src/utils/cancellable-queries.spec.ts
packages/compass-import-export/src/export/export-csv.spec.ts
packages/compass-import-export/src/export/export-json.spec.ts
packages/compass-import-export/src/export/gather-fields.spec.ts
packages/compass-import-export/src/modules/legacy-export.spec.js
packages/compass-import-export/src/utils/collection-stream.spec.ts
packages/compass-import-export/src/utils/collection-stream.ts
packages/data-service/src/data-service.spec.ts
packages/data-service/src/data-service.ts

Another one, now for insert methods. Base is still the previous PR, this should make it easier to review and I'll continue rebasing and resolving conflicts when the previous ones land

chore(data-service): promisify insert* and delete* methods COMPASS-6620

---

packages/compass-app-stores/src/stores/instance-store.js

This PR fixes the issue with refresh button on collection grid not refreshing the collection stats.

fix(databases-collections-list): fixes the problem of refresh button on collection tab not refreshing the collection stats - COMPASS-6738

---

packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/basic-group.spec.tsx
packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/basic-group.tsx
packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/index.ts

feat(stage-wizard): basic group implementation COMPASS-6661

---

packages/compass-e2e-tests/helpers/commands/set-validation.ts
packages/compass-e2e-tests/tests/read-only.test.ts
packages/compass-schema-validation/src/components/validation-editor/validation-editor.jsx
packages/compass-schema-validation/src/components/validation-editor/validation-editor.spec.jsx

Update schema validation editor to use codemirror and new autocompleter

chore(schema-validation): replace ace with codemirror COMPASS-6748

---

packages/compass-e2e-tests/helpers/commands/add-collection.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/databases-collections/src/components/collection-fields/fle2-fields.jsx

Another one, this time for create collection dialog fields

chore(databases-collections): replace ace with codemirror in create collection dialog COMPASS-6765

---

packages/compass-import-export/src/components/import-preview.tsx

chore(import): Make the whole header the tooltip target COMPASS-6631

---

packages/compass-aggregations/package.json
packages/compass-import-export/package.json
packages/compass-indexes/package.json
packages/compass-query-bar/package.json
packages/compass-query-history/package.json
packages/compass-schema-validation/package.json
packages/databases-collections/package.json
scripts/check-peer-deps.js

This PR is created in order to shorten [the original PR for creating $match stages using visual form](https://github.com/mongodb-js/compass/pull/4308). In this PR we:
- fix the incorrect calculation of extraneousInProdDeps in compass-scripts. ~~Not sure why it didn't create issues before.~~ This did not popup so far because probably we always added packages in correct way that didn't generate any errors as per [the following condition](https://github.com/mongodb-js/compass/pull/4316/files#diff-12af47e15a0d57ffca8b5648e2d58e6ca451f03badba380a9cbaff34be1b3dedL86-L90) and the script bailed out early but when I added `hadron-type-checker`, it was missing from peerDependencies and triggered the `hasError` condition which also highlighted the issue of incorrect calculation of …

chore: fixes the miscalculation of extraneousInProdDeps in compass-scripts and bumps the version of mongodb-query-parser

---

.github/workflows/update-electron.yaml

Call the update script nightly and create a PR

chore: add script to update electron automatically

---

.github/workflows/update-electron.yaml

chore: change update-electron branch

---

packages/compass-collection/src/stores/context.tsx
packages/compass-schema/package.json
packages/compass-schema/src/stores/store.js

chore(schema): log error messages from schema analysis failures

---

packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/lookup/lookup.spec.tsx
packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/lookup/lookup.tsx
packages/compass-aggregations/src/modules/collections-fields.spec.ts
packages/compass-aggregations/src/modules/collections-fields.ts

fix(stage-wizard): lookup changes COMPASS-6770

---

packages/compass-logging/src/logger.ts
packages/compass-schema/src/stores/store.js

See HELP-45308 / COMPASS-6809.

fix: wrap schema analysis telemetry computation in try/catch HELP-45308

---

packages/compass-schema/src/components/promo-banner.tsx

chore(compass-schema): US-english spelling for `modeling` in Hackolade banner

---

.evergreen/buildvariants.in.yml
.evergreen/buildvariants.yml
.evergreen/functions.yml
.evergreen/tasks.in.yml
.evergreen/tasks.yml
package.json

chore: check vulnerabilities in CI COMPASS-6831

---

packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace/index.tsx

fix(stage-wizard): reduce resizer height to accomodate for padding

---

packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.spec.tsx
packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.tsx

Designs: https://www.figma.com/file/KNSE9YVqWCNJaSeIiOFMFo/OIDC-Auth-in-Compass?type=design&node-id=2118%3A1062&t=ymaCFKM4kuBz6MtD-1

chore(connection-form): add warning to oidc preview authentication method

---

packages/compass-import-export/src/components/import-toast.tsx

fix(import): imported, not exported

---

configs/mocha-config-compass/compass-plugin.js
configs/mocha-config-compass/index.js
configs/mocha-config-compass/main-process.js
configs/mocha-config-compass/react.js
configs/mocha-config-compass/register/assets-import-register.js
configs/mocha-config-compass/register/chai-dom-register.js
configs/mocha-config-compass/register/css-import-register.js
configs/mocha-config-compass/register/electron-renderer-register.js
configs/mocha-config-compass/register/enzyme-register.js
configs/mocha-config-compass/register/jsdom-global-register.js
configs/mocha-config-compass/register/resolve-from-source-register.js
configs/mocha-config-compass/register/sinon-chai-register.js
configs/mocha-config-compass/register/tsnode-register.js
configs/mocha-config-compass/register/unhandled-rejections.js
configs/mocha-config-compass/register/why-node-running.js
packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/sort/sort.spec.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-stages.spec.tsx
packages/compass-aggregations/src/modules/aggregation.spec.ts
packages/compass-aggregations/src/modules/pipeline-builder/pipeline-preview-manager.spec.ts
packages/compass-explain-plan/src/components/explain-plan-modal.spec.tsx
packages/compass-query-history/src/stores/favorite-list-store.spec.js
packages/compass-query-history/src/stores/recent-list-store.spec.js
packages/compass-query-history/src/utils/comparable-query.spec.js
packages/compass-query-history/src/utils/favorite-query-storage.spec.js
packages/data-service/src/data-service.spec.ts

chore: make mocha tests fail on unhandled rejections

---

packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx

fix(stage-wizard): correct label COMPASS-6895

---

packages/compass-preferences-model/src/feature-flags.ts

Enable Stage Wizard feature by default

feat(stage-wizard): enable feature COMPASS-6814

---

packages/compass-explain-plan/src/components/explain-toolbar/explain-toolbar.spec.tsx
packages/compass-explain-plan/src/components/explain-toolbar/explain-toolbar.tsx

chore(compass-explain-plan): renamed the segment control title for output from 'Raw Json' to 'Raw Output' - COMPASS-4456

---

packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.spec.tsx
packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.tsx

re https://mongodb.slack.com/archives/G2L10JAV7/p1686152137832869

chore(connection-form): remove OIDC prod warning

---

.evergreen/functions.yml

chore: create jira tickets even if the report fail

---

packages/compass/package.json

fix: fix SNYK-JS-FASTXMLPARSER-5668858 COMPASS-6905

---

packages/compass-shell/src/modules/runtime.js
packages/compass-shell/src/stores/store.js
packages/compass-shell/src/stores/store.spec.js

Make it so that the `enableShell` toggle does not only control whether the shell is displayed, but actually create or tear down the shell runtime instance in according to it.
This obviously does not fix any issues on its own, but it does unblock development on e.g. https://github.com/mongodb-js/compass/pull/4484, and seems like a good idea in general, because it also gives users a workaround around not just the current Electron bug, but also future problems where having the shell process running in the background leads to undesirable behavior in the main Compass app.

fix(compass-shell): let enableShell setting control runtime start/stop

---

packages/compass-crud/src/stores/crud-store.ts
packages/compass-e2e-tests/tests/collection-documents-tab.test.ts

fix(telemetry): track `has_sort`

---

packages/compass-connections/src/components/connecting/connecting.tsx
packages/compass-connections/src/stores/connections-store.ts

feat(compass-connections): add connecting message when connecting with OIDC COMPASS-6875

---

packages/compass-e2e-tests/tests/connection-form.test.ts
packages/compass-e2e-tests/tests/oidc.test.ts
packages/compass-preferences-model/src/feature-flags.ts
packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.spec.tsx
packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-tab.spec.tsx

feat(connection-form): set enable OIDC auth mechanism feature flag to released COMPASS-6803

---

packages/compass-editor/src/json-editor.tsx
packages/compass-explain-plan/src/components/explain-tree/clock.tsx
packages/compass-explain-plan/src/components/explain-tree/explain-tree-stage.spec.tsx
packages/compass-explain-plan/src/components/explain-tree/explain-tree-stage.tsx

This PR covers a few non-blocking points identified in the [Visual updates to explain plan PR](https://github.com/mongodb-js/compass/pull/4487):
- Multiline editor will take care of having a minimum height if there are actions like format, copy, custom, etc to be shown as well. Earlier the container was overflowing on top of the action buttons.
- Clock in explain plan visual tree will now take care of accommodating bigger milliseconds numbers as well but normalising them to nearest time value (seconds, minutes, hours). Earlier these numbers would have overflown out of the container
- Shard card in the explain plan visual tree will now trim the shard name in the middle, whenever there is a possibility of the overflow of the name. Earlier we were trimming at the end (CSS) but it is quite …

chore(compass-explain-plan, compass-components): explain plan visual improvements follow up

---

package-lock.json
packages/data-service/package.json

Detect by URI if a user tries to connect to Atlas. If errors, overwrite the error message to help users troubleshoot the issue and point to the fact, that their IP might not be whitelisted in the Atlas network settings.

feat: add Atlas error message when connection fails due to IP access issue COMPASS-6842

---

package-lock.json
packages/compass-aggregations/package.json
packages/compass-collection/package.json
packages/compass-connections/package.json
packages/compass-e2e-tests/package.json
packages/compass-explain-plan/package.json
packages/compass-import-export/package.json
packages/compass-indexes/package.json
packages/compass-schema/package.json
packages/compass-shell/package.json
packages/compass/package.json
packages/connection-form/package.json
packages/connection-model/package.json
packages/data-service/package.json
packages/databases-collections/package.json
scripts/package.json

chore(deps): bump mongosh and driver to latest

---

package-lock.json

Trying to figure out how this managed to land in main, but at least this should fix it

chore: fix package lock

---

scripts/update-electron.js

So the autoupdate of `electron` won't try to auto-downgrade

chore(scripts): auto-update electron independently from node

---

packages/compass-import-export/src/utils/collection-stream.ts

https://github.com/mongodb/node-mongodb-native/blob/dc068ac1f6e91794836e103f8a06c2580405ad76/src/bulk/common.ts#L1092-L1095

fix(import): use bulkWrite correctly COMPASS-6928

---

package-lock.json
packages/compass-components/src/components/document-list/element.tsx

COMPASS-6939
*before*
https://github.com/mongodb-js/compass/assets/1791149/679b95ec-0f38-40c5-8df6-89f426df1f22
*after*
https://github.com/mongodb-js/compass/assets/1791149/334712f1-3a27-4145-867d-7f9032f205e8

feat(compass-crud): auto expand object and array field types on field add COMPASS-6939

---

packages/compass-components/src/components/guide-cue/guide-cue-service.spec.ts
packages/compass-components/src/components/guide-cue/guide-cue-service.ts
packages/compass-e2e-tests/helpers/compass.ts
packages/compass-e2e-tests/index.ts

feat(guide-cue): disable in tests

---

packages/compass-preferences-model/src/feature-flags.ts

chore(preferences-model): add feature flag for ai query input COMPASS-6955

---

.github/workflows/codeql.yml

chore(github-workflows): fix for codeql failing on PRs because of yml format error

---

package-lock.json
package.json
packages/compass/package.json

truncate origins for vulnerability reports in jira

chore(ci): truncate origins for vulnerability reports in jira

---

packages/compass-app-stores/src/stores/instance-store.js
packages/compass-import-export/src/components/import-toast.tsx
packages/compass-import-export/src/import/import-csv.spec.ts
packages/compass-import-export/src/import/import-csv.ts
packages/compass-import-export/src/import/import-json.spec.ts
packages/compass-import-export/src/import/import-json.ts
packages/compass-import-export/src/import/import-types.ts
packages/compass-import-export/src/import/import-utils.spec.ts
packages/compass-import-export/src/import/import-utils.ts
packages/compass-import-export/src/modules/import.ts

In this PR we add a signal for bloated documents identified during import.

feat(compass-import-export): signal for bloated documents during import

---

.github/workflows/merge-bump-packages-pr.yaml
package-lock.json

chore: workflow to auto merge the bumped packages PR

---

.github/workflows/start-beta.yml
scripts/release.js

Tested this on a separate repo: https://github.com/mcasimir/test-compass-release-workflow/commits/beta-releases

chore(ci): fix rejected push in release script

---

packages/compass-components/src/components/combobox-with-custom-option.tsx

Use the value from the `evt.target` to fix index creation. To test follow the steps:
1. Create and index and start typing in the field name text box
2. Select a field from the suggested field dropdown
3. Create and index 
The index should be created on the field selected from the dropdown. 
The bug is introduced in the PR https://github.com/mongodb-js/compass/pull/4479

fix: use value from the evt.target to fix index creation COMPASS-6981

---

.snyk
package-lock.json

I broke the .snyk file. This fixes it.

chore : ignore snyk js aggridcommunity 1932011 again

---

packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/index.ts
packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/use-case-card.tsx

Replaced placeholder copy with the actual copy for the Sort Stage Wizard.

chore: Updated copy for sort stage wizard COMPASS-7014

---

packages/compass-preferences-model/src/storage.spec.ts

test(preferences): add storage tests COMPASS-7037

---

package-lock.json
packages/data-service/package.json
packages/data-service/src/data-service.spec.ts
packages/data-service/src/data-service.ts
packages/data-service/src/instance-detail-helper.spec.ts
packages/data-service/src/instance-detail-helper.ts
packages/data-service/test/helpers.ts

A follow up of https://github.com/mongodb-js/mongodb-build-info/pull/22, which brings updated logic for fake deployment detection to Compass.

chore: fixes inaccurate detection of fake mongodb deployments - COMPASS-7045

---

.evergreen/functions.yml
package.json

chore(ci): retry publish-package-next

---

packages/atlas-service/src/main.spec.ts
packages/atlas-service/src/main.ts

For cases where we are racing events against each other, I forgot to clean up the unused event listeners being attached after `race` resolved. This patch adds abort controllers to the listeners to make sure we clean up after resolve

chore(atlas-service): clean up unused listeners

---

packages/connection-storage/src/connection-storage.spec.ts

tests(connection-storage): add appName tests COMPASS-7060

---

packages/atlas-service/src/main.spec.ts
packages/atlas-service/src/main.ts
packages/atlas-service/src/renderer.ts
packages/compass-query-bar/src/stores/ai-query-reducer.spec.ts
packages/compass-query-bar/src/stores/ai-query-reducer.ts

Update terminology to resolve a cofusion what user enters in UI and what user prompt we send to AI:
- **User input** - the user message from UI that should be converted into MQL.
- **User prompt** - the message that combines the user input and supplementary data that we merge together before sending it to AI, e.g. collection name, database name, scheme.

refactor: rename userPrompt to userInput

---

packages/databases-collections/src/components/drop-collection-modal.tsx

Whenever a user tries to drop a collection(let's say collection A), and does so successfully they have to type in the name of the collection. 
After that if they goto another collection(let's say collection B) and try to drop that collection as well, they see that in the prompt they still see the previously dropped collections' name(collection A).
[COMPASS-7035](https://jira.mongodb.org/browse/COMPASS-7035)
None
None

fix(drop-ui): clear drop collections input state if drop collections success COMPASS-7035

---

packages/compass-connections/src/components/connections.spec.tsx
packages/compass-connections/src/components/legacy-connections-modal.tsx
packages/compass/src/main/application.ts
packages/connection-storage/src/connection-storage.spec.ts
packages/connection-storage/src/connection-storage.ts
packages/connection-storage/src/renderer.ts

In this PR, we are showing a list of Legacy Connections to the user in the modal. 
<details>
<summary>Preview</summary>
https://github.com/mongodb-js/compass/assets/1305718/6a459a02-faa8-4b11-ad75-8ce7f572c2e7
</details>

feat(connections): show list of legacy connections COMPASS-7081

---

package-lock.json
package.json

I haven't tested `npm run publish-packages` or `npm run publish-packages-next` yet. Other than that I've verified that all usage of lerna (that I could find) works locally.

chore: use lerna 7 COMPASS-6941

---

packages/compass-query-bar/src/components/option-editor.tsx
packages/compass-query-bar/src/components/query-ai.spec.tsx
packages/compass-query-bar/src/components/query-ai.tsx
packages/compass-query-bar/src/components/query-option.tsx
packages/compass-query-bar/src/modules/change-filter.spec.ts
packages/compass-query-bar/src/stores/ai-query-reducer.ts

Track AI related events:
- Track a query is edited [COMPASS-7109](https://jira.mongodb.org/browse/COMPASS-7109)
- Track a prompt is submitted [COMPASS-7110](https://jira.mongodb.org/browse/COMPASS-7110)

feat: track AI related events COMPASS-7109, COMPASS-7110

---

packages/compass-aggregations/src/modules/pipeline-builder/pipeline-ai.ts
packages/compass-query-bar/src/stores/ai-query-reducer.spec.ts
packages/compass-query-bar/src/stores/ai-query-reducer.ts

COMPASS-7137
Adds some of the events in the [tracking plan](https://docs.google.com/spreadsheets/d/1Wi7np8CooM0b3xPHZNd-iYst_DnKEo7FBswbnSXKoys/edit#gid=953290655).

chore(compass-query-bar, compass-aggregations): add telemetry events for failed ai and success ai COMPASS-7137

---

packages/connection-storage/src/connection-storage.spec.ts
packages/connection-storage/src/connection-storage.ts

fix(connections): add support for downgrade to a version with storage-mixin COMPASS-7174

---

packages/atlas-service/src/main.spec.ts
packages/atlas-service/src/main.ts

Based on discussions with @addaleax, I'm refactoring how oidc-plugin is used by atlas service to a more idiomatic approach: instead of keeping access token and auth state in sync with the plugin, we just always request token directly from the plugin

chore(atlas-service): always use requestToken to get token from oidc-plugin

---

package-lock.json

Reverts mongodb-js/compass#4778

Revert "chore(deps): bump mongodb from 5.7.0 to 5.8.0"

---

packages/compass-preferences-model/src/feature-flags.ts

feat(feature-flag): Add feature flag for atlas search index management COMPASS-7161

---

packages/atlas-service/src/main.spec.ts
packages/atlas-service/src/main.ts
packages/atlas-service/src/renderer.ts
packages/atlas-service/src/util.ts
packages/compass-aggregations/src/modules/pipeline-builder/pipeline-ai.ts
packages/compass-query-bar/src/stores/ai-query-reducer.ts

Update throwIfNotOk so it returns a custom AIError status codes.

feat: handle 406 error message COMPASS-7189

---

packages/connection-storage/package.json
packages/connection-storage/src/main.ts

Add missing exported files, and label production dependencies as such. Also export `getConnectionTitle` from the main exports and not only the renderer since that would be required for using this package inside the VSCode extension, if we ever want to make that happen.

fix(connection-storage): fix package.json

---

packages/atlas-service/src/main.ts

fix(atlas-service): deduplicate log id

---

packages/compass/release/fixtures/config.json
packages/compass/release/fixtures/expected-beta.json
packages/compass/release/fixtures/expected-ga.json
packages/hadron-build/commands/upload.js
packages/hadron-build/test/upload.test.js

Since the bump to Electron 23 in 80a9e175edd3/Compass 1.38, Windows 7/8/8.1 is no longer a set of platforms that we support, see https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice.
This change reflects that in our download center descriptions.

chore: clarify that Compass only supports Windows 10+ COMPASS-7219

---

packages/atlas-service/src/main.spec.ts
packages/atlas-service/src/main.ts
packages/atlas-service/src/util.ts

COMPASS-7223
Two changes needed to incorporate the /hello endpoint
- the URL needed to be tweaked, as the old URL required auth (see [CLOUDP-200492](https://jira.mongodb.org/browse/CLOUDP-200492) for details)
- the response when the feature is disabled is actually just null (as per the [API spec](https://docs.google.com/document/d/1VplQzRSdUOf0NU-guhorKC4WmJMsoyItcD16uaolGYA/edit#bookmark=id.sactqldm5fym))
So far just manually tested

COMPASS-7223: tweaks to incorporate hello endpoint

---

package-lock.json
packages/compass-connections/package.json
packages/connection-form/package.json
packages/data-service/package.json
packages/data-service/src/instance-detail-helper.spec.ts
packages/data-service/src/instance-detail-helper.ts
packages/data-service/src/run-command.ts
packages/data-service/test/helpers.ts
packages/instance-model/index.d.ts
packages/instance-model/lib/model.js

feat(data-service): setup local atlas detection COMPASS-7213

---

packages/compass-settings/src/components/settings/atlas-login.spec.tsx
packages/compass-settings/src/components/settings/atlas-login.tsx

chore(settings): update atlas settings text and icon

---

packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-stages.tsx
packages/compass-components/src/components/generative-ai/ai-entry-svg.tsx
packages/compass-components/src/components/generative-ai/ai-experience-entry.tsx
packages/compass-components/src/components/generative-ai/generative-ai-input.tsx
packages/compass-query-bar/src/components/query-bar.tsx

chore(compass-components): styling ai entry and exit button

---

packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.tsx
packages/compass-indexes/src/components/search-indexes-modals/update-search-index-modal.spec.tsx
packages/compass-indexes/src/modules/search-indexes.spec.ts
packages/compass-indexes/src/modules/search-indexes.ts

fix(search-indexes): clean up the modal state and do not update on no change

---

packages/compass-e2e-tests/helpers/compass.ts

chore(compass-e2e): use atlas-dev for e2e tests COMPASS-7245

---

packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
packages/compass-e2e-tests/tests/collection-import.test.ts
packages/compass-e2e-tests/tests/instance-sidebar.test.ts

Attempting to debug the frequent flake.

chore: screenshot the moment before clicking the add database button in the sidebar COMPASS-7086

---

packages/compass-components/src/components/generative-ai/generative-ai-input.spec.tsx
packages/compass-components/src/components/generative-ai/generative-ai-input.tsx
packages/compass-e2e-tests/tests/collection-ai-query.test.ts

Currently, we use the following error: `Something went wrong, please try again later. If the error persists, try changing your prompt.`, but it sounds like an unexpected error that we don't know how to handle. We want it to be a bit more informative for users like `Sorry, we were unable to generate the query, please try again. If the error persists, try changing your prompt.`.

refactor: update query generation error message COMPASS-7257

---

package-lock.json
packages/compass-preferences-model/src/storage.spec.ts
packages/compass-preferences-model/src/storage.ts
packages/compass-user-data/package.json
packages/compass-user-data/src/user-data.ts
packages/compass/src/main/index.ts

fix: atomic writes to preferences COMPASS-7270 COMPASS-7269 

---

packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.tsx
packages/compass-indexes/src/modules/search-indexes.ts

fix(search-indexes): avoid flicker when modal closes COMPASS-7248

---

packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-ai.tsx
packages/compass-components/src/components/feedback-popover.spec.tsx
packages/compass-components/src/components/feedback-popover.tsx
packages/compass-query-bar/src/components/query-ai.tsx

- COMPASS-7211: Record users' positive or negative feedback even if they did not provide a feedback text.
- COMPASS-7251: Show a confirmation toast when feedback is submitted

feat: improve AI feedback experience COMPASS-7211, COMPASS-7251

---

packages/compass-aggregations/src/modules/pipeline-builder/pipeline-ai.ts
packages/compass-query-bar/src/stores/ai-query-reducer.ts

COMPASS-7250
To help us understand what sorts of errors folks are running into a lot.

chore(generative-ai): add error codes to fetch error telemetry COMPASS-7250

---

package-lock.json
packages/hadron-build/package.json

This should fix the `Error: undefined` in the publish flow when file upload fails

fix(build): bump devtools-github-repo to fix error logs

---

packages/compass-crud/src/stores/crud-store.spec.ts
packages/compass-crud/src/stores/crud-store.ts

fix(insert-document): handle invalid bson COMPASS-7316

---

configs/eslint-config-compass/index.js
packages/atlas-service/src/store/atlas-signin-reducer.spec.ts
packages/atlas-service/src/store/atlas-signin-reducer.ts
packages/compass-crud/src/components/editable-document.tsx
packages/compass-crud/src/components/table-view/cell-editor.tsx
packages/compass-schema/src/stores/store.js
packages/compass-shell/src/plugin.spec.jsx
packages/compass/src/main/window-manager.ts
packages/ssh-tunnel/src/index.ts

Replace, or where unused remove, usage of `process.nextTick()` and `setImmediate()`, both of which are Node.js-specific APIs for async deferral for which browser-compatible replacements with near-identical behavior exist.
Add linting rules to prevent usage of these methods. There might be a way to scope these linting rules to only the packages that we intend to use in browser environments, or exclude them from applying to test files. However, that seems unnecessary, given that the replacements are no harder to use, so a consistent style across the entire Compass codebase seems preferable.

chore: avoid process.nextTick() and setImmediate() COMPASS-7314

---

packages/data-service/src/data-service.spec.ts

This has been causing CI failures on main.

fix(data-service): relax getSearchIndexes error message test

---

package-lock.json
packages/compass-logging/package.json
packages/data-service/src/connect-mongo-client.ts
packages/ssh-tunnel/package.json
packages/ssh-tunnel/src/index.ts

chore(ssh-tunnel): add logging and improve displayed error message COMPASS-7336

---

package-lock.json
packages/compass-components/package.json
packages/compass-components/src/components/leafygreen.tsx
packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
packages/compass-indexes/src/components/search-index-template-dropdown/index.tsx
packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.tsx
packages/compass-indexes/src/modules/search-indexes.ts

In this PR, implemented following UI fixes:
1. Render small segmented tabs for sub-indexes tabs.
2. In create/update modal, move templates info icon next to its label.
3. Remove spacing (top/bottom) around Index Definition Editor.
4. After create/update/delete of search index, the toast should variant should be 'progress', not success.
<table>
<tr>
<td> Old
<td> New
<tr> 
<td> 
<td> 
<tr>
<td>
<td>
<tr>
<td>
<td><img width="566" alt="image" src="https://github.com/mongodb-js/compass/assets/1305718/0b8af45c-f238-4461-bc91-e60b0d940811">
<tr>
<td>
<td>
</table>

fix(search-indexes): ui fixes COMPASS-7304

---

packages/data-service/src/data-service.spec.ts
packages/data-service/src/data-service.ts

feat(bulk-update): add data-service method to retrieve before/after documents for update preview

---

packages/compass-preferences-model/src/feature-flags.ts

chore: add feature flags for bulk operations COMPASS-7324

---

packages/compass-components/src/components/guide-cue/guide-cue-service.ts
packages/compass-crud/src/components/crud-toolbar.spec.tsx
packages/compass-crud/src/components/crud-toolbar.tsx
packages/compass-crud/src/components/delete-data-menu.tsx
packages/compass-crud/src/components/document-list.tsx

_no release notes because it's under a feature flag._

feat: add delete button next to querybar COMPASS-7324

---

packages/compass-aggregations/src/utils/pipeline-storage.ts
packages/compass-user-data/src/index.ts
packages/compass-user-data/src/user-data.spec.ts
packages/compass-user-data/src/user-data.ts

- Export `Stats` as a custom type, rather than relying on the Node.js `fs` module’s `Stats` type. While this means duplicating code, it also ensures that our *interface* for `UserData` is something that could be implemented without reliance on a Node.js environment.
- Refactor the `UserData` class to avoid separate code paths for reading file contents with and without stats, to reduce code duplication.
- Adjust tests that expect exceptions to fail if no exception was thrown (rather than only fail if the wrong one was thrown), and adjust one error message test to also run fine on Node.js 20.

chore(compass-user-data): refactor filesystem stats handling COMPASS-7313

---

package-lock.json
packages/compass-crud/package.json
packages/compass-crud/src/components/bulk-delete-modal.spec.tsx
packages/compass-crud/src/components/bulk-delete-modal.tsx
packages/compass-crud/src/components/document-list.tsx
packages/compass-crud/src/stores/crud-store.spec.ts
packages/compass-crud/src/stores/crud-store.ts

feat: delete bulk operation modal COMPASS-7326

---

packages/compass-crud/src/stores/crud-store.ts

feat: add feedback toasts for delete bulk ops COMPASS-7328

---

.evergreen/generative-ai-accuracy-test.yml

Got the error
```
parsing config file: getting includes: load project error(s): retrieving file for include './functions.yml': fetching project file for project '10gen-compass-main' at revision '...': Requested file at ./functions.yml not found
```

chore(generative-ai): update ai accuracy tests evergreen include path

---

package-lock.json
packages/atlas-service/package.json
packages/compass-aggregations/package.json
packages/compass-field-store/package.json
packages/compass-generative-ai/package.json
packages/compass-import-export/package.json
packages/compass-query-bar/package.json
packages/compass-schema/package.json

chore(deps): bump mongodb-schema to 12.0.0 COMPASS-7124

---

packages/compass-e2e-tests/tests/atlas-login.test.ts
packages/compass-preferences-model/src/feature-flags.ts
packages/compass-preferences-model/src/utils.ts

COMPASS-7226
Now that the feature is released we don't need to have this preference anymore.

chore(compass-preferences-model): remove bypass ai hello check preference COMPASS-7226

---

packages/compass-components/src/components/leafygreen.tsx
packages/compass-crud/src/components/bulk-update-dialog.spec.tsx
packages/compass-crud/src/components/bulk-update-dialog.tsx
packages/compass-crud/src/stores/crud-store.ts

Follow-up from https://github.com/mongodb-js/compass/pull/5007

feat: reset the bulk update modal when re-opened COMPASS-7325

---

.gitattributes

chore(bson-transpilers): hide Github diffs for bson-transpilers generated file changes

---

packages/compass-crud/src/stores/crud-store.ts

Same as https://github.com/mongodb-js/compass/pull/5011 but for updates.

feat: add feedback toasts for bulk updates COMPASS-7327

---

packages/compass-crud/src/components/json-editor.tsx

slack convo
| - | - |
| <img width="750" alt="Screenshot 2023-11-09 at 3 08 43 PM" src="https://github.com/mongodb-js/compass/assets/1791149/18624c2b-f32a-4b42-9873-513466a9a041"> | <img width="760" alt="Screenshot 2023-11-09 at 3 07 29 PM" src="https://github.com/mongodb-js/compass/assets/1791149/33ac348a-b04e-4f95-9b27-2336096974c9"> |

chore(crud): add minLines to crud json editor for smaller docs design

---

packages/compass-aggregations/src/components/aggregation-side-panel/index.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
packages/compass-crud/src/components/view-switcher.tsx
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-query-bar/src/components/query-bar.tsx
packages/compass-shell/src/components/shell-header/shell-header.spec.tsx
packages/compass-shell/src/components/shell-header/shell-header.tsx
packages/compass-sidebar/src/components/navigation-items.spec.tsx
packages/compass-sidebar/src/components/navigation-items.tsx

Removes "hint" guide cues from the UI. Many of them were to signal new features that are not as new anymore, and users seem to prefer other indications.

feat: remove outdated guide cues COMPASS-7396

---

packages/compass-components/src/components/document-list/document-actions-group.spec.tsx
packages/compass-components/src/components/document-list/document-actions-group.tsx

Slack conversation: https://mongodb.slack.com/archives/GDTJXPHD0/p1699634338997979?thread_ts=1698672833.818749&cid=GDTJXPHD0

chore(compass-components): add tooltips to doc actions

---

packages/connection-storage/src/connection-secrets.spec.ts
packages/connection-storage/src/connection-secrets.ts

fix(connection-storage): remove oidc serialized state from connection  COMPASS-7453

---

packages/compass-aggregations/src/modules/side-panel.spec.ts
packages/compass-aggregations/src/stores/store.ts

Make the wizard panel hidden by default

feat(stage-wizard): wizard panel hidden by default

---

packages/compass-crud/src/components/bulk-delete-modal.spec.tsx
packages/compass-crud/src/components/bulk-delete-modal.tsx
packages/compass-crud/src/components/bulk-update-dialog.spec.tsx
packages/compass-crud/src/components/bulk-update-dialog.tsx
packages/compass-crud/src/components/document-list.tsx
packages/compass-crud/src/stores/crud-store.ts

fix(crud): don't show the number of documents if it is null/undefined COMPASS-7454

---

packages/compass-crud/src/components/bulk-delete-modal.tsx
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/collection-bulk-delete.test.ts

chore: add e2e tests to delete modal

---

packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/use-case-card.tsx

Fixes this error caused by wizard

chore(aggregations): fix error in console

---

packages/compass-saved-aggregations-queries/src/components/aggregations-queries-list.test.tsx
packages/compass-saved-aggregations-queries/src/components/aggregations-queries-list.tsx
packages/compass-saved-aggregations-queries/src/stores/index.ts

chore: filter out update queries from My Queries

---

packages/compass-crud/src/components/bulk-delete-modal.spec.tsx
packages/compass-crud/src/components/bulk-delete-modal.tsx
packages/compass-crud/src/components/bulk-update-dialog.spec.tsx
packages/compass-crud/src/components/bulk-update-dialog.tsx
packages/compass-crud/src/components/readonly-filter.tsx

feat(bulk-update): render document count and restyle query preview 

---

packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx

feat(search-indexes): clarify search index management support

---

packages/compass-crud/src/components/bulk-update-dialog.spec.tsx
packages/compass-crud/src/components/bulk-update-dialog.tsx
packages/compass-crud/src/components/document-list.tsx
packages/compass-crud/src/stores/crud-store.spec.ts
packages/compass-crud/src/stores/crud-store.ts

feat: disable the update preview when transactions are not supported COMPASS-7449

---

packages/compass-components/src/components/toast-body.tsx
packages/compass-components/src/index.ts
packages/compass-crud/src/components/bulk-actions-toasts.spec.tsx
packages/compass-crud/src/components/bulk-actions-toasts.tsx
packages/compass-crud/src/stores/crud-store.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/collection-bulk-delete.test.ts
packages/compass-e2e-tests/tests/collection-bulk-update.test.ts
packages/compass-import-export/src/components/export-toast.tsx
packages/compass-import-export/src/components/import-toast.tsx

https://github.com/mongodb-js/compass/assets/1822138/a403f687-eabd-4a28-a7fc-d3c943c1dcd7

feat: extract toasts and add a CTA for refresh COMPASS-7457

---

packages/compass-e2e-tests/tests/connection-form.test.ts
packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.spec.tsx
packages/connection-form/src/utils/authentication-handler.spec.ts
packages/connection-form/src/utils/authentication-handler.ts

fix(connection-form): include OIDC in `$external` auth mechanism list COMPASS-7512

---

packages/compass-crud/src/components/bulk-actions-toasts.spec.tsx
packages/compass-crud/src/components/bulk-actions-toasts.tsx

feat: close toast when the refresh button is clicked COMPASS-7514

---

.github/workflows/codeql.yml

chore(code-ql): ignore scripts

---

.github/dependabot.yml

chore: add dependabot configuration file COMPASS-6454

---

packages/compass-crud/src/stores/crud-store.spec.ts

chore(compass-crud): add new preferences passing to bulk update test

---

packages/compass-aggregations/src/components/aggregation-side-panel/index.tsx
packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-editor.tsx
packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace/dnd-wrapper.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-ai.spec.tsx
packages/compass-aggregations/src/components/saving-pipeline-modal/saving-pipeline-modal.tsx
packages/compass-aggregations/src/components/stage-editor/stage-editor.tsx
packages/compass-aggregations/src/components/stage-preview/atlas-stage-preview.tsx
packages/compass-collection/src/components/collection-tab.tsx
packages/compass-connections/src/components/connections.tsx
packages/compass-connections/src/components/form-help/form-help.tsx
packages/compass-crud/src/components/crud-toolbar.tsx
packages/compass-crud/src/components/insert-document-dialog.tsx
packages/compass-home/src/components/home.tsx
packages/compass-indexes/src/stores/drop-index.tsx
packages/compass-query-bar/src/components/query-ai.spec.tsx
packages/compass-query-bar/src/components/query-history/favorite-list.tsx
packages/compass-query-bar/src/components/query-history/recent-list.tsx
packages/compass-query-bar/src/components/query-option.tsx
packages/compass-schema-validation/src/components/validation-editor/validation-editor.tsx
packages/compass-schema-validation/src/components/validation-states/validation-states.tsx
packages/compass-serverstats/src/components/current-op-component.jsx
packages/compass-serverstats/src/components/detailview-component.jsx
packages/compass-serverstats/src/components/server-stats-toolbar.tsx
packages/compass-shell/src/plugin.tsx
packages/compass-shell/src/stores/store.ts
packages/compass-sidebar/src/plugin.tsx
packages/compass/src/app/index.jsx
packages/databases-collections-list/src/items-grid.tsx

This patch replaces direct logger usage with a hook in components

chore(logging): use logger hook for tracking and logging in react components COMPASS-7407

---

packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
packages/compass-aggregations/src/stores/store.ts
packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
packages/compass-preferences-model/src/feature-flags.ts

refactor: remove stage wizard feature flag code COMPASS-6887

---

package-lock.json
packages/compass-aggregations/package.json
packages/compass-crud/package.json
packages/compass-import-export/package.json
packages/compass-indexes/package.json
packages/compass-query-bar/package.json
packages/compass-schema-validation/package.json
packages/connection-form/package.json
packages/databases-collections/package.json

Invalid date values would crash Compass when serialising the query. The fix in mongodb-query-parser detects these specific cases and serialise them with the value 'Invalid Date'.

fix(export,query-bar): bump mongodb-query-parser COMPASS-7515

---

packages/compass-e2e-tests/helpers/commands/listen-for-telemetry-events.ts

test(e2e): wait for new telemetry events COMPASS-7573

---

packages/compass-e2e-tests/helpers/commands/add-collection.ts
packages/databases-collections/src/components/create-namespace-modal.tsx

Can't recreate this locally, so this is a bit of a shot in the dark. But the test failure did point out that we don't scroll to the error banner so I fixed that as a drive-by.

chore(e2e): fix E2E test for adding a collection with a custom collation COMPASS-7569

---

.snyk

chore: ignore snyk vuln SNYK-JS-AGGRIDCOMMUNITY-1932011 COMPASS-7570

---

packages/compass-e2e-tests/tests/import-export-connections.test.ts

chore: re-enable the CLI connections tests on windows

---

.evergreen/tasks.in.yml

chore(ci): add functions in evergreen tasks.in

---

packages/mongodb-explain-compat/test/fixtures/unsharded-aggregate-on-mongos.7.2.in.json
packages/mongodb-explain-compat/test/fixtures/unsharded-aggregate-on-mongos.7.2.out.json
packages/mongodb-explain-compat/test/index.js

It doesn't look like code changes are necessary for us, so just adding example data as a test case here should be enough for this ticket.

chore(mongodb-explain-compat): add 7.2 mongos unsharded collection explain COMPASS-7603

---

packages/compass-crud/src/utils/cancellable-queries.ts

chore(compass-crud): prepare for unsharded collections in sharding catalog COMPASS-7602

---

packages/compass/src/app/index.tsx
packages/compass/src/main/logging.ts

see also https://github.com/mongodb-js/compass/pull/5448

chore: add renderer process unhandled rejection handler COMPASS-7268

---

packages/compass/src/main/handle-error.ts
packages/compass/src/main/handle-uncaught-exception.ts
packages/compass/src/main/handle-unhandled-rejection.ts
packages/compass/src/main/index.ts

reverting the revert to add it back again after we release
see also https://github.com/mongodb-js/compass/pull/5449

chore: add main process unhandled rejection handler COMPASS-7268

---

.evergreen/functions.yml
.evergreen/preinstall.sh

Reverts mongodb-js/compass#5470
node 20 is failing some tests

Revert "chore(ci): use node v20.11.1 in CI"

---

packages/compass-preferences-model/src/feature-flags.ts

chore: add feature flag for multiple connections

---

.evergreen/start-docker-envs.sh

Will not help us now, but should make figuring these errors easier in the future

ci(evergreen): use docker compose where available instead of standalone docker-compose

---

package-lock.json
packages/compass-components/src/index.ts
packages/connection-form/package.json
packages/connection-form/src/components/connection-form-actions.tsx
packages/connection-form/src/components/connection-form.spec.tsx
packages/connection-form/src/components/connection-form.tsx
packages/connection-form/src/hooks/use-connect-form.spec.ts
packages/connection-form/src/hooks/use-connect-form.ts
packages/connection-form/src/hooks/use-connection-color.spec.tsx
packages/connection-form/src/hooks/use-connection-color.ts

feature: adapt the connection form component to the new design guidelines COMPASS-7652

---

packages/connection-form/src/components/connection-form.tsx
packages/connection-form/src/hooks/use-connect-form.spec.ts
packages/connection-form/src/hooks/use-connect-form.ts

fix: review inconsistent behaviours in the connection modal form. COMPASS-7712

---

packages/compass-sidebar/src/components/multiple-connections/saved-connections/saved-connection-list.spec.tsx
packages/compass-sidebar/src/components/multiple-connections/saved-connections/saved-connection-list.tsx
packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
packages/connection-form/src/components/advanced-connection-options.tsx
packages/connection-form/src/components/connection-form-actions.tsx
packages/connection-form/src/components/connection-form-modal.tsx
packages/connection-form/src/components/connection-form.spec.tsx
packages/connection-form/src/components/connection-form.tsx
packages/connection-form/src/index.ts

https://jira.mongodb.org/browse/COMPASS-7709
Adding connection-form as a modal, to be opened from the sidebar.
Hint: Do hide whitespaces for the diff.

feat: connection form as a modal COMPASS-7709

---

packages/compass-e2e-tests/helpers/compass.ts
packages/compass-e2e-tests/tests/in-use-encryption.test.ts

chore(e2e): disable range test for 8.0+

---

packages/compass-aggregations/src/components/pipeline-toolbar/index.spec.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/index.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.spec.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.tsx
packages/compass-query-bar/src/components/query-bar.tsx

**Before**
https://github.com/mongodb-js/compass/assets/1305718/e3781089-f26a-4b4f-ae25-e1b4faa01246
**After**
https://github.com/mongodb-js/compass/assets/1305718/9e592090-66c7-424a-893a-04880d754c9a

chore(compass-aggregations): remove pipeline text from toolbar COMPASS-7742

---

packages/connection-form/src/components/form-help/form-help.tsx

fix(connection-form): dark mode support for new connection information cards COMPASS-7753

---

packages/compass/src/main/application.ts

Follow up to https://github.com/mongodb-js/compass/pull/4941
Add `localhost` to the allowed cloud URLs to authorize requests to MMS running locally.

fix(compass): set up local mms COMPASS-7767

---

packages/connection-form/src/components/connection-form.tsx

Improved styles for the modal form:
- the form takes most of the viewport height, with the content being scrollable
- the footer has a top border (something I missed in the first implementation 🤦 )
Both are behind the feature toggle.

chore(connection-form): update modal form styles COMPASS-7784

---

.github/workflows/authors-and-third-party-notices.yaml
.github/workflows/bump-packages.yaml
.github/workflows/publish-compass.yaml
.github/workflows/publish-packages.yaml
.github/workflows/start-beta.yml
.github/workflows/start-ga.yaml

chore(ci): use the same node and npm version as we do in EVG ci

---

.github/dependabot.yml
.github/workflows/update-electron.yaml

chore(ci): start using update-electron script again

---

.github/workflows/update-electron.yaml

chore(ci): update dependabot action

---

packages/compass-import-export/src/components/import-preview.tsx

COMPASS-7801
| ga | main | pr |
| - | - | - |
| <img width="925" alt="Screenshot 2024-03-28 at 2 26 40 PM" src="https://github.com/mongodb-js/compass/assets/1791149/59d34547-15b9-4a7e-8561-e790b5787fdf"> | <img width="919" alt="Screenshot 2024-03-28 at 2 14 22 PM" src="https://github.com/mongodb-js/compass/assets/1791149/41b9f816-7280-4655-9008-07f71606d39f"> | <img width="916" alt="Screenshot 2024-03-28 at 2 49 57 PM" src="https://github.com/mongodb-js/compass/assets/1791149/05823f51-3053-482c-a0d6-9f5816989473"> |

chore(import-export): update import csv table styles for LeafyGreen changes COMPASS-7801

---

packages/compass-app-stores/src/instances-manager.spec.ts
packages/compass-app-stores/src/instances-manager.ts
packages/compass-app-stores/src/plugin.tsx
packages/compass-app-stores/src/provider.ts
packages/compass-app-stores/src/stores/instance-store.spec.ts
packages/compass-app-stores/src/stores/instance-store.ts

This is first of the PR related to work in COMPASS-7718. It introduces MongoDBInstancesManager, an event emitter that also keep track of MongoDBInstances for connected connections.
MongoDBInstancesManager is suppose to help us in removing direct dependency on MongoDBInstance and DataService from plugins that are expected to be rendered even in the non-connected part of the application tree. These plugins for now are WorkspacesPlugin, Sidebar and all the global modals that the WorkspacesPlugin renders. Changes for the mentioned plugins will follow in upcoming PRs.

feat(compass-app-stores): introduce MongoDBInstancesManager for supporting workspace initialisation without DataService / MongoDBInstance COMPASS-7718

---

packages/compass-generative-ai/scripts/ai-accuracy-tests.ts

COMPASS-7757
Adds some time elapsed tracking to our accuracy tests, and a bit of cleanup on the stored db format.

chore(generative-ai): update accuracy test result format COMPASS-7757

---

packages/compass-components/src/hooks/use-confirmation.spec.tsx
packages/compass-components/src/hooks/use-confirmation.tsx

This patch introduces a confirmation id an a `key` prop on the confirmation modal component to make sure that the React state of the modal is completely reset every time a new confirmation request is happening.
The fix for the initially reported issue is available in leafygreen, but updating leafygreen as always is a bit more complicated that just bumping a single version of a single package, so we are fixing the issue on our side for now. This is also something we probably want to do anyway to make sure that every confirmation request done through `showConfirmation` method is starting from the clean slate without relying on leafygreen implementation details

fix(components): make sure that confirmation modal always asks for confirmation input COMPASS-7613

---

packages/databases-collections/src/components/rename-collection-modal/rename-collection-modal.spec.tsx
packages/databases-collections/src/components/rename-collection-modal/rename-collection-modal.tsx

chore(databases-collections): fix typo in rename collection banner

---

packages/compass-app-stores/package.json
packages/compass-app-stores/src/instances-manager.spec.ts
packages/compass-app-stores/src/provider.ts
packages/compass-connections/src/connection-info-provider.tsx
packages/compass-connections/src/connection-scoped-app-registry.spec.ts
packages/compass-connections/src/connection-scoped-app-registry.ts
packages/compass-connections/src/provider.ts
packages/compass-field-store/package.json
packages/compass-field-store/src/index.spec.ts
packages/compass-field-store/src/modules/index.ts
packages/compass-field-store/src/stores/field-store-service.ts
packages/compass-field-store/src/stores/hooks.ts
packages/compass-field-store/src/stores/store.spec.ts
packages/compass-indexes/src/components/indexes/indexes.tsx
packages/compass-schema/src/components/compass-schema.tsx
packages/compass-shell/package.json
packages/compass-shell/src/plugin.spec.tsx
packages/compass-web/src/entrypoint.tsx
packages/compass/src/app/components/home.tsx
packages/connection-storage/src/provider.ts

Trying to cut down the size of #5679.
This one is simply moving ConnectionInfoProvider from connection-storage to compass-connections.

chore(compass-connections, connection-storage): moved ConnectionInfoProvider and the locators to @mongodb-js/compass-connections

---

.github/workflows/codeql.yml

chore(ci): update codeql queries

---

packages/compass-generative-ai/scripts/ai-accuracy-tests.ts

COMPASS-7850
This pr adds two accuracy tests to our daily accuracy tests. Will likely do another pr adding more tests this week. These tests are also subject to change. Our existing tests could also probably be reduced as some of them are a bit too simple and redundant. 
Evergreen:  https://spruce.mongodb.com/commits/compass-generative-ai-accuracy

chore(generative-ai): add query and aggregation accuracy tests COMPASS-7850

---

packages/atlas-service/src/atlas-service.spec.ts
packages/atlas-service/src/atlas-service.ts
packages/compass-generative-ai/src/atlas-ai-service.spec.ts
packages/compass-generative-ai/src/atlas-ai-service.ts

fix(generative-ai): parse ai response correctly COMPASS-7780

---

packages/compass-e2e-tests/tests/database-collections-tab.test.ts

https://spruce.mongodb.com/task/10gen_compass_main_ubuntu_test_web_sandbox_firefox_6625b692ee7196000714947a_24_04_22_01_00_02/tests?execution=0&sortBy=STATUS&sortDir=ASC

chore(e2e): refresh before checking if the badge is there COMPASS-7878

---

packages/compass-sidebar/src/components/legacy/sidebar-databases-navigation.tsx
packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.tsx
packages/databases-collections-list/src/collections.tsx
packages/databases-collections-list/src/databases.tsx
packages/databases-collections/src/collections-plugin.spec.tsx
packages/databases-collections/src/collections-plugin.tsx
packages/databases-collections/src/components/collections.tsx
packages/databases-collections/src/components/databases.tsx
packages/databases-collections/src/index.ts
packages/databases-collections/src/modules/collections.ts
packages/databases-collections/src/modules/databases.ts
packages/databases-collections/src/stores/drop-namespace.spec.tsx
packages/databases-collections/src/stores/drop-namespace.tsx

chore: adapt DropNamespacePlugin to multiple connections COMPASS-7863

---

packages/compass/src/app/components/home.tsx
packages/compass/src/app/components/workspace.tsx

These changes I missed in my previous PR.

chore: add DropNamespacePlugin to multiConnections render tree and also add scopeName on AppRegistries

---

packages/compass-e2e-tests/index.ts

Once a second for 60 seconds after cleanup(), list the active resources still in use. To try and debug why it sometimes hangs.

chore(e2e): print active resources

---

packages/compass-workspaces/src/components/workspaces.tsx

chore(collection-header): remove semicolon

---

packages/compass-connections/src/components/legacy-connections-modal.tsx

fix(compass-connections): fixes CPU hikes because of bad useEffect dependency

---

.github/workflows/codeql.yml

Run scans on tags, also remove linting related warnings as they cause a lot noise on reports

chore(ci): run codeql scans on tags

---

packages/atlas-service/src/components/ai-signin-modal.tsx
packages/compass-settings/src/components/settings/settings-list.tsx

Remove "Preview" badging from the Atlas login modal and GenAI settings.

feat: remove the Preview badge COMPASS-7890

---

packages/compass-aggregations/src/components/create-view-modal/create-view-modal.tsx
packages/compass-aggregations/src/index.ts
packages/compass-aggregations/src/modules/create-view/index.spec.ts
packages/compass-aggregations/src/modules/create-view/index.ts
packages/compass-aggregations/src/modules/saving-pipeline.ts
packages/compass-aggregations/src/stores/create-view.spec.ts
packages/compass-aggregations/src/stores/create-view.ts
packages/compass-app-stores/src/stores/instance-store.spec.ts
packages/compass-app-stores/src/stores/instance-store.ts
packages/compass-sidebar/src/components/legacy/sidebar-databases-navigation.tsx
packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.tsx
packages/compass/src/app/components/workspace.tsx

In this PR we modified CreateViewPlugin to work with ConnectionsManager and expect connectionId to be passed alongside the eventParameters for 'open-create-view' event, to support creating views for multiple different connections.
The event 'view-created' that gets emitted after successfully creating view also gets passed with connectionId as extra args so that compass-app-stores can react only when instance's connectionId matches that of event's connectionId.
Notes for reviewers:
---
The first two commits (7f45bc593bdfb3db8a6b0d44e1d61e97f5c1bc45, f6c4baea880b3b680201a65470dc5b65b1e28b95) do not bring any functional change and are meant only to align the module's code with the rest of the modules.
So, for an easy diff experience you can check [those …

chore(compass-aggregations): adapt CreateViewPlugin to work with dynamically provided connectionId for supporting multiple connections COMPASS-7861

---

packages/compass/src/app/components/update-toasts.tsx
packages/compass/src/app/index.tsx

fix(auto-updates): only show toast when user updates

---

packages/bson-transpilers/symbols/python/templates.yaml

Remove the escape sentence as the returned value is using r string and no need to append double `\` to escape characters.
While using export to python the following query 
```js
{message: {$regex: /\d+/}}
```
will be translated into 
```python
{
'message': {
'$regex': re.compile(r"\\d+")
}
}
```
----
The expected outcome should be:
```python
{
'message': {
'$regex': re.compile(r"\d+")
}
}
```
or
```python
{
'message': {
'$regex': re.compile("\\d+")
}
}
```
Since r string(`r""`) is used in the return value, an extra escape for the `\` is redundant and breaks the semantic of the original regex.

fix(bson-transpilers-python-regex): No need to escape `\` in regex

---

packages/compass-generative-ai/src/components/generative-ai-input.tsx

COMPASS-7901
Improves the look of the animation and makes the hover and focus state not override the styles.
*before*
https://github.com/mongodb-js/compass/assets/1791149/ed5c0797-0083-4230-a235-2e283f846d0c
*after*
https://github.com/mongodb-js/compass/assets/1791149/43a6f428-8396-41a4-9983-3849bb2195ec

chore(generative-ai): update gen ai in progress animation COMPASS-7901

---

THIRD-PARTY-NOTICES.md
packages/compass-components/src/components/item-action-controls.spec.tsx
packages/compass-components/src/components/item-action-controls.tsx
packages/compass-connections-navigation/src/connection-item.tsx
packages/compass-connections-navigation/src/connections-navigation-tree.spec.tsx
packages/compass-connections-navigation/src/constants.tsx
packages/compass-connections-navigation/src/tree-item.tsx
packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.tsx
packages/compass-sidebar/src/components/multiple-connections/saved-connections/saved-connection-list.tsx
packages/compass-sidebar/src/components/multiple-connections/saved-connections/saved-connection.tsx
packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx

https://github.com/mongodb-js/compass/assets/1305718/d1769520-2f44-4387-b4f4-d3ed5e24a12e

feat(sidebar): add support to create db from connection COMPASS-7885

---

README.md
scripts/generate-readme-packages-overview.js

```bash
node scripts/generate-readme-packages-overview.js
```

chore: update README with latest packages and descriptions

---

packages/compass/src/app/components/update-toasts.tsx

Updates to the update/restart toasts' styles/copy

fix(compass): update toasts copy and button style

---

packages/hadron-build/lib/mac-notary-service.js

Missed this in 62dc601357ec992127 (sorry).

fix(hadron-build): add missing throw from recent change

---

packages/compass-crud/src/components/readonly-filter.tsx

There was some confusion around what the empty/uneditable text box in bulk updates and deletes represents. Instead of displaying "{}" in the text box, this PR changes it to read "None"
N/a
N/a

fix(bulk ops): clarify no filter applied text box for bulk deletes and updates

---

.evergreen/buildvariants.yml
.evergreen/config.json
.evergreen/tasks.yml

ci(tests): add e2e tests for 8.0 COMPASS-7951

---

packages/compass/src/main/menu.spec.ts
packages/compass/src/main/menu.ts

For multiple-connections:
- we remove 'Disconnect' from under 'Connect'
- 'New Window' is moved under 'Window'

fix: update connect menu for multiple connections COMPASS-7913

---

packages/compass-e2e-tests/tests/read-only.test.ts
packages/databases-collections/src/components/collections.tsx

This also fixes the E2E tests that were looking for wrong selectors so far and thus always passing.

fix(databases-collections): fixes the visible "Create collection" button despite Compass being in readonly mode

---

packages/compass-sidebar/src/components/legacy/sidebar.tsx

fix(compass-sidebar): ensure connection gets saved as favorite from old sidebar COMPASS-7980

---

package-lock.json
packages/compass-connections-navigation/src/constants.tsx
packages/compass-connections-navigation/src/item-actions.ts
packages/compass-connections/src/hooks/use-connection-repository.ts
packages/compass-shell/package.json
packages/compass-shell/src/components/compass-shell/tab-compass-shell.tsx
packages/compass-shell/src/components/shell-header/shell-header.tsx
packages/compass-shell/src/index.ts
packages/compass-shell/src/plugin.tsx
packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.tsx
packages/compass-workspaces/src/components/workspaces-provider.tsx
packages/compass-workspaces/src/components/workspaces.tsx
packages/compass-workspaces/src/index.ts
packages/compass-workspaces/src/provider.tsx
packages/compass-workspaces/src/stores/workspaces.ts
packages/compass-workspaces/src/types.ts
packages/compass/src/app/components/workspace.tsx

https://github.com/mongodb-js/compass/assets/10037761/990ae815-559a-4063-b063-b9366173706a
(might be missing something else in the list above so please feel free to mention it)

chore(compass-shell): adds support for opening shell for multiple connections COMPASS-7720

---

packages/hadron-build/commands/upload.js
packages/hadron-build/test/upload.test.js

chore(ci): set minimum macOs version to 10.15+ COMPASS-7990

---

packages/compass-aggregations/src/utils/modal-descriptions.tsx

chore(compass-aggregations): fixes the pipeline confirmation text COMPASS-7989

---

package-lock.json
packages/compass-connections-navigation/src/index.ts
packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.tsx
packages/compass-sidebar/src/components/use-filtered-connections.ts

This is to unblock any refactoring effort on the filter work

chore(compass-sidebar): moved existing filter logic to a separate hook

---

.github/workflows/authors-and-third-party-notices.yaml
docs/security-test-summary.md
package-lock.json
package.json
packages/atlas-service/src/main.spec.ts
packages/compass-connection-import-export/src/hooks/use-export.spec.ts
packages/compass-e2e-tests/tests/import-export-connections.test.ts
packages/compass-e2e-tests/tests/in-use-encryption.test.ts
packages/compass-e2e-tests/tests/no-network-traffic.test.ts
packages/compass-e2e-tests/tests/oidc.test.ts
packages/compass-e2e-tests/tests/protect-connection-strings.test.ts
packages/compass-export-to-language/src/modules/transpiler.spec.ts
packages/compass/src/main/auto-connect.spec.ts
packages/connection-form/src/components/connection-string-input.spec.tsx
packages/connection-form/src/utils/validation.spec.ts
packages/connection-info/src/connection-secrets.spec.ts
packages/connection-storage/src/encrypt.spec.ts
packages/connection-storage/src/import-export-connection.spec.ts
packages/data-service/src/connect-mongo-client.spec.ts
packages/data-service/src/csfle-collection-tracker.spec.ts
packages/ssh-tunnel/src/index.spec.ts
scripts/.eslintrc.js
scripts/generate-security-test-summary.ts
scripts/package.json
scripts/security-test-summary-template.md
scripts/tsconfig-lint.json

chore(ci): label security tests and generate summary report COMPASS-7960

---

.snyk

Refs: https://github.com/mongodb-js/compass/commit/613cff3a56cf44a177f

chore(ci): reinstate snyk ignore reason for ag-grid-community finding

---

packages/compass-workspaces/src/components/index.tsx
packages/compass-workspaces/src/index.spec.tsx

chore(compass-workspaces): fix for sidebar getting remounted on every render

---

.github/workflows/start-beta.yml
.github/workflows/start-ga.yaml

This is required for `gh workflow run` as added in e5750044d407147a6373.

fix(ci): pass github token to release scripts

---

scripts/release.js

Today in "Things that would have been prevented by TypeScript" :)

fix(ci): add missing `await`

---

scripts/release.js

fix(ci): add missing newline

---

package-lock.json
packages/compass-sidebar/package.json
packages/compass-sidebar/src/components/multiple-connections/connections-navigation.tsx
packages/compass-sidebar/src/components/use-filtered-connections.spec.ts
packages/compass-sidebar/src/components/use-filtered-connections.ts

(compass-sidebar): fixes disconnected item retaining its expanded state when connected again  COMPASS-7967

---

packages/compass-collection/src/components/collection-header-actions/collection-header-actions.spec.tsx
packages/compass-collection/src/components/collection-header-actions/collection-header-actions.tsx

fix(collection): hide edit view button in readonly mode COMPASS-7688

---

.evergreen/functions.yml

chore(ci): run `snyk monitor` on an ongoing basis COMPASS-8022

---

packages/compass-sidebar/src/components/use-filtered-connections.spec.ts

Must've been a bad automerge on main

fix(sidebar): fix import for createLogger method

---

THIRD-PARTY-NOTICES.md
package-lock.json
packages/compass-explain-plan/src/components/explain-plan-side-summary.tsx
packages/compass-explain-plan/src/components/explain-tree/explain-tree-data.ts
packages/compass-explain-plan/src/components/explain-tree/explain-tree-stage.tsx
packages/explain-plan-helper/package.json
packages/explain-plan-helper/src/index.spec.ts
packages/explain-plan-helper/src/index.ts
packages/explain-plan-helper/src/utils.spec.ts
packages/explain-plan-helper/src/utils.ts
packages/explain-plan-helper/test/fixtures/clustered_scan.json
packages/explain-plan-helper/test/fixtures/count_scan.json
packages/explain-plan-helper/test/fixtures/express_clustered_scan.json
packages/explain-plan-helper/test/fixtures/express_index_scan.json

chore(explain-plan-helper): add support for express plan COMPASS-7794

---

packages/compass-preferences-model/src/feature-flags.ts
packages/compass-query-bar/src/components/option-editor.spec.tsx

feat(query-bar): release query history autocompletion COMPASS-8096

---

packages/compass-connections-navigation/src/base-navigation-item.tsx
packages/compass-connections-navigation/src/utils.ts

I still have to get buy-in for this, but this is the PR so long.

fix(sidebar): Make the hover/active background effect take up the full element. ie. flush with the sides

---

packages/compass-components/src/components/workspace-tabs/tab.tsx
packages/compass-e2e-tests/helpers/commands/open-shell.ts
packages/compass-e2e-tests/helpers/commands/run-find-operation.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/my-queries-tab.test.ts
packages/compass-e2e-tests/tests/search-indexes.test.ts

* when you have multiple active connections that have the namespace
* when you have multiple active connections, and only one of them has the namespace
* when you have multiple active connections, and none of them have the namespace

chore(e2e): Add E2E tests for new My Queries use cases COMPASS-8152

---

packages/compass/src/main/menu.spec.ts
packages/compass/src/main/menu.ts

fix: rename Connect app menu item COMPASS-8161

---

package-lock.json
packages/compass-e2e-tests/tests/proxy.test.ts
packages/compass-preferences-model/package.json
packages/compass/package.json
packages/compass/src/app/utils/csp.ts
packages/compass/src/main/application.ts
packages/compass/src/main/window-manager.ts

feat(compass): apply proxy settings to electron app and session COMPASS-8143

---

.snyk

chore: push expiration date of SNYK-JS-AGGRIDCOMMUNITY-1932011 

---

packages/compass-e2e-tests/tests/oidc.test.ts

fix(e2e-tests): re-enable OIDC tests on 8.0.x COMPASS-7966

---

packages/compass-e2e-tests/tests/search-indexes.test.ts

fix(compass-e2e-tests): skip failing search index test COMPASS-8220

---

.github/workflows/authors-and-third-party-notices.yaml

Example failure: https://github.com/mongodb-js/compass/actions/runs/10592423499/job/29351719797

chore(ci): set `HADRON_DISTRIBUTION` for generated file update GH action

---

packages/compass-crud/src/components/crud-toolbar.spec.tsx
packages/compass-crud/src/components/crud-toolbar.tsx

Looks like we forgot to update this bit when docsPerPage was introduced.

fix(compass-crud): fix nextPage availability logic COMPASS-8239

---

packages/compass-explain-plan/src/stores/explain-plan-modal-store.ts
packages/data-service/src/data-service.ts

fix(explain-plan): use executionStats verbosity COMPASS-8263

---

README.md

```shell
node ./scripts/generate-readme-packages-overview.js
```
https://github.com/mongodb-js/compass/blob/main/scripts/generate-readme-packages-overview.js

chore: update readme with packages overview

---

packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace/dnd-wrapper.tsx
packages/compass-aggregations/src/components/saving-pipeline-modal/saving-pipeline-modal.tsx
packages/compass-aggregations/src/modules/is-new-pipeline-confirm.ts
packages/compass-connections/src/index.tsx
packages/compass-connections/src/stores/connections-store-redux.ts
packages/compass-crud/src/components/insert-document-dialog.tsx
packages/compass-import-export/src/components/export-modal.tsx
packages/compass-import-export/src/components/import-modal.tsx
packages/compass-saved-aggregations-queries/src/components/aggregations-queries-list.tsx
packages/compass-saved-aggregations-queries/src/stores/delete-item.ts
packages/compass-saved-aggregations-queries/src/stores/open-item.ts
packages/compass-shell/src/components/shell-info-modal/shell-info-modal.tsx
packages/compass-sidebar/src/components/csfle-connection-modal.tsx
packages/compass-telemetry/src/generic-track.ts
packages/compass-telemetry/src/index.ts
packages/compass-telemetry/src/ipc-track.ts
packages/compass-telemetry/src/provider.tsx
packages/compass-telemetry/src/telemetry-events.ts
packages/compass-telemetry/src/types.ts
packages/compass/src/app/utils/telemetry.ts
packages/databases-collections/src/components/rename-collection-modal/rename-collection-modal.tsx
packages/databases-collections/src/modules/create-namespace.ts
packages/databases-collections/src/stores/drop-namespace.tsx

Other pre-req for: https://jira.mongodb.org/browse/COMPASS-8058
- More detailed types for telemetry events
- Make sure that connection scoped events have a 3rd param for track, and that other events have only 2.

chore: improve telemetry types for connection events

---

packages/compass-e2e-tests/tests/logging.test.ts
packages/compass-telemetry/src/telemetry-events.ts
packages/compass/src/app/utils/telemetry.spec.ts
packages/compass/src/app/utils/telemetry.ts

I missed this in https://github.com/mongodb-js/compass/pull/6166

fix(telemetry): add support for multiple kms providers

---

package-lock.json
package.json

Update `express` to update `body-parser` to update `send` to resolve autogenerated vuln tickets COMPASS-8293 through COMPASS-8297

chore(deps): update express COMPASS-8293

---

.github/ISSUE_TEMPLATE/config.yml

Update to the Github issue submission configuration to change "Report a Bug" link to  https://jira.mongodb.org/  from https://jira.mongodb.org/projects/COMPASS/summary, as the latter presents an error message when not logged in to the MongoDB Jira instance.

chore: Change "Report a Bug" link in repo COMPASS-8267

---

packages/compass-aggregations/src/modules/aggregation.ts
packages/compass-telemetry/src/telemetry-events.ts

https://mongodb.slack.com/archives/G2L10JAV7/p1726057446618879
COMPASS-8301

chore(aggregations): telemetry add stage names to aggregation executed COMPASS-8301

---

packages/compass-indexes/src/components/indexes/indexes.spec.tsx
packages/compass-indexes/src/components/regular-indexes-table/property-field.tsx
packages/compass-indexes/src/components/regular-indexes-table/regular-indexes-table.spec.tsx
packages/compass-indexes/src/components/regular-indexes-table/regular-indexes-table.tsx
packages/compass-indexes/src/components/regular-indexes-table/status-field.tsx
packages/compass-indexes/src/modules/regular-indexes.spec.ts
packages/compass-indexes/src/modules/regular-indexes.ts
packages/compass-indexes/src/modules/rolling-indexes-service.ts

feat(compass-indexes): Poll rolling indexes where available, add status column COMPASS-8217  COMPASS-8329

---

packages/compass-e2e-tests/helpers/compass.ts

This adds runtime options when starting the Electron app in e2e tests to write the Electron log into a file which will be attached to the task on Evergreen.

chore(ci): log electron app messages

---

packages/compass/src/main/application.ts

fix(proxy): show friendly error when proxy config is not supported COMPASS-8345

---

package-lock.json
packages/compass-web/package.json

COMPASS-8350
For [cookie](https://www.npmjs.com/package/cookie) ^0.7.0

chore(deps): update express for new cookie dep version COMPASS-8350

---

packages/compass-sidebar/src/components/connections-filter-popover.tsx

Fixing a broken comment in `connections-filter-popover.tsx`

Update comment in connections-filter-popover.tsx

---

configs/webpack-config-compass/package.json
package-lock.json
packages/atlas-service/package.json
packages/compass-crud/package.json
packages/compass-e2e-tests/package.json
packages/compass-explain-plan/package.json
packages/compass-find-in-page/package.json
packages/compass-import-export/package.json
packages/compass-indexes/package.json
packages/compass-query-bar/package.json
packages/compass-schema-validation/package.json
packages/compass-shell/package.json
packages/compass-utils/package.json
packages/compass-web/package.json
packages/compass/package.json
packages/compass/src/main/menu.spec.ts
packages/compass/src/main/menu.ts
packages/connection-storage/package.json
packages/hadron-build/package.json
packages/hadron-ipc/package.json
scripts/package.json

chore(deps): update electron COMPASS-8505

---

.github/workflows/bump-packages.yaml
.github/workflows/update-electron.yaml

Reverts mongodb-js/compass#6536 since the app now has PR permissions.

chore(ci): revert "use the devtools bot user token for PRs"

---

packages/compass-components/src/components/file-input.spec.tsx
packages/compass-components/src/components/file-input.tsx
packages/compass-e2e-tests/helpers/commands/connect-form.ts

Use Unicode ellipses and use consistent language for the FileInputBackendContext wrappers.

chore(compass-components): small editorial fixes for FileInput

---

packages/compass-crud/src/stores/crud-store.ts

Sorta related https://jira.mongodb.org/browse/COMPASS-8529

fix(crud): don't fallback to zero if the count cannot be determined

---

.github/workflows/authors-and-third-party-notices.yaml

Without this, Evergreen CI fails for the commit, as there is no CodeQL SARIF report available for it.

chore(ci): do not apply 'skip actions' to automatically generated commit

---

.github/workflows/authors-and-third-party-notices.yaml

This reverts commit aae495fc08ecee47a64d199ea074e2e8a613abdb.
This means we'll need to find another solution for ensuring that we generate SARIF files for commits.

Revert "chore(ci): do not apply 'skip actions' to automatically generated commit (#6546)"

---

packages/compass-connections-navigation/src/with-status-marker.tsx

Position status icon exactly to the bottom-right corner wrt its parent element.
|         | Compass         | Cloud                      |
| :----------- | :--------------: | -------------------------: |
| Before | <img width="264" alt="image" src="https://github.com/user-attachments/assets/219c4b98-d75e-4ade-a87e-31ca598b6e47" /> | ![image](https://github.com/user-attachments/assets/5cd356d2-e6bf-442e-94a5-0c576e29ca90)  |
| After    | <img width="278" alt="image" src="https://github.com/user-attachments/assets/ce8072e4-889f-44d0-8d34-55ca95666434" /> | ![image](https://github.com/user-attachments/assets/32104b12-081c-417b-bba2-c1699f4b11b4) |

fix(connections): adjust status marker position CLOUDP-289203

---

packages/compass-web/src/entrypoint.tsx

fix(compass-web): add tracking for compass-provider COMPASS-8658

---

packages/compass-web/src/preferences.tsx

Show search indexes banner instead of disabled search indexes feature toggle in compass-web.
Looks like this now: 
Formerly looked like this (the tooltip is inaccurate, and the preferred fix is to use the banner not to show that toggle at all)
I verified when you click through the Search you wind up at url like `https://cloud-dev.mongodb.com/v2/<group>#/clusters/atlasSearch/Cluster3` which shows the Atlas search indexes feature as desired.

fix(compass-web): Show search indexes banner instead of disabled search indexes feature toggle in compass-web COMPASS-8802 CLOUDP-289698

---

packages/compass-e2e-tests/tests/time-to-first-query.test.ts

follow-up to https://github.com/mongodb-js/compass/pull/6614

chore(e2e): forgot to remove half the comment

---

.evergreen/create-sbom.sh

Trying to debug some scp timeouts
https://parsley.mongodb.com/evergreen/10gen_compass_main_package_rhel_package_compass_patch_7543fc546fa8176745b6f248458505eef113e0d6_6787dc9065173e0007fc3745_25_01_15_16_04_36/0/task?bookmarks=0,4891

chore: scp -v to try and debug timeouts

---

packages/compass-e2e-tests/helpers/smoke-test/build-info.ts
packages/compass-e2e-tests/smoke-test.ts

1. Add `autoUpdatable` flag
1. Refactor some of the installer logic 😬

Add `autoUpdatable` flag and refactor installer logic

---

packages/compass-e2e-tests/helpers/commands/save-aggregation-pipeline.ts

CI flake: https://spruce.mongodb.com/task/10gen_compass_main_test_packaged_app_macos_14_arm_test_packaged_app_3_patch_ba5c36f53031c6fcb1fc00d35830a2559c02c397_67895b4c81fc830007367944_25_01_16_19_17_36/logs?execution=0&sortBy=STATUS&sortDir=ASC

fix(e2e-tests): wait for modal to disappear COMPASS-8847

---

packages/compass-components/src/components/document-list/document-edit-actions-footer.tsx

Fixed a typo that I experienced editing a record.

fix(typo): "no longer exists"

---

.github/workflows/bump-packages.yaml
.github/workflows/update-electron.yaml

Format was `Name <email>`, not just email.

chore(ci): use correct format for automated PR author

---

.github/workflows/test-installers.yml

Add a dummy workflow I can use to test an actual implementation on another branch.
I need this for the "Run workflow" button to appear in the GHA UI.

chore(ci): add workflow to test installers on GHA

---

.mailmap

chore: update `.mailmap` with current contributors

---

packages/compass-shell/src/components/compass-shell/tab-compass-shell.tsx

chore(shell): fix logid

---

.github/ISSUE_TEMPLATE/config.yml

I wanted to see if touching the config (in this case adding a new line at the end of the file) would trigger some workflow at GitHub 🤞

chore(github): touch the issue template config COMPASS-8982

---

packages/compass/src/main/menu.spec.ts
packages/compass/src/main/menu.ts

chore(compass): update restart menu item text to restart to update

---

configs/webpack-config-compass/package.json
package-lock.json
packages/atlas-service/package.json
packages/compass-crud/package.json
packages/compass-e2e-tests/package.json
packages/compass-explain-plan/package.json
packages/compass-find-in-page/package.json
packages/compass-import-export/package.json
packages/compass-indexes/package.json
packages/compass-query-bar/package.json
packages/compass-schema-validation/package.json
packages/compass-shell/package.json
packages/compass-utils/package.json
packages/compass-web/package.json
packages/compass/package.json
packages/connection-storage/package.json
packages/hadron-build/package.json
packages/hadron-ipc/package.json
scripts/package.json

Reverts mongodb-js/compass#6782

Revert "chore(deps): bump electron to 32.3.3 COMPASS-9075"

---

packages/compass-indexes/src/components/regular-indexes-table/status-field.tsx

feat(indexes): show tooltip for rolling index build status COMPASS-9129

---

package-lock.json
packages/compass-aggregations/package.json
packages/compass-field-store/package.json
packages/compass-generative-ai/package.json
packages/compass-import-export/package.json
packages/compass-query-bar/package.json
packages/compass-schema/package.json

This is to bring in the fix for empty required

fix: bump mongodb-schema COMPASS-9110

---

packages/compass-schema-validation/src/components/validation-states.tsx

Videos with simulated delay/
before 
https://github.com/user-attachments/assets/8b668cd5-bbc5-4019-bf54-03a5970cbcb6
after
https://github.com/user-attachments/assets/ffbcc471-9956-43d7-b2b4-04077ef87e4a

chore(schema-validation): add initial load loading spinner

---

.snyk

chore(snyk): add exception for non-applicable vuln COMPASS-9146

---

package-lock.json

fix: update braces to 3.0.2

---

packages/data-service/src/data-service.ts

Let me know if there is something that is safe to log and we do need - we could filter that

fix: remove logging for currentOp COMPASS-9203

---

packages/compass-indexes/src/components/regular-indexes-table/property-field.tsx
packages/compass-indexes/src/components/regular-indexes-table/status-field.tsx
packages/compass-indexes/src/components/regular-indexes-table/type-field.tsx
packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.tsx

Missed this when we last worked on the indexes plugin.

fix(compass-indexes): fix tooltip triggers in indexes plugin COMPASS-8449

---

packages/compass-web/sandbox/index.tsx

One liner follow-up based on https://github.com/mongodb-js/compass/pull/6869#discussion_r2047183743

chore(web): do not turn ff on by default in sandbox

---

packages/compass-indexes/src/components/create-index-fields.tsx
packages/compass-indexes/src/components/create-index-form/create-index-form.tsx
packages/compass-indexes/src/components/create-index-form/index-flow-section.spec.tsx
packages/compass-indexes/src/components/create-index-form/index-flow-section.tsx
packages/compass-indexes/src/components/create-index-form/mdb-code-viewer.spec.tsx
packages/compass-indexes/src/components/create-index-form/mdb-code-viewer.tsx
packages/compass-indexes/src/components/create-index-form/query-flow-section.spec.tsx
packages/compass-indexes/src/components/create-index-form/query-flow-section.tsx

State is maintained going back and forth from the toggle and clicking the code equivalent toggle will show the code version. I made the code viewer a component and also used it in the query flow section.
Index Flow
escaped characters
Query Flow

feat: Added code equivalent functionality CLOUDP-311784

---

packages/compass-welcome/src/components/web-welcome-tab.spec.tsx
packages/compass-welcome/src/components/web-welcome-tab.tsx

COMPASS-9016
More specific copy for DE welcome page

style(web): Change Data Explorer welcome page copy COMPASS-9016

---

packages/compass-indexes/src/modules/create-index.tsx

Update URL for "learn more" on rolling index builds
- [/] New tests and/or benchmarks are included
- [/] If this change updates the UI, screenshots/videos are added and a design review is requested
- [/] I have signed the MongoDB Contributor License Agreement (https://www.mongodb.com/legal/contributor-agreement)
None
None

chore(compass-indexes): change docs link to nav to rolling index builds directly COMPASS-9276

---

packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
packages/compass-indexes/src/components/indexes/indexes.tsx

| - | - |
| <img width="630" alt="Screenshot 2025-05-13 at 1 33 16 PM" src="https://github.com/user-attachments/assets/93d16312-edce-439a-83f6-cf35970af58c" /> | <img width="539" alt="Screenshot 2025-05-13 at 1 31 58 PM" src="https://github.com/user-attachments/assets/6c5efd86-7541-45b5-be0f-2f51a4ac4299" /> |

chore(indexes): update padding to allow for focus ring to show on toolbar buttons

---

packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-ai.tsx
packages/compass-generative-ai/src/components/generative-ai-input.tsx

Modifying the placeholder text to be more Data Explorer-friendly and include a mention that you can paste queries in other languages. The text may wrap if the tab is opened with a smaller window size, but I don't think this is a problem
Smaller window:

chore: update natural language query bar text COMPASS-9369

---

.tool-versions

https://asdf-vm.com/ 
mms also uses this.

chore: add asdf .tool-versions file with node js

---

packages/collection-model/lib/model.js

COMPASS-9377
fix(sidebar): show system.profile collections COMPASS-9377

fix(sidebar): show profiler collections COMPASS-9377

---

package-lock.json

Updating nested dependency - tar-fs to avoid https://security.snyk.io/vuln/SNYK-JS-TARFS-10293725

fix: update tar-fs to fix vulnerability

---

configs/eslint-config-compass/index.js
configs/webpack-config-compass/src/index.ts
configs/webpack-config-compass/src/loaders.ts
configs/webpack-config-compass/src/util.ts
packages/compass-e2e-tests/helpers/commands/get-feature.ts
packages/compass-e2e-tests/helpers/commands/open-settings-modal.ts
packages/compass-e2e-tests/helpers/commands/set-feature.ts
packages/compass-e2e-tests/helpers/compass.ts
packages/compass-e2e-tests/tests/auto-connect.test.ts
packages/compass-import-export/src/components/export-modal.tsx
packages/compass-import-export/src/utils/open-file.ts
packages/compass-intercom/src/setup-intercom.spec.ts
packages/compass-logging/src/ipc-logger.ts
packages/compass-schema-validation/test/mocha-plugins.ts
packages/compass-serverstats/src/components/current-op-component.tsx
packages/compass-shell/src/modules/worker-runtime.ts
packages/compass-telemetry/src/ipc-track.ts
packages/compass-utils/src/electron.ts
packages/compass/src/app/application.tsx
packages/compass/src/main/menu.spec.ts
packages/compass/src/main/optional-deps.ts
packages/compass/src/main/setup-csfle-library.ts

Another straightforward one, rule got renamed

chore(eslint-config): replace no-var-require with no-require-imports COMPASS-9459

---

configs/eslint-config-compass/index.js
packages/compass-components/src/components/guide-cue/guide-cue-service.ts

Only one case for this one in the codebase

chore(eslint-config): re-enable no-unsafe-declaration-merging rule COMPASS-9459

---

packages/compass-aggregations/src/components/stage-toolbar/stage-operator-select.tsx

Was closing some old tickets, small drive-by change that I thought I can just do

chore(aggregations): use combobox xsmall instead of custon height COMPASS-6347

---

package-lock.json
packages/compass-data-modeling/package.json
packages/compass-data-modeling/src/components/diagram-editor.tsx

COMPASS-9433
Asking about the text in slack: https://mongodb.slack.com/archives/C08P2P6ADJL/p1751291088103799

feat(data-modeling): show mixed type information on node field COMPASS-9433

---

package-lock.json
packages/compass-editor/package.json

COMPASS-9485
https://github.com/codemirror/commands/commit/22d21193e4adc6fd54910c784f1dfd9dd93de630

fix(deps): bump @codemirror/commands for multiline editor fix COMPASS-9485

---

packages/databases-collections/src/stores/drop-namespace.tsx

fix(databases-collections): add question mark to the modal title COMPASS-9505

---

packages/compass-aggregations/src/components/aggregations/aggregations.spec.tsx
packages/compass-aggregations/src/components/pipeline/pipeline.tsx
packages/compass-aggregations/src/plugin.tsx
packages/compass-preferences-model/src/feature-flags.ts

Added a feature flag `enableSearchActivationProgramP1`

feat(aggregations): add feature flag for search activation program phase 1 COMPASS-9571

---

packages/compass-generative-ai/src/components/ai-optin-modal.tsx

chore(compass-generative-ai): use latest disclaimer, fix dark mode colour, center align

---

packages/compass-indexes/src/components/indexes/indexes.tsx

Open search indexes in a new tab

fix(compass-indexes): make search indexes open in a new tab COMPASS-9904

---

packages/compass-e2e-tests/tests/in-use-encryption.test.ts
packages/compass/scripts/download-csfle.js

chore: use `continuous` crypt_shared library again COMPASS-9782
