- package-lock.json
- package.json
Collection tabs were not getting cleared from the collection store on disconnect, creating the appearance of being connected to a different server when collection names were equal.
> COMPASS-3842: Clear collection tabs on disconnect

- .travis.yml
- package-lock.json
- package.json
- src/main/window-manager.js
Bringing COMPASS-3814 to 1.20 releases! This is already in master
- adds showInfoDialog to be used when sharing schema as JSON
- does not cache npm on travis
@durran did i do this right for 1.20 betas?
> COMPASS-3814: add respondTo ipc event to show info dialogue (#1795)

- .evergreen/preinstall.sh
- package.json
Evergeen uses `npm@6.5.0` so `npm install` fails due to `engines` constraint in package.json. This PR fixes the version constraint and will use npm@latest on evergreen going forward.
> chore: update npm version to fix evergeen

- package-lock.json
- package.json
Bumping the version of `compass-aggregations` that fixes the problem with aggregation tab  blanking out when importing a pipeline with an invalid stage.
> COMPASS-3950: fix(aggregation): handle error when importing a pipeline with an invalid stage

- package-lock.json
- package.json
Reverts an accidental upgrade of import-export and puts it back to `3.0.1`
Don't quite yet want to release the new import-export changes, so to be safe just reverting back.
> downgrade compass-import-export to v3.0.1 for 1.20 release

- package-lock.json
- src/app/migrations/1.20.0-beta.0.js
- src/app/migrations/connection-disk.js
Migration to 1.20 no longer segfaults as the async module was removed.
> COMPASS-3967: Migrate without segfault

- package-lock.json
- package.json
⚠️ Backporting this PR for master|1.21-releases is not required because #1844 was a backport-only to `1.20-releases`.
Pins to 4.0.x which includes the fix https://github.com/mongodb-js/compass-import-export/commit/ffe4ae5c9114d557639d54435ab0befd4e774c52 without including new import export stream backend but https://github.com/mongodb-js/compass/commit/3e09c9bc2ca33d31fb535f33bca28a7270c9a1be didn't include plugin api version bump.
Related #1844 
Fixes COMPASS-3994 (no longer shows API error message)
Fixes COMPASS-3995 (import dialog now opens correctly)
> fix(import-export): COMPASS-3994: Incompatible API  Plugin version 

- package.json
> 🎉 @lrlna is currently traveling so I've aggregated the PR's below to start testing in master and allow for more jetlag recovery time!
- UX improvements: display doc count, do not display line numbers mongodb-js/compass-import-export#20
- Closes COMPASS-3961: allow adding missing fields mongodb-js/compass-import-export#19
- Closes COMPASS-3851: ability to add fields when exporting collection mongodb-js/compass-import-export#17
`+ ADD FIELD` button scrolls over to the bottom of the table and focuses on the input field to be edited. The field is only saved on `enter`, which is indicated by the text on the side of the table. When the input field is submitted, `fields` props are updated and the component is refreshed. That particular field is saved even after the user goes to `OUTPUT` and …
> feat(import-export): Add ability to specify projection for export

- package-lock.json
- package.json
Adds a [preview table](https://mongodb-js.github.io/compass-import-export/?path=/story/examples-importpreview--simple) of the file you are importing with checkboxes to exclude fields and select to specify a different type. This closes the current Import Export improvements epic.
Also includes fixes for bug with `globalAppRegistry`: refresh after import now works and default metrics are back. 
@mmarcon I've included extended diagnostics in devtools console you may be able to see in the screenshot. Should help ease any triage/debugging issues in beta.
There are a lot of things I want to tweak and improve [already so I started a list in the README](https://github.com/mongodb-js/compass-import-export#todoideas).
- https://github.com/mongodb-js/compass-import-export/pull/18
- …
> feat(import-export): Specify import types and projection

- .evergreen/preinstall.sh
- package.json
Evergreen:
https://evergreen.mongodb.com/task/10gen_compass_stable_macos_oneshot_compile_test_package_publish_patch_4689a36f0a459d92e83aa6d73d276eaa516be5d8_5df069c8e3c331637cdf4e45_19_12_11_04_00_31
https://evergreen.mongodb.com/task/10gen*compass_stable_macos_oneshot_compile_test_package_publish_d4727c739528f966c091d0b72bd081545614ceee_19_12_10_18_15*01
Leads to `debug.log` artifacts:
https://s3.amazonaws.com/mciuploads/10gen-compass-stable/d4727c739528f966c091d0b72bd081545614ceee/macos/oneshot-compile-test-package-publish2019-12-10T18*20_09*792Z-debug.log
```
27155 verbose stack Error: invalid bin entry for package acorn@2.7.0. key=acorn, value=bin/acorn
27155 verbose stack     at BB.map.bin (/data/mci/49eb92a47448056f632251afd33b64c1/src/.deps/lib/node*modules/npm/node*modules/bin-link …
```
> 1.20-releases: COMPASS-4018: Fixing build

- .evergreen/preinstall.sh
#1866 for master and 1.21.0-beta.0 Unblocks COMPASS-4026
Bad npm release blocking our builds and releases. See full details in #1866
- Related #1866
> COMPASS-4018: Fix evergreen for bad npm release

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
Current issue templates are not being registered since a colon at the end of a
line in github's yaml is not considered valid.
Non compass changes.
> remove colons at the end of title yaml in github issue templates

- package-lock.json
- package.json
Evergreen:
https://evergreen.mongodb.com/version/5e386060e3c3311158f8f2e2
Rollback `electron-winstaller` to `2.5.1` for now. Don't upgrade until [BUILD-2932](https://jira.mongodb.org/browse/BUILD-2932) is done.
* Fixes COMPASS-4127 
* Answers BUILD-10250
[Evergreen windows builds](https://evergreen.mongodb.com/task/10gen_compass_master_windows_package_and_publish_compass_3d7b0895c3d7ed4aada6f997286a8a57d7f835b5_20_01_31_17_33_22) started failing with the electron 6 update:
```
[2020/01/31 12:47:29.021] ×  Error: Error: Failed with exit code: 4294967295
--
[2020/01/31 12:47:29.021] Output:
[2020/01/31 12:47:29.021] System.AggregateException: One or more errors occurred. ---> System.Exception: Failed to sign, command invoked was: '.\signtool.exe sign yes …
```
> build: COMPASS-4127: Fix code signing on Windows

- package-lock.json
- package.json
TLS attributes no longer get removed when switching between the form view and URI view.
> COMPASS-4135: Persist TLS attributes across views

- package-lock.json
- package.json
COMPASS-4025: remove explicitlyIgnoreSession when running an export as something seems to have changed in the driver.
- https://github.com/mongodb-js/compass-import-export/pull/127
- https://github.com/mongodb-js/compass-import-export/pull/128
> fix(export): COMPASS-4025: remove explicitlyIgnoreSession

- package-lock.json
- package.json
COMPASS-4212: handle edge cases where we can't show a preview such as a partial load from a json file which has very large documents for example https://github.com/10gen/mongohouse/blob/master/testdata/stores/dynamic/test/largeDocument/payload.json.gz?raw=true
https://github.com/mongodb-js/compass-import-export/pull/140
> fix(import-preview): COMPASS-4212: handle edge cases where we can't show

- package-lock.json
- package.json
- fix(import): COMPASS-4206: Make type detection/casting work right when importing/exporting `.json`. a093933
- feat(export): Pick up nested objects to include in projection f6baf06
```javascript
doc = {
_id: 'Arlo', 
location: {
place: 'home',
activity: {
sleeping: true,
is: 'on the couch'
}
};
```
Before this would populate the projection as:
Now you can specify full paths for more control over what is actually returned:
Use case: (See a 1M line csv imported that is 300 fields wide and you only want 2).
- fix(export): Add tests to make sure csv's have correct headers. df70ff9
- fix(export): Headers should be dotnotation for nested object paths.
https://www.npmjs.com/package/discogs-data-tools
`mongoexport` CSV of all label names in the dicogs database:
[Andy Pavlo's BitTorrent Data …
> fix(import): COMPASS-4206: Fix type detection and export formatting.

- .travis.yml
Removes NPM_TOKEN in travis, since none of our repositories are private anymore.
> remove NPM_TOKEN from travis.yml

- package-lock.json
- package.json
From mongodb-js/compass-serverstats#32
> Currently causing compass builds on windows to fail. Appears one of less's underlying deps update introducing the below:
> 
> ```
> [2020/04/03 17:54:40.550] 2020-04-03T17:54:40.550Z check-max-path 2 paths too long!
> [2020/04/03 17:54:40.550] 2020-04-03T17:54:40.550Z check-max-path paths that are too long:  [
> [2020/04/03 17:54:40.550]   'C:\\data\\mci\\f8d375254475f97179b344bb6912df63\\src\\dist\\MongoDBCompassIsolatedEditionBeta-win32-x64\\resources\\app.asar.unpacked\\node_modules\\@mongodb-js\\compass-serverstats\\node_modules\\less\\packages\\css-parser\\node_modules\\chevrotain\\diagrams\\vendor\\railroad-diagrams.js',
> [2020/04/03 17:54:40.550]   'C:\\data\\mci\\f8d375254475f97179b344bb6912df63\\src\\dist\\MongoDBCompassIsolatedEditionBeta …
```
> fix(build): Fix Windows failure caused by bad dependency meta in serverstats

- package-lock.json
- package.json
Fixes HELP-14887 Compass does not appear to permit connecting to an analytics node on Atlas
Caused by NODE-2541
https://github.com/mongodb/node-mongodb-native/releases/tag/v3.5.6
> chore(deps): COMPASS-4229 Update node driver to v3.5.6

- package-lock.json
- package.json
Storage mixing was getting bunded with query history which also bundled a wrongly compiled keytar.
> COMPASS-4218: Storage mixin should not be bundled

- package-lock.json
- package.json
- COMPASS-4246: Don't error out on non comma spaced csvs.
- COMPASS-4249: Proper field deselection of more than 1 field.
- COMPASS-4251: Fail gracefully on malformed JSON.
> Fixes for 1.21 input/export bugs

- package-lock.json
- package.json
- src/main/window-manager.js
electron-devtools-installer leaves orphaned files in the user data dir that prevents any electron app from loading on Windows after the first run. This PR removes it, as we really don't use them anyways.
> Remove devtools

- src/app/styles/tab-nav-bar.less
https://jira.mongodb.org/browse/MONGOSH-89
This PR is a small styling tweak for components to ensure when they overflow the window height the tab header doesn't scroll on scroll, just the content inside the `tab-views`. This mostly impacts the styling of `schema` and `explain plan` because their styling doesn't account for content needing to vertically scroll. 
Once all of the styling is in, it should also improve the current performance tab, which currently doesn't allow any scrolling on overflow.
This styling goes in tandem with https://github.com/mongodb-js/compass-home/pull/112
Once they're all in I'd like to run through all of the components and make sure we're handling things nicely.
We'll want to add `compass-shell` as a plugin in this repo, but that can wait for `compass-shell` to …
> MONGOSH-89: Shell plugin as global role in Compass

- package-lock.json
- package.json
Build was failing: https://evergreen.mongodb.com/task/10gen_compass_master_macos_oneshot_compile_test_package_publish_6699cdf4718a6cc9027adaba498cef6349c6362b_20_06_03_19_03_04
After merging in compass shell in: 
https://github.com/mongodb-js/compass/pull/1963
This PR fixed the dependency that caused the build failure from compass-shell (Which is what this PR pulls in):
https://github.com/mongodb-js/mongosh/pull/213
> Bump mongosh version for build fix

- package-lock.json
- package.json
Uses latest `compass-crud` and `hadron-type-checker` to accomodate editing,
pasting and inserting Int64 large numbers.
> COMPASS-3806: update compass-crud@9.0.8

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- package-lock.json
- package.json
- src/app/loading/loading.js
- src/app/setup-plugin-manager.js
- src/app/setup-style-manager.js
- src/main/index.js
- src/main/window-manager.js
When importing agg pipeline form text limit documents used for a preview even if pipeline includes the `out` stage, otherwise the aggregation will be executed on the whole collection and freeze the UI. Even tho according to the design the `out` stage should be the last stage in the pipeline and we expect that all documents should be exported to another collection, we can still use the `limit` stage here because we don't start exporting yet. To do so a user should click the `Save Documents` button, and only then the pipeline without limiting will be executed.
For more details see: https://github.com/mongodb-js/compass-aggregations/pull/268
Ticket: https://jira.mongodb.org/browse/COMPASS-4263
I also fixed lint warnings and GitHub templates, since I have noticed these small issues and it was …
> COMPASS-4263: limit docs for out preview

- package-lock.json
- package.json
Uses new `mongodb-ace-autocompleter` that has the missing `,` in the template for the `$merge` stage.
> Bump mongodb-ace-autocompleter dependency

- package-lock.json
- package.json
The new version has the new template for `$search` in the agg pipeline builder.
The previous template for `$search` was missing `index` and was using a deprecated operator.
> COMPASS-4403: Bumped ace-autocompleter

- package-lock.json
Our `package-lock.json` has some extra packages that were introduced https://github.com/mongodb-js/compass/commit/db7554ae5ce2d0bad52e8ae48c62736b76ab6a1a#diff-32607347f8126e6534ebc7ebaec4853d
This PR clean installs and generates package-lock.json. 
Hopefully this decreases the size of the generated artifacts: https://github.com/mongodb-js/compass/releases/tag/untagged-6941d81a6c33b14996c1 They doubled ater the package-lock.json additions.
> Clean npm install package-lock.json generate

- package-lock.json
- package.json
Fixes a bug in query-parser which caused misrepresented integer to be used in NumberLong when  the value was > MAX_SAFE_INTEGER.
> COMPASS-4355: Allow queries and $match with NumberLong > MAX_SAFE_INTEGER

- package-lock.json
- package.json
> chore: bump hadron-module-cache to 1.0.1

- .evergreen.yml
- package-lock.json
- package.json
- https://github.com/mongodb-js/electron-installer-codesign/pull/6
- https://github.com/mongodb-js/hadron-build/pull/365
- https://github.com/mongodb-js/electron-installer-codesign/pull/7
- https://github.com/mongodb-js/hadron-build/pull/367
- https://github.com/mongodb-js/hadron-build/pull/368
🤞
> COMPASS-4077 - Notarize builds for macOS

- package-lock.json
- package.json
f18f4f65ccea0c812 only fixed this for accessing collections from
the sidebar, this does so for accessing them from the
collections table.
> COMPASS-4353 - Update more deps for better readonly/view handling

- package-lock.json
- package.json
COMPASS-4453 
Pulls in https://github.com/mongodb-js/compass-crud/pull/300 which improves the update document behavior.
Also pulls in a few ux improvements and bug fixes which we in version 10.0.1:
mongodb-js/compass-crud@80d32a4
mongodb-js/compass-crud@a784e90
mongodb-js/compass-crud@7bf235e
> COMPASS-4463: Bump compass-crud to 10.0.2 to pull in update document bug fix

- package-lock.json
- package.json
COMPASS-4423
Pulls in https://github.com/mongodb-js/compass-crud/pull/308
feat(compass-crud): COMPASS-4423 add support for multi-line string input editing
> COMPASS-4423: Multi line string input editing (bump compass-crud)

- package-lock.json
- package.json
Update to https://github.com/mongodb-js/compass-sidebar/releases/tag/v3.2.9:
* fix: remove broken actions from dropdown and update icon COMPASS-4500 (mongodb-js/compass-sidebar#142)
> fix: remove broken import/export sidebar actions COMPASS-4500

- package-lock.json
- package.json
COMPASS-4492
This pulls in PR: mongodb-js/ace-autocompleter#65
> fix(COMPASS-4492): remove sql pipeline stage operator

- package-lock.json
- package.json
Fixes queries not being rendered properly in the export dialog, e.g. an `ObjectId` being represented as a `new Buffer(...)` by updating to https://github.com/mongodb-js/compass-import-export/releases/tag/v5.2.3.
> fix(compass-import-export): Ensure queries are rendered properly in export dialog COMPASS-4481

- package-lock.json
- package.json
Updates a few dependencies that bump default max time ms query/aggregation option to 1 minute from 5 seconds:
https://jira.mongodb.org/browse/COMPASS-4530
5 second timeout is too small and often a reason for query failures.
- https://github.com/mongodb-js/compass-aggregations/pull/324
- https://github.com/mongodb-js/query-parser/pull/66
- https://github.com/mongodb-js/compass-query-bar/pull/179
> feat(COMPASS-4530): Update aggregations, query-bar, query-parser to increase max time ms limit to 1 minute

- package-lock.json
- package.json
Pins the antlr4 dependency at `4.7.2` from the bson-transpilers package. 4.9.0 was causing the following issue:
Pulls in https://github.com/mongodb-js/bson-transpilers/pull/137
Now aggregations loads:
> fix(deps): pin antlr4 dependency at 4.7.2

- src/app/migrations/index.js
Skips the migrations run if the `package.json` version matches a placeholder, i.e. starts with `0.0.0`.
> chore: skip migrations when package version is placeholder

- package-lock.json
- package.json
Use find instead of sample in import-export. `$sample` is too slow for the import-export dialog window and it was introduced to solve a bug that is actually caused by something else.
> fix: Use find instead of sample in import-export

- package-lock.json
- package.json
Bumps `compass-export-to-language` to https://github.com/mongodb-js/compass-export-to-language/releases/tag/v6.0.7.
> fix(export-to-language): Disable builders for Java pipeline export COMPASS-4475

- package-lock.json
- package.json
Actual code: https://github.com/mongodb-js/compass-schema/commit/29b8d057a7f2b6381bdfca43c041b9a6cfdf3090
> fix: show detailed types in schema COMPASS-4648

- .npmrc
After fixing the dependency in browser-runtime-core
(https://github.com/mongodb-js/mongosh/pull/487) we can now re-enable
engine strict.
> chore: re-enable engine strict COMPASS-4535

- package-lock.json
- package.json
COMPASS-4727
Pulls in https://github.com/mongodb-js/compass-connect/pull/275 and https://github.com/mongodb-js/compass-connect/pull/274
> fix(compass-connect): Connection name overflowing on connecting screen COMPASS-4727

- README.md
Fixed formatting of ``package.json``
Current view:
Fixed:
> misc: Fixed formatting of package.json in Readme.md

- package-lock.json
- package.json
See https://github.com/mongodb-js/compass-import-export/pull/244
> fix(compass-import-export): Prevent import modal from breaking Compass when import fails

- package-lock.json
- package.json
Seems like import-export update is causing some weird issues (see [this slack thread](https://mongodb.slack.com/archives/G2L10JAV7/p1617010583052700?thread_ts=1616773086.052200&cid=G2L10JAV7))
> fix(import-export): Revert import-export to the previous stable version

- package-lock.json
- package.json
Reverts mongodb-js/compass#2148
After some additional info we don't believe that this change caused the issue, so reverting the revert
> Revert "fix(import-export): Revert import-export to the previous stable version"

- .evergreen.yml
- package.json
- scripts/monorepo/find-failing-tests.js
So while spending some time trying to get proper info about which tests are currently failing I actually managed to make tests completely green for macos on evergreen. I'm suggesting that we unscope all evergreen commands again, and just skip tests for machines where tests are failing at the moment. This is already better than what we have at the moment and means that at least on one system we will test all the packages before releasing.
Here's a ✅ evergreen run with current patch: https://spruce.mongodb.com/version/6092b371850e6120e8030f97/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
For some context here are the tickets that have to be solved before we can run tests on other machines (this will be done separately, outside of this PR): 
- https://jira.mongodb.org/browse/COMPASS-4789
- …
> ci(monorepo): Re-enable tests for all packages, but only on macos

- packages/compass/package.json
Compass has its own publishing flow and is not published to npm. This should also filter it out when doing `lerna publish`
> chore(mongodb-compass): Mark compass as private so it's not published by lerna

- packages/compass-aggregations/package.json
- packages/compass-app-stores/package.json
- packages/compass-auto-updates/package.json
- packages/compass-collection-stats/package.json
- packages/compass-collection/package.json
- packages/compass-collections-ddl/package.json
- packages/compass-connect/package.json
- packages/compass-crud/package.json
- packages/compass-database/package.json
- packages/compass-databases-ddl/package.json
- packages/compass-deployment-awareness/package.json
- packages/compass-export-to-language/package.json
- packages/compass-home/package.json
- packages/compass-import-export/package.json
- packages/compass-indexes/package.json
- packages/compass-instance/package.json
- packages/compass-loading/package.json
- packages/compass-metrics/package.json
- packages/compass-plugin-info/package.json
- packages/compass-query-bar/package.json
- packages/compass-query-history/package.json
- packages/compass-schema-validation/package.json
- packages/compass-schema/package.json
- packages/compass-server-version/package.json
- packages/compass-shell/package.json
- packages/compass-sidebar/package.json
- packages/compass-ssh-tunnel-status/package.json
- packages/compass-status/package.json
Something we stumbled upon while releasing packages today together with @addaleax. We currently use `install` to download akzidenz fonts, the fonts are needed only for local dev but install is also triggered when package is installed as a dependency. Additionally now that we are using monorepo root script to download them, it causes issues by referencing file that definitely is not there when package is installed as a dependency. As a fix we will use [`prepare` script](https://docs.npmjs.com/cli/v6/using-npm/scripts#life-cycle-scripts) that is triggered on local installs and before publishing only (we don't really need it before publishing, but there is no "local install only" script that we can use)
> fix: Only download fonts on local install

- packages/compass-shell/.gitignore
- packages/compass-shell/src/assets/less/compass/_theme.less
- packages/compass-shell/src/assets/less/compass/components/_buttons.less
- packages/compass-shell/src/assets/less/compass/components/_caret.less
- packages/compass-shell/src/assets/less/compass/components/_index.less
- packages/compass-shell/src/assets/less/compass/components/_message-background.less
- packages/compass-shell/src/assets/less/compass/components/_mms-icons.less
- packages/compass-shell/src/assets/less/compass/components/_modal-status-message.less
- packages/compass-shell/src/assets/less/compass/components/_react-select.less
- packages/compass-shell/src/assets/less/compass/components/_sortable-table.less
- packages/compass-shell/src/assets/less/compass/components/_zero-state.less
- packages/compass-shell/src/assets/less/compass/variables/_index.less
- packages/compass-shell/src/assets/less/compass/variables/_layout.less
- packages/compass-shell/src/assets/less/compass/variables/_palette.less
Seems like due to how the gitignore was written all of the compass style files were not migrated
> fix(@mongodb-js/compass-shell): Add back missing less files

- .evergreen.yml
- package-lock.json
- package.json
- packages/compass-shell/config/webpack.base.config.js
- packages/compass-shell/package.json
- packages/hadron-react-bson/config/webpack.base.config.js
- packages/hadron-react-buttons/config/webpack.base.config.js
- packages/hadron-react-components/config/webpack.base.config.js
- packages/hadron-react-utils/config/webpack.base.config.js
- scripts/install-electron.js
The main issue causing some `hadron-*` package fail to install was electron not being able to run it's postinstall script correctly when installation is running with a high concurrency (our case unfortunately). To work around it, I split the install/bootstrap in CI in two parts, one will install all dependencies in all packages skipping electron binary download, the other will sequentially go through all the packages and install electron where required.
One unfortunate side-effect of it is that build became slower, so I had to bump the timeout on the whole CI run. But there is a chance that when we are able to `lenra bootstrap` everything with hoisting, this workaround can go away, so I think it's good enough for now.
Another issue that became noticeable after electron installation was …
> test: Fix CI flakiness on windows around tests in packages using electron COMPASS-4818

- .evergreen.yml
- .evergreen/pretest.sh
- packages/collection-model/package.json
- packages/compass-connect/karma.conf.js
- packages/compass-connect/package-lock.json
- packages/compass-connect/package.json
- packages/compass/package-lock.json
- packages/compass/package.json
- packages/connection-model/test/connect.test.js
- packages/hadron-auto-update-manager/package.json
- packages/hadron-build/test/fixtures/hadron-app/package.json
- packages/hadron-ipc/package.json
- packages/metrics/package.json
- packages/storage-mixin/package-lock.json
- packages/storage-mixin/package.json
- packages/storage-mixin/test/secure.test.js
- packages/storage-mixin/test/splice-disk.test.js
- packages/storage-mixin/test/splice.test.js
So initially I was planning to do those tickets separately, but most of the fixes were incredibly tiny, so I included all of them in one PR
The following fixes were applied:
- Add `xvfb-maybe` to the test scripts where needed
- Custom MongoDB Server version was causing failure in some cases where the version was too new for the Ubuntu version that we are running (specifically server v4.2 is not supported on ubuntu 14). I bumped the ubuntu version which should be enough to fix the problem, but also removed all the server versions overrides from packages so that there is only one place where it's configured for the CI test run
- Skip "secure backend" tests in `storage-mixin` that use `keytar`. So this one is a weird one. Theoretically we had a workaround for that specific …
> test: Make sure all tests are passing on Ubuntu and RHEL COMPASS-4789 COMPASS-4791 COMPASS-4792 COMPASS-4793 COMPASS-4794

- packages/compass-auto-updates/package-lock.json
- packages/compass-auto-updates/package.json
- packages/compass-export-to-language/package-lock.json
- packages/compass-export-to-language/package.json
- packages/compass-loading/package-lock.json
- packages/compass-loading/package.json
- packages/compass-plugin-info/package-lock.json
- packages/compass-plugin-info/package.json
- packages/compass-preferences-model/package-lock.json
- packages/compass-preferences-model/package.json
- packages/compass-server-version/package-lock.json
- packages/compass-server-version/package.json
- packages/compass-serverstats/package-lock.json
- packages/compass-serverstats/package.json
- packages/compass-ssh-tunnel-status/package-lock.json
- packages/compass-ssh-tunnel-status/package.json
- packages/compass-status/package-lock.json
- packages/compass-status/package.json
- packages/compass-user-model/package-lock.json
- packages/compass-user-model/package.json
- packages/hadron-spectron/package-lock.json
- packages/hadron-spectron/package.json
Electron versions < 6 don't support `ELECTRON_SKIP_BINARY_DOWNLOAD` env flag and this causes flakiness [issues in CI for windows](https://evergreen.mongodb.com/task/10gen_compass_master_windows_oneshot_compile_test_package_publish_e2b0fa346e4b5dbdbb83d82de4acd129efc67e71_21_05_19_11_40_33). This change although bumps majors should not cause any issues as the change aligns versions with compass and if something would be broken there we would most definitely noticed.
Evergreen run to confirm that: https://spruce.mongodb.com/version/60a509bbd1fe074b793b3b93/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> chore: Bump electron < 6 to 6.1.7 (version that compass is using)

- packages/compass-collection-stats/package-lock.json
- packages/compass-collection-stats/package.json
- packages/compass-databases-ddl/package-lock.json
- packages/compass-databases-ddl/package.json
- packages/compass-explain-plan/package-lock.json
- packages/compass-explain-plan/package.json
- packages/compass-export-to-language/package-lock.json
- packages/compass-export-to-language/package.json
- packages/compass-indexes/package-lock.json
- packages/compass-indexes/package.json
- packages/compass-schema-validation/package-lock.json
- packages/compass-schema-validation/package.json
- packages/compass-schema/package-lock.json
- packages/compass-schema/package.json
- packages/compass-serverstats/package-lock.json
- packages/compass-serverstats/package.json
- packages/compass-sidebar/package-lock.json
- packages/compass-sidebar/package.json
A bit of a follow up to https://github.com/mongodb-js/compass/pull/2198 where we updated dependency versions. This PR adds `mongodb-client-encryption` as a dev dep to a number of the packages which had their mongodb drivers used in dev updated in dependencies.
A couple other manual changes:
- add `lodash.sortby` as a dependency to `compass-indexes`. I haven't investigated how this wasn't breaking before.
- add `mongodb-connection-model` as a dev dep to `compass-explain-plan`, since it uses the `data-service` which has `connection-model` as a peer dep.
Two notes for things I came accross during this:
- `compass-instance` has a broken `npm start` (looks like it was like this pre-monorepo)
- `compass-schema` running as dev `npm start` needs to be taken a look at, it says it needs …
> chore: Add `mongodb-client-encryption` as dev dep where needed

- packages/compass-collection-stats/config/webpack.dev.config.js
- packages/compass-collection-stats/electron/index.js
- packages/compass-collection-stats/src/stores/store.js
- packages/compass-collection-stats/src/stores/store.spec.js
- packages/data-service/lib/native-client.js
Allow the collection stats view to work with time series collections:
- add a workaround for the missing `stats.count` (manually call invoking `ds.estimatedCount`)
- fix the verbose parameter for `collectionStats`
- improve error handling
> feat(compass-collection-stats):  display time-series stats on the collection header COMPASS-4779

- packages/connection-model/test/connect.test.js
- packages/index-model/test/fetch.test.js
Seems like tests that are using mongodb-runner mocha hooks are never able to start server in time for the test suite to go through, we will disable the suites using those tests for now and address it later in COMPASS-4866
[Link to the Evergreen patch](https://spruce.mongodb.com/task/10gen_compass_master_rhel_oneshot_compile_test_package_publish_patch_1b916a64e54b5965ce833dcc53142648aa816d76_60b882b13627e054ac5cc26a_21_06_03_07_20_27/logs?execution=1)
> chore: Disable flaky RHEL test suites that are using mongodb-runner

- packages/hadron-build/lib/target.js
Seems like it didn't work before and breaking installer now so we are disabling it for now. See [this Slack thread](https://mongodb.slack.com/archives/G2L10JAV7/p1623169331107600) for more context
> fix(hadron-build): Do not sign deb installers

- packages/compass-explain-plan/electron/index.js
- packages/compass-explain-plan/src/components/explain-plan/explain-plan.less
The PR updates the development of the package `compass-explain-plan` so that it runs. Previously it was throwing an error and when rendered had no height.
> chore(compass-explain-plan): Update development electron environment

- package.json
- scripts/monorepo/publish-all.js
We need to sync package-locks after doing a publish on packages to make sure that in CI (and locally) everything can install correctly
> feat(release): Update package lock for private packages during publishing

- packages/connection-model/package.json
This package depends on the mongodb driver not just as a dev
requirement, but also for its actual code.
I’ve spent some time trying to make it compatible so that it
would work with the 4.0 driver as well, but that seems like a
larger task after all and it probably makes more sense to just
do proper npm dependency declaration here, and make sure that
this package always gets the 3.x driver.
> fix(connection-model): make mongodb a proper dependency

- packages/compass-shell/package.json
- packages/compass-shell/src/modules/adapt-driver-v36-connection-params.js
> chore: use mongodb-connection-string-url package in compass-shell

- packages/compass-sidebar/src/components/sidebar-collection/sidebar-collection.jsx
- packages/compass-sidebar/src/components/sidebar-collection/sidebar-collection.spec.js
Adds folder icons to collections in the sidebar.
> feat(compass-sidebar): Add folder icon to collections in sidebar

- packages/compass-export-to-language/src/stores/store.spec.js
cherry-picked from #2252 as it's relatively isolated and seems to fix CI in PR workflows
> test(@mongodb-js/compass-export-to-language): Remove timeout (default one is bigger) and wrap check in try catch

- .github/workflows/check-test-build.yaml
This PR brings back artifact building by addressing two issues that were present there:
- Windows machines weren't able to pick up wix toolset. Fixed by explicitly providing wix toolset path to env path
- MacOS was trying to upload the whole .app folder structure and even though it's not that big of an issue, there is no point in that as there is a zip archive with .app included available. Fixed by a more explicit glob for uploaded artifacts
> ci(github): Fix wix path missing on Windows; Limit artifacts that we upload with a better glob

- .github/workflows/authors-and-third-party-notices.yaml
- .github/workflows/build.yaml
- .github/workflows/check-test.yaml
Some small clean-ups for workflows:
- Split build and test into separate things so we can run them in parallel and "require" only one of them to pass before merging in the future if we want to
- fetch all git history so we can run tests only in the packages that were changed in the PR, this should speed up testing in most cases and give quicker feedback
- Add a name to update authors workflow just so it looks prettier in actions UI 😸
> ci(github): Split build and test into two separate workflows; Try to only test/check changed packages

- packages/compass-aggregations/src/components/stage-preview/stage-preview.jsx
- packages/compass-aggregations/src/modules/pipeline.js
COMPASS-4222
This PR removes the explicit check for a `$merge` pipeline stage before adding a `$limit` to a pipeline. Previously we had refactored this to work so that it only applies the limit for the preview pipeline, but missed removing this check (we were fixing a similar bug for `$out`).
Here's a `$merge` in the aggregation pipeline not freezing the UI and also outputting the whole collection:
https://user-images.githubusercontent.com/1791149/122267556-0c888300-cea9-11eb-8adb-edf5aed96954.mp4
> fix(compass-aggregations): limit preview documents in stage preview for $merge pipeline COMPASS-4222

- .evergreen.yml
Add public registry to `npmrc` to avoid using the internal artifactory by accident
> chore: force use public registry

- .evergreen.yml
This PR cleans up all unused parts of the evergreen config and adds a workaround for a notary-service hack on Windows. This doesn't fix the build completely as all the other fixes are happening in #2270, you can see that compared to main branch "notary service hack" step is not failing anymore in [this evergreen run](https://evergreen.mongodb.com/task_log_raw/10gen_compass_master_windows_oneshot_compile_test_package_publish_patch_75d0eb43ffa0e9e3df332adfb50d20f22ab69312_60cc59cb562343777f494e06_21_06_18_08_31_33/0?type=T#L26459)
> ci(evergreen): Clean-up evergreen config and fix notary service hack for win

- .github/workflows/build.yaml
- .gitignore
- scripts/monorepo/verdaccio.yaml
So when I did #2260 I somehow forgot that `hadron-build` reinstalls Compass deps from scratch and doesn't bundle anything from the repo with the Compass app. This PR addresses the issue by doing a fake release and publish to the local repo and bundling Compass against this locally running repository, this means that now GitHub CI will actually produce a build of Compass app with the latest changes from the repo
(Not sure how smooth this will go in CI, but it seems to be working for me locally)
> ci(github): Use mock registry in build action so that Compass build includes local packages

- .evergreen.yml
So I'm not really sure how this fixes windows builds because even before we started moving things around, evergreen was deleting `signtool.exe` both in `node_modules/@mongodb-js/electron-wix-msi` and `node_modules/electron-winstaller` and copying it over only to `node_modules/@mongodb-js/electron-wix-msi` so it's not a change that we introduced, but copying signtool to both places it was removed from fixes the build
Here's a few evergreen runs that confirm that:
- https://spruce.mongodb.com/version/60cc999e9ccd4e75e6bc1fa5/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
- https://spruce.mongodb.com/version/60cc9a8957e85a77118fc03c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
- https://spruce.mongodb.com/task/10gen_compass_master_windows_oneshot_compile_test_package_publish_patch_965e3f9b98e …
> ci(evergreen): Copy signtool to node_modules/electron-winstaller

- packages/compass-aggregations/src/modules/pipeline.js
- packages/compass-deployment-awareness/.depcheckrc
- packages/compass-deployment-awareness/package.json
- packages/compass-deployment-awareness/src/models/topology-type.js
- packages/compass-indexes/package.json
- packages/compass-schema/package.json
- packages/compass-shell/package.json
- packages/compass-shell/src/modules/adapt-driver-v36-connection-params.js
- packages/compass-shell/src/modules/adapt-driver-v36-connection-params.spec.js
- packages/compass/package.json
- packages/compass/src/app/migrations/legacy-connection.js
- packages/connection-model/README.md
- packages/connection-model/lib/connect.js
- packages/connection-model/lib/model.js
- packages/connection-model/package.json
- packages/connection-model/test/build-uri.test.js
- packages/connection-model/test/connect.test.js
- packages/data-service/lib/native-client.js
- packages/data-service/package.json
- packages/data-service/test/data-service.test.js
- packages/data-service/test/native-client.test.js
- packages/databases-collections/package.json
- packages/index-model/package.json
This is fairly functional already, but ~~e.g. the aggregation pipeline builder doesn't appear to work yet, and~~ I have only checked a small subset of Compass's functionality here.
> feat: bump driver to 4.x beta COMPASS-4805

- .github/workflows/build.yaml
- .github/workflows/check-test.yaml
It failed in #2275 and it's not clear why so that would help. It's also more helpful if we don't fail fast and see which platforms are affected by possible issues
> ci(github): Fix logging for the hadron build process and do not fail fast

- .github/workflows/build.yaml
- packages/compass/package.json
- packages/hadron-build/commands/release.js
- scripts/bump-private-dependencies.js
Another thing that I missed while making builds work in GitHub CI: because we are doing a canary release that doesn't commit anything, the `version` lifecycle is not running and compass doesn't get a dependencies version bump while doing a release. With this change we should finally get a Compass build in CI that is happening against local modules
> ci(github): Include private packages when doing a canary publish in ci

- .github/workflows/build.yaml
Windows builds fail pretty often with an unexpected zlib error
and as there seems to be no good reason for it and nothing comes
up when searching for an error we are lowering the concurrency
in hopes that this will magically solve the issue
> ci(github): Do publish with concurrency 1

- .evergreen.yml
The way we are currently trying to set up npm cache dir is not working due to usage of `${}` syntax for referencing a variable. This syntax is also used by evergreen for expansions and there is no way to prevent evergreen from trying to expand those variables even when there is nothing to replace them with. This PR addresses the issue by removing the syntax and also escaping the $ symbol so it is actually preserved in the env file that we are writing.
Here's [an evergreen patch](https://spruce.mongodb.com/version/60d1fb06a4cf476958b6e842/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) that I started to confirm that I didn't brake anything by changing this.
> ci(evergreen): Escape $ when writing env file and don't use ${} syntax in file

- packages/compass-aggregations/src/modules/create-view/index.js
- packages/compass-aggregations/src/modules/update-view.js
- packages/compass-collection/electron/renderer/index.js
- packages/compass-collection/src/components/collection-header/collection-header.jsx
- packages/compass-collection/src/components/collection/collection.jsx
- packages/compass-collection/src/components/collection/collection.spec.js
- packages/compass-collection/src/components/create-tab/create-tab.jsx
- packages/compass-collection/src/components/create-tab/create-tab.spec.js
- packages/compass-collection/src/components/workspace/workspace.jsx
- packages/compass-collection/src/modules/context.js
- packages/compass-collection/src/modules/tabs.js
- packages/compass-collection/src/modules/tabs.spec.js
- packages/compass-collection/src/stores/store.js
- packages/compass-collection/test/stores/store.spec.js
- packages/compass-crud/electron/renderer/index.js
- packages/compass-crud/package.json
- packages/compass-crud/src/components/document-actions.jsx
- packages/compass-crud/src/components/document-list-view.jsx
- packages/compass-crud/src/components/document-list.jsx
- packages/compass-crud/src/components/document.jsx
- packages/compass-crud/src/components/expansion-bar.jsx
- packages/compass-crud/src/components/readonly-document.jsx
- packages/compass-crud/src/stores/crud-store.js
- packages/compass-explain-plan/src/components/explain-json/explain-json.jsx
- packages/compass-explain-plan/src/components/explain-json/explain-json.less
- packages/compass-sidebar/src/components/sidebar-collection/sidebar-collection.jsx
- packages/compass-sidebar/src/components/sidebar-database/sidebar-database.jsx
- packages/compass-sidebar/src/modules/collection.js
- packages/compass-sidebar/src/modules/collection.spec.js
- packages/databases-collections/src/modules/show-collection.js
COMPASS-4781
This PR updates how we show documents in time-series collections to only show cloning and copying documents (time-series collections can only be added to, not edited).
Since we were customizing the actions for certain collections, I also noticed we could add copying documents in a few places. This pr adds the ability to copy an explain plan and copy a document in a view.
A bit of refactoring on how tabs pass their collection information around, less argument list and more objects - is this a useful refactor?
Maybe we wait till post 1.27 to merge since it hits a few packages.
These changes also fix a couple smaller bugs when user would create new tabs from a read only view, they would be shown editing functionality.
*document in time-series collection*
*document in view w/ …
> feat(compass-crud): Show document actions for time series collections COMPASS-4781

- packages/compass-sidebar/src/components/collection-type-icon/collection-type-icon.jsx
- packages/compass-sidebar/src/components/collection-type-icon/collection-type-icon.less
- packages/compass-sidebar/src/components/collection-type-icon/collection-type-icon.spec.js
- packages/compass-sidebar/src/components/collection-type-icon/index.js
- packages/compass-sidebar/src/components/sidebar-collection/sidebar-collection.jsx
- packages/compass-sidebar/src/components/sidebar-collection/sidebar-collection.less
With datalake, a read only collection that isn't a view we were showing two icons in the sidebar. This PR updates it so we only show one.
> fix: Show collection icon on read only collections (that aren't views)

- packages/compass-metrics/src/modules/get-cloud-info.js
- packages/compass-metrics/src/modules/get-cloud-info.spec.js
- packages/compass-metrics/src/modules/rules.js
Spotted in the latest beta that metrics plugin was not starting correctly:
The root cause was mixing of esm and commonjs exports that webpack processes into the code that fails during the runtime
> fix(@mongodb-js/compass-metrics): Change commonjs export to esm

- packages/compass-aggregations/src/components/modify-source-banner/modify-source-banner.jsx
- packages/compass-collection/package.json
- packages/compass-collection/src/components/collection-header-actions/collection-header-actions.jsx
- packages/compass-collection/src/components/collection-header-actions/collection-header-actions.less
- packages/compass-collection/src/components/collection-header-actions/collection-header-actions.spec.js
- packages/compass-collection/src/components/collection-header-actions/index.js
- packages/compass-collection/src/components/collection-header-actions/view-information.jsx
- packages/compass-collection/src/components/collection-header/collection-header.jsx
- packages/compass-collection/src/components/collection-header/collection-header.less
- packages/compass-collection/src/components/collection-header/collection-header.spec.js
- packages/compass-collection/src/components/collection-header/read-only-badge.jsx
- packages/compass-collection/src/components/collection-header/time-series-badge.jsx
- packages/compass-collection/src/components/collection-header/view-badge.jsx
- packages/compass-collection/src/components/collection-header/view-information.jsx
COMPASS-4845
This PR updates our collection headers to use leafygreen-ui badges and buttons. It adds a time-series badge for time series collections.
Here's what it looks like now:
View:
Time-series collection:
Editing a view's pipeline collection header:
> feat(compass-collection): Update collection header to have new badges COMPASS-4845

- packages/databases-collections/src/components/collections/collections-table/collections-table.jsx
- packages/databases-collections/src/components/collections/collections-table/collections-table.spec.js
- packages/databases-collections/src/modules/collections/collections.js
- packages/databases-collections/src/modules/show-collection.js
Part of COMPASS-4906 
This PR updates the collections table to show `-` instead of `0` for the document count for time-series collections and views.
> fix(databases-collections): show `-` instead of `0` for collection document count in collections table COMPASS-4906

- packages/compass-crud/src/stores/crud-store.js
- packages/compass-import-export/electron/renderer/components/import-export/import-export.jsx
- packages/compass-import-export/electron/renderer/index.js
- packages/compass-import-export/src/index.js
- packages/compass-import-export/src/modules/export.js
- packages/compass-import-export/src/modules/export.spec.js
- packages/compass-import-export/src/plugin.js
- packages/compass-import-export/src/stores/export-store.js
- packages/compass-import-export/src/stores/import-store.js
- packages/compass-import-export/src/stores/index.js
- packages/compass-import-export/src/stores/store.js
- packages/compass-import-export/src/utils/get-shell-js.js
COMPASS-4537 COMPASS-4906
This PR fixes a couple bugs around import/export:
- Fixes opening the export modal by properly counting documents on time-series collections and views. The collection function `estimatedDocumentCount` errors on views and time-series collections, so now we use `countDocuments`. This is more expensive, so we could change up the ui here to either background load with a loader, or hide the count entirely. We do get to skip the count when we open the export from the export button on `compass-crud` by passing the count from the resulting query there.
- Fixes showing the correct count for the query used to find the documents to be exported. Previously we would always show the estimated count, although we would export the expected amount of documents resulting from the …
> fix(import-export): Use query document count in export COMPASS-4537, COMPASS-4906

- packages/compass-collection/src/assets/less/compass/components/_tab-nav-bar.less
- packages/compass-collection/src/components/collection-header/collection-header.less
- packages/compass-collection/src/components/collection/collection.jsx
- packages/compass-connect/src/assets/less/compass/components/_tab-nav-bar.less
- packages/compass-database/src/components/database/database.jsx
- packages/compass-deployment-awareness/src/assets/less/compass/components/_tab-nav-bar.less
- packages/compass-home/src/assets/less/compass/_tab-nav-bar.less
- packages/compass-home/src/assets/less/serverstats/index.less
- packages/compass-instance/src/plugin.jsx
- packages/compass-serverstats/styles/index.css
- packages/compass-serverstats/styles/index.less
- packages/compass/src/app/styles/tab-nav-bar.less
- packages/hadron-react-components/package.json
- packages/hadron-react-components/src/tab-nav-bar.jsx
- packages/hadron-react-components/test/tab-nav-bar.test.jsx
This PR updates the tabs used in the instance, database, and collection views to [leafygreen-ui tabs](https://github.com/mongodb/leafygreen-ui/tree/main/packages/tabs). Now arrow keys can also be used to navigate the tabs, so this probably gives a bit of an accessibility improvement.
https://user-images.githubusercontent.com/1791149/123879193-893a4900-d90e-11eb-92a4-6217dbd8bb4d.mp4
> style(hadron-react-components): Update tabs to LeafyGreen tabs

- packages/connection-model/package.json
- packages/connection-model/test/connect.test.js
- packages/index-model/package.json
- packages/index-model/test/fetch.test.js
When used with the mocha hooks, mongodb-runner seems to fail tests
with timeout quite often as it doesn't manage to start the server
before mocha timeout throws. Hopefully moving this server start stop
process to npm scripts will make CI a bit less flaky
[Evergreen patch](https://spruce.mongodb.com/version/60dc637961837d3bf1797d22/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) to confirm that this doesn't break anything
> chore: Replace usage of mongodb-runner mocha hooks with {pre,post}test scripts

- packages/compass-schema-validation/src/components/validation-states/validation-states.jsx
- packages/compass-schema-validation/src/components/validation-states/validation-states.spec.js
- packages/compass-schema-validation/src/modules/edit-mode.js
- packages/compass-schema-validation/src/modules/edit-mode.spec.js
- packages/compass-schema-validation/src/stores/store.js
- packages/compass-schema-validation/src/stores/store.spec.js
Custom validation can not be added to time-series collection, this PR disables validation tab interactions and adds a warning message at the top of the subtab
> feat(@mongodb-js/compass-schema-validation): Do not allow to edit validation for time-series collection COMPASS-4780

- packages/compass-deployment-awareness/src/components/deployment-awareness.jsx
- packages/compass-deployment-awareness/src/components/load-balanced.jsx
- packages/compass-deployment-awareness/src/components/load-balanced.less
- packages/compass-deployment-awareness/src/components/load-balanced.spec.js
- packages/compass-deployment-awareness/src/models/topology-type.js
- packages/connection-model/README.md
- packages/connection-model/lib/connect.js
- packages/connection-model/lib/model.js
- packages/connection-model/package.json
- packages/connection-model/test/build-uri.test.js
- packages/connection-model/test/parse-and-build-uri.js
- packages/connection-model/test/parse-uri-components.test.js
Pending a driver update to include NODE-3011, this should give
us what we need to support load balanced connections (specifically,
I tested this against the current state of that PR and it works).
> feat: support load balancer connections COMPASS-4898

- packages/databases-collections/src/components/collection-fields/time-series-fields.jsx
- packages/databases-collections/src/components/collection-fields/time-series-fields.less
- packages/databases-collections/src/components/collection-fields/time-series-fields.spec.js
COMPASS-4895
This PR adds a field for `granularity` for time-series collection configuration. This can be seen when creating a database or collection on a cluster with MongoDB version > 5.0
*What the select looks like*
*`db.getCollectionInfos()` for collections created with it*
> feat(databases-collections): Add granularity field to create collection COMPASS-4895

- packages/databases-collections/src/components/collections/collections-table/collections-table.jsx
- packages/databases-collections/src/components/collections/collections-table/collections-table.spec.js
> fix: hide drop-collection button in compass read-only COMPASS-4891

- packages/databases-collections/src/components/collapsible-field-set/collapsible-field-set.jsx
- packages/databases-collections/src/components/collection-fields/capped-collection-fields.jsx
- packages/databases-collections/src/components/collection-fields/capped-collection-fields.spec.js
- packages/databases-collections/src/components/collection-fields/collection-fields.jsx
- packages/databases-collections/src/components/collection-fields/time-series-fields.jsx
- packages/databases-collections/src/components/collection-fields/time-series-fields.spec.js
COMPASS-4890
This pr disables the `time-series` collection configuration when `capped` collection is selected, and vice-versa. Added tooltips with more info but they weren't working easily with modals so I removed and this pr just disables the checkboxes.
https://user-images.githubusercontent.com/1791149/124798065-f490a600-df20-11eb-8549-511fb2300b81.mp4
> feat(databases-collections): Disable collection configuration checkboxes when another is active COMPASS-4890

- packages/compass-collection-stats/src/components/collection-stats/collection-stats.jsx
This pr makes the props for the `compass-collection-stats` component optional to avoid the noisy warnings that they don't exist on initial load. 
Although it looks like the components are always rendered with these props, how we initially build these components and connect their store is making the initial prop validation fail. Looking into it more I noticed a number of packages (`compass-connect`,  to name a few)have their top level props marked as optional because of situations like this pr is updating. Created COMPASS-4935 to improve that.
> chore(compass-collection-stats): make plugin props optional

- packages/compass-shell/src/components/compass-shell/compass-shell.jsx
- packages/compass-shell/src/components/compass-shell/compass-shell.spec.js
- packages/compass-shell/src/components/info-modal/info-modal.jsx
- packages/compass-shell/src/components/info-modal/info-model.spec.js
- packages/compass-shell/src/components/resize-handle/resize-handle.less
- packages/compass-shell/src/components/shell-header/shell-header.jsx
- packages/compass-shell/src/components/shell-header/shell-header.less
COMPASS-4844
This PR updates `compass-shell` to show the mongosh version in the help panel. We also increased the height of the toolbar of this panel (28->32) and updated some of the type, removing some `beta`s and clarifying semantic keys with uppercase. 
Here's how it looks now:
https://user-images.githubusercontent.com/1791149/124827489-17808180-df44-11eb-8b2a-d8209023e653.mp4
Do we use `mongoSH` in a lot of places? Maybe we should update it to MongoDB Shell.
> fix(compass-shell): Show mongosh version in help panel, increase panel height, update text COMPASS-4844

- packages/connection-model/lib/model.js
- packages/connection-model/test/build-uri.test.js
- packages/connection-model/test/parse-and-build-uri.js
Set authSource instead of appending it for `LDAP`, `KERBEROS` and `X509`.
> fix: remove duplicated authSource from url COMPASS-4940

- package.json
- packages/hadron-build/commands/release.js
The `npm install --production` we have in `hadron-build` won't compile `addaleax/node-mongodb-native#71d4c39e5c858f49d10e840df626eca4da653e28`.
This is a quick fix that adds an additional `npm install` for the driver if comes from a fork (just as a safeguard in case we would forget removing it)
> fix: build re-compile driver COMPASS-4939

- packages/compass-connect/src/stores/index.js
- packages/compass-connect/test/renderer/stores/index.spec.js
Currently Compass always overrides `appname` with Electron application name when opening a connection to the server. We want to only do that if the user haven't provided their own appname in the connection string. Additionally, we don't really want to expose it as a possible connection option as the use-case for changing `appname` is pretty rare, so we are not exposing it anywhere in the connection form
Here's a mongodb server log entry for connection with connection string `mongodb://localhost:27020?appname=please-keep-me-intact` before the change:
```json
{"t":{"$date":"2021-07-12T14:01:11.510+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn15","msg":"client metadata","attr":{"remote":"172.23.0.1:58712","client":"conn15","doc":{"driver":{"name":"nodejs","version":"4.0.0-beta.6 …
```
> feat(@mongodb-js/compass-connect): Do not override appname if provided by the user COMPASS-4901

- packages/databases-collections/src/components/create-database-modal/create-database-modal.jsx
- packages/databases-collections/src/components/create-database-modal/create-database-modal.spec.js
quick drive by - before the blue message would stay when collection name was filled in.
https://user-images.githubusercontent.com/1791149/125349375-7d498080-e32b-11eb-85d4-0668739de886.mp4
> chore(databases-collections): hide message to fill in collection name when its filled in

- packages/compass-crud/src/components/readonly-document.jsx
- packages/hadron-react-components/src/tab-nav-bar.jsx
Noticed some warnings in console, doing a bit of updating to remove them. There are a few more in other packages, but I figured these are a few to start.
https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops
> chore(compass-crud,hadron-react-components): Replace deprecated react componentWillReceiveProps usage

- packages/compass-connect/src/components/form/authentication/kerberos/cname-input.jsx
- packages/connection-model/lib/model.js
- packages/connection-model/test/build-uri.test.js
- packages/connection-model/test/parse-and-build-uri.js
- packages/connection-model/test/parse-uri-components.test.js
This updates the handling of Kerberos-relevant properties to be compatible with the latest driver v4. Notably support for "Service Name" has been implemented correctly. The code change also takes care to not include duplicate settings in the query parameter for Kerberos (e.g. having a dedicated `gssapiServiceName` query parameter _and_ a `SERVICE_NAME` authentication mechanism property). All properties will still be read and parsed initially but then transferred over properly to the correct properties the driver understands.
In order to support hostname canonicalization the `gssapiCanonicalizeHostName` authMechanismProperty is used which the driver v4 currently looks at. This needs to be adjusted once NODE-3351 is implemented.
The PR also includes a fix where changing the toggle for …
> fix(compass-connect,connection-model): support all Kerberos options COMPASS-4529

- scripts/gather-licenses.js
"Update third party notices" job on main is failing for a while, seems like the root cause is one of the Compass dependencies having a weird package.json published with the dist that throws off gather licenses script, or to be more specific the `pkgUp` logic.
This PR fixes the issue by trying to find package.json closest to the dependency root and only if this failed it falls back to the usual flow of using `pkgUp` starting from the resolved location of the dependency.
> fix: Check that package.json that we found contains at least the minimal amount of required keys

- packages/bson-transpilers/README.md
As discussed in COMPASS-4930 we will not try to fix shell target and instead will keep its output compatible only with legacy shell
> chore(bson-transpilers): Add warning about shell output COMPASS-4930

- packages/compass/release/branch.spec.js
- packages/compass/release/bump.spec.js
- packages/compass/release/download-center.spec.js
- packages/compass/release/index.spec.js
- packages/compass/release/publish.spec.js
- packages/compass/release/version.spec.js
- packages/compass/release/wait-for-assets.spec.js
Those get stuck on macos in evergreen and we want to skip them for now just so we can quickly unblock the failing macos CI
> test(mongodb-compass): Skip release tests in Evergreen CI

- packages/compass/src/app/setup-plugin-manager.js
We stumbled on an interesting issue with Alena where a transitive dependency update broke latest Compass app build due to the usage of `eval` that wasn't there in the previous version. Even though this is currently happens not because we manually updated something, but rather because when Compass app is packaged, it doesn't have a package-lock, so all sorts of inconsistencies are possible, this made me look a bit closer on how we handle this `eval` override and I think it would make sense to remove this environment check so that we would actually be able to catch something like this in the future when running Compass locally and not only in the packaged application.
Also just thinking out loud here, but I'm wondering if we want this behavior at all, it wouldn't stop malicious actors from …
> chore(mongodb-compass): Remove node_env check around eval override

- packages/compass-query-bar/src/plugin.spec.js
Was chatting with @chrisrichie25 on how we can test the query bar in Atlas and noticed we could use a test here to test more of the behavior of the component w/ its props so this just a quick add testing the apply and onChange functionality of the ace editor + query bar.
> test(compass-query-bar): Add test for query bar updating

- packages/compass-metrics/src/modules/features.js
- packages/compass-metrics/src/modules/rules.js
Add 'ExportToLanguage' resource to features.js file in order to track 'compass:export-to-language:opened' and 'compass:export-to-language:run' events. All events should have corresponding feature actions, otherwise telemetry will be missing: https://jira.mongodb.org/browse/COMPASS-4379
I added some TODO comments to the code since I noticed that not only export to language features and rules weren't in sync but many others. Probably other telemetry events are missing because of that. I left it without further investigation because we are going to replace the current metrics with new Segment metrics: https://jira.mongodb.org/browse/COMPASS-4946
> fix(compass-metrics): telemetry for export to language is missing COMPASS-4379

- packages/compass-serverstats/styles/index.less
Quick drive by 1 line style fix. Happens on smaller screens/windows.
Noticed some of these styles are duplicated, probably something to reduce at some point.
*before*
*after*
> fix(compass-serverstats): styling content height fix

- packages/compass/src/app/setup-plugin-manager.js
Well, guess what, removing this guard actually breaks dev build of compass because jade templates are not compiling anymore. Will revert for now so that `main` is not broken
> Revert "chore(mongodb-compass): Remove node_env check around eval override"

- packages/compass-shell/src/components/compass-shell/compass-shell.less
COMPASS-4985
Before (there is a scrollbar there I promise):
After:
This probably goes away in a newer electron version, but I think we might as well patch it now. In the https://github.com/mongodb-js/mongosh/tree/main/packages/browser-repl storybook for instance the scollbar contrasts correctly.
> fix(compass-shell): style scrollbar to increase contrast COMPASS-4985

- packages/compass-crud/src/components/editable-value.jsx
- packages/compass-crud/src/components/editable-value.spec.js
COMPASS-4988
Fixes the field width and text area height on fields with string values that are very long and not multi line. Should allow selecting the value and scrolling.
Before:
After:
> fix(compass-crud): Text area height and field width with large 1 line strings COMPASS-4988

- packages/compass-aggregations/src/components/input-builder-toolbar/input-builder-toolbar.less
- packages/compass-aggregations/src/components/input-builder/input-builder.jsx
- packages/compass-aggregations/src/components/input-builder/input-builder.less
- packages/compass-aggregations/src/components/input-preview/input-preview.jsx
- packages/compass-aggregations/src/components/input-preview/input-preview.less
- packages/compass-aggregations/src/components/input-toolbar/input-toolbar.jsx
- packages/compass-aggregations/src/components/input-workspace/input-workspace.jsx
- packages/compass-aggregations/src/components/stage/stage.jsx
This makes the top preview area on the aggregations tab horizontally resizable. Something I missed when making them resizable and finally got around to.
https://user-images.githubusercontent.com/1791149/125370564-bcd49480-e34c-11eb-93ee-43c1811da52e.mp4
> feat(compass-aggregations): make top area preview resizeable

- packages/compass-query-bar/src/components/query-bar/query-bar.jsx
- packages/compass-query-bar/src/components/query-bar/query-bar.spec.js
- packages/compass-query-bar/src/plugin.spec.js
This PR adds the ability for one to hide the square sorts place holder in the sort option of the query bar. This feature makes it possible for one to be clear about the type of sorts that are supported in the query bar. For example, in the case that the square brackets are not supported, one can hide the sort square brackets placeholder.
> feat(@mongodb-js/compass-query-bar): Add prop to toggle visibility of sorts square bracket placeholders CLOUDP-97063

- packages/compass-components/.depcheckrc
- packages/compass-components/package.json
The rest of the project uses `jsdom-global` lol looks like the more used of the two also. Probably mistyped or copy pasted wrong.
https://www.npmjs.com/package/jsdom-global
https://www.npmjs.com/package/global-jsdom
> chore(compass-components): use jsdom-global remove global-jsdom for mocha testing dom 

- packages/compass-components/.eslintrc.js
- packages/data-service/.eslintrc.js
Workaround for the [Node.js/win32 issue](https://github.com/nodejs/node/issues/34866) that breaks eslint-typescript checks in Evergreen cygwin environment because of how windows hosts in evergreen link directories when setting up cygwin
[Evergreen patch](https://spruce.mongodb.com/version/611bb98b2fbabe0a4281c684/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) that is still running, but already passed the `check` stage that was failing before
> fix(eslint): Use path.resolve for tsconfig to work around cygwin issues in Evergreen

- packages/compass-sidebar/package.json
- packages/compass-sidebar/src/components/sidebar-title/sidebar-title.jsx
- packages/compass-sidebar/src/components/sidebar-title/sidebar-title.less
Updates collapsed sidebar home/logo to be the MongoDB leaf from [leafygreen-ui/logo](https://www.mongodb.design/component/logo/example/) with a background color that shows the user's favorite color. This is a bit of the work from sidebar changes in the mini skunkworks panels, just breaking it out into a few parts.
*Before*
https://user-images.githubusercontent.com/1791149/129843687-a32a5b4d-c3b2-498d-87ab-a21a0ff1ec6d.mp4
*After*
https://user-images.githubusercontent.com/1791149/129843656-4ea75236-77d2-4a1d-b95c-74996a685a26.mp4
> feat(compass-sidebar): use logo in collapsed sidebar

- .github/workflows/build.yaml
- package.json
- packages/hadron-build/commands/release.js
- packages/hadron-build/lib/generate-package-lock.js
Local registry publishing works great in GitHub CI and locally, but Evergreen does weird things and fails to to a publish. We would need some time to investigate why Evergreen is not working well with this approach and to unblock main branch we will put the local registry publishing behind an environment flag
[Evergreen patch](https://spruce.mongodb.com/version/611e05a73e8e863612b1a918/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) that should pass now hopefully 🤞
> chore(hadron-build): Put local registry publishing logic behind an env flag

- packages/compass-query-bar/src/modules/merge-geo-filter.js
- packages/compass-query-bar/src/stores/query-bar-store.js
- packages/compass-query-bar/test/modules/merge-geo-filter.spec.js
- packages/compass-query-bar/test/renderer/query-bar-store.spec.js
mergeGeoFilter incorrectly detected geo filter queries by looking at the field name to see if it is "coordinates", but coordinate fields can be called anything.
The geo queries coming from the schema are actually using [Geospatial Query Operators](https://docs.mongodb.com/manual/reference/operator/query-geospatial/), so `newGeoQueryFilter` looks like this for the first query:
```json
{
"coordinates": {
"$geoWithin": {
"$centerSphere": [
[
-139.23222157287597,
37.19803100919542
],
0.3673330493291723
]
}
}
}
```
Where `"coordinates"` is just the field name. It could also be something like `"start station location"` or `"end station location"`.
Then for the second one onwards, `newGeoQueryFilter` looks something like like this:
```json
{
"$or": [
{
"coordinates": {
"$geoWithin": { …
```
> fix: correctly detect geo filters to be merged (COMPASS-4968)

- .evergreen.yml
- packages/compass-components/.eslintrc.js
- packages/data-service/.eslintrc.js
This workaround from https://github.com/mongodb-js/compass/pull/2403 breaks eslint vscode integration (and will probably break all the other ones) and this seems to be more important to me than having this check running in evergreen on windows (we also would still have it in all the other environments we are running our tests in)
> ci(evergreen): Remove the cygwin workaround for lint and disable verify step on windows

- packages/compass-aggregations/src/modules/index.js
- packages/compass-aggregations/src/modules/index.spec.js
There are various cases where [generateStage](https://github.com/mongodb-js/compass/blob/d320c8a64d2df7b47ac313f42f0141769c99f104/packages/compass-aggregations/src/modules/stage.js#L75) returns `{}` so the pipeline array has valid stages with empty objects mixed in. Solution was to just filter those out where they get made in openCreateView.
I split the code out so I can easily unit test it as openCreateView suffers from that thunk dispatch problem where it isn't easy to spy on what it passes on.
> fix: filter out {} stages from the view pipeline (COMPASS-4977)

- .evergreen.yml
Typescript compiler was not picking up the config paths correctly and failing to build, similar to eslint issue before that, but in case of tsc there is no way to work around the issue without actually switching the working directory which this PR does
[Evergreen patch](https://spruce.mongodb.com/version/611fa002850e61502ae420a5/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) to confirm that this doesn't break the build or the flow on other machines (it [passed once](https://spruce.mongodb.com/task/10gen_compass_main_windows_oneshot_compile_test_package_publish_patch_46c246b7d05984f898f0346e01fa41efed93fb95_611f96eb0ae6061dc4578269_21_08_20_11_50_27/logs?execution=0) for me, but I want to double-check)
> ci(evergreen): Force evergreen to run on drive z instead of c to workaround Node.js issues with cwd on windows

- .gitignore
- packages/compass-import-export/src/utils/import-preview.js
A better explanation of the bug is if you import fields with names that contain non-ascii characters, then those will always import as strings, no matter what you select in the dropdown.
---
Uncommenting [this debug call](https://github.com/mongodb-js/compass/blob/db22d48d9acdf606727bbb13d42db0b1e382f653/packages/compass-import-export/src/utils/import-apply-types-and-projection.js#L61) it prints `{“keyPathToTransform”:{“”:“Number”},“keyPath”:“价格“}`. See that it made the path a blank string. It clearly stripped all non-ascii characters when it tried to turn it into dot notation.
That happened [here](https://github.com/mongodb-js/compass/blob/db22d48d9acdf606727bbb13d42db0b1e382f653/packages/compass-import-export/src/utils/import-preview.js#L77)
Here you can see where that change was …
> fix: remove hack that seems to have no upside (COMPASS-4987)

- .github/workflows/build.yaml
We have a separate ticket for getting to the root cause of this windows zlib issue, but as a temporary workaround I want to try bringing back the retries that we had here before when registry publishing was only done in github ci
> ci(github): Retry package and publish step to hopefully work around windows publishing issues

- packages/data-service/test/connectivity.spec.ts
As `docker-compose` seems not to be available on RHEL Evergreen machines we skip the connectivity tests there.
> tests(data-service): skip connectivity tests on RHEL

- .github/workflows/build.yaml
- .github/workflows/check-test.yaml
- packages/compass-e2e-tests/helpers/compass.js
- packages/compass-e2e-tests/helpers/delay.js
- packages/compass-e2e-tests/helpers/retry-with-backoff.js
- packages/compass-e2e-tests/tests/smoke.test.js
GitHub CI macOS host got annoyingly flaky when trying to test packaged app. Seems like it's not a constant failure, but some flakiness on the initial app start logic. To try to work around that I added some retries for the logic that happens in `before` hook of the tests, let's see if this helps.
Also added some verbose debug logging similar to what native-client was doing (thanks for the original implementation @addaleax!) to maybe be able to get to the bottom of issue
> fix(compass-e2e-tests): Retry app start waiting logic to make tests less flaky on github ci macos machines

- packages/compass-schema-validation/src/components/compass-schema-validation/compass-schema-validation.jsx
- packages/compass-schema-validation/src/components/validation-states/validation-states.jsx
- packages/compass-schema-validation/src/components/validation-states/validation-states.spec.js
- packages/compass-schema-validation/src/modules/index.js
- packages/compass-schema-validation/src/modules/is-loaded.js
- packages/compass-schema-validation/src/modules/is-loaded.spec.js
- packages/compass-schema-validation/src/modules/validation.js
- packages/compass-schema-validation/src/modules/validation.spec.js
- packages/compass-schema-validation/src/stores/store.js
**Testing:**
If you're looking for an easy way to test this, the citibike.trips and compass_analytics.active_users collections have validation configured.
**Changes:**
It used to load the moment the compass-schema-validation store got created, now it happens when the user browses to the validation tab.
This means that it is more likely that the validations haven't been fetched from the db by the time the user sees the validation component, so I had to introduce some more state (isLoaded). Now it won't render the zero state if it is still loading the validations. Otherwise you would see the zero state (something to the effect of "you don't have any validations, start by adding some") flash momentarily while the validations load even if it does load validations in the end. I figured that …
> fix: lazy-load validations when the user browses to the validation tab (COMPASS-4998)

- packages/compass-connect/src/components/form/ssl-server-client-validation.jsx
As the driver no longer supports multiple SSL CA files to be specified, the option to select multiple files is removed.
> fix(compass-connect): only allow a single CA file COMPASS-5065

- configs/eslint-config-compass/index.js
- packages/data-service/package.json
- packages/data-service/src/connection-storage.spec.ts
- packages/data-service/src/connection-storage.ts
- packages/data-service/src/legacy-connection-model.spec.ts
- packages/data-service/src/legacy-connection-model.ts
- packages/storage-mixin/lib/backends/disk.js
- packages/storage-mixin/lib/backends/splice-disk-ipc.js
- packages/storage-mixin/lib/backends/test.js
- packages/storage-mixin/lib/index.js
Add a `ConnectionStorage` interface and class (not integrated yet).
This class at the moment only uses the usual storage-mixing / connection model mechanism to store and load connections. At the moment is intended isolate further changes to the storage from the rest of Compass and unblock frontend work.
In a future iteration it will replace completely the way connections are loaded and stored.
> refactor: add ConnectionStorage interface COMPASS-5010

- packages/data-service/src/connection-options.ts
- packages/data-service/src/legacy-connection-model.spec.ts
- packages/data-service/src/legacy-connection-model.ts
The conversion methods to convert between the new `ConnectionOptions` and the legacy `ConnectionModel` were missing proper handling for SSL/TLS configuration.
> fix(data-service): ensure conversion takes SSL options into account

- packages/compass-sidebar/src/components/sidebar-collection/sidebar-collection.jsx
- packages/compass-sidebar/src/components/sidebar-collection/sidebar-collection.spec.js
COMPASS-5015
Fixes duplicating a view, we weren't passing the db name.
Looks like this isn't a new bug. Opened a discussion in slack about the naming of these variables which could have led to this bug (having a test for this, and probably just creating the view from here instead of an event passed to `compass-aggregations` would probably avoid things like this too). Here's where compass-aggregations handles the event: 
https://github.com/mongodb-js/compass/blob/main/packages/compass-aggregations/src/modules/create-view/index.js#L153
https://user-images.githubusercontent.com/1791149/131891962-4ac7fef5-8532-4f9e-9867-f143f8f57479.mp4
> fix(compass-sidebar): pass source namespace when duplicating view COMPASS-5015

- packages/compass-e2e-tests/helpers/commands/close-privacy-settings-modal.js
- packages/compass-e2e-tests/helpers/commands/close-tour-modal.js
- packages/compass-e2e-tests/helpers/retry-with-backoff.js
* reverse: true, not reverse: false..
* going with waitForVisible rather than waitForExist so it mirrors the one we used when we got there and that's all that matters anyway.
* console.warn() the error in retry-with-backoff if we're going to retry. Really helpful in debugging and to spot if and why it ever retries.
> fix: properly reverse the waitForX calls

- packages/compass-shell/src/components/compass-shell/compass-shell.module.less
COMPASS-5050
Before
After
https://user-images.githubusercontent.com/1791149/134076072-67a69754-62ab-440a-820c-7eeb5f572af2.mp4
> fix(compass-shell): Fix compass-shell overlaying modals COMPASS-5050

- packages/compass-query-bar/src/components/option-editor/option-editor.jsx
- packages/compass-query-bar/src/components/option-editor/option-editor.module.less
- packages/compass-query-bar/src/components/options-toggle/options-toggle.module.less
- packages/compass-query-bar/src/components/query-bar/query-bar.jsx
- packages/compass-query-bar/src/components/query-bar/query-bar.module.less
- packages/compass-query-bar/src/components/query-option/query-option.jsx
- packages/compass-query-bar/src/components/query-option/query-option.module.less
Modified the option-editor/option-toggle to use flex so that they don't overlap one another  when the screen width is decreased and text in the editor doesn't get hidden underneath the options-toggle. 
JIRA: https://jira.mongodb.org/browse/COMPASS-5098
- [ x] Ran existing test suite
- [ x] Tested manually
- [ x] Bugfix
https://jira.mongodb.org/browse/CLOUDP-100208 (MMS data explorer feature) depends on this PR.
- [ x] Patch (non-breaking change which fixes an issue)
> fix(compass-query-bar): find filter/options editor no longer overflows beneath the options toggle COMPASS-5098

- packages/compass-indexes/src/components/create-index-modal/create-index-modal.spec.js
There was a large amount of spam from the tests of the `compass-indexes` package which would crash evergreen on windows.
I think the spam came from two modals being tested both trying to grab focus. Although these tests are running separately, they must be somehow not unmounted after the test is run (maybe an internal animation on unmounting?).
This PR makes it so the testing modal component is unmounted after the tests are run using enzyme's `unmount`. Definitely a bit of a weird bug to trackdown 😅 
Evergreen patch: https://spruce.mongodb.com/version/614a7f31d1fe077c9fbcba7a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> fix(compass-indexes): unmount test component with focusing modal

- packages/compass-e2e-tests/tests/logging.test.js
- packages/compass-shell/package.json
- packages/compass-shell/src/stores/store.js
> feat(compass-shell): integrate shell logging COMPASS-5035

- .github/workflows/build.yaml
- .github/workflows/check-test.yaml
- Default timeout is 360 mins which is too much, we can fail our tests much faster
- Always upload Compass app builds so they can be inspected locally when tests fail
Hoping this will help investigate why GH CI is not happy with latest changes in main when trying to test packaged app
> ci(github): Add timeout and always upload compass app builds if present

- configs/webpack-config-compass/src/index.ts
So the root cause of the packaged app currently not working (and the tests failing in GitHub CI) in `main` was incorrectly bundled native Node.js modules. The reason I couldn't reproduce it until I got a macOS build from #2472 to debug is that I have this change already in #2465 and while checking out back and forth between branches I completely forgot to rebuild webpack config before repackaging the app 🤦 Good thing we had CI tests to confirm that this is not just some flakiness!
> fix(mongodb-compass): Do not bundle native modules with the rest of the Compass app

- packages/compass-e2e-tests/helpers/compass.js
- packages/compass/src/app/setup-plugin-manager.js
- packages/compass/src/main/application.js
- packages/compass/src/main/index.js
- packages/compass/src/main/logging.js
On macOS overriding `HOME` variable confuses keychain and causes weird issues when running e2e tests locally (you would see an error `no keychain found to store "x"` because default keychain is missing):
To work around that I added a new env variable that allows to explicitly set log path to something else when running Compass. I also refactored setup code a bit to match it with what Compass is already doing: moved it all into `Application` method and tried to use electron APIs to resolve paths.
As a drive-by I also fixed unhandled rejection dialog that was never showing up before if app crashed before it had a chance to emit a `ready` event
> chore(compass-e2e-tests, mongodb-compass): Move compass logging setup to the Application code and use a special env var to override log path in tests

- .evergreen.yml
- packages/compass/release/index.spec.js
- cygwin was not happy with the file urls, interpreted them weirdly and couldn't push to the remote failing with `remote /C://... not found` error, luckily it seems like it's not required to pass file urls to git, it works with just file paths fine, so that's what I did
- now that Compass is built with webpack having `DEBUG=*` in the evergreen config caused everything (mostly babel) to log massive amounts of unhelpful information, I reduced the debug and npm verbosity to more reasonable levels
[Here's an evergreen run](https://spruce.mongodb.com/version/6150a18557e85a7b5280ee2a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) that passes on windows and ubuntu
We currently still have issues on RHEL where mongocryptd fails to build for some reason and on macOS where storage-mixin started …
> ci(evergreen): Make logs less verbose and fix release tests on cygwin

- packages/compass-e2e-tests/helpers/keychain.js
- packages/compass-e2e-tests/index.js
- packages/compass-e2e-tests/package.json
- packages/compass/src/main/application.js
I was digging more into what happened with the e2e tests and why y'all macOS users started having issues when running tests locally. I am not sure if this is the whole explanation but here's what I found so far:
- One thing was more or less kind of an unexpected bug/side-effect of how Compass stores stuff in the keychain. We were running tests against a production build of the application, but this also meant that the app name was set to the "production" version: "MongoDB Compass" (no postfixes). This meant that when tests are running, they are storing connection info under the same name as production app. It meant that when you would open a "real" Compass app installed on your machine after a test run is finished, it would try to read those connections also and prompt you for password as …
> chore(compass-e2e-tests): Clarify the keychain switching and allow to skip the build

- packages/compass-e2e-tests/tests/logging.test.js
Some times e2e tests for logging seems to fail for reasons not always related to the logging itself.
In the spirit of keeping the e2e tests value significantly higher than their maintenance cost in the long run I tried to make the checks a bit more tolerant. Let me know if I didn't do something silly @addaleax!
Also on my machine I couldn't get them to run properly, will see how it goes in the CI.
> chore: relax e2e logging tests

- .github/workflows/build.yaml
- CONTRIBUTING.md
- package.json
They were required before, but now they are completely optional and handled by webpack config automatically
> chore: Don't provide any `HADRON_*` env vars for package-compass script

- packages/compass-crud/src/components/toolbar.jsx
- packages/compass-e2e-tests/helpers/commands/click-visible.js
- packages/compass-e2e-tests/helpers/commands/close-collection-tabs.js
- packages/compass-e2e-tests/helpers/commands/connect-with-connection-form.js
- packages/compass-e2e-tests/helpers/commands/index.js
- packages/compass-e2e-tests/helpers/commands/navigate-to-collection-tab.js
- packages/compass-e2e-tests/helpers/commands/navigate-to-database-tab.js
- packages/compass-e2e-tests/helpers/commands/navigate-to-instance-tab.js
- packages/compass-e2e-tests/helpers/commands/set-ace-value.js
- packages/compass-e2e-tests/helpers/commands/wait-for-animations.js
- packages/compass-e2e-tests/helpers/compass.js
- packages/compass-e2e-tests/helpers/selectors.js
- packages/compass-e2e-tests/package.json
- packages/compass-e2e-tests/tests/smoke.test.js
- packages/compass-import-export/src/components/export-modal/export-modal.jsx
- packages/compass-import-export/src/components/select-file-type/select-file-type.jsx
- packages/hadron-react-components/src/option-selector.jsx
This is a bit of a hack because there is no standard browser functionality for selecting an output path and the code uses some elecron APIs that we can't test with webdriver. The app displays the path in a readonly input type file, but that's not hooked up so we can change things from there - if you change the value through code it updates the display, but that's not the source of truth so it doesn't work. What I came up with here is to use [custom events](https://www.falldowngoboone.com/blog/talk-to-your-react-components-with-custom-events/) to provide a hook that we can call to ultimately call the prop that dispatches the action.
Please let me know if you have any better ideas. Obviously this isn't ideal, but at least the rest of the process can be tested this way.
This means the …
> chore: export documents e2e test (COMPASS-5047)

- packages/hadron-react-bson/src/index.js
- packages/hadron-react-bson/src/timestamp-value.jsx
- packages/hadron-react-bson/test/index.test.jsx
- packages/hadron-react-bson/test/timestamp-value.test.jsx
Displaying Timestamp fields as Longs renders the individual fields
meaningless. Instead, render them using a custom class that
displays the time/increment fields separately.
> fix(hadron-react-bson): add Timestamp display component COMPASS-5100

- packages/compass-crud/src/components/insert-document-dialog.jsx
Fixes clicking on a field type off the modal and closing the modal (gif shows before this change):
https://user-images.githubusercontent.com/1791149/135966539-5bf13ca3-84b1-4237-8438-6165b2c2fedd.mp4
> fix(compass-crud): fix field type select click modal backdrop close

- packages/compass-aggregations/config/webpack.dev.config.js
- packages/compass-collection-stats/config/webpack.dev.config.js
- packages/compass-collection-stats/package.json
- packages/compass-connect/package.json
- packages/compass-crud/package.json
- packages/compass-explain-plan/package.json
- packages/compass-export-to-language/package.json
- packages/compass-schema-validation/package.json
- packages/compass-schema/package.json
- packages/compass-shell/config/webpack.dev.config.js
- packages/compass-sidebar/package.json
- packages/databases-collections/config/webpack.dev.config.js
Since we don't allow FLE in Compass this is a workaround for https://jira.mongodb.org/browse/NODE-3632 in order to keep support for Centos/Rhel7.
> fix: remove mongodb-client-encryption from bundle

- packages/compass-e2e-tests/helpers/commands/listen-for-telemetry-events.js
- packages/compass-e2e-tests/tests/logging.test.js
- packages/compass/src/main/telemetry.ts
Track distribution (normal/readonly/isolated) and channel
(stable/beta/dev) in telemetry data, and fix the compass_version field
to only be major.minor, not the full version.
> chore: track compass edition in telemetry COMPASS-5242

- packages/compass-sidebar/src/components/sidebar-title/sidebar-title.jsx
We bumped this in a recent pr, but these props weren't updated and were giving some warnings/errors in console. This pr updates them and makes the new logo look nice.
> fix(sidebar): Update logomark props for new logo

- configs/eslint-config-compass/index.js
- configs/eslint-config-compass/package.json
Adds https://github.com/facebook/react/tree/main/packages/eslint-plugin-react-hooks with recommended settings to our shared eslint config. This has checks for https://reactjs.org/docs/hooks-rules.html which shouldn't be much but I think it'll be a good thing since we're adding more hooks going forward in Compass.
Looks like this isn't part of the react eslint plugin recommended: https://github.com/yannickcr/eslint-plugin-react#other-useful-plugins
> chore(eslint-config): Add eslint react-hooks plugin with recommended settings

- packages/compass-home/src/components/home.tsx
This adds dependencies to the useEffect where we create and teardown the appRegistry event listeners. Previously we would do this on any render, now we will do it only when relevant dependencies are updated to avoid the extra subscribing and unsubscribing. 
Breaking this out of a larger PR I had it in.
> chore(compass-home): add deps to avoid extra listener refreshes

- packages/compass-schema/src/components/compass-schema/compass-schema.jsx
Now there is [only one tooltip](https://github.com/mongodb-js/compass/blob/daaa1f7ade7e4300ac540f566a79bb5a558061a4/packages/compass-schema/src/components/type/type.js#L135) for every schema field type probability, not also one [disused page-wide](https://github.com/mongodb-js/compass/blob/daaa1f7ade7e4300ac540f566a79bb5a558061a4/packages/compass-schema/src/components/compass-schema/compass-schema.jsx#L227-L229) one that shares the same identical id as all the others.
> remove extra tooltip with identical id COMPASS-4664

- packages/collection-model/lib/model.js
- packages/compass-app-stores/src/stores/instance-store.spec.js
- packages/data-service/src/data-service.spec.ts
- packages/data-service/src/data-service.ts
- packages/data-service/src/instance-detail-helper.spec.ts
- packages/data-service/src/instance-detail-helper.ts
- packages/data-service/src/run-command.ts
- packages/data-service/test/helpers.ts
- packages/database-model/lib/model.js
In Compass we _always_ want databases and collections from privileges to be present in the UI even when they don't exist or user can't list databases or collections with the corresponding commands for any reason. To achieve that and not loose this behavior ever again I moved all this privileges resolution logic to the `dataService` so that all the possible places in Compass that are listing databases and collections get a consistent result when asking for this data. This fixes a regression issue introduced in 1.29 due to me removing this logic by accident in the `instance-helper` refactoring PR not that long ago
I had to move some tests around in `data-service` package so I recommend you review this with [whitespace diff disabled](https://github.com/mongodb-js/compass/pull/2579/files?w=1)
> fix(data-service, database-model, collection-model): Always merge db/colls from privileges into listDatabases/listCollections command result

- packages/compass-e2e-tests/helpers/commands/open-tour-modal.js
This works around an obscure issue when running tests locally on
macos where the firewall warning popup seems to prevent this script
from being stuck
> test(e2e): Use ipc directly to open tour modal

- packages/compass-connect/src/stores/index.js
Catch and logs telemetry failures so that it doesn't get to be an unhandled promise.
@gribnoysup I started to have issues with the dns resolution too with atlas, i don't know if this actually fixes it since those are quite sporadic for me, but we need a `.catch` there anyway.
> fix: handle failed telemetry dns resolutions

- packages/compass-crud/src/stores/crud-store.js
- packages/compass-crud/src/stores/crud-store.spec.js
- packages/data-service/src/data-service.ts
This fixes an issue with Serverless instances of MongoDB where trying to run multiple session commands in parallel is causing driver to throw an error. We learned from the driver team that even though running concurrent session commands works in some cases, it's really not something that we should be doing, so the fix is to have a separate session for every command we are running in parallel here
> fix(compass-crud): Use separate sessions for all operations in compass-crud COMPASS-5299

- packages/connections/.mocharc.js
- packages/connections/package.json
- packages/connections/src/components/connections.spec.tsx
- packages/connections/src/components/connections.tsx
- packages/connections/src/stores/connections-store.ts
This pr moves some of the connections setup (temp directory creation and connection saving) into `before` helpers instead of `beforeEach`. I'm thinking some of the flakiness we were witnessing on ci were due to this frequent setup and teardown and hopefully this will fix it. 
Edit: Looks like it still happened on ubuntu
> chore(connections): Move expensive beforeEach test setup into before operation

- packages/compass-crud/src/stores/crud-store.js
- packages/compass-crud/src/utils/cancellable-queries.spec.js
- packages/data-service/src/data-service.spec.ts
- packages/data-service/src/data-service.ts
I merged #2593 before noticing @mcasimir s suggestion to rename the method in https://github.com/mongodb-js/compass/pull/2593#discussion_r751274012
> chore(data-service): Rename killSession to killSessions

- package.json
- scripts/changed.js
Pretty often I find myself in situation where I want to run `check` or `test` against changed packaged, react to the issues this surfaces (like the need to run reformat or something) and continue from where I stopped. Added a command for that that looks kinda like this when used:
> chore(scripts): Add script to interactively run commands against changed packages

- .github/workflows/connectivity-tests.yaml
- packages/data-service/package.json
- packages/data-service/src/connect-mongo-client.ts
- packages/data-service/src/connect.spec.ts
NOTE: still need to add tests before we merge, but tested manually and the fix is that one. 
This code threw me off completely:
```
if (
!url.searchParams.has('tlsCertificateFile') &&
url.searchParams.has('tlsCertificateKeyFile')
) {
url.searchParams.set(
'tlsCertificateFile',
url.searchParams.get('tlsCertificateKeyFile') as string
);
}
```
Actually `tlsCertificateFile` is also a MongoClient connection option, and in that case represents the client cert, while in the string is a "temporary" replacement of `tlsCertificateKeyFile`
> fix: tlsCertificateFile being ignored COMPASS-5298

- packages/compass-crud/src/components/document-list.jsx
https://mongodb.slack.com/archives/G2L10JAV7/p1637584911321400
> don't show the zero state if we're fetching documents but not debouncing

- packages/compass-app-stores/src/stores/instance-store.js
- packages/compass-collection-stats/src/components/collection-stats/collection-stats.jsx
- packages/compass-collection-stats/src/stores/store.js
- packages/compass-collection-stats/src/stores/store.spec.js
- packages/compass-collection/src/modules/context.js
The root cause was that we didn't emit a fetch on the model when the namespace was changed, the fix
is adding listeners for all the important events that signal that the collection is shown on the screen now
(unfortunately there is no one consistent event communicating that at the moment)
Hiding stats is a workaround for the issue with events not being emitted when we switch to the source
collection that can be used to trigger the data fetch, this is a bigger issue to resolve so for now
I'm just hiding the stats for these cases completely as they are not that important anyway when editing
and we don't consider them too important in general (new designs don't have as many shown there) so
this feels to me like an alright compromise (also allows to keep the scope of the fix to the minimum)
> fix(instance-model, compass-collection): Fetch collection info when active namepsace changes and don't show collStats when editing a view

- packages/hadron-ipc/lib/main.js
Fixes https://mongodb.slack.com/archives/G2L10JAV7/p1637691135338300
Even though I'm able to reproduce with beta, I absolutely can't reproduce this with a local build, but this should fix it, this is the only place where we reference `isDestroyed` in our code and [based on the docs](https://www.electronjs.org/docs/latest/api/browser-window#browserwindowfromwebcontentswebcontents) it can be `null` if webContents is not attached to any browser windows (which is I guess the case where we closed the window, but managed to activate the event listener just before that)
> fix(hadron-ipc): Check if we actually got a browser window from webContents before responding

- packages/compass/src/app/network-optin/index.html.tmpl
Based on TS feedback:
* rephrased feedback tool part to convey that there is nothing visible
for the user that will change but that they are just opting in for
being occasionally contacted for feedback
* moved auto-updates checkbox up at the beginning so it's less likely
that users will miss it
Makes the privacy settings easier to understand for users.
> chore: Reordered/rephrased privacy settings COMPASS-5320

- .github/workflows/connectivity-tests.yaml
- packages/data-service/package.json
- packages/data-service/src/connect-mongo-client.ts
- packages/data-service/src/connection-options.ts
- packages/data-service/src/legacy/legacy-connection-model.spec.ts
- packages/data-service/src/legacy/legacy-connection-model.ts
Follow up to: https://mongodb.slack.com/archives/G2L10JAV7/p1637755933356700
We will allow `tlsCertificateFile` in the url to keep track of the legacy `model.sslCert` property.
> feat(data-service):  keep tlsCertificateFile as uri param COMPASS-5321

- packages/compass-connect/src/stores/index.js
- packages/compass-metrics/src/modules/rules.js
- packages/data-service/src/instance-detail-helper.spec.ts
- packages/data-service/src/instance-detail-helper.ts
- packages/data-service/src/run-command.ts
- packages/data-service/test/helpers.ts
- packages/instance-model/lib/model.js
> feat(data-service): Improves identification of atlas cluster

- packages/collection-model/lib/model.js
- packages/compass-sidebar/src/stores/store.js
- packages/data-service/src/data-service.spec.ts
- packages/data-service/src/data-service.ts
- packages/data-service/src/instance-detail-helper.spec.ts
- packages/data-service/src/instance-detail-helper.ts
- packages/database-model/lib/model.js
- packages/databases-collections/src/stores/collections-store.js
- packages/databases-collections/src/stores/databases-store.js
- packages/instance-model/lib/model.js
This was initially reported to the MongoDB Support (see [this thread](https://mongodb.slack.com/archives/G2L10JAV7/p1637910050381800) for additional details). People using Compass 1.29.5 would randomly get performance issues when using the app. Sometimes it will connect and show databases normally, sometimes it would be stuck on the "Loading databases" screen for a long time or even indefinitely.
I did a few performance profiles and compared the data-service behavior between the two versions and found two differences that we introduced with the recent changes to the `data-service` and `instance-model` store subscriptions even though we tried to keep the behavior with the global overlay as close to the old one as possible with the help of the `COMPASS_NO_GLOBAL_OVERLAY` environmental flag. …
> fix(mongodb-compass): Do not overfetch `connectionInfo` and do not update state too often COMPASS-5327

- packages/data-service/src/data-service.spec.ts
- packages/data-service/src/data-service.ts
Fixes "can't use local db ..." in latest beta that was introduced recently because the tests for this was also not set up correctly 🤦
> fix(data-service): Fix error handling in listCollections

- packages/compass-collection/package.json
- packages/databases-collections/package.json
- packages/hadron-react-bson/package.json
Fix for evergreen being broken currently. Running compile in these packages when `DEBUG` variable is set will break the build and fail tests, running the build is also not require in these particular cases as mocha-webpack will do it with a different config file that doesn't break if `DEBUG` variable is set.
> fix(collection, databases-collections, hadron-react-bson): Don't compile if tests are using mocha electron

- packages/compass-home/package.json
- packages/compass-home/src/components/home.spec.tsx
- packages/compass-home/src/components/home.tsx
- packages/connect-form/src/connect-form.tsx
COMPASS-5301
This PR moves handling of the ipc `app:disconnect` event into compass-home for the new connect form.
This has no behavior changes from the current disconnect flow.
```bash
env USE_NEW_CONNECT_FORM="true" npm start
> chore(compass-home): handle disconnect in compass-home with new connect form COMPASS-5301

- packages/ace-theme-query/index.js
spotted here https://mongodb.slack.com/archives/G2L10JAV7/p1638787434466700
This PR undoes this:
But I don't know if we can do anything about this:
Maybe with !important?
> undo some of ace_placeholder's new default styling

- packages/compass-connect/package.json
- packages/compass-metrics/package.json
- packages/connect-form/package.json
- packages/connect-form/src/connection-string-input.tsx
- packages/connection-model/lib/redact.js
- packages/connection-model/package.json
- packages/connection-model/test/redact.test.js
- packages/connections/package.json
- packages/data-service/package.json
- packages/data-service/src/redact.spec.ts
- packages/data-service/src/redact.ts
Use a common connection string redaction utility from the
`mongodb-connection-string-url` package that is shared
between mongosh and Compass.
> chore: use shared connection string redaction utility COMPASS-5308

- packages/data-service/src/connect-mongo-client.spec.ts
- packages/data-service/src/connect-mongo-client.ts
- packages/data-service/src/ssh-tunnel.ts
Fail connections for which simple commands (e.g. ping) cannot be
run immediately, rather than just providing the user with an
unusable interface for the connection.
> chore(data-service): fail connection if ping fails COMPASS-5341

- configs/mocha-config-compass/package.json
- configs/mocha-config-compass/register/tsnode-register.js
Cherry-picked from #2640 because it seems like this PR is not the only one where it's causing issues
> fix(mocha-config-compass): Disable source map processing when running code in electron / web runtime in tests

- .github/workflows/build.yaml
No other ideas what's up with Windows, maybe this will help 🤞 
We were locking it before because CI was doing this "local publish", but that's not happening anymore and so this version locking is not needed really
> ci(github): Do not unnecessarily lock npm version in build task

- packages/explain-plan-helper/package.json
Makes sure that compass always picks up the latest changes when packaged
> chore(explain-plan-helper): Add missing webpack export for the package

- packages/data-service/src/connect-mongo-client.spec.ts
- packages/data-service/src/connect-mongo-client.ts
> fix(data-service): do not ignore directConnection=false COMPASS-5376

- packages/connections/src/components/connections.tsx
This PR removes the placeholder MongoDB Compass header/logo on the connect page, we'll investigate down the line if we'll put something here. Chatted with Claudia, for now we'll remove this as it's probably not what we'll end up doing.
> chore(connections): remove temp logo in new connect form

- packages/data-service/src/index.ts
- packages/data-service/src/legacy/legacy-connection-model.spec.ts
- packages/data-service/src/legacy/legacy-connection-model.ts
- scripts/package.json
- Export `ConnectionSecrets`, `extractSecrets`, `mergeSecrets` from `mongodb-data-service` to let them be imported by VSCode.
- Additionally, the `convertConnectionInfoToModel` function of DataService should be updated to let pass not only the ampersand model as an attribute but also the raw connection model.
Dependency of https://github.com/mongodb-js/vscode/pull/377
> feat: export secrets methods and parse raw models COMPASS-5378

- .evergreen.yml
- packages/hadron-build/lib/target.js
Somehow missed it in the initial refactor of the config 🙈
> ci(evergreen): Add missing msi asset and fix RELEASES path

- packages/databases-collections-list/src/collections.tsx
Follow-up to https://github.com/mongodb-js/compass/pull/2653 so that we show the same numbers everywhere
> chore(databases-collections-list): Only show used storage size

- packages/data-service/src/data-service.ts
- packages/data-service/src/instance-detail-helper.ts
Sharded clusters don't have `dbStats.db` value in the command response, so adapt function was returning `name` as `undefined` which was overriding the `name` value that was set on the model during the initial `listDatabases` call. As we always have the db name already the fix is just to not rely on the `db` property returned by `dbStats`
Fixes COMPASS-5389
> fix(data-service): Do not return name from adapted dbStats COMPASS-5389

- packages/compass-shell/src/components/shell-header/shell-header.jsx
fix(toggle-shell): use key instead of keyCode COMPASS-5385
In a keyboard event, `keyCode` is deprecated. Use `key` instead.
> fix(toggle-shell): use key instead of keyCode

- packages/compass-aggregations/src/components/pipeline/modals/import-pipeline.jsx
- packages/compass-aggregations/src/components/stage-editor/stage-editor.jsx
- packages/compass-query-bar/src/components/option-editor/option-editor.jsx
- packages/compass-schema-validation/src/components/validation-editor/validation-editor.jsx
You might have noticed that ever since the ace upgrade we've had these warnings appear in the console that it couldn't load the worker for the mongodb mode. Seems like it somehow worked anyway but was a lot of noise in the logs.
I eventually traced it down to react-ace [setting the mode before it processes editorOptions or setOptions](https://github.com/securingsincity/react-ace/blob/2f3411256e5d1a669bddecefb17259316e23cc48/src/ace.tsx#L231-L291). So at that point it still uses the useWorker: true default and not useWorker: false that we set.
The fix I came up with sets the mode property passed to the constructor to something builtin (javascript) and then sets the mode as part of setOptions, after useWorker. Which is a bit dodgy because it relies on the undefined behaviour in …
> bug: make the ace worker loading warnings go away

- packages/compass-logging/package.json
- packages/compass/package.json
COMPASS-5401
Pulls in https://github.com/mongodb-js/mongodb-log-writer/pull/10
> fix(compass-logging): bump mongodb-log-writer to allow browser envs COMPASS-5401

- configs/eslint-config-compass/index.js
- package.json
- packages/connect-form/src/utils/connect-form-errors.ts
- packages/connect-form/src/utils/connect-form-warnings.ts
- packages/connections/src/components/connections.tsx
- packages/data-service/src/data-service.ts
- packages/data-service/src/instance-detail-helper.ts
- packages/data-service/test/helpers.ts
Few eslint tweaks as I noticed we are leaving around unused vars quite a bit:
- turn `@typescript-eslint/no-unused-vars` into an error and fix where it was breaking
- add `npm run reformat` as top-level script
- disable '@typescript-eslint/no-explicit-any' in tests (was a warning). I don't feel strongly about this, just noticed that we use `any` a lot in specs and if we are ok with it we can turn this rule off. Happy to hear your thoughts and revert though.
> chore(eslint): make @typescript-eslint/no-unused-vars error

- packages/bson-transpilers/test/run-yaml.test.js
- packages/bson-transpilers/test/yaml/bson-methods.yaml
- packages/bson-transpilers/test/yaml/bson.yaml
- packages/bson-transpilers/test/yaml/error-misc.yaml
- packages/bson-transpilers/test/yaml/imports.yaml
- packages/bson-transpilers/test/yaml/partial.yaml
Refs: https://github.com/mongodb/js-bson/pull/476
Refs: https://jira.mongodb.org/browse/NODE-3815
> fix(bson-transpilers): account for bson Decimal128 validation changes

- packages/compass-home/src/components/workspace.tsx
- packages/data-service/src/ssh-tunnel.ts
fix: remove unused vars
after merging [2676](https://github.com/mongodb-js/compass/pull/2676), the evergreen check failed for the release. 
On PRs we run `npm run check-ci` only for the changes that were made. On Evergreen, we run it for the whole codebase and as a result we have liniting errors from the codebase.
> fix: remove unused vars

- packages/data-service/package.json
- packages/data-service/src/connect-mongo-client.spec.ts
- packages/data-service/src/connect-mongo-client.ts
- packages/data-service/src/data-service.ts
- packages/data-service/src/ssh-tunnel.ts
Stumbled on this during the unified connections work, this makes
the code more complex without providing value.
(The tests to become a bit more complex because of this, since we
no longer know which port the internal network server used. I think
that’s a good tradeoff, though.)
> chore(data-service): remove get-port module usage

- packages/compass-e2e-tests/helpers/commands/shell-eval.js
- packages/compass-e2e-tests/helpers/telemetry.js
The flake always happens in the `shellEval` method, seems like we are trying to run a command before shell itself is open and interactive, I can't find the root cause though, it seems to be happening exclusively on macos machines in gh ci
> fix(e2e): Retry shell opening sequence and fix screen event check in e2e tests

- packages/compass-aggregations/src/constants.js
Add link and descriptions for the `$densify` stage.
> feat(agg): add link and descriptions for the $densify stage COMPASS-5177

- packages/compass-saved-aggregations-queries/package.json
- scripts/create-workspace.js
For got to add this one to the new package which makes the tests fail on RHEL, also added this to the workspace template so we don't miss this flag by mistake in the future
> fix: Pass no-sandbox flag to electron mocha to make sure tests can run on RHEL

- configs/webpack-config-compass/src/externals.ts
- package.json
- packages/compass/package.json
- packages/connection-model/lib/model.js
- packages/connection-model/package.json
This PR externalizes `os-dns-native` package from main Compass bundle and unpacks is from asar to make sure that native dependency can be correctly required in the application (`bindings` package doesn't work inside asar). I managed to test it locally by disabling Node.js `dns` module before connecting per @addaleax suggestion (this is what `mongosh` does right now to test this os-dns-native behavior) and it seems to work fine.
There is still an issue with packaging the application that exists in this branch due to `os-dns-native` failing to rebuild on macos with the following error:
```
npm ERR! code 1
npm ERR! path /Users/sergey.petushkov/Projects/MongoDB/compass2/packages/compass/dist/MongoDB Compass Dev-darwin-x64/MongoDB Compass …
```
> chore: Package os-dns-native with Compass COMPASS-4768 

- .vscode/extentions.json
- packages/compass-components/package.json
- packages/compass-databases-navigation/package.json
- packages/compass-home/package.json
- packages/compass-logging/package.json
- packages/compass-saved-aggregations-queries/package.json
- packages/connect-form/package.json
- packages/connections/package.json
- packages/data-service/package.json
- packages/databases-collections-list/package.json
- packages/explain-plan-helper/package.json
- packages/hadron-app-registry/package.json
- packages/ssh-tunnel/package.json
- scripts/create-workspace.js
Small quality of life change, also generates an html and lcov report for unit tests (only for the new package format).
> chore: add html and cov report to packages using nyc

- packages/connections/package.json
- packages/connections/src/components/connection-list/connection-list.tsx
- packages/connections/src/components/connection-list/connection-menu.spec.tsx
- packages/connections/src/components/connection-list/connection-menu.tsx
- packages/connections/src/components/connection-list/connection.tsx
- packages/connections/src/components/connections.tsx
- packages/connections/src/components/resizeable-sidebar.tsx
- packages/connections/src/stores/connections-store.ts
Adds two new options in connections context menu: Duplicate and Remove.
> feat(connections): adds connection menu to duplicate and remove COMPASS-5255

- packages/compass-components/package.json
This has a fixed outline color and transition timing that aligns it with other components on the page (and current lg-ui in general)
|Before|After|
|---|---|
|<img width="325" alt="image" src="https://user-images.githubusercontent.com/5036933/150302860-6f29fd10-c488-4dac-bee6-e4e7f16b5d9b.png">|<img width="325" alt="image" src="https://user-images.githubusercontent.com/5036933/150303015-199cd5a0-b9d0-4b77-b8ba-a36bdd6fb36d.png">|
> chore(compass-components): Update card to latest

- packages/compass-aggregations/src/components/stage-preview/stage-preview.jsx
- packages/compass-aggregations/src/modules/pipeline.js
- packages/compass-e2e-tests/helpers/selectors.js
- packages/compass-e2e-tests/tests/smoke.test.js
Fix aggregation pipeline selector to show Atlas search CTA when not connect to Atlas.
> fix: show atlas search cta when not connect to atlas COMPASS-5278

- package.json
- packages/connect-form/src/components/connect-form-actions.tsx
- packages/connect-form/src/components/connect-form.spec.tsx
- packages/connect-form/src/components/connect-form.tsx
- packages/connect-form/src/components/validation-summary.spec.tsx
- packages/connect-form/src/components/validation-summary.tsx
- packages/connect-form/src/hooks/use-connect-form.ts
- packages/connections/src/components/connections.tsx
- packages/connections/src/stores/connections-store.ts
- Display form errors according to design.
- Make sure form errors and actions are always visible in the viewport. 
- Display connection errors
> feat(connect-form): display form errors COMPASS-5313

- configs/mocha-config-compass/compass-plugin.js
They should be kebab case as the arguments you would pass in the command line, not camel case
(I'm keeping the removal of the `no-sandbox` from scripts out of this PR because I want to test first that it doesn't break evergreen, but this fix is already helpful to unblock tests that are failing in #2701)
> fix(mocha-config-compass): Fix argument names that are passed to the electron-mocha through mocha config

- .github/workflows/check-test.yaml
- configs/eslint-config-compass/index.js
- packages/compass-components/src/hooks/use-default-action.ts
- packages/compass-components/src/index.ts
- packages/compass-saved-aggregations-queries/package.json
- packages/compass-saved-aggregations-queries/src/components/saved-item-card.test.tsx
- packages/compass-saved-aggregations-queries/src/components/saved-item-card.tsx
- packages/compass-saved-aggregations-queries/src/util/format-date.tsx
- packages/databases-collections-list/src/namespace-card.tsx
This adds new card component for saved items. This is how it looks:
> chore(saved-aggregations-queries): Add saved item card component

- packages/connect-form/src/components/connect-form.tsx
Remove the additional space added to the right by the `overflow-y: scroll`
Main:
PR:
> style(connect-form): fix padding with overflow-y: scroll

- packages/compass-connect/src/modules/telemetry.js
- packages/connections/src/modules/telemetry.spec.ts
- packages/connections/src/modules/telemetry.ts
- packages/data-service/src/data-service.ts
Track whether Socks5 was used as a tunnel, and expose the target
topology type in telemetry (useful as a way of checking whether
multi-host connections are being used or not).
> chore: add telemetry for socks5 COMPASS-5449

- packages/connect-form/src/components/advanced-options-tabs/authentication-tab/authentication-default.spec.tsx
- packages/connect-form/src/components/advanced-options-tabs/authentication-tab/authentication-default.tsx
- packages/connect-form/src/utils/authentication-handler.spec.ts
- packages/connect-form/src/utils/authentication-handler.ts
COMPASS-5097
```js
db.createUser({
user: "C;Ib86n5b8{AnE@xew[TU%^^#@401823&^*!(@#)%XZy,)E6G%%!dk123",
pwd: "C;I\z/b86n5b8{AnE@xew[TU%^^#@401823'&^*!(@#)%XZy,)E6G%%!dkabc",
roles: [ { role: "readWrite", db: "test" },
{ role: "read", db: "reporting" } ]
})
```
```bash
mongosh "mongodb://C%3BIb86n5b8%7BAnE%40xew%5BTU%25%5E%5E%23%40401823%26%5E*!(%40%23)%25XZy%2C)E6G%25%25!dk123:C%3BIz%2Fb86n5b8%7BAnE%40xew%5BTU%25%5E%5E%23%40401823'%26%5E*!(%40%23)%25XZy%2C)E6G%25%25!dkabc@localhost:27017/test"
```
> chore(connect-form): encode and decode username and password fields

- packages/compass-home/src/plugin.tsx
- packages/connections/src/components/connections.tsx
- packages/hadron-react-components/src/tab-nav-bar.jsx
COMPASS-4986
Adds a leafygreen provider to the connections/connect-form page. This improves the usability of the leafygreen components (for instance keyboard selection events now have their focus state separately from mouse interactions on the form tabs).
https://github.com/mongodb/leafygreen-ui/tree/main/packages/leafygreen-provider
> chore(connections): Add leafygreen provider to top level of Compass COMPASS-4986

- packages/connect-form/src/components/advanced-options-tabs/authentication-tab/authentication-aws.spec.tsx
- packages/connect-form/src/components/advanced-options-tabs/authentication-tab/authentication-aws.tsx
- packages/connect-form/src/components/advanced-options-tabs/authentication-tab/authentication-gssapi.spec.tsx
- packages/connect-form/src/components/advanced-options-tabs/authentication-tab/authentication-gssapi.tsx
- packages/connections/src/modules/telemetry.spec.ts
> feat(connect-form): add support for MONGODB_AWS COMPASS-5439

- packages/compass-query-bar/src/components/query-option/query-option.module.less
> fix(query-bar): increase input width for query bar max timeout ms area COMPASS-4639

- packages/connect-form/src/components/advanced-options-tabs/authentication-tab/authentication-plain.spec.tsx
- packages/connect-form/src/components/advanced-options-tabs/authentication-tab/authentication-plain.tsx
- packages/connect-form/src/components/advanced-options-tabs/authentication-tab/authentication-x509.tsx
- packages/connect-form/src/hooks/use-connect-form.ts
- packages/connect-form/src/utils/validation.ts
> feat(connect-form): Add PLAIN and x509 auth mechanisms COMPASS-5436, COMPASS-5437

- packages/compass-aggregations/package.json
- packages/compass-app-stores/package.json
- packages/compass-auto-updates/package.json
- packages/compass-collection/package.json
- packages/compass-explain-plan/package.json
- packages/compass-export-to-language/package.json
- packages/compass-field-store/package.json
- packages/compass-find-in-page/package.json
- packages/compass-import-export/package.json
- packages/compass-indexes/package.json
- packages/compass-metrics/package.json
- packages/compass-saved-aggregations-queries/package.json
- packages/compass-saved-aggregations-queries/src/components/aggregations-queries-list.tsx
- packages/compass-saved-aggregations-queries/src/stores/aggregations-queries-items.ts
- packages/compass-saved-aggregations-queries/src/stores/index.ts
- packages/compass-saved-aggregations-queries/src/stores/instance.ts
- packages/compass-schema-validation/package.json
- packages/compass-shell/package.json
- packages/compass-sidebar/package.json
- packages/databases-collections/package.json
Started adding new state to handle opening saved aggregations / queries, but very quickly ran into issues with redux@3 type definitions so updated redux to 4 everywhere. The breaking changes seem to be mostly about typedefs and package exports and running tests for all updated packages seems to still work just fine.
This also includes some code I already added for the new instance model slice for the new plugin and some changes to how existing stores are typed to make them work with redux@4 types
> chore: Update redux to v4; Store instance in the saved-agg-queries-plugin COMPASS-5413

- packages/compass-serverstats/src/components/index.less
- packages/compass-serverstats/src/components/rtss-charts.less
- packages/compass-serverstats/src/components/rtss-lists.less
> style(compass-serverstats): Improve layout styles, more style namespacing

- packages/compass-components/src/components/file-input.tsx
- packages/connect-form/src/components/connect-form.tsx
Updates file info link hover styles, makes the favorite button not stay selected after click (after favorite modal closes).
Before:
After:
> chore(connect-form): remove link hover line, deselect favorite button after click

- packages/connect-form/src/components/advanced-options-tabs/advanced-tab/advanced-tab.tsx
- packages/connect-form/src/components/advanced-options-tabs/advanced-tab/url-options-table.spec.tsx
- packages/connect-form/src/components/advanced-options-tabs/advanced-tab/url-options-table.tsx
https://user-images.githubusercontent.com/334881/151790771-5817bb1e-792c-46df-ba39-df9edcb89d3e.mp4
> feat(connect-form): auto add advanced options and remove button

- packages/compass-crud/src/components/document-list.less
COMPASS-5362
before:
after:
https://user-images.githubusercontent.com/1791149/151905197-fd3e6020-f106-4c9c-8c08-7eed3f9236a2.mp4
> fix(compass-crud): Add minimum width to crud toolbar for content COMPASS-5362

- packages/compass-aggregations/package.json
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-preview-toolbar.jsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-preview-toolbar.module.less
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-preview-toolbar.spec.js
- packages/compass-aggregations/src/components/stage-editor-toolbar/toggle-stage.jsx
- packages/compass-aggregations/src/components/stage-editor-toolbar/toggle-stage.module.less
- packages/compass-metrics/.depcheckrc
- packages/compass-metrics/package.json
- packages/compass-sidebar/.depcheckrc
- packages/compass-sidebar/package.json
COMPASS-5470 (part 1 of 2)
This updates our toggles in compass-aggregations to use the leafygreen-ui toggles (wrapped in compass-components). It removes the `react-ios-switch` package as we're no longer using it to show any switches/toggles.
Updated the label of these toggles to be actual labels for a bit more usability/accessibility.
The ticket involves making the toggles in the new connect form visible in dark mode since currently they aren't. I opened this pr so that the fix we do there also fixes these toggles (which suffer from the same lack of visibility in dark mode).
The toggles are now blue and used to be green so I'll run those colors by Claudia before merging and check if we want to keep the green or go with leafygreen's color.
*Before:*
*After:*
*Toggled off:*
*Before*
*After*
> chore(compass-aggregations): use leafygreen toggle in compass-aggregations

- packages/compass-connect/package.json
- packages/compass-e2e-tests/package.json
- packages/compass-metrics/package.json
- packages/connect-form/package.json
- packages/connect-form/src/components/connect-form.spec.tsx
- packages/connect-form/src/utils/connection-string-helpers.spec.ts
- packages/connection-model/package.json
- packages/connections/package.json
- packages/data-service/package.json
- scripts/package.json
1. Bump the `mongodb-connection-string-url` version that includes a fix to throw a proper MongoParseError instead of TypeError that caused returning DUMMY_HOSTNAME in the validation message on the Compass connect form. For the `'mongodb+srv://Y:X@'` URI the error was `'Invalid URL: mongodb+srv://__this_is_a_placeholder__@'`. With this fix the validation error alarms that `'Protocol and host list are required in "mongodb+srv://Y:X@"'`.
2. Make `mongodb-connection-model` a prod dependency in `mongodb-data-service`, because we want to get rid of the connection model package in VSCode, and it errors during "compile:extension-bundles" with status code 2, since we still use data service.
> fix(connect-form): remove host placeholder from validation message COMPASS-5471

- packages/compass-e2e-tests/helpers/commands/navigate-to-database-tab.ts
- packages/compass-e2e-tests/helpers/selectors.ts
- packages/compass-e2e-tests/tests/database-collections-tab.test.ts
- packages/compass-e2e-tests/tests/instance-databases-tab.test.ts
Clicking on database or collection cards that don't start off on screen is flaky. The workaround is to click on the green card title text.
> fix db/collection card flakyness

- packages/compass-components/src/components/file-input.tsx
- packages/connect-form/src/components/advanced-options-tabs/tls-ssl-tab/tls-client-certificate.tsx
- packages/connect-form/src/components/advanced-options-tabs/tls-ssl-tab/tls-ssl-tab.spec.tsx
Updates the tls cert input texts. We still need a way to surface the actual connection string param these inputs correspond to. That will happen in another ticket.
Before:
After:
> chore(connect-form): Update tls input label

- packages/compass/src/main/window-manager.ts
Set a larger initial window width so the atlas CTA is still shown next to the form also in the new connection screen.
before:
after:
> feat(compass): larger initial window width

- packages/connect-form/package.json
- packages/connect-form/src/components/connect-form-actions.spec.tsx
- packages/connect-form/src/components/connect-form-actions.tsx
- packages/connect-form/src/components/connect-form.tsx
- packages/connect-form/src/hooks/use-connect-form.spec.ts
- packages/connect-form/src/hooks/use-connect-form.ts
Adds "Save" and "Connect" button to connection form.
"Save" will be visible only when the current active connection is a Favorite
It will be enabled only when the form fields/connection string changes.
When clicking "New connection" only "connect" will be shown.
> feat(connect-form): Adds Save and Connect button in connect-form COMPASS-5300

- packages/compass-e2e-tests/helpers/compass.ts
- packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
- packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
- packages/compass-e2e-tests/tests/collection-explain-plan-tab.test.ts
- packages/compass-e2e-tests/tests/collection-export.test.ts
- packages/compass-e2e-tests/tests/collection-heading.test.ts
- packages/compass-e2e-tests/tests/collection-import.test.ts
- packages/compass-e2e-tests/tests/collection-indexes-tab.test.ts
- packages/compass-e2e-tests/tests/collection-schema-tab.test.ts
- packages/compass-e2e-tests/tests/collection-validation-tab.test.ts
- packages/compass-e2e-tests/tests/connection.test.ts
- packages/compass-e2e-tests/tests/database-collections-tab.test.ts
- packages/compass-e2e-tests/tests/instance-databases-tab.test.ts
- packages/compass-e2e-tests/tests/instance-performance-tab.test.ts
- packages/compass-e2e-tests/tests/instance-sidebar.test.ts
- packages/compass-e2e-tests/tests/logging.test.ts
- packages/compass-e2e-tests/tests/shell.test.ts
Same reasoning as https://github.com/mongodb-js/compass/pull/2760, but requires less manual bookkeeping.
> Take a screenshot when a before() hook fails

- packages/compass/src/app/theme.js
`remote` wasn't required so when OS_THEME was set it would fail on startup with os theme set.
There aren't any renderer tests in Compass so it'll take a bit of setup before we can add in a test. Test pasted below I'll add in a follow up pr with those configs. Going to merge this in so we can start a beta with the fix.
```js
const {
enableDarkTheme,
disableDarkTheme,
loadTheme
} = require('./theme');
const { expect } = require('chai');
const sinon = require('sinon');
describe('theme', function() {
let appRegistryEmitSpy;
beforeEach(function() {
appRegistryEmitSpy = sinon.fake();
global.hadronApp = {
appRegistry: {
emit: appRegistryEmitSpy
}
};
});
describe('#enableDarkTheme', function() {
it('should set the dark theme on the global hadron app', function() { …
```
> fix: add missing import in theme setting

- packages/collection-model/index.d.ts
- packages/collection-model/lib/model.js
- packages/compass-aggregations/src/stores/store.js
- packages/compass-app-stores/src/stores/instance-store.js
- packages/compass-collection/src/modules/context.js
- packages/compass-collection/src/modules/tabs.js
- packages/compass-collection/src/modules/tabs.spec.js
- packages/compass-collection/src/stores/store.js
- packages/compass-crud/src/stores/crud-store.js
- packages/compass-query-bar/src/stores/query-bar-store.js
- packages/compass-saved-aggregations-queries/src/stores/aggregations-queries-items.ts
- packages/compass-saved-aggregations-queries/src/stores/app-registry.ts
- packages/compass-saved-aggregations-queries/src/stores/index.ts
- packages/compass-saved-aggregations-queries/src/stores/open-item.ts
This PR updates the saved agg / query plugin to emit `open-in-new-tab` event when the card is clicked and changes compass-collection / compass-crud / compass-query / compass-aggregations plugins to check if initial agg / query was provided when the new collection tab and all the corresponding scoped plugin stores are created.
Opening aggregation and query for existing / available namespace:
Opening aggregation for non-existing namespace:
COMPASS-5413
> chore(saved-aggregations-queries): Open saved query / agg on click COMPASS-5413

- packages/compass-components/src/hooks/use-theme.tsx
- packages/compass-components/src/hooks/use-toast.spec.tsx
- packages/compass-components/src/hooks/use-toast.tsx
- packages/compass-components/src/index.ts
- packages/compass-home/src/components/home.tsx
- packages/connections/src/components/connection-list/connection-menu.spec.tsx
- packages/connections/src/components/connection-list/connection-menu.tsx
- packages/connections/src/components/connections.spec.tsx
- packages/connections/src/components/connections.tsx
- packages/connections/src/stores/connections-store.ts
Replace state-based toasts with a global provider + hooks
https://user-images.githubusercontent.com/334881/152865201-f066056e-b46c-4cb2-bb43-0b65f5778b52.mp4
> feat(compass-components): add useToast COMPASS-5473

- packages/data-service/src/data-service.ts
We can only use EJSON-serializable data in the log attributes.
Error objects are not part of that; we need to use the message
of the Error, if one is present, instead.
> fix(data-service): log server description change error message

- packages/connection-form/src/components/advanced-options-tabs/ssh-tunnel-tab/ssh-tunnel-identity.tsx
Currently, in the SSH + Password tab, we use “SSH Port”,
and in the SSH + Identity Fil tab “SSH Tunnel Port”.
Standardize on the former, since we say just “SSH” instead of
“SSH Tunnel” for all other fields, and “SSH Tunnel” is also
a bit redundant anyway.
> chore(connection-form): use “SSH Port” instead of “SSH Tunnel Port” consistently

- packages/compass-saved-aggregations-queries/src/components/delete-item-modal.tsx
- packages/compass-saved-aggregations-queries/src/components/index.test.tsx
- packages/compass-saved-aggregations-queries/src/components/saved-item-card.tsx
- packages/compass-saved-aggregations-queries/src/stores/delete-item.ts
That's what I get for not checking carefully changes that I committed on Friday. @mabaasit spotted that I was passing the same callback property both for deleting and cancelling the delete of an item in the list. This PR fixes it and adds tests for cancelling so that we don't mess it up anymore
> fix(saved-aggregations-queries): Just close the modal on delete cancel instead of deleting item anyway

- packages/compass/package.json
Tricked myself into thinking that this flag is not needed and suggested we remove it here (https://github.com/mongodb-js/compass/pull/2774#discussion_r802374761), but even though we have it in mocha config, it is not actually applied in any meaningful way because it's not a mocha flag, but a chromium flag and so we still need to pass it manually
/cc @Anemy just FYI, sorry for confusion
> fix(compass): Return no-sandbox flag to mocha-electron script

- packages/compass-crud/src/components/document-list.less
> styles(compass-crud): center tooltip over export button

- packages/compass-crud/src/components/editable-element-field.less
- packages/compass-crud/src/components/insert-document-dialog.less
Removes ellipsis that truncates long field names in document view
> chore(compass-crud): Long field names in document view are not truncated anymore COMPASS-5361

- packages/data-service/src/connection-secrets.spec.ts
- packages/data-service/src/connection-secrets.ts
fix(connection-secrets): remove sshTunnelPassword from connectionOptions COMPASS-5239
> fix(connection-secrets): hide ssh tunnel password

- configs/eslint-config-compass/index.js
- configs/eslint-config-compass/package.json
- packages/compass-aggregations/src/stores/create-view.spec.js
- packages/compass-aggregations/src/stores/duplicate-view.spec.js
This fixes two issues I introduced in #2814
-  Having babel as default and overriding it with typescript leads to weird parsing issues when running lint for packages in the monorepo
-  Installing latest version of babel core in eslint config had a side-effect of deduping and hoisting this version for every package in the monorepo, which in turn broke depcheck package because of https://github.com/depcheck/depcheck/issues/688. As the issue is not resolved yet on the depcheck side, our best way of handling this is to make sure that we are not using the version of babel yet that breaks with that config, but as soon as fix is released, we should do a depcheck update in the monorepo
> fix(eslint-config-compass): Fix babel version at 7.14 and separate parser configs

- packages/compass-schema/src/components/coordinates-minichart/coordinates-minichart.jsx
GeoJSON (and thus MongoDB) stores coordinates as [Longitude, Latitude],
while elsewhere the reverse format [Latitude, Longitude] is common.
Compass displays the points on the map correctly, but reverses
the two values in the mouseover text.
Instead of switching to MongoDB/GeoJSON order, just clearly mark which
value is latitude and which is longitude.
> fix(compass-schema): unambiguously display lat/long on map COMPASS-5526

- packages/connection-form/src/components/connection-string-input.tsx
> fix(connection-form): set textarea font size for connection string input

- packages/compass-components/src/components/virtual-grid.tsx
While fixing [keys issues](https://mongodb.slack.com/archives/G2L10JAV7/p1645188660841309), we introduced this issue - on sort or filter of virtual grid list items, the rendered items keep piling up.
https://user-images.githubusercontent.com/1305718/155362906-d81fb2ed-6f39-431b-be7d-d98cb450fbc3.mov
> fix(compass-components): pass correct index to itemKey

- package.json
- scripts/check-leafygreen-dep-usage.js
- scripts/workspace-dependencies.js
COMPASS-5421
This adds a check to ensure we don't introduce [LeafyGreen](https://github.com/mongodb/leafygreen-ui) dependencies outside of `compass-components`. 
Here's how it looks when this check fails:
> chore: Add check for LeafyGreen dependencies outside compass-components package COMPASS-5421

- packages/compass-shell/src/components/shell-header/shell-header.jsx
Fixes issue with shell not resizing properly:
We were passing `lineHeight` without the `px` so it would calculate the height of 32 text lines (spacing 4). That was causing the shell to overflow and act differently in the flow. I think we can do some styling improvements here but this pr will just fix for now.
> fix(compass-shell): use correct units for lineHeight

- packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
Worked here, but I had .only in there by accident and check failed https://spruce.mongodb.com/version/621766a361837d2b3afa768c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Running again without .only https://spruce.mongodb.com/version/6217808b57e85a76cbea32c4/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> Try and fix $out and $merge tests again

- packages/compass-aggregations/package.json
- packages/compass-query-bar/package.json
- packages/compass-schema-validation/package.json
COMPASS-4665
Addresses https://github.com/mongodb-js/compass/issues/2810 - thanks to their pr!
> deps(compass-aggregations): bump `mongodb-ace-autocompleter` dep to v0.10.1 COMPASS-4665

- .evergreen/preinstall.sh
- .evergreen/print-compass-env.js
- .evergreen/print-compass-env.sh
This addresses one of the three current failures in evergreen ci: making sure that RHEL and Ubuntu always use Python 3.6 that node-gyp requires. Here's an [evergreen patch](https://spruce.mongodb.com/version/621c943ca4cf475e2b807450/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) with all related tasks passing (`test-packaged-app` passes the install / build step, but fails on a certain test for an unrelated reason that will be addressed in another PR)
> ci(evergreen): Make sure linux uses Python 3.6 to match node-gyp requirement

- packages/compass-connect/package.json
- packages/compass-connections/package.json
- packages/compass-e2e-tests/package.json
- packages/compass-export-to-language/package.json
- packages/compass-metrics/package.json
- packages/connection-form/package.json
- packages/connection-form/src/components/advanced-options-tabs/advanced-options-tabs.tsx
- packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-tab.spec.tsx
- packages/connection-form/src/components/connect-form.spec.tsx
- packages/connection-form/src/components/connect-form.tsx
- packages/connection-form/src/hooks/use-connect-form.ts
- packages/connection-form/src/utils/authentication-handler.spec.ts
- packages/connection-form/src/utils/authentication-handler.ts
- packages/connection-form/src/utils/connection-string-helpers.spec.ts
- packages/connection-form/src/utils/connection-string-helpers.ts
- packages/connection-form/src/utils/validation.ts
- packages/connection-model/package.json
- packages/data-service/package.json
- scripts/package.json
Use loose validation in the connection form UI. This allows
editing in situations like when the URI contains no username
but a password.
> feat(connection-form): use loose connection string validation

- .evergreen.yml
- packages/hadron-build/commands/release.js
Some e2e tests on RHEL started failing in evergreen with the following error:
```
/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/mci/a309f2563757fe8b8b3ebea999eea8b2/src/packages/compass/dist/MongoDB Compass Dev-linux-x64/resources/app.asar.unpacked/node_modules/keytar/build/Release/keytar.node)
```
This indicated that even though we are using the same machine type to package and test the app, somehow the keytar native module was seemingly built with newer version of OS somehow. We tracked the root cause to electron-rebuild pulling in a prebuilt module for keytar (and other packages) even though we were expecting it to rebuild on the platform we are packaging compass every time.
I [already confirmed](https://spruce.mongodb.com/version/621cf4c03066153875e6c522/ …
> ci(evergreen): Force rebuild by passing a fake tag prefix to electron-rebuild

- .evergreen.yml
- packages/data-service/package.json
- packages/data-service/src/connect.spec.ts
> test: move connectivity tests to EVG (without kerberos)

- packages/compass-aggregations/src/components/input-builder/input-builder.jsx
- packages/compass-aggregations/src/components/input/input.jsx
- packages/compass-aggregations/src/components/stage-editor-toolbar/stage-editor-toolbar.jsx
- packages/compass-aggregations/src/components/stage/stage.jsx
- packages/compass-crud/src/components/document-list.jsx
- packages/compass-crud/src/components/toolbar.jsx
- packages/compass-sidebar/src/components/sidebar-instance-stats/sidebar-instance-stats.jsx
- packages/compass-sidebar/src/components/sidebar/sidebar.jsx
Fixes a few react props warnings, mistypes, old-now-gone-away props, or places where the store isn't setup yet so it passes undefined.
Here's what they looked like:
> chore: fix react prop warnings

- packages/compass-e2e-tests/helpers/commands/index.ts
- packages/compass-e2e-tests/helpers/commands/scroll-to-virtual-item.ts
- packages/compass-e2e-tests/helpers/selectors.ts
- packages/compass-e2e-tests/scripts/insert-data.ts
- packages/compass-e2e-tests/tests/database-collections-tab.test.ts
- packages/compass-e2e-tests/tests/instance-databases-tab.test.ts
The virtual scrolling used on the database and collection lists mean that collections that are off screen might not exist in the page. So we have to keep scrolling down until they are loaded. This command attempts to do that.
This PR also re-enables the test that we had disabled due to a card being too far off screen before.
> chore(e2e): browser.scrollToVirtualItem() COMPASS-5529

- packages/compass-e2e-tests/tests/logging.test.ts
- packages/compass-preferences-model/lib/model.js
- packages/compass-user-model/lib/model.js
- packages/compass/src/app/index.js
- packages/compass/src/main/telemetry.ts
In Compass, we don't have any MongoDB user identifiers. We randomly generate an ID the first time the product is run and then we use that as a user id. The `userId` telemetry field should not store the random UUID, it should store only AUID. The randomly generated UUID should be stored as `anonymousId`.
To not break statistics for existing users:
- We should leave all current users with the tracking they have.
- For new users, we should use the field anonymousID and fill it with a random UUID.
That being said:
- If userId exists we send it to segment. We also copy userId to anonymousId and send it to segment as well.
- If userId does not exist we do not create a new one, we only generate a random UUID and send it to segment as anonymousId.
> fix: use user id and anonymous id as segment identity COMPASS-5487

- packages/compass-connect/src/modules/telemetry.js
- packages/compass-connections/src/components/connections.spec.tsx
- packages/compass-connections/src/components/connections.tsx
- packages/compass-connections/src/modules/telemetry.ts
- packages/compass-connections/src/stores/connections-store.spec.ts
- packages/compass-connections/src/stores/connections-store.ts
- packages/compass-e2e-tests/tests/connection.test.ts
- packages/compass-export-to-language/src/stores/store.js
- packages/compass-metrics/src/modules/rules.js
- packages/connection-form/src/components/connect-form.tsx
- packages/connection-form/src/utils/validation.spec.ts
- packages/connection-form/src/utils/validation.ts
- packages/connection-model/lib/connect.js
- packages/connection-model/lib/model.js
- packages/data-service/src/connection-secrets.ts
- packages/data-service/src/connection-storage.spec.ts
- packages/data-service/src/connection-storage.ts
- packages/data-service/src/connection-title.ts
- packages/data-service/src/data-service.ts
- packages/data-service/src/legacy/legacy-connection-model.ts
- scripts/import-test-connections.js
This came up from a chat with @mmarcon and requests by customers on slack. The gist of the change is:
- We don't do semantic validations on save. Only well-formed strings are saved, ie. no `pineapple`, but users can save connections that would not work with the driver, like those missing passwords.
- If a connection has been saved in the past then we will only update the `lastUsed` field instead of saving all the changes. NOTE: this replicates the behavior of the old connection form.
- Unrelated: Changes the copy for TLS warnings to a more positive language.
> feat(connect-form): Allow saving invalid but well-formed strings

- .evergreen/start-docker-envs.sh
- packages/compass-e2e-tests/tests/connection.test.ts
- packages/connection-model/lib/connection-collection.js
We are currently skipping all e2e tests for all machines except ubuntu
because of that. Generally speaking if we were not able to start these
docker images (and this causes some failures in tests) we should see
these issues instead of silently skipping them
> fix(evergreen): Do not exit when docker / docker-compose is missing on machine

- packages/data-service/src/connection-storage.spec.ts
- packages/data-service/src/connection-storage.ts
Logs exceptions in the conversion from/to legacy model in the `ConnectionStorage` and does not throw if one connection would does not load
> feat(connect-form): ignore parsing errors on load and add logging

- packages/compass-sidebar/src/components/sidebar/navigation-items.jsx
> chore(compass-sidebar): fix react warnings

- packages/compass-explain-plan/src/components/explain-states/explain-states.jsx
- packages/compass-explain-plan/src/components/explain-states/explain-states.module.less
- packages/compass-explain-plan/src/components/zero-graphic/zero-graphic.jsx
- packages/compass-explain-plan/test/setup.js
- packages/compass-schema-validation/package.json
- packages/compass-schema-validation/src/components/validation-states/validation-states.jsx
- packages/compass-schema-validation/src/components/validation-states/validation-states.module.less
- packages/compass-schema/src/components/compass-schema/compass-schema.jsx
- packages/compass-schema/src/components/compass-schema/compass-schema.module.less
- packages/compass/src/app/styles/zero-state.less
- packages/connection-form/src/components/advanced-options-tabs/advanced-tab/url-options.tsx
- packages/hadron-react-components/src/zero-state.jsx
This pr updates the Zero states of the `Schema`, `Explain`, and `Validation` collection views. It fixes the margin that was broken in the recent bootstrap wrangling (that was me oops!). Got a bit carried away and this pr also updates the links, button, and titles to leafygreen components. Not doing any large ui changes here though. 
Before:
After
> fix(hadron-react-components): fix margin and update collection zero state styles COMPASS-5577

- packages/connection-form/src/hooks/use-connect-form.ts
Fixes warnings not being displayed immediately when connections are selected.
> fix(connect-form): display warnings when a connection is selected

- packages/compass-e2e-tests/helpers/commands/exists-eventually.ts
- packages/compass-e2e-tests/helpers/compass.ts
- packages/compass-e2e-tests/index.ts
- packages/compass-e2e-tests/tests/logging.test.ts
- packages/compass-e2e-tests/tests/time-to-first-query.test.ts
- packages/compass/src/app/index.js
Basically: only calculate a userDataDir once. Only delete it if/when we ask for the "firstRun" experience explicitly and then during cleanup after all the tests.
> chore(e2e): Don't do the "first run experience" every time COMPASS-5262

- packages/compass-saved-aggregations-queries/src/hooks/use-grid-filters.tsx
fixes alignment issues on **My Queries** tab.
**Before:**
**After:**
The inconsistency is due to LG adding `margin-top: 2px` in select component(v3.1.0) (which is rendered as button) and no margins on input field.
> fix(compass-saved-aggregations-queries): alignment fix

- packages/compass-schema/src/components/compass-schema/compass-schema.module.less
- packages/compass-schema/src/components/unique-minichart/unique-minichart.jsx
We only have a few `mms-icon` uses in Compass. This pr removes the one in compass-schema. The other occurrences are in the query bar and sidebar. Since those will be handled in seperate leafygreen projects I figured this one could go now so that when the others are removed we can remove the global `mms-icon` styles: https://github.com/mongodb-js/compass/blob/main/packages/compass/src/app/styles/mms-icons.less 
Also brings an improvement of accessibility, using a `button` and not an `i` for handling clicking in the dom.
Before:
After:
> chore(compass-schema): remove `mms-icon` usage in compass-schema

- packages/compass-e2e-tests/helpers/commands/scroll-to-virtual-item.ts
- packages/compass-e2e-tests/helpers/selectors.ts
- packages/compass-e2e-tests/tests/database-collections-tab.test.ts
- packages/compass-e2e-tests/tests/instance-databases-tab.test.ts
- packages/compass-e2e-tests/tests/instance-sidebar.test.ts
> fix(test): scroll virtual tree

- packages/compass-e2e-tests/.prettierignore
- packages/compass-e2e-tests/helpers/commands/set-connect-form-state.ts
Still trying to fix this flake:
> more assertions for the advanced url options

- .evergreen.yml
- packages/hadron-build/lib/target.js
Due to a bug, the --verify flag of the macnotary client
did not work on Electron applications. It is optional,
but helps us catch problems earlier, so let’s enable
it now that that bug is resolved.
Evergreen: https://spruce.mongodb.com/version/620f708a3627e01a876cb3eb/tasks
> chore(ci): use --verify flag of macnotary

- packages/compass-connections/src/components/connection-list/connection-list.spec.tsx
- packages/compass-connections/src/components/connection-list/connection-list.tsx
- packages/compass-connections/src/components/connections.tsx
- packages/compass-connections/src/components/resizeable-sidebar.tsx
- packages/compass-connections/src/stores/connections-store.spec.ts
- packages/compass-connections/src/stores/connections-store.ts
- packages/data-service/src/connection-storage.ts
List of changes:
- derive pre-sorted favorite and recent connections lists from loaded connections
- on connect: delete the last recent if a new one was saved and 10 were already existing
- use `favoriteConncections` and `recentConnections` in the connection list
- isolate `<ResizableSidebar>` from `<ConnectionList>`
> feat(connect-form): limit recent connections to 10

- packages/compass/src/main/menu.ts
This is not a full fix, just a quick workaround based on the reported stack trace. See https://mongodb.slack.com/archives/G2L10JAV7/p1647603276712129
> fix(compass): Catch all errors during theme update

- packages/compass-e2e-tests/tests/logging.test.ts
- packages/compass-e2e-tests/tests/shell.test.ts
Failed here https://evergreen.mongodb.com/task/10gen_compass_testing_coverage_e2e_coverage_d59f5f1f262e6f19aa0200bf68fcdc25ef658aee_22_03_23_00_58_07
I noticed that the shell doesn't have any tests yet but we still open and close compass for no reason because the before hook still executes. So I'm just skipping the file for now.
Also the logging tests get a new user directory and then when we release it detects that we're running a new version so it shows the tour. Which it wasn't doing in dev, because that semver check is always false. By adding the SHOW_TOUR env var we can get it to behave the same in dev and when we release.
> fixes for when we release

- packages/connection-form/src/components/advanced-options-tabs/advanced-tab/url-options-table.tsx
- packages/connection-form/src/components/advanced-options-tabs/advanced-tab/url-options.tsx
Not sure when this got changed, in the most recent beta this looks as intended but in main the styles were a bit broken.
See the `URI Options` table styles
Before:
After:
> chore(connection-form): fix uri options table styling

- packages/compass-import-export/src/components/export-modal/export-modal.module.less
- packages/compass-import-export/src/components/import-preview/import-preview.module.less
- packages/compass-sidebar/src/components/sidebar/navigation-items.jsx
Pulling in a few of changes from https://github.com/mongodb-js/compass/pull/2907 which got lost in a merge conflict.
And a small fix on hovering over the actions in the sidebar from the bootstrap removal.
> styles: fix small styling bugs from bootstrap removal

- packages/hadron-document/.depcheckrc
- packages/hadron-document/package.json
Looks like these were added in the mono repo work, maybe unintentional? I might be missing something cc @gribnoysup https://github.com/mongodb-js/compass/commit/e5830b8f8d688f6cbc6c7f83053fcf04fac93dcd#diff-37e62e398aa57efb932e58a64d36c435cbe728cf81c26cc9ffe5fa82b360aaf3R38
Removing to help cloud upgrading to react v17
> deps(hadron-document): remove unused react deps

- packages/compass-components/src/components/virtual-grid.tsx
- packages/compass-components/src/hooks/use-default-action.ts
- packages/compass-components/src/hooks/use-virtual-grid.test.tsx
- packages/compass-components/src/hooks/use-virtual-grid.ts
- packages/compass-saved-aggregations-queries/src/components/aggregations-queries-list.tsx
- packages/compass-saved-aggregations-queries/src/components/saved-item-card.test.tsx
- packages/compass-saved-aggregations-queries/src/components/saved-item-card.tsx
- packages/databases-collections-list/src/items-grid.tsx
This patch fixes an issue where interacting with any item in the virtual grid would always automatically move focus to the first element in the grid. This has no behavioral effect when interacting with the grid only with a keyboard or with a mouse, but was causing a visual issue that @Anemy [spotted here](https://mongodb.slack.com/archives/G2L10JAV7/p1648139699847949) and a weird keyboard behavior if you would switch from using mouse to keyboard. This new focus / blur handling logic makes sure that the focus is always in sync with whatever and however user is interacting with the items in the list.
> fix(compass-components): Keep the focus in the grid item that received the event

- packages/connection-form/src/components/advanced-options-tabs/tls-ssl-tab/tls-certificate-authority.tsx
- packages/connection-form/src/components/advanced-options-tabs/tls-ssl-tab/tls-client-certificate.tsx
- packages/connection-form/src/components/advanced-options-tabs/tls-ssl-tab/tls-ssl-tab.tsx
With the upcoming CSFLE work, TLS options will not just apply
to the connection to the database, but also to the KMS servers
used by CSFLE.
Since those options are stored differently, making the
TLS Certificate Authority and Client Certificate components
more independent of the usage of connection strings will
help with that CSFLE work.
> chore(connection-form): make TLS options a bit more reusable COMPASS-5638

- packages/compass-shell/src/components/shell-header/shell-header.jsx
Looks like I merged the flash with all of the same colors so it doesn't currently flash. This PR adds the correct colors in.
Here was the original pr https://github.com/mongodb-js/compass/pull/2917
https://user-images.githubusercontent.com/1791149/160538777-7f4e30f0-2c8d-4a07-a571-c70894e9ef59.mp4
> feat(compass-shell): flash embedded mongosh toggle on connect

- packages/compass-aggregations/src/components/input-preview/input-preview.jsx
- packages/compass-aggregations/src/components/input-preview/input-preview.module.less
- packages/compass-aggregations/src/components/stage-preview/stage-preview.jsx
- packages/compass-aggregations/src/components/stage-preview/stage-preview.module.less
- packages/compass-components/src/components/bson-value.tsx
- packages/compass-components/src/components/document-list/document.tsx
- packages/compass-components/src/components/document-list/element-editors.tsx
- packages/compass-components/src/components/document-list/element.tsx
- packages/compass-crud/src/components/document-list.less
- packages/compass-crud/src/components/document.less
- packages/compass-crud/src/components/readonly-document.jsx
- packages/compass-schema-validation/src/components/document-preview/document-preview.jsx
- packages/compass-schema-validation/src/components/document-preview/document-preview.module.less
- packages/compass-schema-validation/src/components/sample-documents/sample-documents.jsx
- packages/compass-schema-validation/src/components/sample-documents/sample-documents.module.less
Some style fixes for the refactored document card view in the aggregations tab that I missed in the original PR
|Before|After|
|---|---|
|<img width="651" alt="image" src="https://user-images.githubusercontent.com/5036933/160834166-8201d705-9c11-44ae-a449-6f0e7be03f85.png">|<img width="563" alt="image" src="https://user-images.githubusercontent.com/5036933/160833836-10019575-4073-498c-a5a6-dfedbdd39ce0.png">|
|<img width="623" alt="image" src="https://user-images.githubusercontent.com/5036933/160834236-a63114aa-1ed3-4ccf-9091-78653d614148.png">|<img width="621" alt="image" src="https://user-images.githubusercontent.com/5036933/160833897-53c4fc50-33da-4cb0-8240-3d4325dd7521.png">|
> fix(compass-aggregations): Update aggregation result preview card styles

- packages/compass-aggregations/package.json
- packages/compass-aggregations/src/components/pipeline-results-workspace/index.tsx
- packages/compass-aggregations/src/components/pipeline-results-workspace/pipeline-results-list.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/index.tsx
- packages/compass-aggregations/src/components/pipeline/pipeline.jsx
- packages/compass-crud/.eslintignore
- packages/compass-crud/index.d.ts
- packages/compass-crud/package.json
- packages/compass-crud/src/components/document-json-view.jsx
- packages/compass-crud/src/components/document-json-view.less
- packages/compass-crud/src/components/document-list-view.jsx
- packages/compass-crud/src/components/document-list.less
- packages/compass-crud/src/index.js
- packages/hadron-document/index.d.ts
Now that we have list view interfaces aligned it was finally possible to re-export views from the CRUD plugin and plug them into the aggregations results view. This is how it looks in the app:
> feat(compass-aggregations): Use CRUD document list to render aggregation results

- packages/compass-e2e-tests/helpers/compass.ts
- packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
- packages/compass-e2e-tests/tests/database-collections-tab.test.ts
I could have re-enabled this in the PR where we started testing multiple mongodb versions, but I didn't think of it.
> chore(e2e): un-skip timeseries collection test

- packages/hadron-build/package.json
This includes a possible fix for the issue when we are trying to update
newly created release too fast resulting in a release not found error
See: https://github.com/mongodb-js/devtools-github-repo/pull/1
> chore(hadron-document): Bump devtools-github-repo package

- packages/compass-components/src/components/document-list/document.spec.tsx
- packages/compass-components/src/components/document-list/document.tsx
- packages/compass-components/src/components/document-list/element-editors.tsx
- packages/compass-components/src/components/document-list/element.tsx
- packages/hadron-document/src/editor/date.js
- packages/hadron-document/src/editor/decimal128.js
- packages/hadron-document/src/editor/double.js
- packages/hadron-document/src/editor/int64.js
- packages/hadron-document/src/editor/objectid.js
- packages/hadron-document/src/editor/standard.js
These hadron document Editor classes require you to call `start` when starting the edit and `complete` when done to sorta "commit" edited value to the Element and I completely missed this during refactoring that I did in https://github.com/mongodb-js/compass/pull/2915. Sometimes not doing this has no effect, but really affects the Date type where not doing this results in the field changing types from Date to String on update as reported [in this community forum post](https://www.mongodb.com/community/forums/t/compass-1-31-date-bug/155731/1)
COMPASS-5664
> fix(hadron-document, compass-components): Call Editor.start / Editor.complete when changing field value COMPASS-5664

- packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
This should fix the failed nightly build.
https://mongodb.slack.com/archives/C03A67M9BCJ/p1649294899662869
> expect $fill to exist for 5.3+

- packages/data-service/src/data-service.spec.ts
- packages/data-service/src/data-service.ts
- packages/data-service/src/instance-detail-helper.spec.ts
- packages/data-service/src/instance-detail-helper.ts
- packages/database-model/lib/model.js
COMPASS-5691 https://github.com/mongodb-js/compass/issues/2953
Atlas shared tier clusters (serverless, M0, M2) with MongoDB server version 5+ do not currently return privileges with the `connectionStatus` command response (fix might be in soon/already w/ [CLOUDP-115805](https://jira.mongodb.org/browse/CLOUDP-115805)). It also fails to `listDatabases`. As a result, currently a user with permissions to only one database would not be able to see their database. 
While there may be a release of Atlas soon making this issue go away, the changes in this PR introduce a workaround so users with exclusive database permissions can use their databases. These changes expand our extra `listDatabases` affordances by referencing the [authenticatedUserRoles](https://www.mongodb.com/docs/manual/reference/c …
> fix(data-service): use databases where user has built in roles in `listDatabases` COMPASS-5691

- packages/compass-components/src/components/document-list/auto-focus-context.tsx
- packages/compass-components/src/components/document-list/document.spec.tsx
- packages/compass-components/src/components/document-list/document.tsx
- packages/compass-components/src/components/document-list/element-editors.tsx
- packages/compass-components/src/components/document-list/element.tsx
- packages/hadron-document/index.d.ts
- packages/hadron-document/src/editor/standard.js
Fixes the issue where trying to edit `null` value would result in no changes to the input, the issue here was due to the useElementEditor hook not updating the actual editor reference correctly and null editor always returning `"null"` as a value. Additionally I fixed the issue with non-editable values not triggering edit mode on double click: now double clicking them will enter the edit mode and focus the type editor (as this seems to be the main use-case)
COMPASS-5697
> fix(compass-components): Recreate Element editor when el type changes from the original one COMPASS-5697

- packages/compass-collection/src/components/collection-header/collection-header.tsx
Updates the background of the collection stats. A similar change will also be in https://github.com/mongodb-js/compass/pull/2965 - we're opening this pr so we can have main ready for a beta and spend more time on that pr since it brings in more changes.
> chore(compass-collection): Update collection header background color

- packages/compass-components/src/components/bson-value.spec.tsx
- packages/compass-components/src/components/bson-value.tsx
We should be less strict with rendering UUIDs that are not valid. Example of both valid and invalid UUID in one document with this patch:
Fixes #2974
> fix(compass-components): Allow to render invalid UUID values COMPASS-5726

- packages/hadron-document/src/utils.ts
- packages/hadron-document/test/document.test.ts
To avoid `Cannot read property '$numberInt' of null` sort of issues
> fix(hadron-document): Skip ejson number type check for non-object values

- packages/connection-form/src/utils/tls-handler.spec.ts
- packages/connection-form/src/utils/tls-handler.ts
The `false` case will be handled by the fix from https://github.com/mongodb-js/devtools-connect/pull/10#pullrequestreview-940672380 but this makes sure that we never even passing this value to devtools-connect package. Please tell me if you don't think that it's a good idea to have this logic here due to duplication across different packages, it's not really required, I was just not sure if we want to handle it in both places or not.
> chore(connection-form): Ensure that useSystemCA is never set to false

- .github/workflows/e2e-tests-osx.yaml
We’ve been running into timeouts recently, bumping it should
help keep our CI green.
> chore(ci): bump macos github actions timeout to 90 minutes

- configs/webpack-config-compass/src/index.ts
- configs/webpack-config-compass/src/loaders.ts
This is more for documentation purposes than for anything else, our electron version is way behind what cloud supports
> chore(webpack-config-compass): Make sure web builds are using cloud supported browser versions

- packages/compass-schema/src/components/compass-schema/compass-schema.module.less
- packages/compass-schema/src/components/field/field.jsx
- packages/compass-schema/src/components/type/type.jsx
- packages/compass-schema/src/components/value-bubble/value-bubble.jsx
COMPASS-5758
When updating the `compass-schema` package to the shared Compass config we disabled a few eslint rules. Turning these rules back on involves fixing accessibility issues in the package. This PR updates three previously non-interactive html elements which we had `onClick` handlers for so that we can better support keyboard navigation and screen readers.
In these changes we're also removing the global `caret` css usage in `compass-schema` so now we only have 2 more occurrences of those in Compass and soon will be able to remove the [caret global styles](https://github.com/mongodb-js/compass/blob/main/packages/compass/src/app/styles/deprecated-bootstrap-styles/caret.less). :D
I investigated turning these components into typescript but I think we will first have to typescript …
> fix(compass-schema): Use interactive html elements for buttons in schema COMPASS-5758

- packages/compass-crud/src/components/insert-csfle-warning-banner.jsx
- packages/compass-crud/src/components/insert-document-dialog.jsx
- packages/compass-crud/src/stores/crud-store.js
- packages/compass-crud/src/stores/crud-store.spec.js
Provide protections against accidental writes of unencrypted data
that was supposed to be encrypted. Specifically:
- Display a noticed in the insert dialogue about whether the inserted
data will be encrypted.
- Block updates that would change the contents of an existing
encrypted field to be unencrypted.
> feat(compass-crud): ensure that users do not write unencrypted data COMPASS-5629

- configs/webpack-config-compass/.depcheckrc
- configs/webpack-config-compass/package.json
- configs/webpack-config-compass/src/loaders.ts
- packages/compass-collection/package.json
- packages/compass-collection/src/stores/context.tsx
- packages/compass-export-to-language/electron/renderer/index.js
- packages/compass-export-to-language/package.json
- packages/compass-export-to-language/src/stores/index.js
- packages/compass-export-to-language/src/stores/store.js
- packages/compass-export-to-language/src/stores/store.spec.js
This dependency is causing plugin code to blow up in browser environments that Cloud supports (see COMPASS-5772 for more info). As we discussed on standup we were okay with just removing the feature completely, but this seems to be a relatively clean way of keeping the behavior and moving the library usage outside of the package.
As a drive-by there is also a tiny change to webpack config that should just reduce the amount of babel helpers code in the bundle: instead of being added in place every time they are used, they all will be imported from this babel runtime package.
> chore(compass-export-to-language): Remove usage of `mongodb-connection-string-url` from plugin COMPASS-5772

- .evergreen/compass_package.sh
- .evergreen/node-gyp-bug-workaround.sh
- .evergreen/preinstall.sh
- .evergreen/print-compass-env.sh
- .evergreen/retry-with-backoff.sh
- .evergreen/start-docker-envs.sh
- .evergreen/xvfb-service.sh
- Add `set -e` to bash scripts on EVG so they exit on failures
- Add a `retry-with-backoff.sh` script used to invoke curl to mitigate CI flakes due to failures during downloads of `node.js`
> chore: make CI bash scripts fail on error

- packages/compass-crud/src/stores/crud-store.js
- packages/compass-crud/src/stores/crud-store.spec.js
COMPASS-5781
Unfortunately, the server currently does not support
`returnDocument: 'after'` for FLE2 operations.
We emulate it by running with `returnDocument: 'before'`
followed by a `find` operation in that specific case.
> fix(compass-crud): fallback if `returnDocument: 'after'` fails for FLE2

- packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.tsx
- packages/connection-form/src/components/advanced-options-tabs/csfle-tab/kms-local-key-generator.tsx
- packages/connection-form/src/components/advanced-options-tabs/csfle-tab/kms-provider-fields.tsx
- packages/connection-form/src/utils/csfle-handler.spec.ts
- packages/connection-form/src/utils/csfle-handler.ts
- packages/connection-form/src/utils/csfle-kms-fields.ts
COMPASS-5715
Together with the additions in the collection creation form,
this is all that is missing for users to be able to get
started with FLE2 only through Compass.
> feat(connection-form): add in-UI option for generating local KMS key

- packages/compass-crud/src/components/document.less
Otherwise context menu for element actions is not visible. Reported by Max in the [slack channel](https://mongodb.slack.com/archives/G2L10JAV7/p1651469285057849)
> chore(compass-crud): Do not hide card overflowing content

- packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-workspace.jsx
- packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-workspace.spec.jsx
- packages/compass-aggregations/src/components/stage-editor/stage-editor.jsx
- packages/compass-aggregations/src/components/stage-editor/stage-editor.spec.jsx
- packages/compass-aggregations/src/components/stage/stage.jsx
- packages/compass-aggregations/src/modules/pipeline.spec.js
- packages/compass-aggregations/src/modules/pipeline.ts
- packages/compass-aggregations/src/modules/stage.spec.js
- packages/compass-aggregations/src/modules/update-view.spec.js
- packages/compass-saved-aggregations-queries/src/typings.d.ts
- packages/compass-saved-aggregations-queries/test/fixtures.ts
This PR removes our use of [ace editor's](https://cloud9-sdk.readme.io/docs/snippets) `insertSnippet` command. This command was causing any items which matched the token, which was by default anything starting with `$` to be removed when the stage operator was changed. This unintentional replacing was made more evident when we added the ability for the stage content not to change when the operator is changed.
To fix this we are now replacing the ace snippet completion by replacing the tokens explicitly (see the `replaceOperatorSnippetTokens` function). As a result of this approach we are able to remove the `fromStageOperators` flag, which, from what it looks like, was used to prevent an additional preview reload when the stage operator changed. We're also removing the `snippet` from the …
> fix(compass-aggregations): remove ace editor snippet completion, complete operator snippets on our end COMPASS-5683

- packages/compass/src/main/application.ts
- packages/compass/src/main/auto-update-manager.ts
- packages/hadron-auto-update-manager/index.js
- packages/hadron-auto-update-manager/package.json
Cover auto-update with logging
NOTE: this also changes the initialization sequence slightly so that logging and telemetry are set up before the rest
> chore(auto-update-manager): add logging for autoupdates

- packages/connection-form/src/utils/csfle-handler.spec.ts
- packages/connection-form/src/utils/csfle-handler.ts
Instead of setting the KMS provider’s config to `undefined`
when no options are provided for that KMS, just delete it entirely.
In particular, previously connectivity would have been
impacted by the fact that `hasAnyCsfleOption()` would
not be able to properly handled `undefined` values in the
KMS provider config. That function is also adjusted here
to handle these cases more defensively.
> fix(connection-form): delete KMS provider option when empty COMPASS-5798

- packages/data-service/src/data-service.ts
The mongodb-client-encryption package gets its corresponding driver
package through `require('mongodb')` by default. However, when packaging
Compass, we include mongodb-client-encryption in the unpacked asar,
but not the driver itself, so this fails.
For these cases (and also just to generally ensure that versions match),
an explicit way to specify the driver package is available,
so we should use that here.
> fix(data-service): use dependency injection for getting ClientEncryption COMPASS-5796

- packages/compass/src/index.d.ts
- packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.tsx
- packages/connection-form/src/components/advanced-options-tabs/csfle-tab/encrypted-field-config-input.tsx
- packages/connection-form/src/utils/csfle-handler.spec.ts
- packages/connection-form/src/utils/csfle-handler.ts
- packages/connection-form/src/utils/validation.ts
- packages/data-service/src/data-service.spec.ts
- packages/data-service/src/data-service.ts
I decided to leave in `schemaMap` support since it’s highly analogous
and might be useful for debugging, especially as long as FLE2 CRUD
support is not something that exists in everybody’s testing environment.
> feat(connection-form): use encryptedFieldsMap instead of schemaMap COMPASS-5645

- packages/compass-aggregations/src/components/pipeline-results-workspace/index.spec.tsx
- packages/compass-aggregations/src/constants.js
- packages/compass-aggregations/src/modules/limit.spec.js
- packages/compass-aggregations/src/modules/pipeline.spec.js
This PR updates the preview document limit amount in compass-aggregations to 10 from 20.
There's a performance regression in the aggregation pipeline around the rendering of documents COMPASS-5764 . While we diagnose the cause of the issue lets first decrease the sample amount to 10 from 20 to reduce the amount of documents we're rendering. We can increase this amount back when the issue is fixed.
> fix(compass-aggregations): update default document preview amount to 10 from 20

- packages/compass-aggregations/src/components/pipeline-results-workspace/index.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/index.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.spec.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-options/index.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/index.spec.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/index.tsx
- packages/compass-aggregations/src/components/pipeline/collation-toolbar.jsx
- packages/compass-aggregations/src/components/pipeline/collation-toolbar.module.less
- packages/compass-aggregations/src/components/pipeline/pipeline.jsx
- packages/compass-aggregations/src/components/pipeline/pipeline.module.less
We are not changing anything about the current flow of editing, just adding basic support for current behavior in the new toolbar: when you press edit we don't show "Open", "Save", and "New pipeline" actions. We also decided that we don't want to show "Run" or "Export" in this case. There are also small misc changes to paddings in a few places to align them a bit more and proper handling of `isAtlasDeployed` state that aligns it with the current toolbar
> chore(compass-aggregations): Handle view pipeline update in the new pipeline toolbar COMPASS-5811

- packages/connection-form/src/hooks/use-connect-form.spec.ts
- packages/connection-form/src/hooks/use-connect-form.ts
Fixes:
> "Selecting the whole host and trying to delete it keeps the value in the form but also shows a bunch of errors"
With the loose validation in `ConnectionString` is possible to leave the host empty. Also edge cases like `mongodb://,,,/` are handled just fine.
> fix(connect-form): allow empty hosts

- packages/connection-form/src/utils/csfle-handler.spec.ts
- packages/connection-form/src/utils/csfle-handler.ts
- packages/data-service/src/connection-options.ts
- packages/data-service/src/data-service.ts
See the comment for `unsetAutoEncryptionIfEmpty`, this
otherwise makes connecting fail when fully removing previously
configured CSFLE settings for a connection.
> fix(connection-form): clear autoEncryption when empty

- .evergreen/buildvariants.in.yml
- .evergreen/buildvariants.yml
- .evergreen/tasks.in.yml
- .evergreen/tasks.yml
- .evergreen/template-yml.js
This will continue to build compass for 1604 (and run check& test ie linting and unit tests there) then run e2e tests on 2004.
That way we still support 1804 AND we can test against mongodb 5+ on ubuntu AND we don't have to wait for docker on 1804.
And we won't have publishing complicated by 2004 for now. If that's even the cause of our publishing problems.
---
We can and probably should still have the discussion about dropping 1604 support and moving to 1804, but we can have that separately now.
> chore: build on 1604, test on 2004

- packages/compass-components/src/components/document-list/document.tsx
- packages/compass-components/src/components/document-list/element.tsx
- packages/compass-components/src/components/document-list/use-previous.tsx
- packages/compass-crud/src/components/document-list-view.jsx
Another thing that should reduce the input lag for aggregation builder. We noticed that there is a massive blocking "Recalculate Style" block in the perf profile every time documents are updated. I tracked it to using element uuid as a key on the document and elements. Using uuid as a key meant that every time stage preview finished fetching and we re-create the HadronDocument that is used to render the documents, React would completely discard and remount the underlying DOM elements instead of updating existing ones and that removing and adding new DOM elements for every single Element component on the screen is what was causing the "Recalculate Style" to happen
Here's a timeline before and after this change:
|Before|After|
|---|---|
|<img width="956" alt="image" …
> chore(compass-components): Do not use uuid as a key for Documents and Elements

- packages/data-service/package.json
- packages/data-service/src/data-service.spec.ts
- packages/data-service/src/data-service.ts
> feat(data-service): ensure that FLE2 collections are dropped properly COMPASS-5627

- configs/eslint-config-compass/index.js
- configs/eslint-config-compass/package.json
- configs/eslint-plugin-compass/rules/no-leafygreen-outside-compass-components.js
- configs/eslint-plugin-compass/rules/no-leafygreen-outside-compass-components.test.js
* Add eslint rule to check kebab case file name convention
We follow this as a rule, but have no way of automatically validating, @mcasimir suggested that we add this as a eslint rule
* Fix package.json resolution for no-leafygreen-outside-compass-components rule.
This was working correctly when running eslint programmatically, but wasn't resolving the package name for eslint vscode plugin because cwd for the vscode integration would always be a monorepo root
> chore(eslint-config-compass, eslint-plugin-compass): Misc eslint config updates

- packages/compass-e2e-tests/tests/collection-indexes-tab.test.ts
- packages/compass-indexes/src/components/create-index-field/create-index-field.spec.jsx
- packages/compass-indexes/src/components/create-index-modal/create-index-modal.spec.jsx
- packages/compass-indexes/src/utils/has-columnstore-indexes-support.spec.ts
- packages/compass-indexes/src/utils/has-columnstore-indexes-support.ts
- packages/compass/src/index.d.ts
Removes the feature flag so that columnstore index creation is only gated behind server version`6.1.0-alpha0`.
> chore(compass-indexes): remove feature flag for columnnstore indexes

- packages/compass-aggregations/src/components/pipeline-explain/index.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.spec.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.tsx
- packages/compass-aggregations/src/components/pipeline/pipeline.jsx
- packages/compass-aggregations/src/modules/explain.ts
- packages/compass-aggregations/src/modules/index.ts
- packages/compass-aggregations/src/stores/store.spec.js
- packages/compass/src/index.d.ts
feat(explain-aggregation): add explain button in toolbar COMPASS-5787
Show Explain button in aggregation toolbar with a feature flag.
> feat(explain-aggregation): add explain button in toolbar COMPASS-5787

- packages/compass-indexes/src/modules/create-index/index.js
- packages/compass-indexes/src/modules/create-index/index.spec.js
This pr removes the default index name creation in `compass-indexes` so that the server will do it. The server does the[ name generation ](https://www.mongodb.com/docs/manual/indexes/#index-names)we were previously doing.
The place where this will differ is with wildcard indexes. We’re explicitly naming wildcard indexes `wildcard` instead of the server’s `$**` - do we want to continue this or is the server one alright? I’m thinking we can generate names just for wildcards if that’s the case. (This discussion is in #dev-tools-designs on slack)
> chore(compass-indexes): Remove index name creation, default to server naming

- packages/compass-components/src/components/document-list/element.tsx
- packages/compass-crud/src/components/table-view/cell-renderer.jsx
Align the encrypted-field key icon and the `:` element divider before it
in Document components with the normal text baseline.
before:
after:
> chore(compass-components): align key icon in document with baseline COMPASS-5706

- packages/compass-aggregations/src/components/pipeline-results-workspace/index.tsx
- packages/compass-components/src/components/cancel-loader.spec.tsx
- packages/compass-components/src/components/cancel-loader.tsx
- packages/compass-crud/src/components/document-list.jsx
- packages/compass-e2e-tests/helpers/selectors.ts
- packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
- packages/compass-schema/src/components/compass-schema/compass-schema.jsx
Adds some e2e tests for the new "Run aggregation" feature. This covers running, editing and re-running, paginating, and cancelling a long aggregation. I'll do a separate PR to test the "Export aggregation" feature, this feels like a lot of code already
> chore(compass-e2e-tests): Add e2e tests for running an aggregation

- packages/compass-aggregations/src/components/stage-editor/stage-editor.jsx
- packages/compass-aggregations/src/modules/pipeline.ts
- packages/compass-aggregations/src/stores/store.spec.js
ticket: https://jira.mongodb.org/browse/COMPASS-5684
This clears the error message (if any) while leaving isValid as is. This way it won't display the stale message anymore, but it also won't allow you to run the aggregation until you fix the error.
Draft because I still plan on adding a test. Just opening the PR to get some input in the meantime.
> fix(aggregations): hide the stage error message when changing the operator COMPASS-5684

- packages/compass-e2e-tests/helpers/selectors.ts
- packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
Small clean-up to avoid test setup and cleanup code duplication
> chore(compass-e2e-tests): Move explain plan test under the same describe block to avoid duplicating before / after code

- packages/compass-aggregations/src/utils/cancellable-aggregation.ts
In order to kill the session properly for aggregations, we need to pass it to the `.aggregate`, so that operation is linked to the session. And when user cancels, we kill the session and the corresponding operation linked to it is stopped.
> fix(aggregations): use session when running aggregation

- .github/workflows/authors-and-third-party-notices.yaml
Attempts to fix the failures on main when generating `THIRD-PARTY-NOTICES.md` and `AUTHORS` by opening a PR.
No automerge yet, the PR is updated or reopened on each change to `main` but must be merged manually for the time being.
> chore: move auto generated files to PR

- packages/data-service/src/csfle-collection-tracker.spec.ts
- packages/data-service/src/csfle-collection-tracker.ts
COMPASS-5869
Remove the `encryptedFields` duplicates from the insert document modal.
> fix: do not return duplicates of encrypted fields COMPASS-5869

- .github/workflows/release-notes-cleanup.yaml
Remove the substitution regex to auto-link tickets in release notes. We need a better way to do that otherwise we keep wrapping a link inside another link each time a release is edited
> chore(ci): remove buggy auto link tickets in release notes

- configs/mocha-config-compass/index.js
- configs/mocha-config-compass/register/resolve-from-source-register.js
- configs/mocha-config-compass/register/tsnode-register.js
This makes it easier and faster to test monorepo dependencies because
there is no need to re-compile dependencies when working on multiple
packages at the same time and additionally ts-node doesn't need to compile
bundled plugin code which speeds up runtime for some tests where
dependencies on plugins exist. Additionally we might not need to run
bootstrap in CI or locally anymore when all packages are using shared
mocha config which should speed up test runs noticeably
> chore(mocha-config-compass): Make sure that tests are using source for monorepo workspaces

- packages/compass-query-history/src/stores/recent-list-store.js
- packages/compass-query-history/src/stores/recent-list-store.spec.js
I broke some stuff in https://github.com/mongodb-js/compass/pull/3171 while I was addressing feedback and didn't notice because I was relying on the E2E tests that were passing for some reason. Will look into how that's possible later - this should at least fix main in the meantime.
> fix(documents): fixes to recent queries

- packages/compass-aggregations/src/modules/explain.ts
- packages/data-service/src/data-service.ts
- packages/data-service/src/index.ts
Having `ExplainVerbosity` in the plugin imports the whole thing to the webpack bundle and then it blows up when Cloud team is importing the plugin in the mms. This patch re-exports the type from data-service so we can use it and replaces the return values with just strings so that we don't need to use driver export.
> chore(compass-aggregations): Do not import mongodb driver directly in the plugin

- packages/compass-components/src/components/editor.tsx
ACE Editor has a built-in code beautifier. This PR enables it.
It can be activated with `Ctrl+Shift+B`.
We may want to do a follow-up PR to trigger this functionality from a button in the UI, assuming that is possible.
https://user-images.githubusercontent.com/761042/176131040-697e7f4d-bc4b-4017-a917-e0507165b754.mov
> feat(compass-components): Enable ACE code formatter COMPASS-5923

- packages/compass-aggregations/src/components/stage-editor/stage-editor.jsx
- packages/compass-components/src/components/editor.tsx
- packages/compass-crud/src/components/json-editor.jsx
- packages/compass-query-bar/src/components/option-editor/option-editor.jsx
- packages/compass-schema-validation/src/components/validation-editor/validation-editor.jsx
COMPASS-5924
This updates the default for our `Editor` so `showPrintMargin` is false.
https://github.com/securingsincity/react-ace/blob/master/docs/Ace.md
Before
After
> chore(compass-components): Default to hiding print margin in the editor everywhere COMPASS-5924

- packages/connection-form/src/components/advanced-options-tabs/advanced-tab/advanced-tab.tsx
- packages/connection-form/src/components/advanced-options-tabs/advanced-tab/url-options.tsx
- packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-tab.tsx
- packages/connection-form/src/components/advanced-options-tabs/ssh-tunnel-tab/proxy-and-ssh-tunnel-tab.tsx
- packages/connection-form/src/components/advanced-options-tabs/tls-ssl-tab/tls-certificate-authority.tsx
- packages/connection-form/src/components/advanced-options-tabs/tls-ssl-tab/tls-client-certificate.tsx
- packages/connection-form/src/components/form-field-container.tsx
Instead of having inconsistent width specifications for the
individual tabs, remove tab content width specifications and
instead set a shared, pre-specified width for the `FormFieldContainer`
component.
> fix(connection-form): align advanced tab and input field widths

- packages/compass-components/src/components/bson-value.spec.tsx
- packages/compass-components/src/components/bson-value.tsx
- packages/hadron-type-checker/src/type-checker.js
- packages/hadron-type-checker/test/type-checker.test.js
This avoids showing results that cannot be round-tripped
as input data again.
Otherwise, data cannot be round-tripped when converting from/to Binary
blobs properly.
(This is an easy mistake to make, opened https://github.com/mongodb/js-bson/pull/504 to add a warning about this to the js-bson docs.)
> fix: improve `Binary` handling COMPASS-5848

- packages/compass-crud/src/stores/crud-store.js
- packages/compass-crud/src/stores/crud-store.spec.js
- packages/compass-e2e-tests/tests/collection-import.test.ts
- packages/compass-e2e-tests/tests/in-use-encryption.test.ts
Similary to the insert many documents functionality, refresh the documents list after inserting a single document. Counting documents in the `refreshDocuments` function happens asynchronously, therefore the expected count in the related test is 0 now, the same as for `insertMany` tests.
> fix: automatically refresh after CSFLE insert COMPASS-5806

- packages/data-service/src/data-service.ts
Noticed in the logs we were printing `insertOne` instead of `insertMany`
> chore(data-service): update insertMany log message

- packages/compass-crud/src/stores/crud-store.js
- packages/compass-e2e-tests/tests/in-use-encryption.test.ts
When doing `findOneAndReplace` updates, drop `__safeContent__`
for QE-enabled collections.
> fix(compass-crud): drop `__safeContent__` when replacing COMPASS-5856

- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-menus.tsx
As these two buttons open menus, the right glyph caret down gives a hint to that behavior.
Before:
After:
> feat(compass-aggregations): Add right glyph caret down to buttons with menus in compass-aggregations

- packages/compass-aggregations/package.json
- packages/compass-collection/package.json
- packages/compass-connections/package.json
- packages/compass-e2e-tests/package.json
- packages/compass-import-export/package.json
- packages/compass-schema/package.json
- packages/compass-shell/package.json
- packages/compass/package.json
- packages/connection-form/package.json
- packages/connection-model/package.json
- packages/data-service/package.json
- packages/data-service/src/connect-mongo-client.ts
- packages/index-model/package.json
This brings this fix in to compass: https://github.com/mongodb-js/mongosh/pull/1308
> chore: Use the new node-runtime-worker-thread from mongosh COMPASS-5767

- packages/compass-aggregations/package.json
- packages/compass-collection/package.json
- packages/compass-connections/package.json
- packages/compass-e2e-tests/package.json
- packages/compass-import-export/package.json
- packages/compass-schema/package.json
- packages/compass-shell/package.json
- packages/compass/package.json
- packages/connection-form/package.json
- packages/connection-model/package.json
- packages/data-service/package.json
- packages/data-service/src/connect-mongo-client.ts
- packages/index-model/package.json
Reverts mongodb-js/compass#3260
See thread https://mongodb.slack.com/archives/G2L10JAV7/p1657897406423629
Strong suspicion that the node driver bump from 4.6 to 4.8 broke something.
> Revert "chore: Use the new node-runtime-worker-thread from mongosh COMPASS-5767"

- packages/compass/src/main/auto-update-manager.ts
- packages/hadron-auto-update-manager/index.d.ts
- packages/hadron-auto-update-manager/index.js
- packages/hadron-auto-update-manager/test/index.test.js
Currently we don't include arch in the feed url which means that we also wouldn't be able to correctly update Compass on platforms where multiple builds exist, like apple silicon. This is a prerequisite for #3269
> chore(hadron-auto-update-manager): Include real platform and arch in the auto update feed url

- packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-workspace.jsx
- packages/compass-aggregations/src/components/pipeline/pipeline.jsx
- packages/compass-aggregations/src/components/stage-preview/stage-preview.jsx
- packages/compass-aggregations/src/components/stage-preview/stage-preview.module.less
- packages/compass-aggregations/src/components/stage-preview/stage-preview.spec.jsx
- packages/compass-aggregations/src/components/stage/stage.jsx
During project planning we didn't know that out / merge stages are actually supported by mms and so removed these button completely when the project was rolled out to the users. This patch brings them back, not with an explicit test and  using `isAtlasDeployed` flag to indicate that this is still used by the cloud (marking it as a chore as there is no difference for Compass and so doesn't make sense to have it in release notes)
As a drive by I removed the last usage of the `TextButton` and the unnecessary `openLink` helper in this `StagePreview` component I was updating
If you want to test this yourself, the easiest way to do so is to run this locally and use react devtools to switch the property value to `true`:
> chore(compass-aggregations): Show Merge / Save buttons when isAtlasDeployed is true COMPASS-5972

- packages/connection-form/src/utils/url-options.ts
> feat(connection-form): Add enableUtf8Validation option to advanced url options COMPASS-4944

- packages/compass-shell/src/components/compass-shell/compass-shell.jsx
This development focuses editor when you click on compass-shell.
The current behaviour in compass-shell doesn't let us to continue from the input area when we click on it and type something. Mostly, it is creating bad experience and confusion when you are dealing with huge history. It needs to be scrolled to the bottom to reach the input.
I could not find a way to write a proper test on this context because stylings in Shell component are not reachable even if I simulate click events. Open for suggestions.
Current:
https://user-images.githubusercontent.com/9059250/181265518-26c9ea47-1d1f-4451-a55b-fe233678fe66.mov
Development:
https://user-images.githubusercontent.com/9059250/181265699-cc38d435-a92d-4b5d-8f6a-65301d3bc58f.mov
> feat / focus editor when click shell

- packages/compass-schema/src/components/schema-toolbar/schema-toolbar.tsx
Starting to get ready to remove the new toolbar feature flag in the [`COMPASS-5678-query-history-as-popover`](https://github.com/mongodb-js/compass/compare/COMPASS-5678-query-history-as-popover?expand=1) branch.
Doing some cleanup/findings in separate packages in separate prs to keep that one smaller (it's already big).
> chore(compass-schema): dont show schema toolbar when there's nothing to show (feature flagged)

- .evergreen/tasks.in.yml
- .evergreen/tasks.yml
Something weird is going on in evergreen: after [we first run](https://evergreen.mongodb.com/task_log_raw/10gen_compass_main_ubuntu_publish_publish_7d1c8395cb9c4a6d9e3db311a9cd72eaaabcc56a_22_07_28_10_19_46/0?type=T#L493) a function with a specific variable passed, it then [gets applied](https://evergreen.mongodb.com/task_log_raw/10gen_compass_main_ubuntu_publish_publish_7d1c8395cb9c4a6d9e3db311a9cd72eaaabcc56a_22_07_28_10_19_46/0?type=T#L531) [every](https://evergreen.mongodb.com/task_log_raw/10gen_compass_main_ubuntu_publish_publish_7d1c8395cb9c4a6d9e3db311a9cd72eaaabcc56a_22_07_28_10_19_46/0?type=T#L539) [time](https://evergreen.mongodb.com/task_log_raw/10gen_compass_main_ubuntu_publish_publish_7d1c8395cb9c4a6d9e3db311a9cd72eaaabcc56a_22_07_28_10_19_46/0?type=T#L547) we run the …
> chore(ci): Explicitly provide arch when generating expansions for asset downloads

- .evergreen/tasks.in.yml
- .evergreen/tasks.yml
Follow-up to https://github.com/mongodb-js/compass/pull/3308. Forgot to add arch to the actual publish commands and as this is something that is currently completely skipped when not actually publishing, I missed this not actually being validated in my previous PR
> chore(ci): Add explicit arch to publish functions too

- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/index.tsx
- packages/compass-query-bar/src/components/query-bar.tsx
Syncing w/ Claudia before merging, cc @mcasimir 
Now we're using a button with the `Code` icon from https://www.mongodb.design/component/icon/example/
Before
After
> feat(compass-query-bar): update export to language button and icon

- packages/hadron-build/lib/target.js
Something that I missed when adding support for arm64, without this, whatever packaging task finishes last (arm or x64) will upload the files with the same name, overriding the previous one which is definitely not what we want. This path uses more specific filename that we already use for assets uploaded to download center instead of the current one
See [this thread](https://mongodb.slack.com/archives/G2L10JAV7/p1659530390480029?thread_ts=1659511803.513649&cid=G2L10JAV7) for some additional content
> chore: use more specific filename for macos app when packaging

- .evergreen/tasks.in.yml
- .evergreen/tasks.yml
The way the publish flow currently relies on evergreen expansions doesn't allow us to do a release properly because darwin-arm expansions are conflicting with the darwin-x64 ones. As the arm release would not be actually available through download center until we merge https://github.com/mongodb-js/compass/pull/3299 anyway, for now we will just remove these builds from the publish task
> chore(ci): Temporarily remove darwin-arm build from evergreen publish

- packages/compass-components/src/constants/mongodb-ace-theme-query.ts
- packages/compass-query-bar/src/components/option-editor.tsx
Feature flagged:
```
env COMPASS_SHOW_NEW_TOOLBARS="true" npm start
```
This PR updates `compass-query-bar` to make the editor inputs not overflow a few pixels on the right which was hiding a few characters on long inputs.
> chore(compass-query-bar): Make query input not overflow a few pixels off screen on new toolbar

- packages/compass-crud/src/components/add-data-menu.tsx
- packages/compass-crud/src/components/crud-toolbar.tsx
Feature flagged:
```
env COMPASS_SHOW_NEW_TOOLBARS="true" npm start
```
Broken out of pr https://github.com/mongodb-js/compass/pull/3312 
Before:
After:
> chore(compass-crud): Make new crud toolbar buttons not wrap at small widths

- .github/workflows/publish-compass.yaml
- packages/hadron-build/commands/upload.js
Small misc fixes to the publish that I missed in the initial PR
- uploadManifest method arguments changed, but I forgot to update it on call site
- secrets were not set for the task correctly
- added an option to do a manual dry run to test it (and to be able to e.g. roll back releases in case we ever need this)
> chore(ci): add evg secrets for publish workflow; add manual dispatch; fix upload fn arguments

- packages/hadron-build/commands/upload.js
- packages/hadron-build/package.json
Seems like otherwise we are running into secondary rate limits when trying to do it one by one because every upload first fetches release info. Relevant change in devtools-github-releases package: https://github.com/mongodb-js/devtools-github-repo/pull/3
> chore(hadron-build): upload assets to github release in one go

- packages/hadron-build/commands/upload.js
- packages/hadron-build/lib/download-center.js
`download` function second argument is a destination directory, not a destination file. Instead of using it, let's pipe to file instead.
> chore(hadron-build): fix download destination

- packages/compass/package.json
- packages/compass/src/app/index.js
debug-menu hasn't been published to in 5 years, so seems to be unmaintained. Removing it also seemed to remove https://github.com/sindresorhus/electron-debug from the package lock file (massively outdated version) and if it is annoying losing this feature in dev we could just try and bring it back using something like that? Or whatever the modern way is to do this.
> chore(debug) remove debug-menu which broke in the electron upgrade

- packages/hadron-build/commands/upload.js
I had a wrong assumption that only assets that are displayed in the download center need to be uploaded there, but for windows update files (.nupkg ones) this is not true. This patch makes sure that we are not filtering anything out and uploading everything to the download center bucket even if it's not displayed in download center UI
> chore(hadron-build): all assets need to be uploaded to download center

- package.json
The version published previously is missing files in the package:
https://github.com/mongodb-js/devtools-shared/commit/759ddfbcb7b9a9603a69dd9aec1fe4a56db158ab
> ci: update bump-monorepo-packages

- packages/compass-query-history/src/components/toolbar/toolbar.tsx
Making it green like figma mocks.
Before:
After:
> chore(compass-query-hisory): update query history title color styles

- packages/compass-query-bar/src/components/option-editor.tsx
- packages/compass-query-bar/src/components/query-bar.spec.tsx
COMPASS-4900
This PR disables the `indent` and `outdent` ace editor commands for the feature flagged query bar:
```
env COMPASS_SHOW_NEW_TOOLBARS="true" npm start
```
This means a user can now tab navigate around the query bar easier. It also means they can't type a tab or outdent the input. We could alternatively use an `escape` key handler documented in an `aria-label` for the editor which would disable these tab commands so a user can continue tab navigating.
Before:
https://user-images.githubusercontent.com/1791149/184688394-6931af18-72b9-4c84-bd28-30798b73d5e2.mp4
After:
https://user-images.githubusercontent.com/1791149/184687561-45c208ce-9fbe-4618-8874-d2ecb4fb9111.mp4
> feat(compass-query-bar): disable tab commands in ace editor for query bar for keyboard nav accessibility COMPASS-4900

- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.spec.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.tsx
- packages/compass-aggregations/src/components/saved-pipelines/saved-pipelines.spec.jsx
- packages/compass-aggregations/src/components/saved-pipelines/saved-pipelines.tsx
- packages/compass-query-history/src/components/query-history/query-history.jsx
- packages/compass-query-history/src/components/toolbar/toolbar.spec.tsx
- packages/compass-query-history/src/components/toolbar/toolbar.tsx
COMPASS-6028
This pull request adds the namespace to the toolbar title in the query history and saved aggregations panels.
> feat(query-history, aggregations): Show namespace on saved queries and pipelines popovers COMPASS-6028

- packages/compass-aggregations/src/components/pipeline-toolbar/index.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.tsx
Some styling tweaks for the aggregations page to make it more inline with the new toolbars as well as some LeafyGreen dark mode support.
Before:
After:
Before:
After:
> chore(aggregations): remove margin on toolbar, better focus styles button, lg darkmode button

- scripts/monorepo/delete-stale-packages-from-lock.js
- scripts/package.json
A silly change: I noticed that NPM caches the `package.json`s of workspaces in `package-lock.json`, and apparently fails to clean them up, or maybe there are commands that have to be run in order to properly remove a workspace.
Anyway, I've added a script to remove them.
> chore: cleanup package-lock from old workspaces

- packages/compass-query-history/src/components/query-history/query-history.module.less
- packages/compass-query-history/src/index.ts
Fixes COMPASS-6039 - query history actions not working. This was caused by having the actions and store from the scoped modal overriding the actions and store of the popover plugin. This pr updates it so the scoped modal does not register when the feature flag is enabled (and vise versa).
In splitting out the work out of one pr initially I missed this part. Also slight style width drive by improvement. Added feature flagged label as this is not yet released.
> fix(query-history): fix query history actions with feature flag COMPASS-6039

- packages/compass-e2e-tests/tests/connection.test.ts
- packages/compass/package.json
Since it is a dependency of win-export-certificate-and-key,
node-forge should also be unpacked, like its dependent.
This adds an e2e test for verifying that the shell works
when connecting to Atlas using tlsUseSystemCA (since that
is an environment which always uses TLS and should always
match the system CA suite).
> fix(compass): include node-forge in unpacked node_modules COMPASS-5802

- packages/compass-home/src/components/home.tsx
COMPASS-6047
After connecting and disconnecting, the collection submenu was still visible. Now it's hidden until the user is back on a collection.
Open to ideas on testing, we would have to listen to main ipc events in the electron testing environment to fully test it and this emitter is already far from the consumer. Not sure it's worth adding.
Before:
After:
> fix(compass-home): hide collection submenu on disconnect COMPASS-6047

- packages/compass-e2e-tests/helpers/selectors.ts
- packages/compass-indexes/src/components/drop-index-modal/drop-index-modal.jsx
- packages/compass-indexes/src/components/drop-index-modal/drop-index-modal.spec.jsx
fix(indexes): align message properly on delete index modal which was introduced in https://github.com/mongodb-js/compass/pull/3306
Before:
After:
> fix(indexes): align delete index modal text

- packages/data-service/src/connection-secrets.spec.ts
- packages/data-service/src/connection-secrets.ts
- packages/data-service/src/connection-storage.spec.ts
Fully remove KMS providers from the list of providers if their
set of options is empty after extracting secrets, since leaving
an existent-but-empty object and passing it to libmongocrypt
puts it in a state that Compass does not support (namely, providing
credentials on demand after connecting).
> fix(data-service): fully remove empty KMS provider options COMPASS-5930

- packages/index-model/lib/model.js
- packages/index-model/test/index.test.js
fix(index-model): text index is not compound COMPASS-5386
Currently we are reporting text indexes as compound, which is calculated based on the keys of an index.
By default if a text index is created on a single field, it will always have 2 keys (_FTS & _FTSX). In this PR we are making this check stronger, by ensuring:
1. An index having only one text field, is a single index;
2. An index having multiple text only fields, is a compound index (if `extra.weights.length > 1`);
3. An index having multiple fields (text and 1, -1 ...), is a compound index (if `keys.length > 2`).
> fix(index-model): text index is not compound COMPASS-5386

- packages/hadron-document/src/object-generator.ts
- packages/hadron-document/test/document.test.ts
Diff probably best viewed with whitespace changes hidden.
---
Follow-up to c865b66bd7c4 (#3239), which introduced this bug:
Handle updates to arrays in the case in which the updated array
(or another updated path) contains dots or starts with a dollar sign,
using alternatives to `$getField` and `$setField` which can work on
arrays (`$arrayElemAt` for the former, `$concatArrays` + `$slice` for
the latter).
> fix(hadron-document): fix updating arrays with dots in names COMPASS-6011

- packages/compass-sidebar/src/components-legacy/non-genuine-warning-modal/non-genuine-warning-modal.jsx
- packages/compass-sidebar/src/components-legacy/sidebar-instance/sidebar-instance.jsx
- packages/compass-sidebar/src/components-legacy/sidebar/sidebar.jsx
I also moved the non-genuine warning modal into the instance details along with the other modals so they can be wrapped with one ThemeProvider in one place.
This affects the SaveConnectionModal, CSFLEConnectionModal and NonGenuineWarningModal in the old sidebar (ie. without the feature flag).
> fix(legacy-sidebar): Don't inherit the dark theme from the old sidebar for its modals

- packages/compass-crud/src/components/document-list.jsx
> fix(compass-crud): Hide document views when there are no documents

- packages/compass-e2e-tests/tests/collection-indexes-tab.test.ts
- packages/compass-indexes/src/components/create-index-fields/create-index-fields.spec.tsx
- packages/compass-indexes/src/components/create-index-form/create-index-form.spec.jsx
- packages/compass-indexes/src/utils/has-columnstore-indexes-support.spec.ts
- packages/compass-indexes/src/utils/has-columnstore-indexes-support.ts
> feat(compass-indexes): only show columnstore index option for mongodb server >= 7 COMPASS-5970

- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.tsx
- packages/compass-components/package.json
- packages/compass-components/src/hooks/use-focus-ring.ts
- packages/compass-components/src/index.ts
- packages/compass-databases-navigation/package.json
- packages/compass-databases-navigation/src/databases-navigation-tree.tsx
- packages/compass-databases-navigation/src/tree-item.tsx
- packages/compass-indexes/src/components/indexes-table/badge-with-icon-link.tsx
- packages/compass-query-bar/src/components/option-editor.tsx
- packages/compass-query-bar/src/components/query-history-button-popover.tsx
- packages/compass-query-bar/src/components/query-option.tsx
- packages/compass-settings/src/components/modal.tsx
- packages/compass-settings/src/components/sidebar.tsx
- packages/compass-sidebar/src/components-legacy/favorite-button/favorite-button.jsx
- packages/compass-sidebar/src/components/csfle-marker.tsx
- packages/compass-sidebar/src/components/non-genuine-marker.tsx
This fixes a few issues with the aria labels / ids and focusability of the tab content in the settings modal following the [example](https://www.w3.org/WAI/ARIA/apg/example-index/tabs/tabs-manual.html) and documentation I linked to in https://github.com/mongodb-js/compass/pull/3222#discussion_r912736402
I am deliberately not adding a proper keyboard support as this is more involved and for now, while we have only one tab there, can be skipped, but should be addressed as soon as we start adding more tabs there (I opened [a ticket](https://jira.mongodb.org/browse/COMPASS-6097) for that).
I also added a proper focus ring to the elements there and, while I was at it, normalized how we use it as there were a lot of different variations, some of which were just not working correctly
> chore: fix aria issues in settings modal; fix and normalize focus ring usage

- .evergreen/print-compass-env.js
Artifactory is currently 503-ing, this should ensure that we
do not attempt to use that registry and instead pick the
default one even in the CI preinstall script.
> chore(ci): use standard npm registry in preinstall

- packages/storage-mixin/lib/backends/splice-disk-ipc.js
- packages/storage-mixin/lib/backends/splice-disk.js
It can not have been intentional that this overwrote the prototype
methods, rather than the methods of the specific instances, since
the previous code meant that using `SpliceDiskIpcBackend` would have
affected completely independent storage-mixing backends (even including
other instances of `SpliceDiskIpcBackend` itself).
This code has been broken like this since its inception. I did verify
that saving credentials works as it did before.
> fix(storage-mixin): do not monkey-patch prototypes in SpliceDiskIpcBackend

- packages/compass-components/src/components/resizeable-sidebar.tsx
- packages/compass-databases-navigation/src/tree-item.tsx
- packages/compass-sidebar/src/components-legacy/sidebar/sidebar.module.less
- packages/compass-sidebar/src/components/navigation-items.tsx
The reason why we tried bolding the text on hover rather than a background color was because of the hover effect on the icon button on top of the hover effect of the tree item. See videos:
https://user-images.githubusercontent.com/69737/188893757-896967a3-eb88-443f-bf39-a57d26ddafce.mov
https://user-images.githubusercontent.com/69737/188893768-df7049fb-c82d-4f04-a61d-46a70ccfb3c0.mov
https://user-images.githubusercontent.com/69737/188893791-170b87c6-3fbf-4426-86a2-d0d2737692e9.mov
https://user-images.githubusercontent.com/69737/188893793-3d13c3fc-c705-462d-8404-a639bccff756.mov
But.. I now think this is maybe less of a problem than the bold text jiggle effect?
Reference:
leafy green's own sidebar nav has green active color (similar to us) and gray hover effect (same as here): …
> background color, not bold

- .github/PULL_REQUEST_TEMPLATE.md
- packages/connection-form/src/components/advanced-options-tabs/advanced-tab/url-options.tsx
- packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.tsx
- packages/connection-form/src/components/advanced-options-tabs/csfle-tab/encrypted-field-config-input.tsx
- packages/databases-collections/src/components/collection-fields/capped-collection-fields.jsx
- packages/databases-collections/src/components/collection-fields/fle2-fields.jsx
- packages/databases-collections/src/components/collection-fields/time-series-fields.jsx
- packages/databases-collections/src/modules/create-collection/index.js
COMPASS-5653
Updates a few labels to include an id and pass it to the editor (it's a recent change that our ace editors accept ids).
Where there is no item for the label to apply to, this updates the labels to `Body` components with the `weight` `medium`. We could instead use the `Subtitle` here but I was thinking it looked a bit big for the connection form.
Also fixed a few lint warnings in `compass-collection`. Might look into updating that to the new config soon.
LG Typography: https://www.mongodb.design/component/typography/example/
> chore: update todo htmlFor usage in labels COMPASS-5653

- packages/compass-collection/src/components/collection-header-actions/collection-header-actions.tsx
- packages/compass-collection/src/components/collection-header/collection-header.tsx
- packages/compass-databases-navigation/src/collection-item.tsx
- packages/compass-databases-navigation/src/database-item.tsx
COMPASS-6106
This PR makes it so the namespace on the collection page does not overflow and hide the collection stats.
Also a drive by to add the title to the databases and collections in the sidebar so that when a user hovers over it they can see the full title.
Before:
After:
Title:
> fix(collection): Make namespace not overflow width, add title to sidebar items COMPASS-6106

- packages/compass/src/main/telemetry.ts
6fa86474c8e4 introduced a call to `getOsInfo()` in `CompassTelemetry.identify()`. This accidentally changed the order of calls to be `track()` called before `identify()` on the segment API, since `.identify()` would be called asynchronously.
I’m not sure if this has a noticable impact on Segment, but we generally should be calling `.identify()` first I believe.
Also, use this as an opportunity to log errors instead of entirely ignoring them.
> chore(compass): re-reverse identify()/track() order in CompassTelemetry

- packages/compass-indexes/src/components/create-index-fields/create-index-fields.tsx
- packages/compass-indexes/src/components/create-index-form/create-index-form.spec.jsx
- packages/compass-indexes/src/components/create-index-form/create-index-form.tsx
- packages/compass-indexes/src/components/create-index-modal/create-index-modal.tsx
We don't need to explicitly color the `H3` component as it will inherit darkmode in the new leafygreen versions.
Also removed a few debugs I noticed in tests.
Mocks: https://www.figma.com/file/vbjoD4dcisPYRYJ5RRu72k/Compass-LG?node-id=2430%3A64950
Before:
After:
> chore(indexes): Remove unneeded darkmode prop usage, update components to match designs

- packages/compass-components/src/components/error-boundary.tsx
- packages/compass-components/src/components/resizeable-sidebar.tsx
- packages/compass-components/src/index.ts
- packages/compass-sidebar/src/components/sidebar.tsx
- packages/compass-sidebar/src/plugin.jsx
COMPASS-5074
This PR adds an error boundary to the sidebar so that in the unlikely case an uncaught error occurs the entire app isn't unusable. 
We export the width and apply the width as the resizable sidebar is what usually contains the width of the sidebar and it's inside this plugin. We'd like to catch any errors that might occur there as well.
> chore(sidebar): Add error boundary to sidebar COMPASS-5074

- packages/compass-sidebar/src/components/database-collection-filter.tsx
The filter input used to say "Filter your data" which no one was happy with. It now says "Search" although "Filter" might also be a good option?
Furthermore when you hovered over the input the title "Please fill in your field" appeared. Turns out [this is an html5 thing](https://groups.google.com/g/angular/c/pcoFMcLkpHE?pli=1) and the way to get rid of it is by putting `noValidate` on a `<form>` tag. So I added a form tag and disabled onSubmit on it because enter should do nothing in this case.
I then added a title and made it the same as the aria label so it would give you useful information instead.
> chore(sidebar): Change sidebar filter placeholder and title COMPASS-6124

- packages/compass-databases-navigation/src/placeholder-item.tsx
Placeholders were aligned with the icons in the design, this reduces the jump when the actual item pops in
|Before|After|
|---|---|
|![Kapture 2022-09-15 at 16 22 22](https://user-images.githubusercontent.com/5036933/190429003-52ab7d28-d586-4c1b-aeb1-474f3a00a476.gif)|![Kapture 2022-09-15 at 16 20 40](https://user-images.githubusercontent.com/5036933/190429146-047d4d9a-410a-4d20-a83d-8812255b9414.gif)|
> chore(databases-navigation): align placeholder with the icon

- packages/compass-components/src/components/workspace-tabs/tab.tsx
What I saw in Figma seems to also make the icon bigger and vertically centered, but I assume that's the kind of thing we'll template for the new visual brand project.
> chore(tabs): align tabs with the sidebar title area COMPASS-6114

- packages/data-service/src/connect-mongo-client.ts
- packages/data-service/src/data-service.spec.ts
- packages/data-service/src/data-service.ts
- packages/data-service/test/helpers.ts
As discussed in the ticket, we will reconnect the CSFLE-enabled client after running a collMod operation in order to purge internal libmongocrypt caches.
> fix(data-service): reconnect csfle client after collMod COMPASS-5989

- packages/compass-import-export/src/components/import-modal/import-modal.jsx
- packages/compass-import-export/src/components/progress-bar/progress-bar.jsx
- packages/compass-import-export/src/utils/format-number.js
|Before|After|
|---|---|
|<img width="212" alt="image" src="https://user-images.githubusercontent.com/5036933/191705177-2a5e5f60-079e-4f19-ad3d-263542d6f3da.png">|<img width="233" alt="image" src="https://user-images.githubusercontent.com/5036933/191704934-7fadd004-54d3-4485-9c6b-254e4e23c674.png">|
> chore(import-export): fix number formatting for import label

- package.json
- scripts/align-monorepo-dependencies.js
A command that we can use to publish a "next" / "experimental" release from any branch. Later we're planning to use this in evergreen to publish latest versions of packages and trigger an evergreen task on the mms side
> chore(monorepo): add command to do a experimental version bump from head

- packages/compass-crud/src/components/insert-json-document.jsx
- packages/compass-crud/src/components/insert-json-document.module.less
Fixes https://github.com/mongodb-js/compass/issues/3516
We'll be improving this modal and the status message it shows in the leafygreen work, figured I'd open this as it's quick and not connected to that work.
We could also add variant sizes to the editor, then the aggregations and other places could avoid these things.
> fix(crud): improve selection area for insert document editor

- .evergreen/functions.yml
- .github/workflows/publish-packages.yaml
Fixes a few issues with how we try to publish packages currently:
- Append token to the npmrc instead of overriding the whole config
- Do not use expansion syntax in evergreen: this gets replaces with nothing before the function is even executed
[Evergreen patch](https://spruce.mongodb.com/task/10gen_compass_main_ubuntu_publish_publish_packages_next_patch_25b11de63d51aa4ca7fda0f3eae67999e3418ca5_633479513e8e860e978cf193_22_09_28_16_42_03/logs?execution=0) to confirm that it works
> ci: fix publish command

- packages/compass-indexes/src/components/indexes-table/indexes-table.tsx
Doesn't look like this made it into a ga so labeling it a `chore` to avoid release notes.
Before:
After:
> chore(indexes): fix indexes table header scrolling

- packages/compass-preferences-model/package.json
Noticed with some recent `compass-preferences-model` work that it wouldn't clean on compile that would lead to needing to restart/remove some files.
> chore(preferences-model): clean on pre-compile

- packages/compass-collection/package.json
- packages/compass-collection/src/components/collection-header/collection-header.tsx
- packages/compass-collection/src/components/collection/collection.tsx
- packages/compass-collection/src/modules/data-service.ts
- packages/compass-collection/src/modules/server-version.ts
- packages/compass-collection/src/modules/tabs.ts
- packages/compass-collection/src/stores/context.tsx
- packages/compass-collection/src/stores/index.ts
- packages/hadron-app-registry/src/app-registry.spec.ts
- packages/hadron-app-registry/src/app-registry.ts
- packages/hadron-app-registry/src/index.ts
To prep for possible bug fixes for [COMPASS-6146](https://jira.mongodb.org/browse/COMPASS-6146) I wanted to introduce more types to reduce chances of introducing more bugs.
Created COMPASS-6162 to add more types down the line (will take some webpack/ts config work though).
Removed usage of `semver` in `compass-collection` - it was used for checking the `minimumServerVersion` in plugin roles, which currently no plugins use. I'll leave a comment to highlight this one.
> chore(compass-collection): Add more types to tab reducers

- .evergreen/functions.yml
So that we don't run on patches or on beta/stable release projects.
> chore: only run publish-packages-next on main commits

- packages/compass-components/src/compass-font-sizes.ts
- packages/compass-components/src/components/accordion.tsx
- packages/compass-components/src/components/workspace-tabs/tab.tsx
- packages/compass-components/src/index.ts
- packages/compass-connections/src/components/connection-list/connection.tsx
- packages/compass-connections/src/components/form-help/form-help.tsx
There were only two: small at 13px and default at 14px. I can't really find any common logic between all the hardcoded font sizes like that. It all seems to be arbitrary design decisions.
ie. I can't think of names for two new typographic elements that we can drop in there and group all the existing ones into and I don't think we'll find any. If you look at the CSS around the font sizes we also do things like override font weight and line height to not even mention all the margin/padding and other layout overrides.
So I think these are layout elements, not typographic (ie. flowing body text ones).
Therefore I think the font sizes are part of the designs and best left next to the rest of the CSS overrides.
If we _do_ find that we have need for another heading or two, then maybe we can add …
> chore: get rid of compassFontSizes COMPASS-6102

- packages/compass-preferences-model/package.json
- packages/compass-preferences-model/src/global-config.spec.ts
- packages/compass-preferences-model/src/global-config.ts
Yargs is informed about the types of options where they can be determined, and performs camel-case expansion on options specified in kebab case.
However, it does not apply those types in the latter case, making it so that `--showed-network-opt-in foo` would lead to a `false` value for `showedNetworkOptIn`, unlike `--showedNetworkOptIn foo`. Address this by also telling yargs about the kebab-case versions explicitly.
> fix(compass-preferences-model): tell yargs about types for kebab case options

- packages/compass-collection/package.json
- packages/compass-collection/src/components/collection-header/collection-header.spec.tsx
- packages/compass-collection/src/components/collection/collection.spec.tsx
- packages/compass-collection/src/components/collection/collection.tsx
- packages/compass-collection/src/components/workspace/workspace.tsx
- packages/compass-collection/src/modules/stats.ts
- packages/compass-collection/src/modules/tabs.ts
- packages/compass-collection/src/stores/index.spec.ts
- packages/compass-collection/src/stores/index.ts
Fixes COMPASS-6146 and https://github.com/mongodb-js/compass/issues/3491
This PR updates the `stats` reducer in `compass-collection` so that each `namespace` gets its own stats. That makes it so when folks change between tabs the collection stats are what they expect.
Looking at how we're typing our redux and we'll probably want to be using slices with `createSlice` to improve these reducer types down the line. As this is a bug fix we'd like out sooner, and because this entire store is `any` typed currently, I'd like to keep consistency in this package and do something similar to what we were doing before. Docs: https://redux.js.org/usage/usage-with-typescript#define-slice-state-and-action-types
> fix(compass-collection): Add map for collection stats for tab namespace isolation COMPASS-6146

- packages/compass-components/src/hooks/use-focus-ring.ts
- packages/compass-sidebar/src/components/navigation-items.tsx
Looks like we lost this accessibility with the new sidebar, this pr adds it back in. This makes it so that folks using a keyboard for navigation can navigate to these buttons (using tab to navigate). Should help screenreaders. To open up screenreader on a mac you can use `command+F5`.
I was also looking at adding a `nav` element or `role="navigation"` landmark to the sidebar, but I think we can do that another time.
https://user-images.githubusercontent.com/1791149/194962288-2f9255cf-9ae8-4248-adbc-413c6b2b7ff1.mp4
> chore(sidebar): make `My Queries` and `Databases` nav items tab-able 

- packages/compass-preferences-model/src/global-config.spec.ts
Looks like this broke on main as a result of two branches being merged, with one of them breaking the tests of the other. Bound to happen sometimes I think. 
The commit from here added the test:
https://github.com/mongodb-js/compass/commit/38f0a541828d7d712b092e393ed821d0861a439e#diff-785edfc1a8b56e2e358018591788f11a30558cb232932d5eaa7affecf73cf0e2R90
And the `positionalArguments` argument parsing was added here:
https://github.com/mongodb-js/compass/commit/cc94f77fa369dc1c1d3cb852e488779fbfb53a8a#diff-06a7ccc654153e56e5f96f96cbd04b2fb5f73b79ad7fec92af0c62f432c87cc7R130
So when the test was merged the `positionalArguments` cli argument parsing didn't exist yet; doesn't look like a bug, just a broken test.
As noted in this comment …
> chore(preferences-model): update test, add new positionalArguments parsed argument

- packages/compass-e2e-tests/tests/in-use-encryption.test.ts
Unindexed encrypted field updates that were not working before were fixed in [SERVER-68065](https://jira.mongodb.org/browse/SERVER-68065) but these fields can't be queried, so this patch adds some special handling around this case.
I am keeping the workaround for the issue in place in case we ever add 6.0 as an explicit version to our test matrix, but also feel free to tell me if y'all don't think this is required, I'll clean it up
> chore(e2e): handle unindexed encrypted field update in fle test COMPASS-6194

- packages/compass-components/src/components/interactive-popover.tsx
- packages/compass-components/src/components/workspace-container.tsx
- packages/compass-components/src/components/workspace-tabs/workspace-tabs.tsx
- packages/compass-components/src/index.ts
- packages/compass-connections/src/components/connecting/connecting-animation.tsx
- packages/compass-connections/src/components/connection-list/connection-list.tsx
- packages/compass-find-in-page/src/components/find-in-page-input.tsx
- packages/compass-shell/src/components/compass-shell/compass-shell.jsx
- packages/connection-form/src/components/advanced-connection-options.tsx
Tiny quality of life improvement: replaces `transparentize` with `rgba` from polished. `transparentize` uses an inverted form for the opacity compared to `rgba` (1 - `opacity`) and is a bit confusing when we need to convert from figma or from less ([fade](https://lesscss.org/functions/#color-operations-fade)).
`fade(@color1, 30%)` --> `rgba(color1, 0.3)` --> `transparentize(0.7, color1)`
> chore: use rgba instead of transparentize

- packages/compass-query-bar/src/components/option-editor.tsx
- packages/compass-query-bar/src/components/query-bar.tsx
COMPASS-6185
This updates the first row query bar styles to use [`alignItems: flex-start`](https://developer.mozilla.org/en-US/docs/Web/CSS/align-items) so that when the filter is multi-line the other options do not adjust their position. This is a bit brittle, it requires all of the elements to be the same height and behave similarly as they aren't centered vertically (previously done with `alignItems: center`.) I left a comment where we have styles set specifically for this.
| Before | After |
| --- | ----------- |
| ![Screen Shot 2022-10-14 at 12 24 44 PM](https://user-images.githubusercontent.com/1791149/195895174-9bf82e61-1405-47a5-8cdc-d20adcd63d22.png) | ![Screen Shot 2022-10-14 at 12 16 23 PM](https://user-images.githubusercontent.com/1791149/195895225-8d22953f-33f8-4a51-9d3e-e0a41 …
> chore(query-bar): use align-items: flex-start in query bar for filter expansion styles COMPASS-6185

- packages/compass-aggregations/src/modules/pipeline-builder/index.ts
- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-builder.ts
- packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.spec.ts
- packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
- packages/compass-aggregations/src/utils/is-action.ts
I am looking for ways to make COMPASS-6167 not introduce a million changes at the same time, so the plan for now is:
- Add new slice with tests (this PR). It doesn't make much sense on it's own, but is more or less the only cutoff point I could find for now
- Connect to all existing components. This really can't happen in multiple patches and I'll have to do it in one go
- Clean up components props and prop types
- Clean up unused store code
> chore(compass-aggregation): add new slice for stage-by-stage editor COMPASS-6167

- packages/compass-components/src/components/leafygreen.tsx
If a leafygreen Menu (and therefore MenuItems) makes its way into a `<form>` somehow then clicking on a menu item will submit that form. This is because it uses a button tag without specifying a type and buttons by default have `type="submit"`.
> chore: Make sure MenuItems are type button, not type submit

- packages/compass-logging/src/index.spec.ts
- packages/compass-logging/src/index.ts
COMPASS-6189
Doesn't look like anything is wrong with telemetry. While investigating I figured it might be good to still track an event when fetching the attributes for the event fails. This would ensure if something breaks in a function like the fetching connection details one here: https://github.com/mongodb-js/compass/blob/27e900f99a6608b77068ba74cc4171fe898a1106/packages/compass-connections/src/modules/telemetry.ts#L125 that we still track the event, however with an `error_fetching_properties: true`  attribute so we know something is up.
Before merging I'm going to check with product that emitting the same event with that attribute is okay. We might instead want to send a different, unique, event with the event name in the properties.
Also I'll cleanup the tests a bit so they aren't …
> chore(telemetry): track event on fetching attribute failure, add tests COMPASS-6189

- packages/compass-components/src/components/document-list/element-actions.tsx
- packages/compass-components/src/components/document-list/element.tsx
- packages/compass-components/src/components/interactive-popover.spec.tsx
- packages/compass-components/src/hooks/use-toast.spec.tsx
- packages/compass-components/src/hooks/use-toast.tsx
- packages/compass-connections/src/components/connection-list/connection.tsx
- packages/compass-crud/src/components/breadcrumb.jsx
- packages/compass-crud/src/components/table-view/add-field-button.jsx
- packages/compass-crud/src/components/table-view/cell-editor.jsx
- packages/compass-crud/src/components/table-view/cell-renderer.jsx
- packages/compass-crud/src/components/updatable-icon-button.jsx
- packages/compass-import-export/src/components/import-modal/import-modal.jsx
- packages/compass-import-export/src/components/progress-bar/progress-bar.jsx
- packages/compass-query-bar/src/components/query-bar.spec.tsx
- packages/compass-query-history/src/components/favorite/favorite-list-item.jsx
- packages/compass-query-history/src/components/query/query.jsx
- packages/compass-query-history/src/components/recent/recent-list-item.jsx
- packages/compass-query-history/src/components/saving/saving.jsx
- packages/compass-schema/src/components/type/type.jsx
- packages/compass-schema/src/components/value-bubble/value-bubble.jsx
- packages/compass-shell/src/components/shell-header/shell-header.jsx
- packages/connection-form/src/components/favorite-color-picker.tsx
- packages/hadron-react-buttons/src/animated-icon-text-button.jsx
- packages/hadron-react-buttons/src/icon-button.jsx
- packages/hadron-react-buttons/src/icon-text-button.jsx
- packages/hadron-react-buttons/src/text-button.jsx
The default type for a button element is submit. So any button that makes its way into a form will submit that form. This is probably not what we want and if it was then I'd argue that it is better to specify type="submit" explicitly.
> chore: make sure every button element has a type

- packages/compass-e2e-tests/helpers/commands/add-collection.ts
- packages/compass-e2e-tests/helpers/commands/add-database.ts
- packages/compass-e2e-tests/helpers/commands/close-settings-modal.ts
- packages/compass-e2e-tests/helpers/commands/close-welcome-modal.ts
- packages/compass-e2e-tests/helpers/commands/drop-collection.ts
- packages/compass-e2e-tests/helpers/commands/drop-database.ts
- packages/compass-e2e-tests/helpers/commands/export-to-language.ts
- packages/compass-e2e-tests/helpers/commands/index.ts
- packages/compass-e2e-tests/helpers/commands/save-favorite.ts
- packages/compass-e2e-tests/helpers/commands/screenshot.ts
- packages/compass-e2e-tests/helpers/compass.ts
- packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
- packages/compass-e2e-tests/tests/collection-indexes-tab.test.ts
- packages/compass-e2e-tests/tests/connection-form.test.ts
- packages/compass-e2e-tests/tests/connection.test.ts
- packages/compass-e2e-tests/tests/database-collections-tab.test.ts
- packages/compass-e2e-tests/tests/in-use-encryption.test.ts
- packages/compass-e2e-tests/tests/instance-databases-tab.test.ts
- packages/compass-e2e-tests/tests/instance-my-queries-tab.test.ts
- packages/compass-e2e-tests/tests/instance-sidebar.test.ts
I have an upcoming PR that changes all the modals, but also inside the modals are forms and things that we'll be changing a lot in the "New Visual Brand" epic. It would be nice to have automated before and after screenshots to make review easier especially since the layout changes in subtle ways. Also nice for devs to spot changes.
This puts screenshots in `.log/screenshots` but it doesn't upload it as artifacts in Evergreen. So for now we have to grab them locally after running the e2e tests.
> chore: take screenshots of the modals encountered in E2E tests

- packages/compass-aggregations/src/components/pipeline-explain/explain-results.tsx
COMPASS-6226
| Before | After |
| --- | --- |
| ![Screen Shot 2022-10-24 at 7 41 04 PM](https://user-images.githubusercontent.com/1791149/197650260-3e630268-397e-4fac-9147-37404a7c1237.png) | ![Screen Shot 2022-10-24 at 7 38 54 PM](https://user-images.githubusercontent.com/1791149/197650284-86a0753d-8391-4ff1-85ab-86fe1d3c32b1.png) |
| ![Screen Shot 2022-10-24 at 7 41 17 PM](https://user-images.githubusercontent.com/1791149/197650267-68c3f2bd-4aab-47cd-b1e3-7511ff0a45d0.png) | ![Screen Shot 2022-10-24 at 7 38 40 PM](https://user-images.githubusercontent.com/1791149/197650298-c950f0f3-9d6b-4ad1-b735-bb66536bedc0.png) |
> chore(aggregations): use `KeylineCard` component in explain results instead of `Card` COMPASS-6226

- .github/ISSUE_TEMPLATE/feature_request.md
Updating to:
**We are currently not using github issues to track feature requests.**
We track feature requests in our feedback forum:
https://feedback.mongodb.com/forums/924283-compass
Please submit feature requests and ideas there. The feedback forum enables other people to vote on ideas so we can get a better sense of how many folks are interested in a change. You can also receive  updates when certain features and requests are implemented.
We're working on making Compass better and are interested to hear your ideas and thoughts!
Please submit bug reports and issues through our public jira project:
https://jira.mongodb.org/projects/COMPASS/summary
> chore: update feature request github issue template to link to feedback forum

- packages/compass-editor/src/ace/theme.ts
Removes margins from ace brackets reported here: https://github.com/mongodb-js/compass/pull/3620#issuecomment-1288715125
> fix(ace-editor): remove margins from ace brackets

- packages/compass-components/src/components/modals/modal-header.tsx
- packages/compass-settings/src/components/modal.spec.tsx
- packages/compass-settings/src/components/modal.tsx
- packages/compass-settings/src/components/sidebar.tsx
I missed this in https://github.com/mongodb-js/compass/pull/3582
At some point that was going to be too different from FormModal and it would still be a Modal and then I addressed some feedback and didn't check it again and it turns out it is totally broken.
So this PR just makes the settings modal a FormModal. Doesn't seem to require any special overrides.
I noticed that the settings modal's sidebar scrolls with the main area, but that was already the case before so no harm done by this PR, I think.
No release notes because the thing I'm fixing hasn't been released.
> fix(settings): Make the settings modal a form modal

- packages/compass-components/src/components/bson-value.tsx
Previously this would scroll and not ellipses. Now that we're making all horizontally scrollable areas always show their scrollbar (the scrollbars for the preview documents were hidden), areas like this with unintended scrolling are more apparent. 
**Before**
**After**
> chore(compass-aggregations): remove inline style on value

- .evergreen/functions.yml
Evergreen team [mentioned](https://mongodb.slack.com/archives/C0V896UV8/p1666965771246289?thread_ts=1666961250.563939&cid=C0V896UV8) that the errors that we are running into when signing app on macos should be fixed in the latest client. Makes sense to be to always use the latest version and not fix it to something specific, but please tell me if you think otherwise
> chore(evergreen): always use latest notary service client for signing

- packages/compass-explain-plan/src/components/explain-json/explain-json.module.less
- packages/compass-explain-plan/src/components/summary-index-stat/summary-index-stat.jsx
- packages/compass-explain-plan/src/components/summary-index-stat/summary-index-stat.module.less
- packages/compass-explain-plan/src/components/summary-stat/summary-stat.module.less
Makes it so there's better contrast for the info icons, text, and the border doesn't jump on view switch:
https://user-images.githubusercontent.com/1791149/199077323-476d2c57-a0d4-4fb0-ad95-e4f9d0906d98.mp4
| - | - |
| ![Screen Shot 2022-10-31 at 1 52 51 PM](https://user-images.githubusercontent.com/1791149/199077461-ef8f77ca-12fa-4e43-aebc-4a6bb2d33bd4.png) | ![Screen Shot 2022-10-31 at 1 55 03 PM](https://user-images.githubusercontent.com/1791149/199077474-863a00bd-58e5-4272-b4da-f6c5c25a990b.png) |
> chore(explain-plan): improve contrast, align borders and margin

- packages/compass-components/src/components/document-list/document-actions-group.tsx
- packages/compass-components/src/components/document-list/typography.ts
- packages/compass-crud/src/components/document.less
COMPASS-6229
This brings the font size and line height of fields in documents back to what it used to be and removes a bit of the overall vertical document padding to give more screen space to data. We could probably go a little further and reduce a bit of the padding and spacing on the left side of fields, however a lot of that is paired with the editing view and for this ticket we are focusing on vertical space.
| Before | After |
| - | - |
| ![Screen Shot 2022-10-31 at 2 15 07 PM](https://user-images.githubusercontent.com/1791149/199081824-2aac8ba4-e562-4b12-a570-39bacc07859b.png) | ![Screen Shot 2022-10-31 at 2 16 04 PM](https://user-images.githubusercontent.com/1791149/199081842-bdbc1efb-a06a-4d49-a494-dfd2c35ca6ac.png) |
| ![Screen Shot 2022-10-31 at 2 09 51 …
> chore(compass-crud):  improve document readability and spacing styles COMPASS-6229

- packages/compass-components/src/hooks/use-theme.tsx
- packages/compass-components/src/index.ts
- packages/compass-editor/src/ace/index.ts
- packages/compass-editor/src/ace/theme.ts
- packages/compass-editor/src/base-editor.tsx
Adds dark theme support for editor component. The theme is basically a copy of browser repl, AFAIU we are not planning to copy leafygreen highlight theme, just copy over whatever mongosh is doing for the dark without many changes. Also worth noting that slight changes between GA and this PR are already on main and coming form the palette update that was just not released yet.
Code editor:
|Light Before (current GA)|Light After|Dark Mode|
|---|---|---|
|<img width="232" alt="image" src="https://user-images.githubusercontent.com/5036933/199005927-2f79bf16-c448-4d43-9899-87111e055c3b.png">|<img width="289" alt="image" src="https://user-images.githubusercontent.com/5036933/199006093-f789e1e6-6752-4b9f-988f-a5fb90bd12d9.png">|<img width="286" alt="image" …
> feat(compass-editor): add leafygreen dark theme for the editor COMPASS-6241

- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-parser/pipeline-parser.spec.ts
- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-parser/pipeline-parser.ts
- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-parser/stage-parser.spec.ts
- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-parser/stage-parser.ts
The reason we were not attaching comments correctly is that the logic would short circuit immediately when stage is enabled, leading to some situations ending up with most of the stages ending up attached to the last stage.
This patch fixes the issue by refactoring the logic a bit, instead of attaching comments as trailing, we do it similar to the babel parser where everything is first attached as a leading comment, and only the leftover comments are passed as trailing comments to the last stage
> chore(compass-aggregations): attach disabled stages as leading comments to enabled stages COMPASS-6246

- packages/compass-connections/src/components/connecting/connecting.tsx
| - | - |
| ![Screen Shot 2022-10-31 at 2 39 10 PM](https://user-images.githubusercontent.com/1791149/199084654-2f0c6e8f-e9ea-44a7-9df5-13b54005015e.png) | ![Screen Shot 2022-10-31 at 2 42 15 PM](https://user-images.githubusercontent.com/1791149/199085268-d5b9ab95-8f5f-49c4-a2cd-f16946bae5a7.png) |
Aligned the padding to the same as the `MarketingModal` from LeafyGreen: https://www.mongodb.design/component/marketing-modal/example/
We don't use that modal as we're showing this in a non-marketting popup situation.
> chore(connections): increase bottom padding on connecting modal

- packages/compass-query-bar/src/components/query-option.tsx
COMPASS-6224
Removes some extra top padding to bring the labels in line with the values. I think I set this a while back before some of the editor styling improvements and cleanup.
How it looks now:
> chore(query-bar): align label with value COMPASS-6224

- packages/compass-e2e-tests/helpers/commands/select-stage-operator.ts
One of the tests, `supports tweaking settings of an aggregation and saving aggregation as a view`, started to flake very often in CI, seems like it's happening because sometimes the stage editor is not automatically focused after operator is being selected. To work around the issue in CI, we click the editor to manually put it in focus. This does mean that we are not testing this auto focus behavior, but this seems like an acceptable compromise to fix a very frequent flake
> chore(ci): manually focus stage editor when selecting stage operator

- packages/compass-connections/src/components/connection-list/connection-list.tsx
- packages/compass-connections/src/components/connection-list/connections-title.tsx
- packages/compass-connections/src/modules/connection-attempt.spec.ts
- packages/compass/.gitignore
- packages/compass/scripts/download-fonts.js
- packages/compass/src/app/styles/fonts.less
COMPASS-6265
Mocks: https://www.figma.com/file/vbjoD4dcisPYRYJ5RRu72k/Compass-LG?node-id=4053%3A78365
Updates the title and removes the logomark (instead of removing the title entirely https://github.com/mongodb-js/compass/pull/3673)
| current ga | before | after |
| - | - | - |
| ![Screen Shot 2022-10-31 at 4 41 25 PM](https://user-images.githubusercontent.com/1791149/199107487-64ca9de0-8bbc-4430-b45c-cbb6fdcc0f16.png) | ![Screen Shot 2022-10-31 at 4 46 23 PM](https://user-images.githubusercontent.com/1791149/199107636-b02e218e-3dc8-48f0-a633-e4a3c87d219b.png) | <img width="387" alt="Screen Shot 2022-11-02 at 12 02 33 PM" src="https://user-images.githubusercontent.com/1791149/199540700-71fc3949-f499-489b-a2fc-b25706f56133.png"> |
> chore(connections): update sidebar title, add mongodb font COMPASS-6265

- .gitignore
- packages/compass/.npmrc
- packages/hadron-build/commands/release.js
This is not allowed by npm workspaces, can lead to undefined behavior and causes this annoying message to always stick at the end of any command run with npm
> chore(mongodb-compass): remove npmrc from compass source and copy on build from root

- packages/compass-components/package.json
- packages/compass-components/src/components/workspace-container.tsx
Removes slight flicker of the workspace container shadow when switching between tabs
> chore(compass-components): remove shadow flicker

- packages/compass-crud/src/components/ag-grid-dist.css
- packages/compass-crud/src/components/ag-grid.less
- packages/compass-crud/src/components/document-table-view.jsx
- packages/compass-crud/src/components/table-view-cell.less
- set `user-select: none` on column headers
- add a visual indication that the column can be dragged
- set a `text` cursor on editable table cells
- setup cell editor to display on single click (more idiomatic and fixes other unwanted selections on double-click)
- prevent columns from disappearing when dragged out of the table
https://user-images.githubusercontent.com/334881/199733611-6a6b54e6-401c-47a6-bfba-45f4e4795d1a.mp4
> fix: improve table view interactions

- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.spec.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-menus.tsx
With new text editor, we don't need a pipeline as text as a separate option anymore (rest of the code clean up we will do when the flag is flipped)
> chore(compass-aggregations): do not show pipeline as text option when text editor enabled COMPASS-6170

- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
Just so that they take a bit less space. Also for now we decided that "Stages" is just generally a better name than "Builder UI" for the stages editor (but this might change in the future)
> chore(compass-aggregation): use shorter action labels COMPASS-6264

- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/index.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-menus.tsx
- packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
Small bug in the initial implementation: when stage is toggled, network errors should be cleaned up as they are a side-effect of the preview functionality, this also could lead a weird state where you'd not be able to do anything with the pipeline because network errors were one of the states affecting actions disabled state.
As part of a fix in addition to cleaning up the state correctly, we want to make validation less strict: we handle server errors when running, exporting, or explaining a pipeline, so only syntax errors, that prevent us from generating the pipeline to run, should be accounted for when disabling these actions
> chore(compass-aggregations): clear network errors on stage toggle; do not disable actions on network errors COMPASS-6250

- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-builder.spec.ts
- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-builder.ts
- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-preview-manager.ts
- packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.spec.ts
- packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
- packages/compass-aggregations/src/modules/pipeline-builder/text-editor-pipeline.spec.ts
- packages/compass-aggregations/src/modules/pipeline-builder/text-editor-pipeline.ts
A race condition case we didn't account for in the initial implementation. Added a test to cover this case too
> chore(compass-aggregations): cancel preview fetch for pipeline / stages even if we don't run the pipeline COMPASS-6278

- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.spec.tsx
- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-builder.spec.ts
- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-builder.ts
- packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
- packages/compass-e2e-tests/tests/instance-my-queries-tab.test.ts
As part of the refactoring pipeline builder logic we made validation and parsing of the pipeline stricter to avoid confusing corner cases in UI that were present in the old implementation (e.g., stages with errors would be treated like empty objects when exporting to language giving weird export results), this had an annoying side-effect: default pipeline we had is a broken pipeline which means that you are starting with the ui in the "warning" state.
We decided that a reasonable solution to this will be just not to have default pipeline broken and have it as empty pipeline, it means that you will need to add first stage manually, but we have two CTAs on the screen that lead you to adding a new stage
> chore(compass-aggregations): change default pipeline to empty pipeline instead of a broken pipeline COMPASS-6263

- packages/compass-aggregations/src/modules/pipeline-builder/text-editor-output-stage.ts
- packages/compass-aggregations/src/modules/pipeline-builder/text-editor-pipeline.ts
Otherwise you can end up in weird state where text editor pipeline always shows you an error
> chore(compass-aggregation): clean up text editor out stage slice when editors are switched back and forth COMPASS-6274

- packages/compass-query-bar/src/components/option-editor.tsx
- packages/compass-query-bar/src/components/query-bar.spec.tsx
Reverts https://github.com/mongodb-js/compass/pull/3351 as that was impacting the aggregation editors as well.
> chore(query-bar): revert tab behavior in editor

- packages/compass-preferences-model/src/preferences.spec.ts
- packages/compass-preferences-model/src/preferences.ts
Bug fixes to account for the fact that not only explicitly updating the value of a preference can change its value, but also fetching preferences from disk, if another Compass instance has concurrently modified the preferences model file.
> fix(compass-preferences-model): account for changes in preferences while fetching

- packages/compass-import-export/src/components/export-field/export-field.jsx
- packages/compass-import-export/src/components/export-select-fields/export-select-fields.jsx
Some commit broke the tooltip, thought we may as well implement the new designs
> chore: fix export modal info

- packages/compass-settings/src/components/settings/features.spec.tsx
- packages/compass-settings/src/components/settings/features.tsx
Expose protectConnectionStrings in settings UI. Follow up PR of [COMPASS-6066](https://jira.mongodb.org/browse/COMPASS-6066).
> feat: expose protectConnectionStrings in settings UI COMPASS-6262

- packages/compass-aggregations/src/utils/stage.js
- packages/compass-aggregations/src/utils/stage.spec.js
fix aggregations error. when running an empty pipeline, the plugin throws an error.
> fix(aggregations): empty stage

- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-parser/stage-parser.ts
- packages/compass-aggregations/src/modules/pipeline-builder/stage.spec.ts
We are copying comments to the stage value, but not cleaning them up from the node, which leads to comments being duplicated when converting stage to string
(base is #3770 because this uses refactored `Stage.toString` in tests)
> chore(compass-aggregations): fix duplicated trailing comments in stages

- packages/compass-crud/src/components/cell-editor.spec.jsx
- packages/hadron-document/src/element.ts
- packages/hadron-document/test/element.test.ts
COMPASS-6160
Fixes a bug with updating a field in a document named `_id` that isn't the document's top level `_id`. Also noticed that we don't hide some of the other editing controls like type changing which can lead to some wonky behavior. That would be a different fix, that issue and this one that's being fixed here have both present in Compass for a while, not new.
Before:
After:
https://user-images.githubusercontent.com/1791149/201825536-34fcd68c-acd1-4687-b28d-25bbd80d61f8.mp4
> fix(hadron-document): check for root level when deciding if `_id` key is editable COMPASS-6160

- packages/compass-editor/src/ace/theme.ts
|Before|After|
|---|---|
|<img width="184" alt="image" src="https://user-images.githubusercontent.com/5036933/201687741-4722e3a5-854a-4051-83b1-721de57801e4.png">|<img width="195" alt="image" src="https://user-images.githubusercontent.com/5036933/201685031-435c6eaa-e623-42db-9b55-5957c6d18ce1.png">|
|<img width="184" alt="image" src="https://user-images.githubusercontent.com/5036933/201687914-fbdfd978-62f8-477e-a4a0-feb55ead2a81.png">|<img width="179" alt="image" src="https://user-images.githubusercontent.com/5036933/201686850-00c533fd-4ef6-494f-b7c9-0d3c9e774092.png">|
> chore(compass-editor): use leafygreen icon for error annotations

- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-builder.ts
- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-parser/stage-parser.spec.ts
- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-parser/stage-parser.ts
- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-parser/utils.ts
- packages/compass-aggregations/src/modules/pipeline-builder/stage.ts
- packages/compass-aggregations/src/utils/stage.js
Follow-up to [this thread](https://mongodb.slack.com/archives/G2L10JAV7/p1668687407278799). I foolishly removed `parseEJSON` for the assertion logic for stages at some point because I totally missed that it indeed does a bunch of additional validation on AST. I think I would prefer to somehow be able to export this logic from the package in addition to the actual parsing, but for now I'm just bringing the check back with some additional improvements to the error messaging
> fix(compass-aggregations): stricter validation and better error messages for stages

- packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
See [this thread](https://mongodb.slack.com/archives/G2L10JAV7/p1668795567516309) for details. Probably easier to check the changes with [whitespace changes ignored](https://github.com/mongodb-js/compass/pull/3788/files?diff=split&w=1)
> fix(e2e): wait for syntax error and always reset maxTimeMS at the end

- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-builder.spec.ts
- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-builder.ts
Small drive-by that I spotted when working on a previous PR: `parseEJSON` will be able to parse different values even with the ast validation it is doing, this adds additional check to make sure we are only storing pipelines, and nothing else
> fix(compass-aggregations): check that parsed pipeline is an array

- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-menus.tsx
- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-builder.ts
- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-mode.ts
- packages/compass-aggregations/src/modules/saved-pipeline.ts
- packages/compass-aggregations/src/utils/pipeline-storage.spec.js
- packages/compass-aggregations/src/utils/pipeline-storage.ts
- packages/compass-components/src/hooks/use-toast.tsx
- packages/compass-components/src/index.ts
We initially didn't want to allow this because it leads to weird behavior when loading the pipeline, but after some discussions decided that it would be okay to do. In case when loaded pipeline contains syntax errors, we will force users in the text editor mode as we can't parse invalid source to stages. And to avoid making the editor type switch more surprising, we will show a toast indicating that the loaded pipeline contained errors that didn't allow us to parse it:
> chore(compass-aggregation): allow to save pipelines with syntax errors

- packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-editor.tsx
- packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-preview.tsx
- packages/compass-aggregations/src/components/pipeline/modals/import-pipeline.spec.jsx
- packages/compass-crud/src/components/json-editor.jsx
- packages/compass-editor/src/ace/theme.ts
- packages/compass-editor/src/base-editor.tsx
- packages/compass-editor/src/index.ts
- packages/compass-editor/src/inline-editor.tsx
- packages/compass-editor/src/multiline-editor.tsx
- packages/compass-schema-validation/src/components/validation-editor/validation-editor.jsx
Visible by default on focus / hover for all editors, but tell me if you think we should hide it somewhere
> chore(compass-editor): add copy and format buttons to multiline ace editors

- packages/compass-import-export/package.json
- packages/compass-import-export/src/modules/export.ts
- packages/compass-import-export/src/modules/import.ts
- packages/compass-import-export/src/utils/bson-csv.js
Two things:
1) We weren't only updating the progress every 250ms like the code was asking for.
2) There was a flood of debug() calls that killed the dev console at least in development.
This speeds up exports in development on my local machine by at least 1000x.
> fix(export): Speed up export COMPASS-6332

- packages/compass-schema/src/components/value-bubble/value-bubble.jsx
I confirmed with Claudia and this is contrasty enough now.
> fix(schema): increase compass schema value bubble contrast COMPASS-6230

- packages/compass-preferences-model/src/global-config.ts
- packages/compass-preferences-model/src/index.ts
- packages/compass-preferences-model/src/preferences.ts
- packages/compass/src/main/index.ts
The original config file suggested including a file in the packages themselves. However, this is hard for a number of reasons; for example, our .deb and .rpm generators do not provide options for specifying configuration files, and if they did, config files would conflict between the different variants of Compass. For the .zip distribution, we ship the Compass executable at the top level of the .zip, meaning that it is impossible to actually write to the path where Compass expects the configuration file just by unpacking the .zip.
As a lightweight alternative, Compass now supports a new `--show-example-config` command line flag, and refers to it, together with a full command showing its usage, in the `--help` output.
> feat: add --show-example-config flag COMPASS-6084

- packages/compass-indexes/src/components/indexes-table/usage-field.spec.tsx
- packages/compass-indexes/src/components/indexes-table/usage-field.tsx
In the tooltip, "commandor" is displayed. Should be "command or". Fixed it in all the concerned files.
Thank you
> fix(compass-indexes): fix typo on Indexes screen

- packages/compass-preferences-model/src/renderer-ipc.ts
The following sequence of events is currently possible:
- A preference value is changed in the main process
- The main process informs the renderer about it
- Consequentially, the renderer starts to refresh its cache
- Something (X) running in the renderer gets the preference value via `getPreferences()` and then listens for changes using `onPreferenceValueChanged()` (as e.g. the React preference utils do)
- The cache refresh operation finishes and updates the cache
X then uses an outdated value of the preference and is not informed about the change in value.
Fix this by keeping track of active cache refresh operations, and if there are any, call the newly installed listener once with the fresh value.
> fix(compass-preferences-model): avoid race condition when installing listeners

- .evergreen/functions.yml
YAML anchors will do a shallow merge, not a deep one, but our code uses then assuming that a deep merge will happen (and it is for now, until evergreen updates their yaml parser version)
See COMPASS-6200 for a more detailed example
> chore(ci): fix yaml anchor usage in evergreen config COMPASS-6200

- packages/compass-query-history/src/components/toolbar/toolbar.tsx
| - | - |
| ![Screen Shot 2022-12-07 at 1 17 39 PM](https://user-images.githubusercontent.com/1791149/206269246-efd20d54-72f5-4dab-be01-59ca8db31231.png) | <img width="405" alt="Screen Shot 2022-12-07 at 1 46 15 PM" src="https://user-images.githubusercontent.com/1791149/206269260-343e438e-8edf-46d9-8be1-97cdce9c1cdc.png"> |
> chore(compass-query-history): update segmented control icon usage

- packages/compass-components/src/hooks/use-theme.tsx
- packages/compass-components/src/index.ts
browser-repl is using `ThemeProvider`, so it can’t be removed just yet.
> fix(compass-components): bring back ThemeProvider for browser-repl

- packages/compass-editor/src/ace/theme.ts
- packages/compass-editor/src/base-editor.tsx
- packages/compass-editor/src/multiline-editor.tsx
- packages/compass/src/app/styles/index.less
This pr makes the scrollbar in editors not overlap the content. I'm not quite sure on the reasoning why we need the global styles here to achieve that. I'd like to get to the bottom of it, but after an hour or two I wasn't sure so I figured getting the fix in would probably be best then I can look at why exactly.
The other fix included in this pr is for the `min-height` of the `Editor` to inherit the min-height from it's container. This is important for letting users click anywhere inside of an editor container to focus the editor. In recent, unreleased changes we lost that ability as we added another container for the editor. Marking this pr a chore as these are fixes for unreleased changes.
I don't think this is necessarily the cleanest solution for this issue, so I'm happy for any …
> chore(compass-editor): fix scrollbars, make editors inherit min-height

- packages/compass-components/src/components/leafygreen.tsx
- packages/compass-crud/src/components/document-json-view.less
`Table`, `Modal`, and `Code` do not currently pull the theme from the LeafyGreen Provider.  In new versions they do pull from the provider, however there's a bug with the language switcher in the Code component, so we're not updating yet. This pr makes it so these components receive the theme from Compass.
[LG-2703](https://jira.mongodb.org/browse/LG-2703)
> chore(compass-components): add darkMode to LeafyGreen components that do not pull from provider

- packages/compass-aggregations/src/modules/import-pipeline.js
- packages/compass-aggregations/src/modules/pipeline-builder/text-editor-pipeline.spec.ts
- packages/compass-aggregations/src/modules/pipeline-builder/text-editor-pipeline.ts
Currently we are not running the preview for pipeline if it has been run the last time. We do this check when user toggles to As Text mode or toggles Auto Preview, which leaves preview in a confused state.
In this PR i am performing this check to only pipeline text change
> fix(aggregations): run preview on pipeline value change COMPASS-6353

- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-builder.spec.ts
- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-builder.ts
This removes the error and allows to run / export pipeline when input in the text editor is empty
> chore(compass-aggregations): treat empty pipeline source as empty array COMPASS-6368

- packages/compass-schema/src/components/field/field.jsx
Not in ga or beta.
Fixes an error that occurs when opening a nested field:
Definitely wouldn't happen if this was typescript 😅  - currently updating schema when removing css grid, so I'll typescript this file on that branch.
> fix(compass-schema): opening nested field schema

- packages/compass-crud/src/components/table-view/add-field-button.tsx
This broke recently in the typescript conversion where we accidentally gained an early return.
> fix(crud): Fix adding a field in the CRUD table view COMPASS-6359

- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-stages.spec.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-stages.tsx
- packages/compass-aggregations/src/modules/pipeline-builder/builder-helpers.spec.ts
- packages/compass-aggregations/src/modules/pipeline-builder/builder-helpers.ts
fix(aggregations): hide add stage in toolbar when there's already a stage COMPASS-6373
> fix(aggregations): hide add stage in toolbar COMPASS-6373

- packages/compass-components/src/hooks/use-effect-on-change.ts
- packages/compass-components/src/hooks/use-theme.tsx
- packages/compass-components/src/index.ts
- packages/compass-crud/package.json
- packages/compass-crud/src/components/document-json-view.less
- packages/compass-crud/src/components/document-json-view.tsx
- packages/compass-crud/src/components/json-editor.tsx
- packages/compass-e2e-tests/helpers/commands/codemirror.ts
- packages/compass-e2e-tests/helpers/commands/index.ts
- packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
- packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
- packages/compass-e2e-tests/tests/in-use-encryption.test.ts
- packages/compass-editor/package.json
- packages/compass-editor/src/index.ts
- packages/compass-editor/src/json-editor.tsx
- packages/compass-saved-aggregations-queries/src/components/aggregations-queries-list.tsx
_Edit from @gribnoysup:_
Recent style updates caused a major performance regression in `ace-editor` mounting behavior: the way ace calculates line height and scroll size always causes a reflow on the page (browser relayouts all elements to make sure that user code gets exact style value at the moment of requesting) for every mounted editor. This was an issue before but with the recent layout and style changes the issue became even more noticeable. Ace editor is great when it's the only thing on the screen, but as we are rendering 20 editors at once in the JSON view, this is a big bottleneck.
We did a quick spike trying out `codemirror` instead, and the performance boost was easily noticeable. Codemirror minimizes the amount of code that requires a reflow and as its unavoidable, seems like …
> fix: speed up document json view COMPASS-6365

- packages/compass-crud/src/components/crud-toolbar.spec.tsx
- packages/compass-crud/src/components/crud-toolbar.tsx
Enable paginate next button when count of documents is unknown so users can paginate to the next page
> fix(crud): enable next page button when count is unknown COMPASS-6340

- packages/compass-crud/src/components/document-json-view.tsx
This adds overflow: 'hidden' to the keyline card. Alternatively we could duplicate the border radius on the data-testid="editable-json" element. Or try and make everything inside there transparent rather than white.
> fix(crud): fix json editor hanging out over the rounded corners

- packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/index.tsx
- packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-editor.tsx
- packages/compass-aggregations/src/components/settings/settings.tsx
- packages/compass-components/src/components/cancel-loader.tsx
| - | - |
| <img width="323" alt="Screen Shot 2023-01-04 at 9 51 02 AM" src="https://user-images.githubusercontent.com/1791149/210581765-5407a987-ffa4-412e-a33f-253a09c41cba.png"> | <img width="202" alt="Screen Shot 2023-01-04 at 9 41 23 AM" src="https://user-images.githubusercontent.com/1791149/210581790-33fc0d69-ddaf-48d2-89d6-80c676db8b4e.png"> |
| <img width="1177" alt="Screen Shot 2023-01-04 at 9 50 51 AM" src="https://user-images.githubusercontent.com/1791149/210581807-dfb6ad2c-7d8e-40f0-8982-6e959a33bccb.png"> | <img width="1172" alt="Screen Shot 2023-01-04 at 9 49 39 AM" src="https://user-images.githubusercontent.com/1791149/210581823-8dc30626-f4de-42ec-afe0-9c9e021ace8d.png"> |
> chore(compass-aggregations): add darkMode support for aggregation settings, pipeline as text background

- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.spec.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.tsx
Tracked internally in [CLOUDP-143514](https://jira.mongodb.org/browse/CLOUDP-143514)
When running Data Explorer, the collation and maxTime options are not supported. Can we hide these elements when running in `isAtlasDeployed` mode?
From [this comment](https://github.com/mongodb-js/compass/blob/fa13b993ef5bb22795a07acfe66c7e59bbad53a4/packages/compass-aggregations/src/stores/store.js#L87), I see that  "isAtlasDeployed is only used by mms to change some behaviour in the aggregations plugin"
> Hide aggregation options when running in Atlas Mode

- packages/compass-editor/package.json
- packages/compass-editor/src/json-editor.tsx
| - | - |
| <img width="318" alt="Screen Shot 2023-01-05 at 8 38 17 PM" src="https://user-images.githubusercontent.com/1791149/210912185-222d6504-0ac8-4749-b221-593224b7d931.png"> | <img width="337" alt="Screen Shot 2023-01-05 at 8 35 57 PM" src="https://user-images.githubusercontent.com/1791149/210912200-7f51f149-33d5-4859-9294-91a8851654b3.png"> |
> fix(compass-editor): use semitransparent color for active line background color

- packages/compass-shell/src/components/compass-shell/compass-shell.jsx
COMPASS-6411
| - | - |
| <img width="925" alt="Screen Shot 2023-01-06 at 12 01 48 PM" src="https://user-images.githubusercontent.com/1791149/211061254-a9babb92-8e13-4e55-9e5c-5d67183415c8.png"> | <img width="960" alt="Screen Shot 2023-01-06 at 12 01 28 PM" src="https://user-images.githubusercontent.com/1791149/211061290-d19499a3-4986-4e4c-897f-38f8ca60a429.png"> |
> fix(compass-shell): set width of compass shell to avoid overflow COMPASS-6411

- packages/compass-settings/src/components/settings/theme.tsx
- packages/compass-settings/src/components/sidebar.tsx
> fix(settings): tweak settings modal text alignment COMPASS-6413 

- packages/compass-e2e-tests/tests/auto-connect.test.ts
`ECONNRESET` seems to be a reasonable alternative error that can occur when failure to connect is the expected outcome.
This should make CI a bit less flaky.
> fix(compass-e2e-tests): make auto-connect test less flaky on Windows

- .evergreen/buildvariants.in.yml
- .evergreen/buildvariants.yml
- .evergreen/config.json
- .evergreen/functions.yml
- .evergreen/tasks.in.yml
- .evergreen/tasks.yml
- .evergreen/template-yml.js
- package.json
Usually around release time we will have issues with gui-enabled macos machines being overloaded with tasks, making release times long and hard to predict. This patch restructures the evergreen configuration to run tasks that require GUI sessions and tasks that don't on separate machines (the way it's implemented is sort of generic, but this only applies to mac machines) which should make our ci pipeline faster.
This change uses buildvariant level task overrides for `run_on` to achieve that (thanks @addaleax for the info about this!) which kinda flips the way we generated our variants before and so the patch might be a bit hard to review, I am happy to provide any additional context on how it's generated now if needed.
The patch I'm checking this with in evergreen [is still …
> chore(ci): restructure config to be able to run tasks that require gui on separate machines COMPASS-6275

- packages/hadron-document/src/utils.ts
- packages/hadron-document/test/document.test.ts
Some reference:
https://github.com/mongodb/specifications/blob/master/source/extended-json.rst#datetime
https://github.com/mongodb/specifications/blob/master/source/extended-json.rst#conversion-table
https://github.com/mongodb/js-bson/blob/35bb2a279343439e1306a0eeb8d65d1abf910929/test/node/specs/bson-corpus/datetime.json#L9-L10
> fix(crud): If a date is in the safe range, go with relaxed EJSON rather than canonical COMPASS-5744

- .evergreen/buildvariants.in.yml
- .evergreen/buildvariants.yml
- .evergreen/config.json
- .evergreen/print-compass-env.sh
- .evergreen/tasks.yml
- .evergreen/template-yml.js
- packages/compass-e2e-tests/tests/logging.test.ts
This patch updates all Ubuntu machines we are using in evergreen CI to 20.04 distro.
This allows us to enable e2e tests for mongodb 5 and 6 on Ubuntu, but also required me to disable 4.0 and 4.4 enterprise e2e tests at the same time. Seems like mongodb toolchain might be missing a dependency required for mongodb to work on this version of Ubuntu correctly, it [fails](https://spruce.mongodb.com/task/10gen_compass_main_ubuntu_test_packaged_app_40x_enterprise_patch_c4b6f0d859d47fb2b0f163fb5b051bdd974d73f0_63beda740305b96865a1d8e6_23_01_11_15_49_26/logs?execution=0) with `error while loading shared libraries: libnetsnmpmibs.so.30: cannot open shared object file: No such file or directory`. This seems like an okay compromise to me for now and we can figure out how to deal with this later, but …
> chore(ci): update ubuntu machines to 20.04 COMPASS-5637

- .github/PULL_REQUEST_TEMPLATE.md
- packages/compass-crud/src/components/table-view/cell-editor.tsx
Move code from the legacy [UNSAFE_componentWillMount](https://reactjs.org/docs/react-component.html#unsafe_componentwillmount) to the constructor.
> refactor: remove UNSAFE_ method in cell-editor COMPASS-6138

- packages/compass-crud/src/components/insert-document-dialog.tsx
Move code from `UNSAFE_componentWillReceiveProps` to `componentDidUpdate` and clean up state, because the `crud-store` operates with the `'modifying' | 'error'` state and it is confusing to have the `'progress' | 'error'` in the component.
> refactor: remove UNSAFE_ method in insert-document-dialog COMPASS-6139

- packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-editor.tsx
- packages/compass-aggregations/src/components/focus-mode/focus-mode.spec.tsx
- packages/compass-aggregations/src/components/focus-mode/focus-mode.tsx
- packages/compass-aggregations/src/components/stage-editor-toolbar/stage-editor-toolbar.tsx
- packages/compass-aggregations/src/components/stage-editor/stage-editor.jsx
- packages/compass-aggregations/src/components/stage-preview-toolbar/stage-preview-toolbar.tsx
- packages/compass-aggregations/src/components/stage.tsx
- packages/compass-aggregations/src/modules/focus-mode.ts
When preview is disabled, we hide the input and output documents in the preview mode:
> chore(compass-aggregations): hide preview in focus mode when auto preview is disabled

- packages/compass-import-export/src/import/guess-filetype.spec.ts
- packages/compass-import-export/src/import/guess-filetype.ts
- packages/compass-import-export/src/import/list-csv-fields.spec.ts
- packages/compass-import-export/src/import/list-csv-fields.ts
- packages/compass-import-export/src/utils/constants.ts
- packages/compass-import-export/test/csv/array.csv
- packages/compass-import-export/test/csv/complex.csv
- packages/compass-import-export/test/csv/object.csv
- packages/compass-import-export/test/csv/objectarray.csv
- packages/compass-import-export/test/fixtures.js
This is what we'll use to calculate the list of columns used in the table at the bottom of the CSV import modal. ie. each one will have a checkbox to select it and a selectbox where you can select the type. This displays while we still calculate the preview and try and autodetect the field types.
The only "tricky" bit is that an array becomes just one field and you don't select "array" as the type, but the type of the actual simple value in there. ie. it is an array of strings or an array of numbers. Example: foo[0],foo[1] becomes just foo.
Similar thing for objects, but that's implicitly handled by the structure of the CSV file. ie. { foo: { bar: 1 } } would export as the field foo.bar which is one of the fields you can assign a type to and it will probably autodetect as type int.
This …
> Feat(import): Function to list the fields contained in a CSV file's header row COMPASS-6422

- packages/compass-aggregations/src/components/focus-mode/focus-mode-modal-header.tsx
- packages/compass-aggregations/src/components/focus-mode/focus-mode.tsx
- packages/compass-aggregations/src/modules/focus-mode.ts
Adds header and related functionality for the "focus mode":
one thing I am skipping in this PR is adding grayed out overlay for a disabled stage as this will conflict with other PRs we have open at the moment, we can add it later
> chore(compass-aggregations): add focus mode modal header COMPASS-6389

- packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-editor.tsx
- packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-preview.tsx
- packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-preview.tsx
- packages/compass-aggregations/src/components/stage-editor/stage-editor.jsx
- packages/compass-aggregations/src/components/stage-preview/index.tsx
- packages/compass-aggregations/src/components/stage-toolbar/option-menu.tsx
- packages/compass-aggregations/src/components/stage.tsx
- packages/compass-aggregations/src/utils/stage.js
- check the stage before assuming that the error indicates atlas only stage
- add new error codes from mongodb 6.2
- small misc fixes to the styles of the stage editor:
|Before|After|
|---|---|
|<img width="400" alt="image" src="https://user-images.githubusercontent.com/5036933/215449898-9fcdffc0-ae36-4418-aae4-b1dfbde622db.png">|<img width="400" alt="image" src="https://user-images.githubusercontent.com/5036933/215449558-7afb9f43-9f74-4895-8fb9-1f84d2c0ed2d.png">|
> fix(compass-aggregations): fix atlas only server error detection

- packages/compass/package.json
- packages/hadron-build/commands/release.js
- packages/hadron-build/package.json
This should resolve this issue where FLE tests broke because the version we are installing with the packaged application is not matching our root package lock. The approach here is more lightweight than [the one we took before](https://github.com/mongodb-js/compass/pull/2369) where we would try to generate a package-lock manually tracking all the dependencies from the generated package tree.
While this means that it is still possible that some transitive dependency will cause issues, the amount of direct dependencies in Compass is small (and those are mostly native dependencies with very small amount of deps) and the amount of logic we need to introduce is way less, so this seems like a reasonable compromise to me.
Also worth noting that this is a kind of a known issue with workspaces, …
> fix(hadron-build): set exact versions for dependencies in compass when packaging

- .evergreen/buildvariants.yml
- .evergreen/config.json
Missed that the failures there were not related to FLE when adding this in #4013, will disable for now just so we can get CI green and will investigate (based on failures, doesn't look like mongodb server is running at all, even though `mongodb-runner` reports that it started successfully)
> chore(ci): disable latest alpha e2e tests on rhel

- packages/compass-editor/package.json
We use it for code formatting in the editor, so it's a prod dependency
> chore(compass-editor): prettier is a prod dependency

- packages/compass-editor/src/index.ts
- packages/compass-editor/src/json-editor.tsx
- packages/compass-editor/src/syntax-highlight.tsx
See [thread](https://mongodb.slack.com/archives/GDTJXPHD0/p1675324013691499) for details. The workaround for the leafygreen Code component styles we added in browser-repl stopped working again, so instead of doing more patches, we decided to switch to using codemirror for the highlighted code output as the styles of this component is completely in our control and performance-wise it is better than Code component (which should help with issues like COMPASS-5883)
> chore(compass-editor): add a syntax highlight component to compass-editor COMPASS-6483

- .husky/pre-commit
- package.json
- scripts/precommit.js
This seems to be something that is tripping up a lot of people when changes are pushed to remote recently (probably because more and more packages are using prettier now) and so as we discussed before I am adding some precommit hooks to deal with this.
I am limiting this only to prettier as it is fast enough to run against only changed files and applied changes can be easily re-staged without any additional user input.
I think adding ts check and eslint to either commit or push hooks while valuable, might add a bit too much friction to the commit process and so those are left out for now. We can definitely discuss this and adjust accordingly later.
> chore(scripts): set up precommit hook to format changed files before commit

- packages/compass-e2e-tests/helpers/selectors.ts
- packages/compass-e2e-tests/tests/collection-validation-tab.test.ts
- packages/compass-schema-validation/src/components/compass-schema-validation/compass-schema-validation.jsx
- packages/compass-schema-validation/src/components/document-preview/document-preview.jsx
- packages/compass-schema-validation/src/components/document-preview/document-preview.spec.jsx
- packages/compass-schema-validation/src/components/document-preview/index.js
- packages/compass-schema-validation/src/components/loading-overlay.tsx
- packages/compass-schema-validation/src/components/sample-documents/sample-documents.jsx
- packages/compass-schema-validation/src/components/sample-documents/sample-documents.spec.jsx
- packages/compass-schema-validation/src/components/validation-editor/validation-editor.jsx
- packages/compass-schema-validation/src/components/validation-editor/validation-editor.spec.jsx
- packages/compass-schema-validation/src/components/validation-states/validation-states.jsx
- packages/compass-schema-validation/src/components/validation-states/validation-states.spec.jsx
- packages/compass-schema-validation/src/modules/sample-documents.js
- packages/compass-schema-validation/src/modules/sample-documents.spec.js
- packages/compass-schema-validation/src/modules/validation.js
- packages/compass-schema-validation/src/stores/store.spec.js
~~This PR removes the document count while fetching sample documents as it was not necessary to find the sample of documents matching and not matching the schema~~
This PR changes the way sample documents are fetched for a provided / modified validator. Changes are summarised below:
- instead of fetching the sample documents for a set / default validator on tab load or on every change, we now provide users with a button to explicitly request a sample document.
- on change of validator, the documents are to be explicitly requested again.
- we now use `$sample` with a sample size of `10000` as our sample space to match and find documents that could / could not match the set validator.
> fix(compass-schema-validation): optimises the opening of tab

- scripts/precommit.js
Small fix to avoid script failing when unsupported files are passed to it
> chore(scripts): ignore unsupported files when reformatting

- packages/compass-preferences-model/src/preferences.ts
- packages/compass-settings/src/components/settings/featureflags.tsx
COMPASS-6499
Nice new doc on these https://github.com/10gen/devtools-internal-docs/blob/main/technical/compass/feature-flags.md
> chore(compass-preferences-model): add new import and export feature flags, currently unused COMPASS-6499

- packages/compass-aggregations/src/components/add-stage/add-stage.tsx
- packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-editor.tsx
- packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-preview.spec.tsx
- packages/compass-aggregations/src/components/focus-mode/focus-mode.tsx
- packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-stages-preview.tsx
- packages/compass-aggregations/src/components/stage-preview/index.spec.tsx
- packages/compass-aggregations/src/components/stage-preview/output-stage-preview.tsx
- packages/compass-aggregations/src/constants.js
- packages/compass-aggregations/src/utils/stage.js
Remove unwanted space in the focus mode header (which shows up when a stage is added).
In this PR, I also added the link to pipeline documentation when the stage operator is not selected yet in focus mode.
> fixes(focus-mode): ui fixes COMPASS-6507

- packages/compass-e2e-tests/helpers/commands/add-collection.ts
- packages/compass-e2e-tests/helpers/selectors.ts
- packages/compass-e2e-tests/tests/database-collections-tab.test.ts
- packages/databases-collections/src/components/collection-fields/collection-fields.jsx
- packages/databases-collections/src/components/collection-fields/has-flexible-bucket-config-support.spec.ts
- packages/databases-collections/src/components/collection-fields/has-flexible-bucket-config-support.ts
- packages/databases-collections/src/components/collection-fields/time-series-fields.jsx
- packages/databases-collections/src/components/collection-fields/time-series-fields.spec.jsx
COMPASS-6491
---
This PR adds fields for configurable options newly introduced in [SERVER-67598](https://jira.mongodb.org/browse/SERVER-67598) namely:
- bucketMaxSpanSeconds
- bucketRoundingSeconds
These options are not visible for connections that are not to server version `< 6.3.0-alpha`. These new parameters (`bucketMaxSpanSeconds`, `bucketRoundingSeconds`) and `granularity` are supposed to be mutually exclusive which is what we convey with the modified description for these fields.
Additionally there is a behaviour modification on existing work:
- `granularity` field which earlier could not be deselected, can now be deselected. Reason behind this change is that `granularity` is an optional field.
> feat(databases-collections): flexi bucket opts for Timeseries

- packages/compass-editor/src/json-editor.tsx
Somehow missed it in the initial implementation: the way font family is applied by the codemirror editor requires us to also set it on the scroller container to override the default.
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/5036933/218994341-dc78641c-4aef-43f4-9815-e63e1b737378.png)|![image](https://user-images.githubusercontent.com/5036933/218994187-79b7af9b-aa2e-4059-a357-d89fcadfb83c.png)|
> chore(compass-editor): fix font in json editor

- packages/hadron-document/src/element.ts
- packages/hadron-document/test/element.test.ts
When cancelling from editing a field in a document that's non-existent, the compass throws an error.
> fix(hardon-document): cancel edit on non-existent field COMPASS-6505

- packages/compass-e2e-tests/helpers/compass.ts
- packages/compass/src/main/auto-update-manager.spec.ts
- packages/compass/src/main/auto-update-manager.ts
Same as https://github.com/mongodb-js/compass/pull/4073 but explicitly calling a method that will throw instead of yielding to flow controller
> fix(mongodb-compass): halt autoupdater on application exit to prevent logger crashing COMPASS-6051

- packages/compass/src/main/logging.spec.ts
- packages/compass/src/main/logging.ts
Second part of COMPASS-6051: we want to be a bit less strict about writing to log file in compass after `stream.end` was called as making sure that everything is perfectly handling application exit across processes is a bit tricky and we don't want to hard crash compass in that case
> chore(mongodb-compass): ignore write after end errors in log writer COMPASS-6051

- packages/compass-import-export/src/import/analyze-csv-fields.spec.ts
- packages/compass-import-export/src/import/analyze-csv-fields.ts
- packages/compass-import-export/src/import/import-csv.spec.ts
- packages/compass-import-export/src/import/import-csv.ts
- packages/compass-import-export/src/import/import-json.spec.ts
- packages/compass-import-export/src/import/import-json.ts
- packages/compass-import-export/src/utils/byte-counter.ts
- packages/compass-import-export/src/utils/utf8-validator.ts
analyzeCSVFields(), importCSV() and importJSON() all have an optional progressCallback. It already had one parameter which is the number of docs processed. It now gains a second parameter which is the number of bytes processed. This (in combination with the file size) makes it possible to show a progress bar for both CSV and JSON files.
The progressCallback fires before it actually writes to the db and regardless of parse or db errors. This is intentional because it relates to how much of the file has been processed. Backpressure kicks in and it doesn't get too far ahead anyway since the whole pipeline will have to wait for batches to be written anyway. ie. there will be a pause after every 1000 docs just like before.
Technically due to buffering the bytes can get slightly ahead of the …
> feat(import): progressCallback(numDocs, numBytes) COMPASS-6528

- packages/compass-import-export/src/import/import-csv.ts
- packages/compass-import-export/src/import/import-json.ts
- packages/compass-import-export/src/utils/import.ts
By making the output param (the log file) optional we can more easily integrate the new functions with the existing UI. It also gives us more options for making this work in DE.
> chore(import): make the output param (log file) for importCSV and importJSON optional COMPASS-6519 COMPASS-6520

- packages/compass-editor/src/json-editor.tsx
Two small improvements to the codemirror-based json editor that I did while looking into how to better split work for replacing ace editor with codemirror
- Refactor compartments (codemirror way to handle editor config changes) handling: add a special reach hook to handle all the compartment update logic in one place as it was handled similarly for many extensions and we will add some more in the future, so seemed like a good idea to clean it up a little
- Add commands and keybindings for copying and formatting: we have the same in base editor and while looking a bit more into how keybindings work in codemirror (as we will need to provide custom ones at least for shell) I added these to try it out and so there is no point not to commit them right away
> chore(compass-editor): unify compartments handling; add keybindings for copy and format

- packages/compass-import-export/src/import/analyze-csv-fields.spec.ts
- packages/compass-import-export/src/import/analyze-csv-fields.ts
- packages/compass-import-export/src/import/import-csv.spec.ts
- packages/compass-import-export/src/import/import-csv.ts
- packages/compass-import-export/src/import/import-json.spec.ts
- packages/compass-import-export/src/import/import-json.ts
- packages/compass-import-export/src/utils/import.ts
Extracted from integrating importCSV and importJSON with the existing UI.
The current import modal uses `docsProcessed` and a `guesstimated total` number of docs to do the progress bar and `docsWritten` plus either the guesstimated total number of docs or the actual number of docs imported (once it reaches the end) for the `X / Y` display.
So to make integration easier we need `docsProcessed` and `docsWritten`. The new UI will only use `bytesProcessed` and the total file size to make a progress bar and then by the end the importCSV / importJSON results (again probably `docsWritten` plus the number of errors) to print the summary.
But having a type there and progress be an object is probably more future proof than positional args anyway.
I updated analyzeCSVFields() at the same time just …
> chore(import) change progressCallback() parameters COMPASS-6519 COMPASS-6520

- packages/compass-import-export/src/import/import-csv.spec.ts
- packages/compass-import-export/src/import/import-csv.ts
- packages/compass-import-export/src/import/import-json.spec.ts
- packages/compass-import-export/src/import/import-json.ts
- packages/compass-import-export/src/utils/collection-stream.ts
- packages/compass-import-export/src/utils/import.ts
Something I'm extracting from the integration PR.
We need `docsProcessed` as not all docs make it to the db (think parse errors). `docsWritten` is useful for the `X / Y` part of the progress in the existing modal and the summary in the future toast. `dbErrors` and `dbStats` largely useful for tests - there's the optional `output` param for streaming errors to a log and `errorCallback` for listening for errors by the UI during an import. (we can probably deduplicate on the fly if we want to continue to display some)
Longer term I think we should remove result.dbErrors, result.dbStats.writeConcernErrors and result.dbStats.writeErrors as there can be a LOT of errors to keep in memory. But for now I'm leaving it as that's existing behaviour in the collection write stream.
> chore(import): rethink importCSV & importJSON result shape COMPASS-6519 COMPASS-6520

- packages/compass-editor/src/ace/aggregation-autocompleter.test.ts
- packages/compass-editor/src/ace/aggregation-autocompleter.ts
- packages/compass-editor/src/ace/query-autocompleter.test.ts
- packages/compass-editor/src/ace/query-autocompleter.ts
- packages/compass-editor/src/ace/stage-autocompleter.test.ts
- packages/compass-editor/src/ace/stage-autocompleter.ts
- packages/compass-editor/src/ace/util.ts
- packages/compass-editor/src/ace/validation-autocompleter.test.ts
- packages/compass-editor/src/ace/validation-autocompleter.ts
- packages/compass-editor/src/autocompleter.test.ts
- packages/compass-editor/src/autocompleter.ts
- packages/compass-editor/test/completer.ts
This patch moves all common logic for filtering mongodb-constants into a separate `completer` function that allows to filter by server version, prefix, and completion type.
More or less the behavior is the same, the main change is around this weird way we do escaping for some fields using `field-store`, the way it does escaping is not reliable and also it needs to be context aware (i.e., we should not autocomplete _with_ quotes when autocompleting inside string token) so this logic is now handled inside the ace autocompleters themselves and not in generic one, here's some examples comparing autocomplete incorrect results before and fixed after:
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/5036933/221172593-b1260ce5-3916-409e-aa23-8196a6f70fd9.png)|![image](h …
> chore(compass-editor): add generic completer for mongodb constants separated from ace autocompleter logic COMPASS-6547

- packages/compass-editor/package.json
- packages/compass-editor/src/json-editor.tsx
This enables codemirror annotations extension with some custom styles and adds an interface to the component to pass annotations to the editor. This is not currently used anywhere, but is a prerequisite to completely switch to codemirror editor
> chore(compass-editor): add support for code annotations COMPASS-6549

- packages/compass-editor/src/json-editor.tsx
Small adjustment for the fold placeholder in codemirror
|Before|After|
|---|---|
|<img width="332" alt="image" src="https://user-images.githubusercontent.com/5036933/221250277-58c53672-c582-446d-9446-8a8f1d94eba4.png">|<img width="323" alt="image" src="https://user-images.githubusercontent.com/5036933/221250150-a86cc3aa-65d1-4dd0-bea6-76ca31ed2378.png">|
|<img width="308" alt="image" src="https://user-images.githubusercontent.com/5036933/221250322-6608fb1d-caf3-4ff9-96fa-0d4320964b82.png">|<img width="337" alt="image" src="https://user-images.githubusercontent.com/5036933/221250035-9d519143-e6ff-4681-b8d3-0cecd37ea37f.png">|
> chore(compass-editor): adjust fold placeholder colors for dark mode

- packages/compass-editor/src/json-editor.tsx
Adds support for passing completion sources to the codemirror editor
> chore(compass-editor): add completer compartment to the codemirror editor

- packages/compass-explain-plan/src/components/explain-summary/explain-summary.tsx
- packages/compass-preferences-model/src/preferences.ts
- packages/compass-settings/src/components/settings/featureflags.tsx
Also re-add a learn more link in the explain plan as a drive-by: https://jira.mongodb.org/browse/COMPASS-6556. For context: we lost all the docs link with the recent design changes in the explain tab we did for the dark mode.
> feat: enable LG darkmode as public preview COMPASS-6515, COMPASS-6556

- packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.spec.ts
- packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
This fixes the issue where selecting initial value for the stage operator will override user input in stage value
> fix(compass-aggregations): do not reset stage value if it was already changed COMPASS-6584

- packages/compass-crud/src/components/document-json-view.tsx
- packages/compass-crud/src/components/json-editor.tsx
- packages/compass-crud/src/stores/crud-store.spec.ts
- packages/compass-crud/src/stores/crud-store.ts
- packages/compass-editor/src/autocompleter.ts
- packages/compass-editor/src/codemirror/document-autocompleter.ts
- packages/compass-editor/src/index.ts
- packages/compass-editor/src/json-editor.tsx
This patch adds field autocompleter for the fields in the document json editor. This is not an existing feature that we needed to re-implement, but we decided to add it as it was a good way to take first stab at using codemirror autocopmletion api. This completer will autocopmplete property names in json or javascript objects and any text when inside a string (this is pretty close to what we are currently doing for the query autocompleter, but a bit more advanced because we will not try to autocomplete field names for property values):
> chore(compass-editor): add document autocompleter COMPASS-6571

- packages/compass/src/main/menu.spec.ts
- packages/compass/src/main/menu.ts
- Move settings under the Compass menu on OSX and Edit menu on Windows and Linux
- Add the edit submenu on windows and linux
- Remove the theme submenu
> feat: place settings under the most idiomatic menu for the platform COMPASS-6430

- packages/data-service/src/connect-mongo-client.spec.ts
- packages/data-service/src/connect-mongo-client.ts
- packages/data-service/src/data-service.ts
- packages/data-service/src/run-command.ts
Otherwise, connecting to a secondary-only replset with `?readPreference=secondary` fails in Compass.
As a drive-by, this also applies the same logic to the `killSessions` helper method.
> fix(data-service): apply readPref to initial `ping` command COMPASS-6595

- packages/compass-editor/src/ace/aggregation-autocompleter.test.ts
- packages/compass-editor/src/ace/aggregation-autocompleter.ts
Regression I introduced in #4096 spotted by Max in latest beta. Added a test so that this doesn't happen again
> chore(compass-editor): escape $ in stage op name

- packages/compass-components/src/hooks/use-effect-on-change.ts
- packages/compass-editor/src/json-editor.tsx
Adding a few new props to the json editor to match interface with our current base editor, this should be the last ones to be able to start replacing some editors in the app when autocompleters are ready
> chore(compass-editor): add min-lines max-lines and allow to hide line highlight

- packages/compass-crud/src/components/crud-toolbar.tsx
- packages/compass-e2e-tests/helpers/commands/run-find-operation.ts
- packages/compass-e2e-tests/helpers/selectors.ts
- packages/compass-e2e-tests/tests/collection-explain-plan-tab.test.ts
Every time the test would populate a namespace with a million new items it would take around 4 minutes on my machine (and around 2 minutes on our extremely beefy CI machines), I refactored these tests to not rely on big collections as a way to ensure that explain plan takes time to execute
> chore(e2e): refactor slow explain plan tests

- packages/compass-e2e-tests/helpers/commands/shell-eval.ts
- packages/compass-e2e-tests/helpers/selectors.ts
To avoid issues with autocomplete triggering (which seems to be the reason for this flaky test on Ubuntu) and just to align with how we input text in other ace editors, I'm switching `shellEval` to use `setAceValue` here
> chore(e2e): use setAceValue in shellEval instead of keys COMPASS-6613

- packages/compass-components/src/components/bson-value.tsx
- packages/compass-components/src/components/item-action-controls.tsx
- packages/compass-components/src/components/modals/info-modal.tsx
- packages/compass-components/src/hooks/use-sort.tsx
- packages/compass-connections/src/components/connection-list/connection.tsx
- packages/compass-crud/src/components/insert-csfle-warning-banner.tsx
- packages/compass-query-bar/src/components/query-history-button-popover.tsx
- packages/compass-query-bar/src/components/query-option.tsx
- packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.tsx
- packages/connection-form/src/components/advanced-options-tabs/csfle-tab/kms-provider-status-indicator.tsx
I was investigating something related to emotion and as a drive-by did a clean up of non-recommended usage of `css` method:
- [Define styles outside your components](https://emotion.sh/docs/best-practices#consider-defining-styles-outside-your-components)
- [Use the style prop for dynamic styles](https://emotion.sh/docs/best-practices#use-the-style-prop-for-dynamic-styles)
> chore(components, crud, connections, query-bar, connection-form): remove usage of css in render

- packages/compass-e2e-tests/helpers/commands/run-find-operation.ts
Extracting this from https://github.com/mongodb-js/compass/pull/4150
~I am honestly confused how this worked so far as we don't have these class names on the reset button for at least 6 months now. I have some other unrelated e2e failures in my other patch, so extracting to see whether this will pass in CI for all machines now in isolation~ Mystery solved with the help from @lerouxb: we never hit this code in any of the current e2e tests so the "breaking" change to the query bar layout went unnoticed for this method
> chore(e2e): use isEnabled instead of class name check

- configs/mocha-config-compass/register/why-node-running.js
- packages/compass-editor/src/ace/aggregation-autocompleter.ts
- packages/compass-editor/src/autocompleter.test.ts
- packages/compass-editor/src/autocompleter.ts
- packages/compass-editor/src/codemirror/ace-compat-autocompleter.ts
- packages/compass-editor/src/codemirror/query-autocompleter.test.ts
- packages/compass-editor/src/codemirror/query-autocompleter.ts
- packages/compass-editor/src/codemirror/stage-autocompleter.test.ts
- packages/compass-editor/src/codemirror/stage-autocompleter.ts
- packages/compass-editor/src/index.ts
- packages/compass-editor/test/completer.ts
This is another patch to prepare for making codemirror a default editor component we use in Compass, this adds stage autocompleter following current ace behavior. As there was a ton of overlap with the query-autocompleter that I added recently, I refactored them a bit to share it (it will also be used for aggregation autocompleter next)
I also finally figured out what was wrong with test harness for codemirror, so units now include tests that require code parsing
> chore(compass-editor): add codemirror autocompleter for stage editor COMPASS-6547

- configs/mocha-config-compass/register/jsdom-global-register.js
- packages/compass-editor/src/codemirror/ace-compat-autocompleter.ts
- packages/compass-editor/src/codemirror/aggregation-autocompleter.test.ts
- packages/compass-editor/src/codemirror/aggregation-autocompleter.ts
- packages/compass-editor/src/codemirror/utils.ts
- packages/compass-editor/src/index.ts
- packages/compass-editor/test/completer.ts
Another autocompleter to be able to replace all multiline editors in compass with codemirror, behaves the same way as the ace one, all the tests from the current one I copied almost one to one. This one also shows descriptions for stages now as we discussed:
> chore(compass-editor): add agg autocompleter for codemirror COMPASS-6575

- packages/compass-import-export/src/import/guess-filetype.spec.ts
- packages/compass-import-export/src/import/guess-filetype.ts
- packages/compass-import-export/src/modules/import.ts
For files containing large json docs detectJSON() would resolve but detectCSV() would never resolve. Something to do with those routines destroying the streams themselves, then the other one stopped executing. Quick and easy fix seems to be to just destroy the stream on the outside after both promises resolved. Now both streams keep processing until we're done.
It now also stops processing CSV as soon as it detects JSON (since it will just go with json as the choice anyway) and there's a transform stream that will error out if we get to 1MB and it still didn't finish detecting CSV. ie. if two lines didn't fit in there it just resolves to 'unkown'.
If we still have problems after this we should Promise.race() with a timeout somewhere. File type detection isn't _that_ critical.
> fix(import): Fix guessFileType() for large JSON docs COMPASS-6629

- packages/compass-import-export/src/components/import-modal.tsx
I ran this by Diancheng and we both agree it looks much better:
> chore(import): Only use a large modal for CSV imports

- packages/compass-connections/src/components/connection-list/connection.tsx
Looks like the `!important` isn't recognized when using the `style` property so it was ignored. It's not needed anymore so these changes remove it and fix the background. We removed the dynamic `css(...)` usage here recently which caused this. 
| - | - | 
| <img width="384" alt="Screenshot 2023-03-22 at 11 37 45 AM" src="https://user-images.githubusercontent.com/1791149/226990834-6d18ffa5-80e4-46a5-ad25-d6d21c172f81.png"> | <img width="319" alt="Screenshot 2023-03-22 at 1 34 47 PM" src="https://user-images.githubusercontent.com/1791149/226990874-65f5c5a8-1318-4151-9387-0ef0de77841c.png"> |
> fix(compass-connections): background color on selected connection

- packages/compass-import-export/src/import/analyze-csv-fields.ts
- packages/compass-import-export/src/modules/import.ts
I forgot to abort the active analyzeCSVFields() (if any) when closing the import modal.
Merge https://github.com/mongodb-js/compass/pull/4182/files#r1146290848 first as this will conflict. That contains the better fix for properly destroying the input stream.
> fix(import): abort analyzeCSVFields() when closing the import modal COMPASS-6633

- packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-editor.tsx
- packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-editor.tsx
- packages/compass-aggregations/src/components/stage-editor/stage-editor.tsx
- packages/compass-aggregations/src/components/stage-toolbar/index.spec.tsx
- packages/compass-aggregations/src/components/stage-toolbar/index.tsx
- packages/compass-aggregations/src/components/stage-toolbar/stage-operator-select.tsx
- packages/compass-aggregations/src/components/stage.tsx
- packages/compass-aggregations/src/modules/pipeline-builder/pipeline-parser/utils.ts
- packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.spec.ts
- packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
- packages/compass-aggregations/src/utils/pipeline-storage.ts
- packages/compass-aggregations/src/utils/stage.js
- packages/compass-components/src/hooks/use-virtual-grid.ts
- packages/compass-components/src/index.ts
- packages/compass-components/src/utils/rafraf.ts
- packages/compass-databases-navigation/src/use-virtual-navigation-tree.tsx
- packages/compass-e2e-tests/helpers/commands/codemirror.ts
- packages/compass-e2e-tests/helpers/commands/select-stage-operator.ts
- packages/compass-e2e-tests/helpers/selectors.ts
- packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
- packages/compass-e2e-tests/tests/instance-my-queries-tab.test.ts
- packages/compass-editor/src/autocompleter.ts
- packages/compass-editor/src/json-editor.tsx
This patch replaces ace editor usage in agg builder with codemirror. All the current behavior is preserved, only one additional change was made in this patch: snippet completion behavior that was preset in stage editor until we unintentionally removed it is restored, now when selecting a stage we actually apply a template as a snippet instead of just pasting usually invalid code in the editor
> chore(compass-aggregations): replace ace with codemirror

- packages/compass-e2e-tests/helpers/selectors.ts
- packages/compass-e2e-tests/tests/collection-indexes-tab.test.ts
- packages/compass-editor/src/json-editor.tsx
- packages/compass-indexes/src/components/create-index-form/collapsible-input.tsx
A small one, replacing ace with codemirror in "Create Index" modal (base is #4187 as I want some changes from there to be available, I'll rebase when it lands)
> chore(compass-indexes): replace ace editor with codemirror

- packages/compass-crud/src/stores/crud-store.spec.ts
- packages/compass-crud/src/stores/crud-store.ts
- packages/compass-schema-validation/src/modules/validation.js
- packages/compass-schema-validation/src/modules/zero-state.js
- packages/compass-serverstats/src/stores/current-op-store.js
- packages/data-service/src/connect.spec.ts
- packages/data-service/src/csfle-collection-tracker.spec.ts
- packages/data-service/src/data-service.spec.ts
- packages/data-service/src/data-service.ts
- packages/data-service/src/run-command.ts
Another data service clean-up patch:
- Remove very generic `command` method and replace it with `killOp`, that's the only command that was used directly outside of data service
- Remove `database` method from the interface and clean up usage in schema-validation. This one is fun: we were fetching db and collection stats every time validation would change so that we can emit some telemetry events for the old telemetry system that was removed
- As a drive-by added a private `_database` method to match `_collection` method inside data service
Base branch is #4196 as these are related patches and one is required for another
> chore(data-service): replace command with killop; remove database method

- packages/compass-crud/src/utils/cancellable-queries.spec.ts
- packages/compass-serverstats/src/stores/current-op-store.js
- packages/compass-serverstats/src/stores/server-stats-graphs-store.js
- packages/compass-serverstats/src/stores/top-store.js
- packages/data-service/src/data-service.spec.ts
- packages/data-service/src/data-service.ts
- packages/data-service/src/run-command.ts
First batch of data service refactoring, this one changes all admin commands to be async instead of callback. There is a bunch of whitespace changes so I suggest to review it with [whitespace changes ignored](https://github.com/mongodb-js/compass/pull/4209/files?diff=split&w=1)
> chore(data-service): refactor top, serverStatus, currentOp to promises COMPASS-6620

- packages/compass-editor/src/json-editor.tsx
As reported in the slack thread. Somehow messed it up when setting up new multi-line editor even though I'm sure I tested it when adding support for `showScroll` property 🙃 Works as expected for me now:
|Horizontal|Both|No scroll visible, but scrolling works (inline editor)|
|---|---|---|
|![image](https://user-images.githubusercontent.com/5036933/228899245-13c8a43d-83e7-4f7e-beb3-3bca5baf6bbe.png)|![image](https://user-images.githubusercontent.com/5036933/228899396-75a447f3-58c8-4761-8990-e6437fb59bd6.png)|![Kapture 2023-03-30 at 18 15 27](https://user-images.githubusercontent.com/5036933/228899850-385452f3-c783-42cf-becd-07dd7047a1bd.gif)|
> chore(compass-editor): fix scroll in multiline editor

- configs/mocha-config-compass/compass-plugin.js
- configs/mocha-config-compass/register/electron-renderer-register.js
- packages/compass-app-stores/package.json
- packages/compass-field-store/package.json
Fixes `"Object can't be cloned"` issues that we saw when running tests with mocha-electron (and have some test suites disabled because of that)
> chore(mocha-config-compass): fix logging failures in mocha-electron

- packages/compass-components/src/components/file-input.spec.tsx
- packages/compass-components/src/components/file-input.tsx
- packages/compass-connection-import-export/src/components/file-input.tsx
- packages/compass-import-export/src/components/export-select-output/export-select-output.tsx
- packages/compass-import-export/src/components/import-file-input.tsx
Looks like passing a `leftGlyph` to LeafyGreen's Button made the width apply over our passed width. Also refactored to not use enums, and to follow lower case variant convention.
| - | - |
| <img width="853" alt="Screenshot 2023-03-30 at 11 06 20 AM" src="https://user-images.githubusercontent.com/1791149/228889173-3f4bdd26-2986-4ad3-829e-ae0c753b8ebb.png"> | <img width="921" alt="Screenshot 2023-03-30 at 11 27 45 AM" src="https://user-images.githubusercontent.com/1791149/228889208-c2a54d4b-d7d9-406c-bf9c-f8dac2f7eccb.png"> |
> fix(compass-components): display width on default file input variant

- packages/compass-query-bar/src/stores/query-bar-reducer.spec.ts
- packages/compass-query-bar/src/stores/query-bar-reducer.ts
- packages/compass-query-bar/src/stores/query-bar-store.spec.ts
- packages/compass-query-bar/src/stores/query-bar-store.ts
- packages/compass-query-history/src/stores/favorite-list-store.js
- packages/compass-query-history/src/stores/recent-list-store.js
Messed it up in recent refactor and forgot to re-subscribe query bar to the query history. Added some new tests to cover this case.
I checked with the version before my refactor and the old behavior was just to apply the query, not to run it, so I am preserving it like that for now. I think maybe for a future improvement it would make more sense if on select we 1) actually run the query 2) close the history list 3) expand options if other values than filter were changed, but to keep the fix simple I'm just restoring the old behavior we had.
I also noticed some very weird query history store behavior when testing this change locally, so opened an issue to deal with that (it doesn't affect anything massively and was there for a long time so kept it as is for now)
> fix(query-bar): listen to query-history events in query-bar and open saved items COMPASS-6680 COMPASS-6681 COMPASS-6685

- packages/compass-editor/src/codemirror/ace-compat-autocompleter.ts
- packages/compass-editor/src/codemirror/aggregation-autocompleter.ts
- packages/compass-editor/src/codemirror/stage-autocompleter.ts
- packages/compass-editor/src/codemirror/utils.ts
- packages/compass-editor/src/json-editor.tsx
Opening this just as a suggestion. In compass channel it was mentioned that having links to the documentation will be helpful, especially for cases where we currently don't have any descriptions provided otherwise, like for [pipeline operators](https://www.mongodb.com/docs/manual/reference/operator/aggregation/). This patch adds links to the `info` block of the autocompletion:
|Aggregation|Stage|
|---|---|
|![image](https://user-images.githubusercontent.com/5036933/229172046-cfdb7271-1e4c-4d54-89af-5150a92f5ad9.png)|![image](https://user-images.githubusercontent.com/5036933/229172807-3efb0fb2-5e9d-47bd-8aaf-09b8aa897145.png)|
> feat(compass-editor): add links to the documentation to the agg and stage autocompleter suggestions COMPASS-6688

- packages/compass-aggregations/src/components/aggregation-side-panel/index.spec.tsx
- packages/compass-aggregations/src/components/aggregation-side-panel/index.tsx
- packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/index.tsx
- packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-editor.tsx
- packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace.tsx
- packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-workspace.spec.tsx
- packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-workspace.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.spec.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
- packages/compass-aggregations/src/modules/index.ts
- packages/compass-aggregations/src/modules/side-panel.spec.ts
- packages/compass-aggregations/src/modules/side-panel.ts
- packages/compass-aggregations/src/stores/store.spec.ts
In this PR, we added a toggle button in aggregations toolbar. When clicked, it shows the sidebar that will house Stage Wizard use cases. This panel is only accessible in stage builder mode.  
https://user-images.githubusercontent.com/1305718/229379826-f9c9451f-66ae-4733-8da0-2eb4eef8117b.mov
> feat(stage-wizard): setup button and panel in aggregations toolbar COMPASS-6653

- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.spec.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
In the previous [PR](https://github.com/mongodb-js/compass/pull/4225) i missed to hide the toggle button behind the feature flag.
> fix(stage-wizard): show toggle button when feature flag is enabled

- packages/compass-import-export/src/modules/cursor-exporter.ts
- packages/compass-import-export/src/modules/export.spec.js
- packages/compass-import-export/src/modules/export.ts
COMPASS-5179, COMPASS-6649
When there's a count from running a query we display that count as the documents to export. This number was only used for ui purposes, so I think removing the count operations when its not available alright. It's not available when the count hasn't been run successfully, which happens on complex queries that timeout, also with views, and time series collections. We already handle the no count case nicely from the exporting aggregations work.
We're also in the process of updating export, which will also involve removing this count, so these changes help there as well.
> fix(compass-import-export): remove re-count when not available COMPASS-5179, COMPASS-6649

- packages/compass-import-export/src/export/export-json.spec.ts
- packages/compass-import-export/src/export/export-json.ts
- packages/compass-import-export/test/docs/all-bson-types.exported.canonical.ejson
- packages/compass-import-export/test/docs/all-bson-types.exported.default.ejson
- packages/compass-import-export/test/docs/all-bson-types.exported.relaxed.ejson
- packages/compass-import-export/test/json/complex.exported.ejson
- packages/hadron-document/src/index.ts
There are three export to JSON variants:
* default
* relaxed
* canonical
EJSON via the bson library gives us relaxed and canonical. Before this PR default was mapped to whatever EJSON.stringify's default was and now it is correctly mapped to our [compass-specific variant](https://github.com/mongodb-js/compass/blob/f2a73a756a616db9e38908d43436c7a52c31ac4f/packages/hadron-document/src/utils.ts#L44-L63).
> feat(export): Map default to our semi-relaxed / compass EJSON style, test with all bson types COMPASS-6708

- packages/compass-e2e-tests/tests/in-use-encryption.test.ts
The CSLFE e2e tests have been failing for more than a week which makes it impossible to get a green CI run.
Re-enabling covered by https://jira.mongodb.org/browse/COMPASS-6600
> chore(e2e): disable CSFLE tests on latest-alpha

- packages/compass/src/main/menu.spec.ts
- packages/compass/src/main/menu.ts
COMPASS-6723
From design sync. The aim is it make it apparent you can have multiple windows.
| - | - |
| <img width="295" alt="Screenshot 2023-04-13 at 10 10 23 AM" src="https://user-images.githubusercontent.com/1791149/231786104-99c13d12-e368-4a63-867a-3c8eca9fc19c.png"> | <img width="366" alt="Screenshot 2023-04-13 at 10 08 45 AM" src="https://user-images.githubusercontent.com/1791149/231786163-0d2eac0f-e7b2-41f9-bc0f-b88124d7a706.png"> |
| <img width="565" alt="Screenshot 2023-04-13 at 10 10 17 AM" src="https://user-images.githubusercontent.com/1791149/231786243-e65d53b6-82f9-4762-b888-727ae6fcae2c.png"> | <img width="320" alt="Screenshot 2023-04-13 at 10 09 49 AM" src="https://user-images.githubusercontent.com/1791149/231786268-b95e05c1-ec51-4205-a987-be493508b457.pn …
> feat: update new connection text to new window COMPASS-6723

- packages/compass-query-bar/src/components/option-editor.tsx
COMPASS-6724
| - | - |
| ![Screenshot 2023-04-13 at 10 37 30 AM](https://user-images.githubusercontent.com/1791149/231794424-a0451409-1dbd-46c5-86a0-ce22d0cd3221.png) | <img width="622" alt="Screenshot 2023-04-13 at 10 30 19 AM" src="https://user-images.githubusercontent.com/1791149/231794174-1c905b7b-9f97-40a0-81da-e92dc996574e.png"> |
> fix(compass-query-bar): show error border when focused COMPASS-6724

- packages/hadron-build/package.json
Pulls in https://github.com/mongodb-js/devtools-github-repo/pull/4
> chore(hadron-build): update devtools-github-repo dependency to 1.3.0

- packages/compass-components/src/components/combobox-with-custom-option.tsx
This PR fixes a small issue where combox rendering custom options will not remeber the previously selected custom option and won't show it either in the drop down of options. Explained also in the video below:
Before:
https://user-images.githubusercontent.com/10037761/233055576-683a2841-95ec-442e-8ad5-2ed6621d0160.mov
After:
https://user-images.githubusercontent.com/10037761/233055596-9ae849ce-8c26-45fb-8464-889cda90c14e.mov
> fix(compass-components): fixes custom options combobox not remembering previously selected custom options

- packages/compass-preferences-model/src/global-config.ts
COMPASS-6527
Previous pr https://github.com/mongodb-js/compass/pull/4208
Looking at the docs this should be one folder up: https://www.mongodb.com/docs/compass/current/settings/config-file/
Currently it's reading from `C:\Users\Rhys\AppData\Local\MongoDBCompass\app-1.63` and we should read from `C:\Users\Rhys\AppData\Local\MongoDBCompass`
> fix(compass-preferences-model): update windows config file fetching location one folder up COMPASS-6527

- packages/compass-collection/src/stores/index.ts
- packages/compass-crud/src/components/crud-toolbar.tsx
- packages/compass-crud/src/stores/crud-store.ts
- packages/compass-import-export/src/components/export-modal.tsx
- packages/compass-import-export/src/components/export-toast.tsx
- packages/compass-import-export/src/components/import-toast.tsx
- packages/compass-import-export/src/components/toast-body.tsx
- packages/compass-import-export/src/export-plugin.tsx
- packages/compass-import-export/src/export/export-json.spec.ts
- packages/compass-import-export/src/modules/export.spec.ts
- packages/compass-import-export/src/modules/export.ts
- packages/compass-settings/src/components/settings/featureflags.tsx
COMPASS-6580
This pr updates the new export flow to run the actual export and show progress toasts. After clicking the export button we show the output file selection. We show toasts similarly to how we do it in import (pr https://github.com/mongodb-js/compass/pull/4169).  When disconnecting we abort the export.
End to end tests will be in https://jira.mongodb.org/browse/COMPASS-6731 
**in progress**
**csv download phase in progress**
**success**
**error**
**stopped**
- Going to check with product/design on the text we show for the download phase of a csv export. That is likely subject to change. Open to suggestions.  https://mongodb.slack.com/archives/GDTJXPHD0/p1682010712466919
> feat(compass-import-export): run export and show progress toasts COMPASS-6580

- packages/compass-import-export/src/modules/export.ts
Looks like we merged new log ids at the same time so they were duplicate.
> fix: update duplicated log ids

- packages/compass-import-export/src/components/export-select-fields.spec.tsx
- packages/compass-import-export/src/components/export-select-fields.tsx
COMPASS-6762
Sometimes folks can have polymorphic data with generated field names. This would cause us to render possibly thousands of fields and would brick the ui. This PR adds a `Show 100 more fields` button to the export select fields ui when there are a lot of fields and more to show.
https://user-images.githubusercontent.com/1791149/234038348-defb85f0-671e-4380-903b-c47427e1f723.mp4
> feat(compass-import-export): show an add more fields button when more fields to show COMPASS-6762

- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.tsx
- packages/compass-query-bar/src/components/query-history-button-popover.tsx
| - | - |
| <img width="215" alt="Screenshot 2023-04-25 at 10 11 25 AM" src="https://user-images.githubusercontent.com/1791149/234309374-4e1eafa9-7677-492b-93e0-a4e8dbd06e91.png"> | <img width="299" alt="Screenshot 2023-04-25 at 10 26 57 AM" src="https://user-images.githubusercontent.com/1791149/234309407-dbe9bcd2-0570-4912-9ae3-f4f80eececa3.png"> |
| <img width="168" alt="Screenshot 2023-04-25 at 10 11 16 AM" src="https://user-images.githubusercontent.com/1791149/234309448-c63a57dc-05db-402b-acef-81d87dc19413.png"> | <img width="319" alt="Screenshot 2023-04-25 at 10 27 03 AM" src="https://user-images.githubusercontent.com/1791149/234309478-6c375796-89e0-4d39-af42-0830c3f93a1e.png"> |
> chore(compass-query-bar, compass-aggregations): add title to the history buttons

- packages/compass-editor/src/codemirror/utils.test.ts
- packages/compass-editor/src/index.ts
- packages/compass-editor/src/json-editor.tsx
- packages/compass-editor/test/completer.ts
Few small updates to compass editor to make it work smoothly in mongosh:
- When `readOnly` is `true`, all command that can change the doc should not produce any action. This is a pretty insignificant corner-case, but I noticed that I can add tabs to the output lines in mongosh, which is kinda weird 😅 
- Allow to pass `maxLines` and handle `Infinity` to allow overrides of default `maxLines` in inline editor (we don't limit it in shell inline editor compared to how these are used in Compass). This can be done also by explicitly passing `maxLines={undefined}` to the component, but this looks weird when reading code
- separate javascript and javascript-expressions languages: even though nothing in compass is rendering just javascript (this is why default for components is kept at …
> chore(compass-editor): handle maxlines infinity; skip doc updates when read only

- .evergreen/functions.yml
I realised I broke it way back here:
https://github.com/mongodb-js/compass/commit/88b9095f6f02a30941867afe895a401153f32f03#diff-feb0f1af5a13163b4f7ffb904fc7ee3422f6d104ed80d80f1af20015461d810c
> chore(e2e): upload the e2e test report as the test results, not a generic artifact

- packages/compass-crud/src/components/crud-toolbar.tsx
- packages/compass-e2e-tests/helpers/commands/set-export-filename.ts
- packages/compass-e2e-tests/helpers/selectors.ts
- packages/compass-e2e-tests/tests/collection-export-legacy.test.ts
- packages/compass-e2e-tests/tests/collection-export.test.ts
- packages/compass-e2e-tests/tests/collection-import.test.ts
- packages/compass-import-export/src/components/export-code-view.spec.tsx
- packages/compass-import-export/src/components/export-code-view.tsx
- packages/compass-import-export/src/components/export-field-options.tsx
- packages/compass-import-export/src/components/export-modal.tsx
- packages/compass-import-export/src/components/export-select-fields.tsx
- packages/compass-import-export/src/components/legacy/export-modal.tsx
- packages/compass-import-export/src/modules/export.ts
- packages/compass/src/index.d.ts
- packages/compass/src/main/index.ts
First part of COMPASS-6731
This PR adds e2e tests for the new export flow. It tests what we already had in e2e tests for export, but this time with the new export flow that is currently feature flagged. In the next pr I'll add tests for the things listed in the `TODO` at the bottom of the test file, we'll be increasing the test coverage for different paths here. Doing separate prs to make it easier to review, and so some tests could be reviewed while others are being worked on.
One or two drive by code cleanups included, can move them into separate pr if desired. Also one fix for export (feature flagged) that is included here, I'll leave a comment on that one. (Thanks to e2e tests for catching.)
> chore(compass-import-export, compass-e2e-tests): add export e2e tests COMPASS-6731

- packages/compass-import-export/src/components/export-modal.spec.tsx
- packages/compass-import-export/src/components/export-modal.tsx
Previously we were showing the `back` button when exporting an aggregation, this pr fixes it to be `Cancel`. Noticed this when writing tests, this pr also adds some tests.
> fix(compass-import-export): show cancel button on export aggregation

- packages/compass-e2e-tests/helpers/insert-data.ts
- packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
- packages/compass-e2e-tests/tests/collection-export-legacy.test.ts
- packages/compass-e2e-tests/tests/collection-export.test.ts
- packages/compass-e2e-tests/tests/collection-import.test.ts
- packages/compass-import-export/src/components/export-code-view.spec.tsx
- packages/compass-import-export/src/export/export-csv.ts
- packages/compass-import-export/src/export/export-json.spec.ts
- packages/compass-import-export/src/export/export-json.ts
- packages/compass-import-export/src/import/import-csv.ts
- packages/compass-import-export/src/import/import-json.ts
- packages/compass-import-export/src/modules/export.ts
- packages/compass-import-export/src/utils/get-shell-js.spec.ts
- packages/compass-import-export/src/utils/get-shell-js.ts
- packages/compass-import-export/src/utils/query-has-projection.spec.ts
Adding tests for COMPASS-6731 (part 2)
This adds end to end tests for various export flows (with the feature flagged export backend and frontend), the new tests include: export with collation+skip+limit+sort, export with projection, abort in progress, abort when disconnecting.
> chore(compass-e2e-tests, compass-import-export): add export e2e tests COMPASS-6731

- packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/basic-group.tsx
- packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/group-with-statistics.spec.tsx
- packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/group-with-statistics.tsx
- packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/group-with-subset.spec.tsx
- packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/group-with-subset.tsx
- packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/index.ts
- packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/sort/sort.tsx
- packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/utils.spec.ts
- packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/utils.ts
- packages/compass-aggregations/test/form-helper.ts
In this PR, we added `$group` use case to generate a subset of documents based on the accumulator. 
<details>
<summary>Preview</summary>
https://user-images.githubusercontent.com/1305718/235797420-d8f901a6-427a-4076-b46f-3e52166a6c50.mov
</details>
> feat(stage-wizard): group with subsets COMPASS-6663

- packages/compass-import-export/src/modules/import.ts
This is so that the progress toast doesn't appear and override the error toast message.
To test you can create a json document with 2000 empty documents and leave out the last `]` character.
> fix(compass-import-export): flush import progress throttle on import error

- packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/index.ts
- packages/compass-aggregations/src/components/stage-wizard/index.tsx
- packages/compass-aggregations/src/modules/collections-fields.ts
- packages/compass-aggregations/src/utils/get-schema.spec.ts
- packages/compass-aggregations/src/utils/get-schema.ts
In this PR, we refactored our `get-schema` helper to also add type information for the fields.
> feat(compass-aggregations): refactor for get-schema to also add type information - COMPASS-6793

- packages/compass-aggregations/src/modules/saved-pipeline.ts
- packages/compass-components/src/hooks/use-toast.spec.tsx
- packages/compass-components/src/hooks/use-toast.tsx
- packages/compass-components/src/index.ts
- packages/compass-connection-import-export/src/components/export-modal.tsx
- packages/compass-connection-import-export/src/components/import-modal.tsx
- packages/compass-connections/src/components/connection-list/connection.tsx
- packages/compass-connections/src/stores/connections-store.ts
- packages/compass-e2e-tests/tests/collection-import.test.ts
- packages/compass-import-export/src/components/import-toast.tsx
- packages/compass-import-export/src/components/toast-body.tsx
- packages/compass-import-export/src/modules/import.ts
- packages/compass-sidebar/src/components/sidebar.tsx
Also updates error text on csv file parsing error.
| - | - |
| <img width="419" alt="Screenshot 2023-05-11 at 10 59 11 AM" src="https://github.com/mongodb-js/compass/assets/1791149/b8a655e5-d640-431d-bbd5-6d818313dfa9"> | ![Screenshot 2023-05-11 at 10 58 34 AM](https://github.com/mongodb-js/compass/assets/1791149/58d7d0ea-5145-47cc-883e-aca78937e395) |
> chore(compass-import-export): update import toast error styles

- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.spec.tsx
- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
- packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
- packages/compass-home/src/components/home.tsx
- packages/compass-preferences-model/src/preferences.ts
- packages/compass-settings/src/components/settings/featureflags.tsx
- packages/compass/src/app/theme.ts
- packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.tsx
In this PR, we make sure that feature flags only have either `undefined` or `true` values.
When undefined, its not written to the preferences file (as a result flag is marked as disabled). And if user disables/enables the flag, it is prioritised. 
When true, if the user had modified the flag, that value is considered, or else the value is set to true in the file.
Also, here we renamed `useStageWizard` to avoid migration. So now when we enable the feature, it will be enabled for all (obviously except for those who disabled it).
Once approved, I'll also update [docs for feature-flags](https://github.com/10gen/devtools-internal-docs/blob/main/technical/compass/feature-flags.md).
> fix(user-preferences): feature flag default values COMPASS-6525

- packages/compass-crud/src/stores/crud-store.spec.ts
- packages/compass-crud/src/stores/crud-store.ts
- Fallback to modifyOneMethod for both `ShardKeyNotFound` and `FLE returnDocument: "after"` errors.
- Use the whole query in modifyOneMethod.
- Remove extra find before modifyOneMethod.
> refactor: fallback to modifyOneMethod with query COMPASS-6058

- packages/compass-e2e-tests/tests/collection-import.test.ts
- packages/compass-import-export/scripts/analyze-csv.ts
- packages/compass-import-export/src/components/import-modal.tsx
- packages/compass-import-export/src/components/import-options.tsx
- packages/compass-import-export/src/csv/csv-types.ts
- packages/compass-import-export/src/export/export-csv.spec.ts
- packages/compass-import-export/src/export/gather-fields.spec.ts
- packages/compass-import-export/src/import/analyze-csv-fields.spec.ts
- packages/compass-import-export/src/import/analyze-csv-fields.ts
- packages/compass-import-export/src/import/guess-filetype.spec.ts
- packages/compass-import-export/src/import/guess-filetype.ts
- packages/compass-import-export/src/import/import-csv.spec.ts
- packages/compass-import-export/src/import/import-csv.ts
- packages/compass-import-export/src/import/list-csv-fields.spec.ts
- packages/compass-import-export/src/import/list-csv-fields.ts
- packages/compass-import-export/src/modules/import.ts
- packages/compass-import-export/test/csv/linebreaks.analyzed.json
- packages/compass-import-export/test/csv/linebreaks.csv
- packages/compass-import-export/test/csv/linebreaks.exported.csv
- packages/compass-import-export/test/csv/linebreaks.gathered.json
- packages/compass-import-export/test/csv/linebreaks.imported.ejson
- packages/compass-import-export/test/csv/linebreaks.preview.json
- packages/compass-import-export/test/fixtures.ts
I'm not exactly sure what's going on in papaparse's [guessLineEndings()](https://github.com/mholt/PapaParse/blob/b5365550968b46c5ec4a9fa37ea26365c92c9a15/papaparse.js#L1358-L1382), but @graboskyc ran into a case where a CSV file with windows style line endings was dropping the last field in the CSV file when imported.
I investigated and realised the \r from the \r\n line ending was still in the header. Upon further investigation I eventually realised that papaparse detected unix style line endings. I added a bunch of unit tests that would replace our test fixtures' unix style line endings with windows style ones so that we can test both cases everywhere. I also made a simplified version of his file as a new test fixture. I quickly realised it almost always detected the windows ones as …
> fix(import): Detect line breaks, pass it on to papaparse COMPASS-6819

- packages/compass-query-bar/src/stores/query-bar-reducer.spec.ts
- packages/compass-query-bar/src/stores/query-bar-reducer.ts
COMPASS-6805
We noticed this when doing some QA for exporting queries. When hitting `Reset` on the query bar it wasn't updating the query results to the blank results and wasn't updating the query to export.
https://github.com/mongodb-js/compass/assets/1791149/1f97405c-7ab3-4e15-bbc4-b6912d459e9e
> fix(compass-query-bar): update reset on query bar to reset results and emit query-changed COMPASS-6805

- packages/compass-import-export/src/import/import-csv.spec.ts
We have plenty of other tests that examine the output and since we're just expecting to not encounter any errors here we might as well set stopOnErrors to true so that it will throw (and fail the test) if it ever encounters any. Then no real need to check that the output file is empty so we won't get the strange OS error.
> chore(import): work around the flake by throwing on errors and then ignoring the empty output

- packages/compass-collection/src/components/collection-header/collection-header.tsx
- packages/compass-collection/src/components/collection-stats-item/collection-stats-item.tsx
- packages/compass-components/src/components/resizeable-sidebar.tsx
- packages/compass-components/src/components/workspace-tabs/tab.tsx
Alternative title: more neon signage.
> chore: change the active green color for dark mode COMPASS-6608

- packages/compass-crud/src/components/insert-json-document.tsx
Same as schema validation tab, remove weird styles that require us to maintain the color in multiple places
|Before|After|
|---|---|
|<img width="611" alt="image" src="https://github.com/mongodb-js/compass/assets/5036933/e106be2f-230c-4503-9cff-dacd85015955">|<img width="622" alt="image" src="https://github.com/mongodb-js/compass/assets/5036933/34f0a952-8762-4203-80c8-3a411112d30c">|
> chore(compass-crud): fix insert dialog dark mode COMPASS-6754

- packages/compass-schema-validation/src/components/validation-editor/validation-editor.jsx
Just removes the padding that adds a need to maintain the color parity, this doesn't match leafygreen anyway
|Before|After|
|---|---|
|<img width="195" alt="image" src="https://github.com/mongodb-js/compass/assets/5036933/6dfa6657-c769-4de9-9aad-94197894f7d3">|<img width="189" alt="image" src="https://github.com/mongodb-js/compass/assets/5036933/178c86b6-18af-448b-88b5-8fc66bccd19e">|
> chore(schema-validation): remove padding and background color COMPASS-6754

- packages/compass-preferences-model/src/preferences.ts
This doesn't remove the feature flag yet, it just changes the default from `undefined` to `true`.
> feat(preferences): enable "Modern Dark Mode" by default

- packages/data-service/src/connect.spec.ts
There's a ticket for fixing it https://jira.mongodb.org/browse/COMPASS-6867
> chore: Skip connects to kerberosCrossRealm for now

- packages/compass-import-export/src/components/import-preview.tsx
COMPASS-6632
Also did some variable naming consistency for the styles.
Links to https://www.mongodb.com/docs/manual/reference/bson-types/
> feat(compass-import-export): add types docs link to import preview COMPASS-6632

- packages/compass-databases-navigation/src/collection-item.tsx
I wanted to add a shortcut for opening collections on new tab. Because, in the times when you need to open a collection in a separate tab, it requires double work and too much mouse movements, and in my opinion, sometimes it slows people down. So, I added a functionality to open collections in new tab when user clicks to the collection with pressing the CMD or Ctrl keys (CMDorCtrl+Click for new tab is already a habit for people), otherwise it will open the collection as it is on the current tab.
I have tested it on macOS and Windows 10 platforms. You can watch the video below for macOS.
https://github.com/mongodb-js/compass/assets/9059250/653c27aa-810c-46a7-aad5-77b83509fb2e
> feat(databases-collections): open collection in new tab shortcut

- packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/match/match-group-form.tsx
This PR addresses an issue brought up in recent usability testing of match stage wizard where the wizard will keep its light background even in the dark mode.
Before:
After:
> fix(compass-aggregations): fixes static light background issue in dark mode for match stage wizard

- configs/webpack-config-compass/src/index.ts
This patch changes default externals for the web target by also registering Node.js built-ins with the new `node:` import schema as externals
> fix(webpack-config): externalize built-in node modules with node: schema for web target

- packages/compass-e2e-tests/helpers/commands/set-connect-form-state.ts
Try and fix the flake we've been seeing in CI where it selects minPoolSize rather than maxPoolSize.
> chore(e2e): wait for animations on the option before clicking to select it

- packages/compass-import-export/src/components/export-modal.tsx
Previously we would only add the filetype to the file name. Now we will always set it to the filetype unless the user changes the filter to `All Files`.
> fix(compass-import-export): add file type filters when exporting COMPASS-6890

- packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.spec.tsx
- packages/compass-components/src/components/more-options-toggle.spec.tsx
- packages/compass-components/src/components/more-options-toggle.tsx
Simple rename of the "Less Options" label to read "Fewer Options" as this is grammatically correct.
> fix: rename "Less Options" to "Fewer Options" COMPASS-6774

- packages/compass-aggregations/src/components/focus-mode/focus-mode.tsx
- packages/compass-components/src/components/index-icon.tsx
- packages/compass-components/src/components/index-keys-badge.tsx
- packages/compass-components/src/components/inline-definition.tsx
- packages/compass-components/src/components/modals/modal-header.tsx
- packages/compass-components/src/components/modals/modal.tsx
- packages/compass-components/src/index.ts
- packages/compass-editor/src/json-editor.tsx
- packages/compass-explain-plan/src/components/explain-body/explain-body.module.less
- packages/compass-explain-plan/src/components/explain-cannot-visualize-banner/explain-cannot-visualize-banner.jsx
- packages/compass-explain-plan/src/components/explain-cannot-visualize-banner/explain-cannot-visualize-banner.module.less
- packages/compass-explain-plan/src/components/explain-plan-modal.tsx
- packages/compass-explain-plan/src/components/explain-plan-side-summary.tsx
- packages/compass-explain-plan/src/components/explain-plan-view.tsx
- packages/compass-explain-plan/src/components/explain-tree/explain-tree.tsx
- packages/compass-explain-plan/src/components/explain-tree/tree-layout.tsx
- packages/compass-explain-plan/src/stores/explain-plan-modal-store.ts
This patch updates explain plan view modal to match the [new designs](https://www.figma.com/file/XRhsB09S1KLJYAbcQi4PUL/EXPO-2393%3A-Performance-signals-MVP?type=design&node-id=357-59649&t=uFXWRf8hDIZRlswQ-0): modal is fullscreen, summary is on the right side now and always present, we also allow to view visual tree for aggregation explain now. Here's a few screenshots with different states:
> feat(explain-plan, compass-aggregations): add visual tree and update summary for the aggregation explain plan COMPASS-6821 COMPASS-6888

- packages/compass-components/src/components/document-list/element-editors.tsx
When editing a document in List View, the dropdown for change the Type of the field is only visible in Light Mode, if you changes the theme to Dark Mode, the background and color text are white.
These changes fix this problem, now when changes to Dark Mode, the background is the same as the Dark Mode background with white text and it is readable.
> fix: support Dark Mode on TypeEditor dropdown - COMPASS-6893
