mongodb-js/compass

packages/compass-connections/src/components/connections.spec.tsx
packages/compass-connections/src/modules/connection-attempt.ts
packages/compass-crud/src/stores/crud-store.spec.ts
packages/compass-crud/src/utils/cancellable-queries.spec.ts
packages/compass-import-export/src/export/export-csv.spec.ts
packages/compass-import-export/src/export/export-json.spec.ts
packages/compass-import-export/src/export/gather-fields.spec.ts
packages/compass-import-export/src/import/import-csv.spec.ts
packages/compass-import-export/src/import/import-json.spec.ts
packages/compass-import-export/src/modules/export.spec.ts
packages/data-service/src/connect-mongo-client.spec.ts
packages/data-service/src/connect-mongo-client.ts
packages/data-service/src/connect.spec.ts
packages/data-service/src/connect.ts
packages/data-service/src/csfle-collection-tracker.spec.ts
packages/data-service/src/data-service.ts

We'll want this eventually for oidc support in VSCode.
The returned `MongoClientConnectionOptions` from `getMongoClientConnectionOptions` which we call in VSCode was returning the productName `MongoDB Compass` and the compass docs link.

chore(data-service): pass optional productName and productDocsLink in connect

---

packages/compass-e2e-tests/tests/oidc.test.ts
packages/compass-home/src/components/home.spec.tsx
packages/compass-home/src/components/home.tsx
packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.tsx
packages/data-service/package.json
packages/data-service/src/connect-mongo-client.spec.ts
packages/data-service/src/connect-mongo-client.ts
packages/data-service/src/connection-options.ts
packages/data-service/src/data-service.ts
packages/data-service/src/index.ts

feat(data-service): add support for re-authentication prompt COMPASS-6800

---

packages/compass-e2e-tests/helpers/commands/run-find-operation.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
packages/compass-e2e-tests/tests/collection-explain-plan-tab.test.ts
packages/compass-explain-plan/src/components/explain-plan-modal.tsx
packages/compass-explain-plan/src/components/explain-plan-view.tsx
packages/compass-preferences-model/src/feature-flags.ts
packages/compass-query-bar/src/components/query-bar.tsx

This patch prepares the codebase for flipping the switch on the feature: update e2e tests for new behavior, changes the flag to preview so it can be enabled through settings. And one small style adjustment, we looked at it with design and decided to change the segmented control size to default instead of large

chore(explain-plan): mark explain plan as feature in preview

---

packages/compass-explain-plan/src/components/explain-plan-view.tsx
packages/compass-explain-plan/src/components/explain-tree/explain-tree.tsx
packages/compass-explain-plan/src/components/explain-tree/tree-layout.tsx
packages/compass-explain-plan/src/components/zoom-control.tsx

This patch adds a zoom control to the visual tree in the modal view (it is not possible to make it work nicely with the old explain plan layout where the header is on the top, this is why the implementation is part of `explain-plan-view.tsx` component and not in the `explain-tree.tsx`):

feat(explain-plan): add zoom control to the modal tree view COMPASS-6843

---

packages/compass-explain-plan/src/components/explain-plan-side-summary.tsx

chore(explain-plan): add the "no index available" badge back to the summary

---

packages/compass-editor/src/json-editor.tsx

COMPASS-6910
| - | - |
| <img width="656" alt="Screenshot 2023-06-12 at 9 00 42 PM" src="https://github.com/mongodb-js/compass/assets/1791149/0d7de850-62ac-4e26-aa52-e276bb834482"> | <img width="652" alt="Screenshot 2023-06-12 at 8 59 52 PM" src="https://github.com/mongodb-js/compass/assets/1791149/fa9922b3-dfcc-4dc2-883c-5cc1cf5ec18b"> |

fix(compass-editors): editor darkmode background selection color COMPASS-6910

---

packages/data-service/src/connect-mongo-client.spec.ts
packages/data-service/src/connect-mongo-client.ts
packages/data-service/src/connection-options.ts

COMPASS-6916
We were setting `ALLOWED_HOSTS` on the `authMechanismProperties` to `*` when enableUntrustedEndpoints is true. This errors as it's an invalid value. This pr updates this handling to do what mongosh does: 
https://github.com/mongodb-js/mongosh/blob/6a6f97712a596a21c61408dfb925e729306030f8/packages/arg-parser/src/arg-mapper.ts#L114-L137 

fix(data-service): update how we set ALLOWED_HOSTS when enableUntrustedEndpoints is true COMPASS-6916

---

configs/tsconfig-compass/tsconfig.common.json

We should be able to get to ES2022, but we would need to solve few compilation errors.

chore: bump ts target to ES2021 COMPASS-5226

---

packages/compass/src/main/auto-update-manager.ts
packages/compass/src/main/auto-updater.ts

If compass was installed with an MSI then squirrel is not available so the autoupdater won't work. This PR aims to detect that and then use the NOOP autoupdater we have for linux renamed appropriately.

fix: disable the autoupdater for MSI installs (windows without squirrel) COMPASS-6857

---

packages/compass-indexes/src/components/indexes-table/property-field.tsx
packages/compass-indexes/src/components/indexes-table/type-field.tsx
packages/compass-indexes/src/utils/index-link-helper.ts

Make sure that the argument to `getIndexHelpLink()` is one of the expected values, not an arbitrary string.

chore(compass-index): make getIndexHelpLink argument typesafe

---

packages/compass-e2e-tests/tests/oidc.test.ts

We noticed this was running as part of ubuntu 40x and 42x, etc when it failed because there isn't an rc4 for those versions yet. Not necessary to run on anything before 7.0 and enterprise.

skip oidc e2e tests unless it is 7.0+ and enterprise

---

packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.tsx
packages/compass-preferences-model/src/feature-flags.ts
packages/compass-query-bar/src/components/option-editor.tsx
packages/compass-sidebar/src/components/navigation-items.tsx
packages/databases-collections-list/src/namespace-param.tsx

It just hit me that we should probably hide them until telemetry is added even though we didn't plan to hide them behind a feature flag initially

chore(preferences-model): hide all insights behind a feature flag

---

packages/compass-components/src/components/signal-popover.tsx

Add a GuideCue to the initial display of SignalPopover

feat(compass-components): guide cue for signal popover

---

package-lock.json
packages/compass-components/src/components/document-list/document-actions-group.tsx
packages/compass-components/src/components/signal-popover.tsx
packages/compass-crud/package.json
packages/compass-crud/src/components/editable-document.tsx
packages/compass-crud/src/components/readonly-document.tsx
packages/compass-crud/src/stores/crud-store.ts
packages/compass-field-store/src/stores/store.js
packages/compass-field-store/src/stores/store.spec.js
packages/hadron-document/src/document.ts

We're calculating the doc size using bsonSize projection and storing this info on the HadronDocument. The value is then used when rendering the card action group

feat(compass-crud): add bloated docs insight to the document list COMPASS-6837

---

packages/compass-components/src/components/signal-popover.tsx
packages/compass-explain-plan/src/components/explain-plan-modal.spec.tsx
packages/compass-explain-plan/src/components/explain-plan-side-summary.tsx
packages/compass-explain-plan/src/components/explain-plan-view.spec.tsx
packages/compass-explain-plan/src/components/explain-plan-view.tsx
packages/compass-explain-plan/src/stores/explain-plan-modal-store.ts

This patch adds another insight

feat(explain-plan): show unindexed query insight in explain plan modal COMPASS-6933

---

packages/compass-components/src/components/item-action-controls.tsx

chore(compass-components): add missing key prop

---

packages/compass-collection/src/components/workspace/workspace.tsx

To see with design if we should keep the old hotkeys, or switch them over.
https://feedback.mongodb.com/forums/924283-compass/suggestions/40556407-ctrl-tab-to-switch-between-tabs

feat(compass-collection): add ctrl + tab and ctrl + shift + tab hotkeys for switching tabs

---

packages/compass-e2e-tests/helpers/commands/navigate-to-collection-tab.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/README.md
packages/compass-e2e-tests/tests/collection-heading.test.ts
packages/compass-e2e-tests/tests/database-collections-tab.test.ts
packages/compass-preferences-model/src/feature-flags.ts

Flipping the feature flag to `released` as there is no feedback to address, it's ready to be released

feat(explain-plan): enable new explain plan by default

---

packages/compass-aggregations/src/components/create-view-modal/create-view-modal.jsx
packages/compass-aggregations/src/components/duplicate-view-modal/duplicate-view-modal.jsx
packages/compass-aggregations/src/components/saving-pipeline-modal/saving-pipeline-modal.jsx
packages/compass-shell/src/components/shell-info-modal/shell-info-modal.jsx
packages/databases-collections/src/components/create-collection-modal/create-collection-modal.jsx
packages/databases-collections/src/components/create-database-modal/create-database-modal.jsx

After removing `trackingId` from modal (https://github.com/mongodb-js/compass/pull/4059), we still had some modals using that prop and react complained about it. I removed those and added tracking for each in their corresponding component.

fix: remove trackingId from modals and track them

---

package-lock.json
packages/compass-components/src/components/document-list/document-actions-group.tsx
packages/compass-components/src/components/signal-popover.tsx
packages/compass-crud/package.json
packages/compass-crud/src/components/editable-document.tsx
packages/compass-crud/src/components/readonly-document.tsx
packages/compass-crud/src/stores/crud-store.ts
packages/compass-field-store/src/stores/store.js
packages/compass-field-store/src/stores/store.spec.js
packages/hadron-document/src/document.ts

Reverts mongodb-js/compass#4566

Revert "feat(compass-crud): add bloated docs insight to the document list COMPASS-6837"

---

packages/compass-components/src/components/index-keys-badge.tsx

COMPASS-6510
As react-testing-library only tests the dom, not the rendered items, I'm not sure what a good regression test would be besides adding onto our end to end tests. Will add one if folks feel it's worth it.
| - | - |
| <img width="430" alt="Screenshot 2023-06-29 at 10 30 55 AM" src="https://github.com/mongodb-js/compass/assets/1791149/7582c478-d355-421c-b04c-34d5acd7df3c"> | <img width="466" alt="Screenshot 2023-06-29 at 10 30 44 AM" src="https://github.com/mongodb-js/compass/assets/1791149/d8557e44-d9ca-47ae-aaa7-8f57090d46d6"> |

fix(compass-components): case sensitive index key badges COMPASS-6510

---

packages/compass-query-bar/src/components/generative-ai/ai-text-input.tsx
packages/compass-query-bar/src/components/query-bar.tsx
packages/compass-query-bar/src/stores/ai-query-reducer.ts
packages/compass-query-bar/src/stores/query-bar-reducer.ts
packages/compass-query-bar/src/utils/index.ts

A couple small improvements to the ai:
- Pulls in some of the improvements in https://github.com/mongodb-js/compass/pull/4607 including the thunk reducer typing fix.
- Updates the `Generate` button to become `Cancel (esc)` when an operation is in progress.
- Cancels any ongoing ai query on unmount.
Figma: https://www.figma.com/file/Ip4CPowv3Uxxhu3klyXA0e/Generative-AI-in-Compass-MVP?type=design&node-id=583%3A24076&mode=dev

chore(compass-query-bar): update ai button styles, cancel on unmount, fix thunk typing

---

package-lock.json
packages/compass-components/src/components/document-list/document-actions-group.tsx
packages/compass-components/src/components/signal-popover.tsx
packages/compass-crud/package.json
packages/compass-crud/src/components/editable-document.tsx
packages/compass-crud/src/components/readonly-document.tsx
packages/compass-crud/src/stores/crud-store.spec.ts
packages/compass-crud/src/stores/crud-store.ts
packages/compass-field-store/src/stores/store.js
packages/compass-field-store/src/stores/store.spec.js
packages/hadron-document/src/document.ts

This reverts the previous revert we had to do and adds an additional check to the fetchDocuments method that doesn't apply $bsonSize projection to the find requests when connected to ADF as it doesn't support $bsonSize projection. First commit reverts the previous revert, second one actually fixes the issue and adds some tests

feat(compass-crud): re-introduce "bloated documents" insight COMPASS-6837

---

packages/compass-explain-plan/src/stores/explain-plan-modal-store.ts
packages/compass-query-bar/src/stores/query-bar-reducer.spec.ts
packages/compass-query-bar/src/stores/query-bar-reducer.ts

Query bar state keeps projection value under `project`, but dataService / driver expects `projection`

fix(compass-query-bar): map project to projection before emitting open-explain-plan event COMPASS-6995

---

packages/compass-aggregations/src/components/focus-mode/focus-mode-modal-header.tsx
packages/compass-collection/src/components/workspace/workspace.tsx
packages/compass-components/src/hooks/use-hotkeys.spec.tsx
packages/compass-components/src/hooks/use-hotkeys.tsx
packages/compass-shell/src/components/shell-info-modal/keyboard-shortcuts-table.jsx

COMPASS-6777
We were using `meta` instead of `mod` for our hotkeys. `meta` is used for the windows key, which is usually not used for hotkeys as it makes the app lose focus. Tested on windows.
Hotkey docs:
https://react-hotkeys-hook.vercel.app/docs/documentation/useHotkeys/basic-usage#modifiers--special-keys
Test hotkeys:
https://www.toptal.com/developers/keycode

fix(compass-components): use mod for hotkey so windows uses ctrl instead of windows key COMPASS-6777

---

packages/compass-aggregations/src/utils/insights.ts
packages/compass-collection/src/components/collection-header/collection-header.spec.tsx
packages/compass-collection/src/components/collection-header/collection-header.tsx

This patch adds an insight that will be shown when stage in the pipeline editor or a view source pipeline contains a `$lookup` stage:

feat(collection, aggregations): show insight when $lookup stage is used COMPASS-6970

---

packages/mongodb-explain-compat/lib/index.js
packages/mongodb-explain-compat/package.json
packages/mongodb-explain-compat/test/fixtures/query-planner-only.json
packages/mongodb-explain-compat/test/index.js

This patch makes sure that explain plan compat still works even if explain plan doesn't contain execution stats. Spotted when adding e2e tests for insights, but this also affects aggregation explain in cases where $out stage is used. Figured out that all this time I was using our test cluster that is still on 4.4 for testing locally 🤦

fix(explain-compat): handle missing execution stats in raw explain

---

package-lock.json
packages/compass-query-bar/src/components/generative-ai/ai-text-input.spec.tsx
packages/compass-query-bar/src/components/generative-ai/ai-text-input.tsx
packages/compass-query-bar/src/components/generative-ai/robot-svg.tsx
packages/compass-query-bar/src/stores/ai-query-reducer.ts

COMPASS-7005
- Moves the text from the state to store (so that it's persisted between the Documents and Schema tabs).
- Adds a clear button.
- Updates the loading and success indicators to replace the close button when they're shown.
**Clear button:**
https://github.com/mongodb-js/compass/assets/1791149/02e4b760-bb06-4fa8-89fb-c398d03914ae
**Loading/success/close styles:**
https://github.com/mongodb-js/compass/assets/1791149/705d26dc-3eec-4d0e-b519-4d7088b3b14e

chore(query-bar): update ai text input styles, move text out of state to store COMPASS-7005

---

configs/eslint-config-compass/index.js
configs/eslint-config-compass/package.json
package-lock.json

This bumps the typescript-eslint plugin. Some warnings are now errors by default.

chore: bump eslint-config-devtools to 0.9.9

---

.snyk
package-lock.json
packages/app-migrations/package.json
packages/compass-crud/package.json
packages/compass-editor/package.json
packages/compass/package.json
scripts/package.json

This PR addresses the following tickets:
- COMPASS-6966
- COMPASS-6967
- COMPASS-6969
related to possible security vulnerability ([SNYK-JS-SEMVER-3247795](https://security.snyk.io/vuln/SNYK-JS-SEMVER-3247795)) introduced by semver < 7.5.2
semver backported the [fix applied in 7.5.2](https://github.com/npm/node-semver/pull/564) for the above mentioned vulnerability also to v5.x (in [5.7.2](https://github.com/npm/node-semver/releases/tag/v5.7.2)) and to v6.x (in [6.3.1](https://github.com/npm/node-semver/releases/tag/v6.3.1)). Since these versions were released ~18 hours ago, the snyk advisory hasn't catch up to the updated info which is why we are disabling this particular vulnerability in our snyk policy for a month.

chore: locks semver 5.7.x to 5.7.2, 6.3.x to 6.3.1 and 7.5.x to 7.5.4 - COMPASS-6966, COMPASS-6967, COMPASS-6969

---

configs/mocha-config-compass/register/resolve-from-source-register.js
configs/tsconfig-compass/tsconfig.common.json
configs/tsconfig-compass/tsconfig.react.json
package-lock.json
packages/atlas-service/.depcheckrc
packages/atlas-service/.eslintignore
packages/atlas-service/.eslintrc.js
packages/atlas-service/.mocharc.js
packages/atlas-service/.prettierignore
packages/atlas-service/.prettierrc.json
packages/atlas-service/main.d.ts
packages/atlas-service/main.js
packages/atlas-service/package.json
packages/atlas-service/renderer.d.ts
packages/atlas-service/renderer.js
packages/atlas-service/src/main.spec.ts
packages/atlas-service/src/main.ts
packages/atlas-service/src/renderer.ts
packages/atlas-service/src/util.ts
packages/atlas-service/tsconfig-lint.json
packages/atlas-service/tsconfig.json
packages/compass-query-bar/package.json
packages/compass-query-bar/src/stores/query-bar-store.ts
packages/compass/package.json
packages/compass/src/main/application.ts
packages/compass/tsconfig-lint.json
packages/data-service/package.json

This patch is part of https://github.com/mongodb-js/compass/pull/4607 that adds the new atlas-service package that will be used to manage Atlas login state. Still need to add some tests, but the implementation is done and open for feedback

chore(atlas-service): add atlas-service package COMPASS-7029

---

packages/atlas-service/src/main.spec.ts
packages/atlas-service/src/main.ts
packages/compass-aggregations/src/typings.d.ts
packages/compass-query-bar/src/stores/ai-query-reducer.spec.ts
packages/compass-query-bar/src/stores/ai-query-reducer.ts

COMPASS-6990
We are now passing the `databaseName` and not passing the `sampleDocuments`.

chore(query-bar, atlas-service): update ai query prompt creation parameters COMPASS-6990

---

packages/atlas-service/src/main.spec.ts
packages/atlas-service/src/main.ts

Adding some more special handling for refresh token sync, was hard to spot during initial testing as on mocked scenarios it worked fine of course, but the way oidc-plugin actually works, refresh-token events are a bit misleading and without this additional check we would open a browser when refresh happens even though it's not required (this was kinda expected that this might happen sometimes, but I hoped we wouldn't run into this immediately).
~I actually still need to test this with a real token and non-modified plugin, but this takes a few hours and reading the plugin code more carefully I'm pretty sure that's the reason for the issue~ Left it running overnight, no browser windows opened, so confirmed that this seems to fix the issue

fix(atlas-service): listen to state-updated before attempting token refresh

---

packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.tsx
packages/compass-aggregations/src/utils/insights.ts
packages/compass-collection/src/components/collection-header/collection-header.tsx
packages/compass-components/src/components/document-list/document-actions-group.tsx
packages/compass-components/src/components/signals.tsx
packages/compass-components/src/index.ts
packages/compass-crud/src/components/crud-toolbar.tsx
packages/compass-crud/src/components/editable-document.tsx
packages/compass-crud/src/components/readonly-document.tsx
packages/compass-crud/src/utils/index.spec.ts
packages/compass-crud/src/utils/index.ts
packages/compass-explain-plan/src/components/explain-plan-side-summary.tsx
packages/compass-import-export/src/components/import-toast.tsx
packages/compass-import-export/src/import/import-csv.spec.ts
packages/compass-import-export/src/import/import-csv.ts
packages/compass-import-export/src/import/import-json.spec.ts
packages/compass-import-export/src/import/import-json.ts
packages/compass-import-export/src/import/import-types.ts
packages/compass-import-export/src/import/import-utils.spec.ts
packages/compass-import-export/src/import/import-utils.ts
packages/compass-import-export/src/modules/import.ts
packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
packages/compass-schema/src/components/field.tsx
packages/compass-sidebar/src/components/navigation-items.tsx
packages/databases-collections-list/src/databases.tsx

This patch adds an unbound array insight to schema, crud, and import:
|Schema|Document card|Toast on import|
|---|---|---|
|<img width="613" alt="image" src="https://github.com/mongodb-js/compass/assets/5036933/d94b2365-0c49-4f8c-b605-18ed0e1842c0">|<img width="768" alt="image" src="https://github.com/mongodb-js/compass/assets/5036933/d6f74ac3-eaf2-4528-90bb-0e6577d6f84b">|<img width="746" alt="image" src="https://github.com/mongodb-js/compass/assets/5036933/8129b2a1-d30d-4b2d-965a-d668a3c137b9">|
First commit just moves all signal definitions to one place to remove duplicates, something we discussed when implementing this initially

feat(crud, schema, import-export): show insight for unbound array COMPASS-6836

---

packages/compass-preferences-model/src/preferences.spec.ts
packages/compass-preferences-model/src/preferences.ts
packages/compass-preferences-model/src/storage.spec.ts
packages/compass-preferences-model/src/storage.ts

When storing data in preferences, we validate user preferences in Preference class and when reading, we validate in Storage class. 
In this PR, we aligned validation and handle it in Preferences class

chore(preferences): validate stored data in preferences COMPASS-7038

---

packages/compass-components/src/components/signal-popover.tsx
packages/compass-query-bar/src/components/option-editor.tsx

This was the same positioning we do for other editor buttons where they overlay the editor context, but in query bar this is too annoying, so instead the insight will push the whole editor to the left when visible
|Before|After|
|---|---|
|![image](https://github.com/mongodb-js/compass/assets/5036933/e3f48b37-52aa-43ff-8408-d6e0e6a918f8)|![image](https://github.com/mongodb-js/compass/assets/5036933/e575caec-7a8a-4a80-acd5-fd10a23c477c)|

chore(query-bar): change insights badge position to relative COMPASS-7036

---

packages/compass/src/app/index.jsx
packages/compass/src/main/application.ts
packages/compass/src/main/index.ts
packages/compass/src/setup-hadron-distribution.ts
packages/connection-storage/src/connection-storage.ts

This fixes an issue on main where secrets are missing from the saved connections. This issue **only affects local dev environment** and the root cause was mostly resolved in #4700, this was just one place where we missed it when converting storage class to static singleton. As a sort-of-related drive by I move all `app.set<prop>` calls that depend on `HADRON_*` variables to the existing `setup-hadron-distribution.ts` file and moved it at the very top of the entrypoint both for main and renderer processes, this doesn't have any effect beyond local dev or e2e runs, but should at least make it consistent even if we forget to use `app.get<prop>` directly in runtime somewhere

chore(connection-storage): make sure correct keychain service name is used by connection storage

---

package-lock.json
packages/atlas-service/package.json
packages/atlas-service/src/main.spec.ts
packages/atlas-service/src/main.ts
packages/compass/src/main/application.ts

This patch adds some logic to atlas-service package that persists and restores serialized auth state of oidc-plugin using system keychain. This means that if you are signed in and close Compass, you don't need to sign in again after re-opening it.
~Opening as draft to keep track of progress, as I need to switch to another task. The feature already works and existing tests were adjusted, but I still need to add some new tests for the added functionality~ Added some tests, so this is fully ready for review now

feat(atlas-service): securely persist and restore atlas login state through keychain

---

packages/compass-preferences-model/src/global-config.spec.ts
packages/compass-preferences-model/src/preferences.ts

fix(preferences): allow empty optional string flags COMPASS-7101

---

packages/compass-components/src/components/feedback-popover.tsx
packages/compass-components/src/components/generative-ai/ai-experience-entry.ts
packages/compass-components/src/components/generative-ai/ai-feedback.tsx
packages/compass-components/src/components/generative-ai/ai-text-input.spec.tsx
packages/compass-components/src/components/generative-ai/generative-ai-input.tsx
packages/compass-components/src/components/generative-ai/index.ts
packages/compass-components/src/components/generative-ai/robot-svg.tsx
packages/compass-components/src/index.ts
packages/compass-query-bar/src/components/query-ai.spec.tsx
packages/compass-query-bar/src/components/query-ai.tsx
packages/compass-query-bar/src/components/query-bar.tsx

Part of COMPASS-7105
We'll be using the same ai input and components in the aggregations implementation. To share them we're moving them to `compass-components` out of `compass-query-bar` and making them a bit more generic. There are still a few places we're using the `Query` terminology. That will be updated when we begin adding in aggregation syntax. Designs: https://www.figma.com/file/Ip4CPowv3Uxxhu3klyXA0e/Generative-AI-in-Compass-MVP?type=design&node-id=13-13954&mode=dev
No UX changes.

refactor(compass-components): move generative ai components to compass-components

---

configs/mocha-config-compass/main-process.js
configs/mocha-config-compass/register/electron-renderer-register.js
packages/compass-preferences-model/src/index.ts
packages/compass-preferences-model/src/setup-preferences.ts
packages/compass-query-bar/src/components/query-ai.spec.tsx
packages/compass-settings/src/components/settings/feature-preview.tsx
packages/compass-settings/src/components/settings/general.spec.tsx
packages/compass-settings/src/components/settings/general.tsx
packages/compass-settings/src/components/settings/oidc-settings.spec.tsx
packages/compass-settings/src/components/settings/oidc-settings.tsx
packages/compass-settings/src/components/settings/privacy.spec.tsx
packages/compass-settings/src/components/settings/privacy.tsx
packages/compass-settings/src/components/settings/settings-list.tsx
packages/compass-settings/src/stores/preferences-sandbox.spec.ts
packages/compass-settings/src/stores/settings.ts

Another clean-up PR I'm opening separately from the actual feature to make it easier to review.
I wanted to make sure that state subscriptions in the settings form are set up in a way that doesn't cause unnecessary re-renders when any value is changed in the store, so this patch changes settings-list to make every settings input a connected component that picks up required primitive values from the store based on `name` instead of settings list mapState functions generating new objects every render whether or not they changed. This also aligns the implementation with [redux style guide](https://redux.js.org/style-guide/#connect-more-components-to-read-data-from-the-store).
While doing this change I stumbled on a few existing small issues with the reducer: un-synced input value causing …

chore(compass-settings): update settings list and input component to have more granular state subscription COMPASS-7098

---

packages/atlas-service/src/main.spec.ts
packages/atlas-service/src/main.ts

This patch fixes the token refresh logic in atlas-service, in the previous patch that added token restore logic I tried to align the logic between refresh and restore which was a mistake because those emit different events. This patch fixes the issue by separating refresh and restore and making sure that refresh token waits only for refresh relevant events. Updated the diagram too to not forget that `tryRefresh` is a separate flow that can be called outside of `requestToken` one. I also added oidc logger hook as requested.

fix(atlas-service): seaprate token refresh and token restore flows; fix events that token refresh is listening to

---

packages/atlas-service/src/main.spec.ts
packages/atlas-service/src/main.ts
packages/atlas-service/src/renderer.ts
packages/atlas-service/src/util.ts
packages/compass-aggregations/src/modules/pipeline-builder/pipeline-ai.spec.ts
packages/compass-aggregations/src/modules/pipeline-builder/pipeline-ai.ts
packages/compass-query-bar/src/constants/query-properties.ts
packages/compass-query-bar/src/stores/ai-query-reducer.ts
packages/compass-query-bar/src/utils/query.ts

This patch makes the backend response validation stricter, adds some new tests and adjusts existing ones to account for the change

chore(atlas-service): add validation for backend response

---

packages/compass-components/src/components/generative-ai/ai-experience-entry.tsx
packages/compass-query-bar/src/components/query-bar.spec.tsx
packages/compass-query-bar/src/components/query-bar.tsx

COMPASS-7039
Shows an `Ask AI` button to the right of the filter input when the filter has content and the ai feature is enabled and closed.

feat(compass-query-bar): add ask ai button to query bar when filter has content COMPASS-7039

---

packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-ai.spec.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-ai.tsx
packages/compass-components/src/components/feedback-popover.spec.tsx
packages/compass-components/src/components/feedback-popover.tsx
packages/compass-components/src/components/generative-ai/ai-feedback.tsx
packages/compass-components/src/components/generative-ai/generative-ai-input.spec.tsx
packages/compass-components/src/components/generative-ai/generative-ai-input.tsx
packages/compass-query-bar/src/components/query-ai.spec.tsx
packages/compass-query-bar/src/components/query-ai.tsx

COMPASS-7120
This pr makes the ai feedback options hidden when `trackUsageStatistics` is disabled in preferences.
As this is still a dev feature flag and not a full preference yet we're not making it derive its setting based off `networkTraffic` just yet.

chore(compass-query-bar, compass-aggregations): hide ai feedback options when telemetry is disabled COMPASS-7120

---

configs/mocha-config-compass/register/compass-preferences-register.js
packages/atlas-service/src/main.spec.ts
packages/atlas-service/src/main.ts
packages/atlas-service/src/store/atlas-signin-reducer.spec.ts
packages/atlas-service/src/store/atlas-signin-reducer.ts
packages/compass-settings/src/components/modal.spec.tsx
packages/compass-settings/src/components/settings/atlas-login.spec.tsx
packages/compass-settings/src/components/settings/atlas-login.tsx
packages/compass-settings/src/components/settings/theme.spec.tsx
packages/compass-settings/src/components/sidebar.spec.tsx
packages/compass-settings/src/stores/index.ts

I merged https://github.com/mongodb-js/compass/pull/4742 without adding enough test coverage for the new behavior, this PR fixes it by adding more tests for "Atlas Login" settings section and for sign out behavior in atlas-service

chore(atlas-service, settings): add tests for settings section and sign out

---

packages/compass-aggregations/src/components/pipeline-toolbar/index.spec.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/index.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-stages.tsx

COMPASS-7136
Hides the `Ask AI` button when in results view.

fix(compass-aggregations): only show ai button when in edit mode COMPASS-7136

---

packages/compass-e2e-tests/tests/instance-sidebar.test.ts

Something we discussed with @mcasimir: for flaky tests that we open tickets for we'd want to add auto-retry as this is anyway what we are doing (just manually) while waiting for flake to be addressed

chore(e2e): auto-retry flaky 'can create a database and drop it' test

---

packages/atlas-service/src/main.spec.ts
packages/atlas-service/src/main.ts

Adds tracking as described in the scope of the project. We checked with CISO team that tracking email when tracking is enabled is okay from their perspective.

chore(atlas-service): add sign in tracking for atlas-service COMPASS-7112

---

packages/atlas-service/src/main.spec.ts
packages/atlas-service/src/main.ts

Just double-checked with product and even though we have confirmation from CISO we decided not to send emails to telemetry

chore(atlas-service): remove email from tracking info COMPASS-7112

---

packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/use-case-card.tsx

Updates the cursor on the stage wizard stages to grab and grabbing to show the drag and drop functionality.
Need to check with design if this is what we want to do, I think this came up as part of chatting to users. The wizard stages are also buttons which, on click, add the wizard at the bottom of the pipeline.

chore(compass-aggregations): update cursor to grabbing to show drag and drop functionality

---

packages/compass-query-bar/src/stores/query-bar-reducer.ts
packages/compass-query-bar/src/types.d.ts
packages/compass-query-bar/src/utils/index.spec.ts
packages/compass-query-bar/src/utils/index.ts

As reported in slack recently, the `isEqual` check is too loose for our case as the key order is important in MongoDB queries in some cases. Because we were considering `{ foo: 1, bar: 2 }`, and `{ bar: 2, foo: 1 }` the same, `query-changed` event would not emit in those cases, making it so that running the query would just run the same one again after updating the input

fix(query-bar): account for changed key order in query COMPASS-7194

---

packages/hadron-plugin-manager/lib/plugin-manager.js

COMPASS-6203
Updates the `Failed to load plugins` message in the logs to make it less likely to get folks to report it to Support.
I opted to make the message less error sounding, we could instead remove the `Hadron Plugin Manager` logs if we want as not many folks are using plugins.
*Before*
```
{"t":{"$date":"2023-09-06T14:09:48.463Z"},"s":"I","c":"COMPASS-PLUGINS","id":1001000141,"ctx":"Hadron Plugin Manager","msg":"Loading plugins from path /Users/rhys/.mongodb/compass/plugins"}
{"t":{"$date":"2023-09-06T14:09:48.506Z"},"s":"W","c":"COMPASS-PLUGINS","id":1001000142,"ctx":"Hadron Plugin Manager","msg":"Failed to load plugins","attr":{"path":"/Users/rhys/.mongodb/compass/plugins","message":"ENOENT: no such file or directory, scandir '/Users/rhys/.mongodb/compass/plugins'"}}
```
*After* …

chore(compass): update failed to load plugins message COMPASS-6203

---

packages/compass-aggregations/src/modules/insights.spec.ts
packages/compass-aggregations/src/modules/insights.ts
packages/compass-aggregations/src/utils/stage.js
packages/compass-explain-plan/src/stores/explain-plan-modal-store.spec.ts
packages/compass-explain-plan/src/stores/explain-plan-modal-store.ts

We learned that non-genuine MongoDB servers, in particular CosmosDB, will execute pipelines when running explain plan even in `queryPlanner` mode. This is especially harmful when pipeline contains one of the out stages: $merge or $out. While we usually don't try to address compatibility issues like that with with non-genuine servers, this one in particular can cause pretty bad data corruption issues, so we are fixing this by always removing out stages before running explain for aggregations for all servers. As a nice side-effect, this actually makes our visual explain plan more detailed for these kinds of pipelines.

fix(aggregations, explain-plan): remove out stages before running explain plan COMPASS-7012

---

packages/compass-aggregations/src/components/stage-preview/index.spec.tsx
packages/compass-aggregations/src/components/stage-preview/index.tsx

chore(aggregations): update search stage preview

---

packages/atlas-service/src/main.spec.ts
packages/atlas-service/src/main.ts
packages/atlas-service/src/util.ts
packages/compass-aggregations/src/components/pipeline-toolbar/index.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-stages.tsx
packages/compass-e2e-tests/helpers/atlas-service.ts
packages/compass-e2e-tests/tests/collection-ai-query.test.ts
packages/compass-preferences-model/src/feature-flags.ts
packages/compass-preferences-model/src/index.ts
packages/compass-preferences-model/src/preferences.ts
packages/compass-preferences-model/src/react.ts
packages/compass-preferences-model/src/utils.ts
packages/compass-query-bar/src/components/query-bar.spec.tsx
packages/compass-query-bar/src/components/query-bar.tsx
packages/compass-settings/src/components/settings/atlas-login.tsx
packages/compass-settings/src/components/settings/feature-preview.tsx

COMPASS-7193
This adds a request to the `hello` endpoint (https://github.com/10gen/compass-mongodb-com/pull/98). This returns if the ai feature is enabled/disabled. This will be used to incrementally rollout the ai feature.
We make a request to this endpoint every time Compass is started. I'm thinking we'll eventually remove this once we're feeling solid about the feature and have it released to everyone.
In [COMPASS-7147](https://jira.mongodb.org/browse/COMPASS-7147) we will add another preference for command line disabling the ai functionality.

feat(atlas-service): ping if ai feature enabled COMPASS-7193

---

packages/atlas-service/src/main.ts
packages/compass-preferences-model/src/preferences.spec.ts
packages/compass-preferences-model/src/preferences.ts
packages/compass-preferences-model/src/utils.ts
packages/compass-query-bar/src/components/query-bar.spec.tsx
packages/compass-settings/src/components/settings/privacy.spec.tsx
packages/compass-settings/src/components/settings/privacy.tsx

COMPASS-7147
This new setting `enableAIFeatures` can be set in the ui, cli, and global config file. Any ideas for better names?
With this we then allow a user to use the ai feature when: 
- This setting is set true.
- They receive a successful hello feature enabled response.
- We have enabled the feature flag (from `development` to `preview`). 
Here's how it looks:

feat(compass-preferences-model): add preference for enabling ai features COMPASS-7147

---

packages/compass/src/main/auto-update-manager.ts

We tracked these, but didn't log them. Got to a situation where the last log was "Update available" and the user says they accepted the update.

chore: add logging around downloading and dismissing updates

---

packages/compass-preferences-model/src/feature-flags.ts

[COMPASS-6866](https://jira.mongodb.org/browse/COMPASS-6866)
We'll be doing a beta today with the feature, now that we have other settings for managing this we can make the ai feature flag released.
- 'preview': the feature flag is disabled by default but shown under the Feature Preview settings.
- 'released': the feature flag is always enabled, is not read from disk and cannot be disabled from settings.

feat(preferences-model): update ai query and aggregations feature flag to released COMPASS-6866

---

packages/compass-aggregations/src/modules/is-modified.js

COMPASS-7234
Sets `isModified` to true after we load from the crud query generation, or the aggregation generation.

chore(aggregations): show confirmation on new pipeline click after an aggregation is generated COMPASS-7234

---

packages/compass/src/main/auto-update-manager.ts
packages/compass/src/main/auto-updater.ts

Working theory:
* the autoUpdates preference starts as disabled
* once preferences are loaded it transitions to enabled
* because it became enabled we transition to AutoUpdateManagerState.CheckingForUpdates
* this then kicks off the check which finds that there is an update available
This change:
* logs whether updates are supported or enabled up front (we were already logging enabled true/false, but likely too late).
* won't register the preference change event handler or enable the autoUpdater based on the preference at all if it is not supported
* logs if autoUpdate is not supported
* logs when the preference changes and we either kick off another check or disable

fix: more auto-update logging, disable if not supported COMPASS-7220

---

packages/compass-collection/src/stores/index.ts
packages/compass-connections/src/modules/telemetry.spec.ts
packages/compass-connections/src/modules/telemetry.ts
packages/compass-sidebar/src/components/connection-info-modal.tsx
packages/compass-sidebar/src/constants/server-version.js
packages/compass-sidebar/src/stores/store.js
packages/compass-sidebar/src/stores/store.spec.js

- Display “AtlasLocalDev” under the “Edition” section of the connection info modal. Also display “Atlas” for Atlas now, to be consistent with mongosh.
- Report telemetry for local Atlas dev environments.

feat: display local Atlas dev environments as such COMPASS-7156

---

packages/atlas-service/src/main.ts
packages/compass-aggregations/src/modules/pipeline-builder/pipeline-ai.ts
packages/compass-query-bar/src/stores/ai-query-reducer.ts

COMPASS-7228
From slack: https://mongodb.slack.com/archives/C05AH835WQN/p1695144172792419
This pr updates the logs to not include the schema and ai response with fields.

chore(atlas-service): dont log field names or schema in atlas service logs

---

packages/atlas-service/src/main.spec.ts
packages/atlas-service/src/main.ts
packages/atlas-service/src/renderer.ts
packages/atlas-service/src/util.ts
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-ai.tsx
packages/compass-aggregations/src/modules/pipeline-builder/pipeline-ai.spec.ts
packages/compass-aggregations/src/modules/pipeline-builder/pipeline-ai.ts
packages/compass-aggregations/src/stores/store.spec.ts
packages/compass-components/src/components/generative-ai/generative-ai-input.spec.tsx
packages/compass-components/src/components/generative-ai/generative-ai-input.tsx
packages/compass-e2e-tests/tests/collection-ai-query.test.ts
packages/compass-query-bar/src/components/query-ai.tsx
packages/compass-query-bar/src/stores/ai-query-reducer.spec.ts
packages/compass-query-bar/src/stores/ai-query-reducer.ts
packages/compass-utils/src/ipc.ts

- Handle error codes and other props from errors in the ui
- Disambiguate `errorCode` from `statusCode`
- Send also `errorCode` to telemetry
- Allow to serialize / de-serialize additional own properties of errors

feat: improve handling of AI errors COMPASS-7210

---

packages/atlas-service/src/util.ts
packages/compass-query-bar/src/stores/ai-query-reducer.ts
packages/compass/src/main/application.ts

Updates how we parse the ai query response when there's an aggregation. Previously we had `aggregation` inside of the `query` object. Now it's at the top level.
Similar update on Compass' backend: https://github.com/10gen/compass-mongodb-com/pull/99

chore(atlas-service): update ai query response handling with aggregation key COMPASS-7241

---

packages/compass-crud/src/utils/index.spec.ts
packages/compass-crud/src/utils/index.ts
packages/compass-schema/src/components/field.spec.tsx
packages/compass-schema/src/components/field.tsx
packages/hadron-document/src/element.ts

To address insight showing up for vector search, we decided to limit the insight only to when array contains other documents, @mcasimir suggested to add to this anything else that can be used as an id referencing a document, so we also check for integers, string, and objectid types. For everything else, including decimals, the insight will not be shown.

chore(insights): make unbound array check apply only to certain bson types COMPASS-7217

---

packages/compass-import-export/src/csv/csv-utils.ts
packages/compass-import-export/src/import/analyze-csv-fields.spec.ts
packages/compass-import-export/src/import/analyze-csv-fields.ts
packages/compass-import-export/src/import/import-csv.spec.ts

There are too many false positives when things look like regular expressions, so it is safer to just go with string. But I chose not to remove the detection because we don't want a validation error when a column _is_ all regexes and the user selects regex. And we do still want validation when selecting a regex.
So if a column has _some_ regexes it will still go with mixed or string. If the user selects type regex in that case it will give a validation warning with the first cell that doesn't look like a regex. If a column is _all_ regexes it will still go with string. If the user then selects a regex it won't complain.

fix: don't automatically select regex when detecting regex COMPASS-7144

---

packages/compass-preferences-model/src/preferences.ts
packages/compass/src/main/application.ts

COMPASS-7235
Updates `atlas-service`'s backend to mms prod. Renames the preference for the atlas config as it would be otherwise defaulting to whatever was previously there in Compass (this is a bug in our preference user data loading).

chore(atlas-service): always use mms prod, rename preference for atlas service backend COMPASS-7235

---

package-lock.json
packages/atlas-service/src/main.spec.ts
packages/atlas-service/src/main.ts
packages/compass-preferences-model/src/preferences.ts
packages/compass-settings/src/components/modal.tsx
packages/compass-settings/src/components/settings/oidc-settings.tsx

As described in COMPASS-7063, we want to use MongoDB server OIDC auth browser option for Atlas Login flow, this patch updates atlas-service to use property from preferences and updates documentation of the OIDC options to try to make it clear how they will apply.
I'll check description changes with product before merging this

chore(atlas-service): use server oidc browser setting for atlas login COMPASS-7063

---

package-lock.json
packages/hadron-build/lib/target.js
packages/hadron-build/package.json

Our .rpm and .deb dependencies haven't been updated in a long time and seem to depend on unnecessary things. This has started to become a problem because some distros have removed some of those.
Looking at electron-installer-redhat and electron-installer-debian they both mix in electron's own requirements so we don't have to specify things that electron depends on - just the extras.
Something I didn't solve here and don't think I can is that amazon linux 2023 removed gnome-keyring, so our .rpm package is still not going to be easy to install there.

fix: update .rpm and .deb deps and requirements COMPASS-7203

---

packages/compass/src/main/index.ts
packages/compass/src/setup-hadron-distribution.ts

Some users are still reporting crashing renderer and we can't figure out the reason, maybe being able to inspect crash dumps will help.
I tried it locally and it seems to work, I crashed renderer with an OOM and saw the reports saved in an expected directory (although I have no idea how to actually inspect the dmp file):

chore(compass-main): activate crash reporter for the application COMPASS-7281

---

packages/compass-preferences-model/src/preferences.ts
packages/compass/src/main/application.ts

`ELECTRON_EXTRA_ARGS="--atlasServiceBackendPreset=atlas-local" npm run start`

chore: add atlas-local to simplify local dev against mms

---

packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.spec.tsx
packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.tsx
packages/compass-indexes/src/modules/search-indexes.spec.ts
packages/compass-indexes/src/modules/search-indexes.ts

chore(search-indexes): only poll search indexes when there is connectivity to the cluster

---

configs/webpack-config-compass/package.json
package-lock.json
packages/compass-user-data/package.json
packages/connection-storage/package.json
packages/connection-storage/src/connection-storage.spec.ts
packages/connection-storage/src/connection-storage.ts

Follow up to dependabot PRs that are apparently not doing what we expect them to do

chore: update package.json to match package-lock versions

---

packages/hadron-build/commands/release.js
packages/hadron-build/lib/target.js

```
warning: ./mongodb-compass-dev-0.0.1-dev.0.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f9f5f923: NOKEY
gtk3
libnotify
nss
libXScrnSaver
libXtst
xdg-utils
at-spi2-core
libuuid
gnome-keyring
libsecret
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(PayloadIsXz) <= 5.2-1
```
```
$ dpkg -I ./mongodb-compass-dev_0.0.1-dev.0_amd64.deb
new Debian package, version 2.0.
size 102706482 bytes: control archive=498 bytes.
585 bytes,    13 lines      control
Package: mongodb-compass-dev
Version: 0.0.1-dev.0
Section: Databases
Priority: optional
Architecture: amd64
Depends: libgtk-3-0, libnotify4, libnss3, libxtst6, xdg-utils, libatspi2.0-0, libdrm2, libgbm1, libxcb-dri3-0, kde-cli-tools | kde-runtime | trash-cli | …
```

fix: use the electron version, not the app's version COMPASS-7305

---

packages/collection-model/lib/model.js
packages/data-service/src/data-service.ts
packages/database-model/lib/model.js
packages/instance-model/lib/model.js

This was reported in [Slack](https://mongodb.slack.com/archives/C0U7K0MC3/p1696014566461709) initially. I did some debugging and there were two issues that were causing this:
The error that ADF returns when trying to get collStats using aggregation pipeline is different from the one returned from the command:
So when we recently refactored this part of code to always use aggregation, the error was not ignored anymore. This patch fixes it by adding another check in the catch block to fix the regression.
While the issue is very noticeable on ADF, it was partially caused by the instance-model and was affecting all collections in general. This second issue is a bit more convoluted, this is something that was introduced a long time ago and because requires users to follow a very specific flow …

fix(data-service): ignore errors when fetching collStats in adf; always fetch collInfo COMPASS-7307

---

scripts/ai-accuracy-tests/index.js

Adds some instructions and support for the `atlas-local` environment for running the ai accuracy tests against a locally running mms.

chore(scripts): add support for running ai accuracy tests vs local mms

---

package-lock.json
packages/compass-indexes/src/components/indexes-table/indexes-table.tsx
packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.tsx

In this PR, added following UX changes:
1. Smaller table column widths in Search Indexes
2. Align Index Actions to the right

fix(search-indexes): smaller column widths COMPASS-7341

---

packages/data-service/src/data-service.ts

Most notably, address that we want to apply the timeout to the entire transaction (currently, the timeout only applies to the *starting* of the transaction, not the remainder of it).
As drive-by fixes, assign a new log id to the method instead of re-using an old one, and simplify the options extraction a bit.

fix(data-service): address review comments for previewUpdate

---

packages/compass-generative-ai/src/components/ai-experience-entry.tsx

COMPASS-7356
Hitting enter in the inputs was submitting these buttons as they don't have type `button` on them. This adds `type` `button` to these items.

fix(generative-ai): add type button html attribute so ai entry buttons don't get html form submit events COMPASS-7356

---

scripts/create-workspace.js

`reformat` can fail if eslint finds unfixable issues, an empty plugin package has some that are expected to be there, so instead of running reformat, we run prettier so that it doesn't fail

chore(scripts): don't use reformat when creating a new package

---

packages/compass-e2e-tests/tests/connection.test.ts

This db is in the `Compass data sets` deployment.
We might want to update this to not be the Compass data sets deployment as well.

chore(compass-e2e-tests): update e2e test db name to have e2e in it

---

configs/webpack-config-compass/src/externals.ts
package-lock.json
packages/atlas-service/package.json
packages/compass-app-stores/package.json
packages/compass-connection-import-export/package.json
packages/compass-editor/package.json
packages/compass-export-to-language/package.json
packages/compass-field-store/package.json
packages/compass-generative-ai/package.json
packages/compass-import-export/package.json
packages/compass-maybe-protect-connection-string/package.json
packages/compass-settings/package.json
packages/compass-test-server/package.json
packages/compass-user-data/package.json
packages/compass-utils/package.json
packages/compass-welcome/package.json
packages/connection-storage/package.json
packages/mongodb-query-util/package.json
scripts/create-workspace.js

A few small fixes that should address some issues that InTel team is seeing when trying to update dependencies:
- Add missing prod deps to user-data package, InTel can add them themselves, but we should be consistent here
- `electron` is externalized by default when packaging for electron webpack target, but not for browser, which bundles [this file](https://github.com/electron/electron/blob/main/npm/index.js) that also pulls in two more Node.js packages with it: `fs` and `path`. If we always externalize it, we can import on runtime and check that the import was missing or just completely replace / exclude it with with webpack using `alias: false`
- Also noticed that `compass-scripts check-exports-exist` wasn't added in every package, we missed adding it to workspace template, and a few …

chore(user-data, workspaces): add missing dependencies; always exclude electron from bundle; fix exports paths COMPASS-7361

---

packages/compass-e2e-tests/helpers/compass.ts
packages/compass-e2e-tests/tests/time-to-first-query.test.ts
packages/compass/src/setup-hadron-distribution.ts

Doesn't look like we can easily get to any useful info to actually debug the root cause why selenium (or devtools server?) fails to start in some cases, so we will just retry this test. If the issue resurfaces, then we can invest more time investigating

chore(e2e): retry ttfq test to work around the flake COMPASS-7374

---

.snyk

Not applicable to how the package is used inside `node-analytics` package

chore(snyk): ignore snyk-js-axios-6032459

---

packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/search/text-search.spec.tsx
packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/search/text-search.tsx
packages/compass-aggregations/src/components/stage-wizard/index.tsx
packages/compass-aggregations/test/form-helper.ts

In this PR, we made following changes:
1. Remove dashes from search types (text-search and fuzzy-search)
2. Rename `wildcard` to `any fields` and disable fields input when `any fields` is selected
3. For a stage wizard which is only applicable for Atlas, use Atlas Only badge to indicate that. 
**Before**
**After**

fix(stage-wizard): ux fixes for $search wizard

---

package-lock.json
packages/compass-collection/package.json
packages/compass-collection/src/stores/tabs.spec.ts
packages/compass-collection/src/stores/tabs.ts
packages/compass/src/app/index.jsx

No user-facing changes, just proxying electron ipc events through `globalAppRegistry` to avoid depending on electron in compass-collection plugin

chore(compass-collection): replace hadron-ipc usage with globalAppRegistry events COMPASS-7310

---

package-lock.json
packages/compass-schema/package.json
packages/compass-schema/src/stores/store.js
packages/compass/src/main/window-manager.ts

To make this plugins a bit more browser-friendly
|Before|After|
|---|---|
|![image](https://github.com/mongodb-js/compass/assets/5036933/645aeb0f-0b3e-4080-8616-22aff23f2ebb)|![image](https://github.com/mongodb-js/compass/assets/5036933/c0d51eda-8c6a-4890-903f-8dd5ad52f868)|
|![image](https://github.com/mongodb-js/compass/assets/5036933/9b28b937-2faa-45fe-933c-fcff5a32f967)|![image](https://github.com/mongodb-js/compass/assets/5036933/08ca629c-fb7d-4211-90ad-0613337b1de7)|

chore(compass-schema): replace hadron-ipc usage with toast component COMPASS-7311

---

packages/compass-aggregations/src/modules/side-panel.ts
packages/compass-aggregations/src/stores/store.ts

This new persistent state behavior wasn't taking preferences into account causing the feature to show up in data explorer / browser environment by default, even though it's disabled there and we don't even show the toggle button

chore(compass-aggregations): do not show stage wizard by default if the feature is disabled in preferences COMPASS-7361

---

packages/compass-components/src/components/document-list/element.tsx

| - | - |
| <img width="1154" alt="Screenshot 2023-11-02 at 10 20 17 AM" src="https://github.com/mongodb-js/compass/assets/1791149/6fe28deb-506d-4cc3-8f2b-67145a8f0236"> | <img width="1155" alt="Screenshot 2023-11-02 at 10 21 58 AM" src="https://github.com/mongodb-js/compass/assets/1791149/288ab4bb-4d55-470c-a942-f10b550eef5a"> |

chore(compass-components): update hover color on document field darkmode

---

packages/compass-home/src/components/workspace.tsx

COMPASS-7395
| - | - |
| <img width="329" alt="Screenshot 2023-11-06 at 11 10 10 AM" src="https://github.com/mongodb-js/compass/assets/1791149/248f9daf-76fa-4b73-b0c7-7dbd473c23a6"> | ![Screenshot 2023-11-06 at 10 54 17 AM](https://github.com/mongodb-js/compass/assets/1791149/024c7910-6a53-443c-80b5-47bbea1665b0) |

fix(compass-home): add z-index to shell container so it overlays sidebar content COMPASS-7395

---

packages/compass-crud/src/stores/crud-store.ts
packages/data-service/src/data-service.ts

Replaces https://github.com/mongodb-js/compass/pull/5049
I tested this manually. I can't immediately figure out how to write a unit test for this, but that's what session.withTransaction does by definition so I suppose we can trust the driver's tests.

feat: automatically retry the update preview on transient transaction errors COMPASS-7369

---

packages/compass-crud/src/stores/crud-store.ts

I now can't recreate the runtime error where the driver complains that we're transitioning from aborted state to aborted anymore. I think let's just enable it for now and then at least we have a chance of it happening again during development while this feature is still feature flagged and then if it does maybe we can at least figure out how to reproduce it?

feat(crud): abort in progress update previews COMPASS-7368	

---

packages/bson-transpilers/package.json
packages/compass-import-export/package.json
packages/compass-maybe-protect-connection-string/package.json
packages/compass-saved-aggregations-queries/package.json
packages/compass-settings/package.json
packages/compass-utils/package.json

Not really a dependency for anything, just aligns package.json with old compass expectations that productName is only provided in package.json file of plugin packages. This was helpful to get a list of plugins, so decided to commit

chore: only use productName in plugin packages

---

packages/compass-aggregations/src/components/stage-preview/output-stage-preview.spec.tsx
packages/compass-aggregations/src/components/stage-preview/output-stage-preview.tsx

Broke it in https://github.com/mongodb-js/compass/pull/5018 and didn't notice as the Compass default case was conveniently covered by existing tests. This fixes the issue and adds more tests (restructures them also a bit to make it clear what are the two different behaviors expected here)
(`no release notes` because this only affects mms in any meaningful way)

fix(compass-aggregations): fix preferences check for Atlas-only out stages preview

---

packages/compass-generative-ai/scripts/ai-accuracy-tests.js

COMPASS-7299
Adds a Spanish test, array project test, and another aggregation test. Also increased the timeout slightly as I'd occasionally get a rate limit.

chore(generative-ai): add additional accuracy tests COMPASS-7299

---

.evergreen/functions.yml
packages/compass-generative-ai/scripts/ai-accuracy-tests.js

COMPASS-7299
We'll be expanding the test results, this should make it so we can more easily look through the results overtime fi we want (rather than having to go through evergreen files/logs/s3 uploads).

chore(generative-ai): insert generative ai accuracy results to db on evergreen COMPASS-7299

---

scripts/logserver.js

I found it useful to use `jq` to filter the output of the logserver, but the logserver currently logs with `console.dir` which is not parsable by jq.  This PR auto-detects when the output of the script is piped writes the output accordingly.  I also added colors for the non-jq use case.

chore(scripts): make scripts/logserver.js output pipeable

---

packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/group-with-statistics.spec.tsx
packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/group-with-statistics.tsx

The `$count` accumulator doesn't take fields as parameter like the other accumulators. 
This was a pretty big assumption which now makes that specific case mess a bit the code, not sure if is the case to refactor it already, but in the interest of unblocking a release is probably a good idea to merge this one first.

fix(stage-wizard): remove field selector from $count

---

package-lock.json
packages/data-service/src/data-service.ts

Long story, but this is sorta related https://github.com/mongodb/node-mongodb-native/pull/3916 and I investigated the issue here https://github.com/lerouxb/unhandled-rejection
Should prevent this:

fix(data-service): don't abort the transaction from 'outside' the transaction COMPASS-7368

---

packages/compass-components/src/components/content-with-fallback.tsx

The fallback content kept rendering css keyframes with opacity 0 which ended up consuming a lot of CPU as seen in the Activity monitor. As I understand, we probably wanted to workaround the inability to animate css display property here and although with the change in place, there is a slight difference in the output, it is probably worth getting to normal CPU usage.

fix(compass-components): do not keep fallback content when not needed COMPASS-7417

---

packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts

fix(stage-wizard): indent generated stages

---

packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-stages.tsx
packages/compass-collection/src/modules/collection-tab.ts
packages/compass-components/src/components/leafygreen.tsx
packages/compass/src/setup-hadron-distribution.ts

This patch is a follow-up to #5118 and addresses more warnings that we can see in the devtools console in renderer. Some of them supressed, some of them are fixed, when possible

chore(compass): suppress some leafygreen warnings; fix react warnings

---

configs/webpack-config-compass/src/args.ts
configs/webpack-config-compass/src/index.ts
packages/compass-app-stores/webpack.config.js

Noticed that `publish-packages-next` is broken in CI. We added a provider to the plugin package, but the dist was never compiled, we forgot to update webpack config for that. This patch updated plugin webpack config to build `dist/provider.js`. Also as a drive-by I'm changing the way we're packaging umd to use a more universal globalObject, every environment we support has `globalThis` now

chore(app-stores): create provider dist

---

packages/compass-e2e-tests/tests/atlas-login.test.ts

Based on the screenshot in CI [this "should allow to accept TOS when signed in" test fails](https://spruce.mongodb.com/task/10gen_compass_main_macos_arm_test_packaged_app_60x_enterprise_patch_71cdcd4459594d1e7853f5ffd251855dc2f22cd6_6555f5642a60edf7d1473fa2_23_11_16_10_56_37/logs?execution=0&sortBy=STATUS&sortDir=ASC) because we check just a moment too early, you can kinda see the toggle being mid-switch animation. I'm adding a `waitFor` method similar to testing-library `waitFor` so that we can retry a few times to hopefully reduce the flake here

chore(e2e): wait for toggle to be checked with retries

---

packages/compass-editor/src/codemirror/document-autocompleter.ts
packages/compass-editor/src/codemirror/utils.test.ts
packages/compass-editor/src/editor.tsx
packages/compass-editor/src/index.ts
packages/compass-editor/test/completer.ts
packages/compass-query-bar/src/components/option-editor.spec.tsx
packages/compass-query-bar/src/components/option-editor.tsx
packages/compass-query-bar/src/components/query-option.tsx

Based on the slack discussion:
- Enable autoinsert of the empty query for all fields in query bar
- Enable autoremove of matching brackets on backspace
As a drive-by I renamed json-editor to editor, we wanted to do this for awhile

feat(query-bar): autoinsert empty document for all fields in the query bar

---

packages/compass-query-bar/src/components/query-history/favorite-list.spec.tsx
packages/compass-query-bar/src/components/query-history/favorite-list.tsx
packages/compass-query-bar/src/components/query-history/query-item/query-item-card.tsx
packages/compass-query-bar/src/plugin.spec.tsx
packages/compass-query-bar/src/stores/query-bar-reducer.spec.ts
packages/compass-query-bar/src/stores/query-bar-reducer.ts
packages/compass-query-bar/src/stores/query-bar-store.ts

feat: saved update queries do not open the modal in readonly mode COMPASS-7460

---

packages/compass-e2e-tests/tests/collection-bulk-delete.test.ts
packages/compass-e2e-tests/tests/collection-bulk-update.test.ts

Follow-up from https://github.com/mongodb-js/compass/pull/5140

chore(e2e): check the new readonly filter in e2e tests COMPASS-7488

---

package-lock.json
packages/compass-connections/src/components/connections.tsx
packages/compass-connections/src/stores/connections-store.ts
packages/connection-form/package.json
packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-gssapi.spec.tsx
packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-gssapi.tsx
packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.spec.tsx
packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.tsx
packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-tab.tsx
packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.tsx
packages/connection-form/src/components/connection-form.spec.tsx
packages/connection-form/src/components/connection-form.tsx
packages/connection-form/src/hooks/use-connect-form-preferences.tsx
packages/connection-form/src/hooks/use-connect-form.ts
packages/connection-form/src/utils/force-connection-options.spec.ts
packages/connection-form/src/utils/force-connection-options.ts
packages/connection-form/src/utils/oidc-handler.spec.ts
packages/connection-form/src/utils/oidc-handler.ts

@himanshusinghs @Anemy this should allow to use the form in VSCode without extra deps and have it reflect potential changes from VSCode preferences. Feel free to do what you deem best with it, so this is not a blocker while I'm out in any way.

chore(connection-form): split connection form from compass preferences

---

packages/compass-editor/src/editor.tsx

COMPASS-7477
Some more discussion on slack https://mongodb.slack.com/archives/G2L10JAV7/p1701094084478219
Updates the code mirror autocomplete tooltip to attach to the dom body as the parent so that the containment context we are adding for container queries don't change the layout.

fix(compass-editor): fix code mirror autocomplete positioning COMPASS-7477

---

packages/compass-aggregations/src/components/modify-source-banner/modify-source-banner.tsx
packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace/index.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/index.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-toolbar-container.tsx

Moves "modifying pipeline ..." banner to the pipeline toolbar so that it stays on the screen when scrolling the stages. Also added the same collapsing logic we have for other buttons in the toolbar to the view switch:
|Before|After|
|---|---|
|![image](https://github.com/mongodb-js/compass/assets/5036933/6b9dd9b6-6686-4c3d-a600-5bca78acc81e)|![image](https://github.com/mongodb-js/compass/assets/5036933/1d50614a-7c1d-49ed-99cb-92b4bb601642)|
|![image](https://github.com/mongodb-js/compass/assets/5036933/293d3026-a151-4d46-8046-4dbf4d01edc0)|![image](https://github.com/mongodb-js/compass/assets/5036933/52ff3ea7-46dc-4421-ba07-1daa31b2ad71)|

chore(aggregations): move 'modifying pipeline ...' banner to the pipeline toolbar

---

package-lock.json
packages/compass-components/src/components/file-input.spec.tsx
packages/compass-components/src/components/file-input.tsx
packages/compass-components/src/index.ts
packages/compass-connection-import-export/package.json
packages/compass-connection-import-export/src/components/file-input.tsx
packages/compass-home/src/components/home.tsx
packages/compass-import-export/src/components/export-modal.tsx
packages/compass-import-export/src/components/import-file-input.tsx
packages/compass-indexes/src/components/search-indexes-modals/create-search-index-modal.spec.tsx
packages/connection-form/src/components/advanced-options-tabs/ssh-tunnel-tab/ssh-tunnel-identity.tsx
packages/connection-form/src/components/advanced-options-tabs/tls-ssl-tab/tls-certificate-authority.tsx
packages/connection-form/src/components/advanced-options-tabs/tls-ssl-tab/tls-client-certificate.tsx

VSCODE-484
This pr adds a `FileInputBackendProvider` which provides a backend for the `FileInput` component to use for opening and saving files. The `connection-form` in VSCode is rendered in a `WebView`, [WebViews](https://code.visualstudio.com/api/extension-guides/webview) have limited permissions and require file access to be done by the main extension, so we will do some messaging for file system access. This new provider gives us the ability to support the different environments.

feat(components): add file input backend provider to allow different file backend environments  VSCODE-484

---

package-lock.json
packages/connection-form/package.json

Only used for types, this makes it so we don't need to add some polyfills in VSCode. VSCODE-488

chore(deps): move connection-storage to dev deps in connection form

---

packages/connection-form/src/components/advanced-options-tabs/advanced-tab/advanced-tab.tsx
packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-default.tsx
packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-tab.spec.tsx
packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-tab.tsx
packages/connection-form/src/utils/authentication-handler.ts

VSCODE-488
This is so we can exclude it from the webview webpack in VSCODE without erroring. We could alternatively add a lot of polyfills (os-browserify path-browserify stream-http timers-browserify url util browserify-zlib) and keep it included. Excluding it seems a bit simpler and probably reduces bundle size.

chore(connection-form): use mongodb dep only with types VSCODE-488

---

packages/compass-components/src/components/workspace-tabs/tab.tsx
packages/compass-components/src/components/workspace-tabs/workspace-tabs.tsx
packages/compass-e2e-tests/helpers/commands/collection-workspaces.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-workspaces/src/components/workspaces.tsx

Small UI changes to tabs based on design feedback:
* view tab breadcrumb now shows the source collection
* for tabs with longer subtitles, we bump the min width now so that you see more label on hover
|Before|After|
|---|---|
|![image](https://github.com/mongodb-js/compass/assets/5036933/d4a3f403-9f87-4b76-9e04-ccf30d1274e2)|![image](https://github.com/mongodb-js/compass/assets/5036933/82ab1e89-37af-4afd-b770-7454572a4b13)|

chore(workspaces): show view source name in breadcrumb; allow more width for longer breadcrumbs

---

packages/compass-components/src/index.ts
packages/compass-components/src/utils/reset-global-css.ts
packages/compass-home/src/components/home.tsx
packages/compass/src/app/styles/index.less

VSCODE-484
This is so that we can use the same reset css in VSCode. Open to other thoughts or approaches for this. (This was something I missed in the tech design oops).

chore(compass-components): add global css reset to compass-components, use in compass-home

---

packages/connection-form/.eslintrc.js

This is a follow up for the [PR-5197](https://github.com/mongodb-js/compass/pull/5197) where we moved 'mongodb' to devDependencies in connection-form. In this PR we are restricting imports from 'mongodb' package to type only to avoid any possible regression in future.

chore: allow type only imports for 'mongodb' package in connection-form

---

package-lock.json
packages/compass-preferences-model/.depcheckrc
packages/compass-preferences-model/package.json
packages/compass-serverstats/package.json
packages/compass-serverstats/src/stores/dberror-store.js

Remove the use of `mongodb-js-errors` package, which was only meant to be affecting the error message of top missing for shards, but that corner case is already handled more gracefully right now:

chore: remove mongodb-js-errors and unused ampersand packages

---

.evergreen/functions.yml
packages/atlas-service/src/secret-store.ts
packages/compass-e2e-tests/tests/atlas-login.test.ts
packages/compass-e2e-tests/tests/import-export-connections.test.ts
packages/compass-e2e-tests/tests/oidc.test.ts
packages/compass/src/app/auto-connect.spec.ts
packages/compass/src/main/application.ts
packages/connection-storage/src/connection-storage.ts

In this PR we are enabling keychain on CI for Linux by using plain-text method to store the credentials. As we are not using keytar to access the keychain, its not triggered at all and hence does not require us to set keychain management on CI or does not block the tests.

tests: enable keychain on ci for linux COMPASS-6119

---

packages/compass-collection/src/components/collection-tab-provider.tsx
packages/compass-collection/src/components/collection-tab.tsx
packages/hadron-app-registry/src/register-plugin.tsx

This patch adds new method to the hadron plugin interface: `useActivate` is a hook that allows to activate plugins (setup store and subscrible to appRegistry events in the current appRegistry scope) without rendering the component first. This is needed for the collection sub tabs so that certain sub tab plugins, like schema or indexes can start listening to events before the sub tab is open for the first time (this is when `plugin.activate` is first called currently as it is part of component rendering lifecycle).

chore(app-registry): add useActivate hook to activate plugins without rendering

---

package-lock.json
packages/compass-aggregations/src/components/pipeline-toolbar/index.spec.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.spec.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.tsx
packages/compass-aggregations/src/components/stage-toolbar/option-menu.spec.tsx
packages/compass-aggregations/src/components/stage-toolbar/option-menu.tsx
packages/compass-components/src/components/options-toggle.spec.tsx
packages/compass-components/src/components/options-toggle.tsx
packages/compass-components/src/index.ts
packages/compass-query-bar/src/components/query-bar.tsx

Brings in some more consistency with the query bar changes.
| - | - |
| ![Screenshot 2023-12-12 at 11 26 17 AM](https://github.com/mongodb-js/compass/assets/1791149/d4c0935f-ea62-48b1-8427-85bf99a4214e) | ![Screenshot 2023-12-12 at 11 26 40 AM](https://github.com/mongodb-js/compass/assets/1791149/41cf2b8c-5224-4678-af0b-23e89097d385) |

chore(compass-aggregations): remove more and fewer from options button label

---

packages/compass-crud/src/components/bulk-update-dialog.tsx

I thought I pushed this before merging the ChangeView PR.

chore: marginally better bulk update modal sizing

---

packages/compass-aggregations/src/components/stage-wizard/index.tsx
packages/compass-aggregations/src/utils/get-schema.spec.ts
packages/compass-aggregations/src/utils/get-schema.ts

Fixes two issues:
- we started passing HadronDocuments to the get schema instead of the actual objects leading to incorrect schema being calculated
- get schema wasn't handling potentially recursive objects well, failing with stack overflow in those cases

fix(aggregations): pass object to the get schema; make sure get schema handles recursive deps

---

packages/compass-crud/src/components/bulk-update-modal.tsx

I suppose it is inevitable that someone's going to _want_ to save the broken query they are working on, but oh well.

feat(crud): disable the save button if the update query is invalid

---

packages/compass-crud/src/components/bulk-actions-toasts.tsx

Otherwise folks might not know things updated if they looked away. I'm thinking this timeout here may have been unintended, there isn't one for the success state. 
I also feel showing errors in a toast without giving more information on the error might be a rough ux pattern, but that's another discussion to have another time.

fix(bulk-update): remove timeout on error toast

---

packages/compass-app-stores/src/stores/instance-store.ts
packages/compass-e2e-tests/tests/collection-import.test.ts

This doesn't have any high user impact currently. It causes stats to not update, but we already consider those "optional" when fetching. Added a test to cover this too

fix(instance): fix namespace stats refresh after document update

---

packages/compass-crud/src/components/bulk-update-modal.tsx

fix(crud): scroll the bulk update preview without its heading

---

packages/compass-query-bar/src/components/hooks.tsx
packages/compass-query-bar/src/index.tsx

I'm splitting this patch out of compass-web PR as it's fairly independant, should make reviewing both easier.
This is not strictly required for compass-web project, we obviously want the query bar to be rendered there too, but makes it easier to work on the package gradually adding new plugins, makes testing some things in isolation simpler, and also this is closer to the old behavior where not having query bar "registered" would not return a component

chore(query-bar): render query bar component only when query bar store rendered

---

configs/mocha-config-compass/react.js
configs/mocha-config-compass/register/jsdom-extra-mocks-register.js
packages/compass-components/src/components/compass-components-provider.tsx
packages/compass-components/src/components/guide-cue/guide-cue.tsx
packages/compass-components/src/index.ts
packages/compass-home/src/components/home.tsx

I'm splitting this patch out of compass-web PR as it's fairly independant, should make reviewing both easier.
This PR moves all compass-components providers into a single one that is then used in home. We will need to do literally the same setup in compass-web, so it's convenient to have them all combined in one like that
It's a bit annoying to review because stuff in home moved around, but not much was actually changed: there is only one provider import instead of multiple ones and all the theme logic was also removed as it's all encapsulated by this new provider now.

chore(compass-components, home): move all compass components provider into a single component

---

configs/webpack-config-compass/src/index.ts

This was never accounting for tsx before, but some packages do have these files as main export entry point, didn't notice until now that the webpack is not set up to handle this

chore(webpack): look for tsx when trying to find an entry file for the config

---

package-lock.json
packages/compass-connections/package.json
packages/compass-connections/src/stores/connections-store.ts
packages/compass-connections/tsconfig.json
packages/compass-e2e-tests/tests/logging.test.ts
packages/data-service/src/connection-attempt.spec.ts
packages/data-service/src/connection-attempt.ts
packages/data-service/src/index.ts

So we can use this in https://github.com/mongodb-js/vscode/pull/631 without copy pasting the module

chore(data-service): move connection attempt into data service for vscode usage

---

packages/data-service/src/data-service.spec.ts
packages/data-service/src/data-service.ts
packages/data-service/src/run-command.ts
packages/data-service/test/helpers.ts

Update DataService to support some streams operations required by VS Code extension.
- Do the new methods need to annotated with @op and what would be the `logId` for them if so?

chore: add streams operation methods to DataService COMPASS-7553

---

packages/compass-indexes/src/components/indexes-table/indexes-table.tsx
packages/compass-indexes/src/components/regular-indexes-table/regular-indexes-table.tsx
packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.tsx

The issue was caused by table height that we use for size calculation not being up to date at the moment of calculating the exact height we were setting on the table. In particular the fact that items in the table could be added or removed was not taken into account at all and that at the moment of reading the values, the items might've not been rendered yet. This patch fixes the issue by removing reliance on the actual table content completely and using `maxHeight` instead.
As a drive-by I changed the rendering a bit to make sure everything that can be memoed is and that we are not calling `css` in render.

fix(indexes): fix table card autosizing COMPASS-7548

---

packages/compass-workspaces/src/stores/workspaces.spec.ts
packages/compass-workspaces/src/stores/workspaces.ts

Users are reporting a regression compared to the old tab behavior where if you already have a certain namespace open in a tab, trying to open the same namespace when active tab is for a different namespace will just move tab active state to the existing tab instead of opening it in the currently active tab. This patch fixes the issue and adds a test to make sure we don't break this unintentionally.

fix(workspaces): open workspace in the same tab when tab type is the same COMPASS-7556

---

packages/compass-e2e-tests/tests/collection-bulk-update.test.ts

This flakes in CI sometimes and it doesn't really matter if the code is indented or not.
```
1) Bulk Update
can save an update query as a favourite and return to it:
AssertionError: expected '{\n $set: {\n  k: 0\n }\n}' to equal '{ $set: { k: 0 } }'
+ expected - actual
-{
- $set: {
-  k: 0
- }
-}
+{ $set: { k: 0 } }
```

chore: Do a regex match on the expected text rather than equality.

---

packages/connection-form/src/components/connection-form-actions.spec.tsx
packages/connection-form/src/components/connection-form-actions.tsx
packages/connection-form/src/components/connection-form.spec.tsx
packages/connection-form/src/components/connection-form.tsx
packages/connection-form/src/hooks/use-connect-form-preferences.tsx

Part of VSCODE-406
This adds a `showFavoriteActions` preferences for the connection form. When set to false the actions around favoriting a connection are hidden. These actions are Compass specific and something we don't want shown in VSCode.

feat(connection-form): add show favorite actions preference, make save prop required VSCODE-406

---

packages/compass-e2e-tests/helpers/chrome-startup-flags.ts
packages/compass-e2e-tests/helpers/compass.ts
packages/compass-e2e-tests/tests/import-export-connections.test.ts
packages/compass/src/main/index.ts
packages/connection-storage/src/connection-storage.ts

In E2E tests we _always_ specify --ignore-additional-command-line-flags and there are _always_ extra command line flags, yet sometimes we're seeing the test `Connection Import / Export` / `can export and import connections through the CLI, protected` (or also plaintext) flake out with this output:
```
FAILURE:  ()
Command failed: /System/Volumes/Data/data/mci/2a7c77e72c4857fd84641f9b71e42597/tmp/from-packaged/MongoDB Compass Dev.app/Contents/MacOS/MongoDB Compass Dev /System/Volumes/Data/data/mci/2a7c77e72c4857fd84641f9b71e42597/src/packages/compass --enable-automation --disable-popup-blocking --disable-extensions --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --metrics-recording-only --disable-default-apps …
```

chore: add some logs for clarification when there are parse errors in the CLI

---

packages/compass-web/package.json
packages/connection-form/src/index.ts

The `check-exports-exist` was failing as we're not currently building a index.d.ts in this package. This pr updates where we link the types and the type entry location so that it successfully completes the checks and has a type. I'm thinking we might want a higher level index.d.ts that includes the sandbox also if that's to be used, I don't know how we'll be using this down the line so that can wait for later work cc @gribnoysup

chore(compass-web): fix type export to unblock package update publishes

---

packages/compass-web/package.json
packages/compass-web/tsconfig-build.json
packages/compass-web/tsconfig.json

Small follow-up to https://github.com/mongodb-js/compass/pull/5337

chore(web): use a separate tsconfig for emitting declarations so that sandbox code is not included

---

packages/compass-e2e-tests/helpers/commands/add-collection.ts
packages/compass-e2e-tests/helpers/commands/click-visible.ts
packages/compass-e2e-tests/helpers/commands/screenshot.ts
packages/compass-e2e-tests/helpers/compass.ts
packages/compass-e2e-tests/tests/in-use-encryption.test.ts
packages/compass-e2e-tests/tests/instance-databases-tab.test.ts
packages/databases-collections/src/components/collation-fields/collation-fields.jsx

Debugging and maybe fixing the e2e test flake where we click on a menu option to select it yet it never seems to have an effect.
As a drive-by I'm also fixing our screenshotting:
* browser.saveScreenshot() is webdriver's command and in order to use it properly we have to give it a full "absolute" path to the screenshot so that the file ends up in a directory (probably .logs) that we'll upload to S3.
* browser.screenshot() is our command that calls browser.saveScreenshot(). It takes a filename only and path.join()s that together with the path where screenshots are supposed to go so you don't have to import that and join it together everywhere.
* browser.clickVisible(selector, options) takes screenshot as an option and it is supposed to just be a filename because it gets passed to …

chore(e2e): scroll to the custom collation field option before clicking and take a screenshot, fix css selector COMPASS-7569

---

package-lock.json
packages/compass-web/package.json

This fixes scram-sha256 connections in the web sandbox
- Bump mongodb-browser to the version that doesn't alias saslprep to the empty module in the build (https://github.com/gribnoysup/mongodb-browser/commit/b2e807ad6ea73f73c4e59a4692936b608f0871a7)
- Bump saslprep (in package-lock) to the version that is browser-compatible so that it can be bundled safely (https://github.com/mongodb-js/devtools-shared/pull/202)

chore(web): bump mongodb-browser; bump saslprep to web compatible version

---

packages/compass-components/src/components/document-list/element-editors.tsx

Our document keys were getting ellipsized on Safari. Apparently when we set the element width to `${element.length}ch` with rest of ellipses creating css, this css is rendered differently on Safari. On any other browser, we would not see any ellipses for the text if the width is available but on Safari, even after having enough width the ellipses comes up. I haven't figure out a reason for that just yet but I guess it might just be different implementation details between browsers.
[Here's](https://codesandbox.io/p/sandbox/elastic-mendeleev-flh8mq?file=%2Fstyles.css) a minimal repro to test this issue.

fix(compass-components): prevent document keys from getting ellipsized on safari COMPASS-7377

---

.evergreen/buildvariants.yml
.evergreen/functions.yml
.evergreen/tasks.yml
package-lock.json
packages/compass-components/src/components/document-list/element-editors.tsx
packages/hadron-build/commands/release.js
packages/hadron-build/lib/signtool.js
packages/hadron-build/lib/target.js
packages/hadron-build/package.json
packages/hadron-build/signtool/go.mod
packages/hadron-build/signtool/signtool.go
packages/hadron-build/test/signtool.test.js

In this PR, we are signing all the remaining compass artifacts - for windows, macos (zip only) and rhel. Steps to verify a files are similar to the one in https://github.com/mongodb-js/compass/pull/5334. 
For windows `.exe` and `.msi`, the files should have a digital signature, chrome (when downloading) and os (when installing) should not complain.

chore(build): sign all artifacts COMPASS-7549

---

.snyk

COMPASS-7570
Previously we had this for a month, updated to 6 months so we don't have to do this monthly.
We don't use valueFormatter and we have our own CellRenderer component.

chore: extend aggrid snyk ignore policy for 6 months COMPASS-7570

---

configs/webpack-config-compass/package.json
package-lock.json

`npm run bootstrap` started failing on main pointing to outdated browserlist. This should fix it.

chore(webpack-config-compass): fixes bootstrap failures related to browserlist

---

.evergreen/tasks.in.yml
.evergreen/tasks.yml

So that when next time something breaks, we have some logs we can look at from the signing process

chore(ci): output sign tools debug log so that we can see signing errors

---

package-lock.json
packages/atlas-service/src/main.spec.ts
packages/atlas-service/src/main.ts
packages/compass-e2e-tests/tests/intercom.test.ts
packages/compass-preferences-model/src/compass-utils.ts
packages/compass-preferences-model/src/preferences-schema.ts
packages/compass-preferences-model/src/utils.ts
packages/compass/src/app/index.tsx
packages/compass/src/app/intercom/setup-intercom.spec.ts
packages/compass/src/app/intercom/setup-intercom.ts
packages/compass/src/index.d.ts
packages/compass/src/main/application.ts
packages/compass/webpack.config.js

We changd the interface for `getActiveUser` some time ago without updating all the places where it is called. The issue was hidden by the error being silently swallowed and the file being JS, not TS, so the issue wasn't caught by our ts checks.
What complicates using the current `getActiveUser` implementation in renderer is that it requires passing UserStorage instance that is only available in the main process when setting up the preferences for the first time, so the fix is to sync additional user data to the preferences so that all of it can be pulled from preferences instead of using UserStorage directly.
I also converted this file to typescript so that we hopefully don't run into something like this here in the future.

fix(compass): make sure we get active user info when setting up intercom

---

packages/compass-crud/src/components/delete-data-menu.tsx
packages/compass-crud/src/components/update-data-menu.tsx

fix(crud): hide update/delete labels on narrow windows

---

packages/compass-web/webpack.config.js

Two small issues with compass-web webpack config I ran into now that I'm actually trying to integrate the package in the mms codebase:
- `output.library` was incorrectly specifying the `name` prop for the commonjs output type causing incorrect export namespacing in the dist. As a drive-by I also switched it to `commonjs-static` which based on the webpack doc should make it interop between esm and commonjs easier
- `react` / `react-dom` was incorrectly bundled with the package causing the `more than 1 react instance detected` error on mount
Also added a ticket number for the TODO about moving browser-ready driver code to the monorepo

fix(compass-web): do not bundle react with the package; make sure webpack doesn't namespace the library output

---

packages/compass/src/main/telemetry.ts

https://jira.mongodb.org/browse/COMPASS-7609
Removing userId from identify and track. This will be replaced by AUID in a following subtask and PR.

fix(compass): remove userId from telemetry calls MONGOSH-7609

---

packages/compass-e2e-tests/tests/collection-rename.test.ts
packages/databases-collections/src/components/rename-collection-modal/rename-collection-modal.spec.tsx
packages/databases-collections/src/components/rename-collection-modal/rename-collection-modal.tsx
packages/databases-collections/src/index.ts
packages/databases-collections/src/modules/rename-collection/rename-collection.spec.ts
packages/databases-collections/src/modules/rename-collection/rename-collection.ts
packages/databases-collections/src/stores/rename-collection.spec.tsx
packages/databases-collections/src/stores/rename-collection.ts

This PR addresses design feedback on the rename collection flow from Misba.  Below, I've copied the feedback from the description of the ticket: 
> 1. Disable the "Proceed to rename" button when the user enters the name of a collection that already exists in the current database and display an error with the following text: `This collection name already exists in this database`
> 	- (follow up to 1.) On the off-chance that a collection is created in the background / from another connection and Compass doesn't have knowledge of it, the user could conceivably attempt to rename a collection to an existing collection that Compass has no knowledge of.  We should handle the "target namespace exists" error that the server returns and display the same error text as 1.  
> 2. Disable the `Proceed …

fix(databases-collections): address design feedback on the rename collection flow COMPASS-7504

---

packages/compass/src/main/handle-error.ts
packages/compass/src/main/handle-uncaught-exception.ts
packages/compass/src/main/handle-unhandled-rejection.ts
packages/compass/src/main/index.ts

We have an unhandled exception handler in compass, but no unhandled rejection handler. This adds one.

chore: add main process unhandled rejection handler COMPASS-7268

---

packages/data-service/src/data-service.ts

I'm trying to work out how an e2e test made it all the way to the databases list and then clicked on the refresh button yet the relevant client in data-service still wasn't initialised? Did previous usage of data-service use the other client?

chore(data-service): call out _which_ client wasn't initialised

---

package-lock.json
packages/compass-aggregations/src/components/pipeline-toolbar/index.spec.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.spec.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/index.tsx
packages/compass-aggregations/src/modules/index.ts
packages/compass-aggregations/src/modules/saved-pipeline.ts
packages/compass-aggregations/src/stores/store.ts
packages/compass-aggregations/test/configure-store.ts
packages/compass-crud/src/stores/crud-store.ts
packages/compass-preferences-model/src/preferences-schema.ts
packages/compass-query-bar/src/components/query-bar.spec.tsx
packages/compass-query-bar/src/components/query-bar.tsx
packages/compass-query-bar/src/stores/query-bar-reducer.ts
packages/compass-query-bar/src/stores/query-bar-store.ts
packages/compass-saved-aggregations-queries/src/index.spec.tsx
packages/compass-saved-aggregations-queries/src/stores/aggregations-queries-items.ts
packages/compass-saved-aggregations-queries/src/stores/delete-item.ts
packages/compass-saved-aggregations-queries/src/stores/edit-item.ts
packages/compass-saved-aggregations-queries/src/stores/index.ts
packages/compass-web/src/index.tsx
packages/my-queries-storage/package.json
packages/my-queries-storage/src/provider.ts

A followup of #5384 in which I missed taking into account how the injection of PipelineStorage and QueryStorage will behave on compass-web. As it turn out we have these features disabled on DE and currently its not in the plan to have them enabled at any point.
This PR marks `PipelineStorage` and `QueryStorage` optional and every part of code which depends on them are modified to deal with the possibility of them being not there.
Additionally we have removed the preference `enableSavedAggregationsQueries` to simplify the dependency between the preference itself and the presence of the storages in contexts. Now we will impose the UI restrictions that earlier were done using the preference, now with the presence/absence of storage value in the context.

chore: fix for compass-web sandbox reporting about missing providers

---

.evergreen/functions.yml
.evergreen/preinstall.sh

With this PR:
* On RHEL 7.6, use an unofficial build.
* We package compass for ubuntu on 16.04 and there we also use the same unofficial build.
* On windows, mac and other ubuntu tasks we use the official build.

chore(ci): use node v20.11.1 in CI

---

packages/atlas-service/src/main.spec.ts
packages/atlas-service/src/main.ts
packages/atlas-service/src/util.spec.ts
packages/atlas-service/src/util.ts
packages/compass-e2e-tests/tests/atlas-login.test.ts
packages/compass-e2e-tests/tests/logging.test.ts
packages/compass-preferences-model/src/preferences-schema.ts
packages/compass/src/main/telemetry.ts

https://jira.mongodb.org/browse/COMPASS-7610
Main changes:
- upon successful atlas login, `telemetryAtlasUserId` is stored in the preferences
- this is then send under `userId` for telemetry calls (`track` and `identify`)
- directly after the user logges in with Atlas, an `identify` call is made
- `identify` call is only send if the `userId = telemetryAtlasUserId` is known
On Logging out:
When the user logs out, we don't clean up the `telemetryAtlasUserId`. this means subsequent identify calls might still be made and they will include the last known `telemetryAtlasUserId`. I discussed this with @gribnoysup and he explained such cleanup would be superfluous since the two ids (anonymous and auid) are anyway coupled in the records by then.
On tests:
I didn't find any existing telemetry unit …

fix: send atlas uid as userId to compass telemetry COMPASS-7610

---

packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.spec.tsx
packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.tsx

See thread https://mongodb.slack.com/archives/G2L10JAV7/p1708594823285709
I'm thinking if we end up doing more changes to these modals it would be nice to separate out the modal from the form to keep the interfaces a little tighter and less prone to these bugs.

fix(compass-indexes): reset atlas search index on reopen and type change

---

.evergreen/buildvariants.yml
.evergreen/config.json
.evergreen/tasks.yml

Downloading chromedriver broke via @puppeteer/browsers which is used in webdriverio and at the time I removed chrome from our tasks. This adds it back again now that that's been fixed.

chore(e2e): add back chrome browser tests for compass-web

---

packages/compass/src/main/index.ts

Looks like this was harmless before the release of macOS Sonoma.

fix: don't include the version number in process.title because it shows in the menubar in macOS Sonoma COMPASS-7513

---

package-lock.json
packages/compass-e2e-tests/tests/collection-rename.test.ts
packages/databases-collections/package.json
packages/databases-collections/src/components/rename-collection-modal/rename-collection-modal.spec.tsx
packages/databases-collections/src/components/rename-collection-modal/rename-collection-modal.tsx
packages/databases-collections/src/index.ts
packages/databases-collections/src/modules/rename-collection/rename-collection.spec.ts
packages/databases-collections/src/modules/rename-collection/rename-collection.ts
packages/databases-collections/src/stores/rename-collection.spec.tsx
packages/databases-collections/src/stores/rename-collection.ts

This PR includes a final change to the rename collections flow.  We intentionally do not update saved queries / aggregations when the user renames a collection, and now we warn the user that they have saved queries / aggregations that might get disassociated.
https://github.com/mongodb-js/compass/pull/5462 adds support for users to associate a new namespace with a saved query/aggregation.

chore(databases-collections): add UI for new rename collection warning COMPASS-7664

---

packages/compass-import-export/package.json
packages/compass-import-export/src/utils/reveal-file.ts
packages/compass/src/main/window-manager.ts

This is crashing the Finder in macOS. Moving it to happen on the main process as [suggested here](https://github.com/electron/electron/issues/17835#issuecomment-489591372) seems to work fine.

fix(export): show the folder via the main process COMPASS-7671

---

packages/compass-e2e-tests/tests/instance-my-queries-tab.test.ts
packages/compass-saved-aggregations-queries/src/components/open-item-modal.tsx
packages/compass-saved-aggregations-queries/src/stores/open-item.ts

If a collection is renamed, any queries or aggregations associated with that namespace are not updated. Users have the ability to open a query or aggregation by selecting the namespace, but they have no way of permanently re-associating a namespace with their queries/aggregations.
This PR adds the ability to permanently update the name space associated with an aggregation or query when they use they open it from the "select namespace" modal.  This scenario may become more common after the "rename collection" feature is released.

feat(compass-saved-aggregations-queries): update namespace for saved aggregations/queries (COMPASS-7665)

---

configs/webpack-config-compass/src/args.ts
packages/compass-generative-ai/webpack.config.js

Was trying to publish packages to update compass-web in POC and ran into a few issues during that process

chore(webpack, gen-ai): build provider.js with other assets; user args.entry when building a webpack config options

---

.evergreen/start-docker-envs.sh
package-lock.json
packages/data-service/package.json

Take in https://github.com/mongodb-js/devtools-docker-test-envs/pull/29, https://github.com/mongodb-js/devtools-docker-test-envs/pull/30 and https://github.com/mongodb-js/devtools-docker-test-envs/pull/31

fix: bump devtools-docker-test-envs

---

.evergreen/functions.yml
packages/compass-e2e-tests/package.json

No idea why I didn't do this from the start.

chore: zip e2e coverage report and upload it

---

packages/compass-connections/src/components/atlas-help/atlas-help.tsx
packages/compass-connections/src/components/connections.spec.tsx
packages/compass-connections/src/components/connections.tsx
packages/compass-connections/src/components/form-help/form-help.tsx
packages/connection-form/src/components/connection-form.spec.tsx
packages/connection-form/src/components/connection-form.tsx
packages/connection-form/src/components/form-help/form-help.tsx

Looks like more changes than it is, mainly copying and moving stuff.
Changes in nutshell:
- added the 2 info panels with updated design to connection-form, behind multiple connections feature toggle
- the original info panels are hidden when the toggle is on
- separated atlas-help to make future changes & cleanup easier, as this will be the only one of the original 'form-help' that remains in the welcome screen (might be completely useless if we don't stay within compass-connections)

feat: information panels for multiple connections

---

packages/compass-crud/src/components/bulk-update-modal.tsx

I'm pretty sure we focused on this detail during development and that I worked on it. I must have broken it at the last moment. See the [ticket](https://jira.mongodb.org/browse/COMPASS-7728) for how bad this can get. It renders the preview pretty much useless for anything but the simplest filter queries.
after screenshots:
(see the ticket for the before screenshot)

fix: don't allow the readonly filter to grow in width indefinitely COMPASS-7728

---

packages/instance-model/index.d.ts

Follow-up to the previous clean-up PR: new check deps script caught some non-existent imports for type values that were just converted by TS to any before, in the previous patch I just explicitly defined them as `any`, in this one I'm adding definitions based on the implementation

chore(instance-model): add types for ServerType and TopologyType exports

---

packages/atlas-service/src/store/atlas-signin-store.ts
packages/compass-e2e-tests/tests/atlas-login.test.ts
packages/compass-settings/src/stores/atlas-login.ts

Clean up Aatlas signing store, so it properly sets the 'unauthenticated' state after a user clicks the "Disconnect" button on the Setting page. Otherwise the "Log in with Atlas" -> "Disconnect" -> "Log in with Atlas" flow doesn't trigger the OIDC auth and a further "Disconnect" throws the "Error: Can't sign out if not signed in yet" error.

fix: can not sign out if not signed in yet COMPASS-7787

---

.github/workflows/authors-and-third-party-notices.yaml

We have it in two other ones, but never had it here it seems, not sure how it worked before

fix(ci): provide an id for create pr step in update authors task

---

packages/compass-aggregations/src/modules/input-documents.ts
packages/data-service/src/data-service.ts

So we can prove that DataService did get these values and (presumably) passed them on.
```
{"t":{"$date":"2024-03-28T10:21:50.952Z"},"s":"I","c":"COMPASS-DATA-SERVICE","id":1001000060,"ctx":"Connection 0","msg":"Running find","attr":{"ns":"config.collections","maxTimeMS":60000}}
```
```
{"t":{"$date":"2024-03-28T10:21:52.211Z"},"s":"I","c":"COMPASS-DATA-SERVICE","id":1001000181,"ctx":"Connection 0","msg":"Running aggregate","attr":{"ns":"Corporate-Registrations.corporations","stages":["$match","$count"],"maxTimeMS":5000}}
```
and now (we didn't specify this maxTimeMS before):
```
{"t":{"$date":"2024-03-28T10:54:30.824Z"},"s":"I","c":"COMPASS-DATA-SERVICE","id":1001000034,"ctx":"Connection 0","msg":"Running estimatedCount","attr":{"ns":"timeseries.random","maxTimeMS":5000}}
```

chore(data-service): log maxTimeMS along with find(), aggregate() and estimatedCount(), always set a default maxTimeMS COMPASS-7747

---

packages/compass-e2e-tests/tests/oidc.test.ts

I filed https://jira.mongodb.org/browse/COMPASS-7810 to re-enable it. Already tried a bunch of things in https://github.com/mongodb-js/compass/pull/5623.

chore(e2e): disable flaky OIDC test

---

packages/compass-settings/src/stores/index.ts

COMPASS-7817
The button for opening settings in the connections and connected sidebar was not working as we weren't listening for the app registry event anymore:
Not sure if this was intentionally removed in the recent home refactor, cc @mabaasit 
https://github.com/mongodb-js/compass/pull/5621/files#diff-a1ee6051686c3f86a59f508a33378dbc58dd5cc070e43dd67821b94b619c2a01L100
The e2e tests didn't catch this as we use the menu event there for opening settings: https://github.com/mongodb-js/compass/blob/7ba428477e5a9fa362a6e884ab37860d6d9a5c40/packages/compass-e2e-tests/helpers/commands/open-settings-modal.ts#L10
Likely a good thing to add a test for. Going to merge this first to keep main releasable.

fix(settings): listen to compass open settings app registry event COMPASS-7817

---

packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.tsx
packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-stages.tsx

Remove extra space from aggregations toolbar when SavedPipelines is not enabled. There's still some space there in order to align with the QueryBar (placeholder text)
Before
After

fix(compass-aggregations): remove space on toolbar

---

packages/compass-workspaces/src/components/index.tsx

Here is compass at its default size:
Then if you size up the sidebar as far as it will go:
If you then size down the window to the minimum size:
As you can see there's a minimum width on the workspaces and it will just "hang out". Which is arguably more or less broken than before.

chore(workspaces): add a minimum width to the compass workspaces COMPASS-7814

---

packages/atlas-service/src/provider.tsx
packages/compass-connections/src/components/connections.spec.tsx
packages/compass-connections/src/connections-manager.ts
packages/compass-connections/src/hooks/use-active-connections.spec.ts
packages/compass-connections/src/hooks/use-can-open-new-connections.spec.ts
packages/compass-connections/src/hooks/use-connection-repository.spec.ts
packages/compass-connections/src/stores/connections-store.spec.ts
packages/compass-preferences-model/src/provider.ts
packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-list.spec.tsx
packages/compass-sidebar/src/components/multiple-connections/saved-connections/saved-connection-list.spec.tsx
packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
packages/compass-web/polyfills/@mongodb-js/compass-connection-import-export/index.ts
packages/compass-web/polyfills/@mongodb-js/connection-form/index.ts
packages/compass-web/sandbox/index.tsx
packages/compass-web/src/entrypoint.spec.tsx
packages/compass-web/src/entrypoint.tsx
packages/compass-web/webpack.config.js
packages/compass/src/app/components/home.tsx
packages/connection-storage/src/provider.ts

Refactoring compass-web to manage connection flow through compass-connections plugin. It brings a ton of irrelevant UI with it, and we can only omit it partially by polyfiling with empty components, but this should bring compass-web and compass electron entrypoints closer to each other, allowing us to easier switch to completely the same entrypoint later down the road

chore(web): use compass-connections in compass-web so that connection logic is similar to the one in compass

---

packages/compass-aggregations/src/components/pipeline-toolbar/index.tsx
packages/compass-generative-ai/src/components/generative-ai-input.tsx
packages/compass-query-bar/src/components/query-bar.tsx

COMPASS-7834
Moves the AI input above the filter input and first row of aggregations toolbar.
| query | aggregation |
| - | - |
| <img width="913" alt="Screenshot 2024-04-09 at 3 07 28 PM" src="https://github.com/mongodb-js/compass/assets/1791149/6bd34243-08c0-4b35-b15d-6881fc301447"> | <img width="1208" alt="Screenshot 2024-04-09 at 3 16 04 PM" src="https://github.com/mongodb-js/compass/assets/1791149/168e5b02-1c91-4a84-9878-cd6b7b2b7e98"> |
| <img width="917" alt="Screenshot 2024-04-09 at 3 09 23 PM" src="https://github.com/mongodb-js/compass/assets/1791149/d52789c3-dbed-4d48-8637-e4862053a523"> | <img width="978" alt="Screenshot 2024-04-09 at 3 14 53 PM" src="https://github.com/mongodb-js/compass/assets/1791149/60dd01d1-12ab-4963-b33d-356e1f3dff5a"> |

chore(generative-ai): move prompt input above query bar and aggregation COMPASS-7834

---

packages/compass-sidebar/src/components/multiple-connections/navigation/navigation.tsx
packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx

PART 2 of the ticket
`multiple-connections/navigation.tsx` is a simplified version of `legacy/navigation-items.tsx`. We don't need the full functionality which was related to the other items. But there might still be other top-level navigation items in the future (e.g. "My tests" from the workshop ;) ).
Note: I don't know how to write a test for the click action (without touching the workspaces)
Note 2: The active & hover colors will need to be updated to fit the new design. This part hasn't been designed yet, I asked Ben and added a note in https://jira.mongodb.org/browse/COMPASS-7844

feat(compass-sidebar): add My queries to the multi-connections sidebar COMPASS-7726

---

packages/compass-settings/src/components/modal.tsx
packages/compass-settings/src/components/settings/gen-ai-settings.tsx

COMPASS-7800
Initially we were thinking this might be the ticket where we update Compass' settings to autosave. Instead this pr updates showing/hiding the ai preferences based off of the sandbox preference. Chatted with Alena to see if we want to go this route for now and defer updating our settings to autosave until we have more of a requirement for it. Ticket for auto-saving settings: COMPASS-7866

chore(settings): use sandbox preference for showing ai settings COMPASS-7800

---

packages/compass-settings/src/components/settings/gen-ai-settings.tsx

COMPASS-7865
We're currently sending our sample documents to the server and into the ai prompt as regular JSON. This means the AI isn't generating good results with certain bson types. It'll take a bit of work server side for us to do this. This pr hides the send sample field values setting for now so that folks aren't turning it on and getting slightly worse results until this is fixed.

chore(settings): hide enableGenAISampleDocumentPassing setting COMPASS-7865

---

packages/connection-storage/src/compass-main-connection-storage.ts

Failing check on main, 2 prs with new ids merged about the same time. It's something we could avoid with a merge queue, but I don't think we need one yet. This doesn't happen often.

chore: de-duplicate log id

---

packages/compass-generative-ai/src/components/generative-ai-input.tsx

Show the multi-colored gradient transition when a user has submitted a prompt for the generative AI. This is similar to the gradient we show with the docs AI input: https://www.mongodb.com/docs/

feat(generative-ai): add gradient while a generate request is in progress COMPASS-7836

---

packages/compass-e2e-tests/index.ts

To deal with the RHEL8 flake where the process sometimes hangs on exit.

chore(e2e): exit after 60 second timeout

---

packages/compass-sidebar/src/components/legacy/navigation-items.tsx

It seems we accidentally broke isPerformanceTabSupported check in https://github.com/mongodb-js/compass/commit/218c26a12feeb7bbdfdb4728d6da83ec9d3be7b8 (2 weeks ago). It means users could open the Performance tab and then would see the error (instead of it being disabled).

fix(compass-sidebar): isPerformanceTabSupported check in legacy sidebar COMPASS-7900

---

packages/compass-aggregations/src/stores/store.ts
packages/compass-app-stores/src/stores/instance-store.ts
packages/compass-crud/src/index.ts
packages/compass-crud/src/stores/crud-store.spec.ts
packages/compass-crud/src/stores/crud-store.ts
packages/compass-import-export/src/index.ts
packages/compass-import-export/src/modules/import.spec.ts
packages/compass-import-export/src/modules/import.ts
packages/compass-import-export/src/stores/import-store.spec.tsx
packages/compass-import-export/src/stores/import-store.ts
packages/compass-workspaces/src/index.ts
packages/compass/src/app/components/workspace.tsx

In this PR we modified ImportPlugin to work with dynamically provided DataService. The event `open-import` now expects `connectionId` to be provided as extra event args and will start the import for the specified connectionId. Places where we emit `open-import` now also provides connectionId as extra args.
When import is finished we emit `import-finished` event, now also with connectionId. The places where we were listening to this event now handles responding to it only when the connectionId matches that of event's connectionId.
As a drive by I also updated the events emitted by compass-crud to be emitted via ConnectionScopedAppRegistry. This is so that those events always carry a connectionId as extra args. In response to this change, compass-app-stores is also modified to only respond …

chore(compass-import-export): adapt ImportPlugin to work with dynamically provided connectionId for supporting multiple connections COMPASS-7859

---

package-lock.json
packages/compass-web/package.json
packages/compass-web/scripts/sync-dist-to-mms.js
packages/compass-web/webpack.config.js

This adds a new npm script to compass-web workspace that makes it a bit easier to work on compass-web locally if you want to see the changes immediately applied in mms. As mentioned in the script description, we can't really use pnpm / npm link for this as symlinking doesn't play well with webpack module resolution logic, so the script is watching for the file changes and copies them over to whatever place compass-web was installed in mms repo. This script also assumes that you did the cloud onboarding first and have the required env variables set up

chore(web): add a watch + sync script

---

.evergreen/compass_package.sh
.evergreen/create-sbom.sh
.evergreen/functions.yml
package-lock.json
packages/compass/package.json
packages/compass/scripts/download-csfle.js

Add generation of [`purls.txt`](https://docs.devprod.prod.corp.mongodb.com/mms/python/src/sbom/silkbomb/docs/PURLS/) and [Silkbomb](https://docs.devprod.prod.corp.mongodb.com/mms/python/src/sbom/silkbomb/docs/SILK)-generated `sbom.json` files to our CI/release infrastructure.
Like the corresponding [mongosh PR](https://github.com/mongodb-js/mongosh/pull/1975), this PR:
- Modifies our crypt_shared-library bundling/downloading step so that we store the version of the crypt_shared library we're bundling
- Generates a list of PURLs and then uses the SilkBomb tool to generate a SBOM file that we can share with DevProd (and later turn into its 'augmented' version with vulnerability information)
Unlike the mongosh PR, this PR:
- Does not bundles the generated sbom.json file in existing release …

feat(ci): add SBOM file to release artifacts

---

packages/compass-components/src/components/item-action-controls.tsx
packages/compass-connections-navigation/src/connection-item.tsx
packages/compass-connections-navigation/src/connections-navigation-tree.tsx
packages/compass-e2e-tests/tests/instance-my-queries-tab.test.ts
packages/compass-sidebar/src/components/legacy/sidebar-databases-navigation.tsx
packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.spec.tsx
packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.tsx

Open performance metrics action. If performance is not available, the menu item is disabled.

fix: performance action COMPASS-7873

---

packages/compass/package.json

Unused since e40f15f16705415070cbdf.

chore(deps): drop unused `vscode-windows-registry` dependency

---

.evergreen/generative-ai-accuracy-test-empty.yml
.evergreen/generative-ai-accuracy-test.yml

Slack thread: https://mongodb.slack.com/archives/C0V896UV8/p1714745238558629
Error that happens without a .yml to point to:

chore(ci): add empty .yml for ai-accuracy test evergreen project to use to pick up recent commits

---

packages/connection-form/src/utils/validation.ts

`=` cannot occur inside 128-character base64 strings, and `-` should be at the end of the character class to avoid specifying a range.

fix(connection-form): fix base64 regular expression COMPASS-7541

---

packages/compass-connections/src/connections-manager.ts
packages/compass-e2e-tests/helpers/commands/disconnect.ts
packages/compass-e2e-tests/helpers/commands/wait-for-connection-screen.ts
packages/compass-web/polyfills/net/index.ts
packages/compass-web/sandbox/atlas-cluster-connections.tsx
packages/compass-web/sandbox/index.tsx
packages/compass-web/sandbox/stored-connections-history.tsx
packages/compass-web/scripts/electron-proxy.js
packages/compass-web/scripts/ws-proxy.js
packages/compass-web/src/entrypoint.tsx
packages/data-service/src/connect-mongo-client.ts
packages/data-service/src/connection-options.ts

Another patch that brings the sandbox code closer to the final integration we expect inside Cloud, this should also make testing Atlas cluster connections locally even easier and hopefully more stable. This patch includes following changes:
- Add support for passing custom lookup option to the driver when connecting. In web environment we'd need a way to pass some custom metadata to our net / tls polyfills so that the information can be passed to the backend proxy. We're still discussing with InTel what exact property should be used, but `lookup` seems like a nice candiate as it's supported by both net and tls and because we can make it return arbitrary data that we'd need while matching original property type and still make it work if driver decides to use it for whatever reason and not …

chore(web): use x509 certs as an auth method for atlas clusters in the sandbox

---

package-lock.json
packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.tsx
packages/compass-sidebar/src/components/multiple-connections/saved-connections/saved-connection-list.spec.tsx
packages/compass-sidebar/src/components/multiple-connections/saved-connections/saved-connection-list.tsx

The button was already there, it just needed some styling. As a drive-by I'm also hiding the zero count like the design specifies.
before:
after with 0 connections:
after with 1 connection:

feat(compass-sidebar): padding around add connection button, don't show zero count in multiple connections

---

packages/compass-connections/src/components/connections-provider.tsx
packages/compass-connections/src/hooks/use-active-connections.ts
packages/compass-connections/src/hooks/use-tab-connection-theme.ts
packages/compass-connections/src/provider.ts
packages/compass-connections/src/stores/connections-store.tsx
packages/compass-web/src/entrypoint.tsx

Currently every time we use connection repository hook, it starts with an empty state and then loads connections in the `useEffect`, meaning that no matter how many times we already read the connections from disk, we'll do it again every time in every component where hook is used re-mounts. In addition to excessive reads, it also introduces a noticeable UI flashing issue in the application.
To avoid the issue right now before we refactored connection repository completely away, this patch adds a new context that stores the actual value returned by the repository hook in the compass-connections top level provider, while the exported `useConnectionRepository` hook now just exposes access to this context

fix(connections): add repository provider to make sure we don't reset repository state every time the hook is used COMPASS-7921

---

packages/compass-components/src/components/error-warning-summary.tsx

Uses overflow wrap so we show the whole error message in the error. We could alternatively use `overflowX: 'auto'` and make the overflowing error scrollable. For reviewers, any preference?
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap
| - | - |
| <img width="831" alt="Screenshot 2024-05-09 at 4 33 01 PM" src="https://github.com/mongodb-js/compass/assets/1791149/3148d9f7-6302-40e1-8de8-3fd470e52bff"> | <img width="793" alt="Screenshot 2024-05-09 at 4 32 46 PM" src="https://github.com/mongodb-js/compass/assets/1791149/9d52591d-3896-4812-8327-399cedb781a8"> |

fix(components): overflow-wrap error messages

---

packages/hadron-build/lib/mac-notary-service.js

These errors can be quite large, so make sure relevant information does not end up being truncated away.

chore(hadron-build): make macnotary errors more verbose

---

packages/compass-indexes/src/components/indexes-table/indexes-table.tsx
packages/compass-indexes/src/components/indexes/indexes.tsx
packages/connection-info/src/connection-title.ts

Two small fixes only relevant for compass-web:
- atlas metadata was not used for building connection title
- layout styles of the indexes view were not set on the right level causing stacking spacing issues
|Before|After|
|---|---|
|<img width="505" alt="image" src="https://github.com/mongodb-js/compass/assets/5036933/1f58e96c-91e5-49dd-8f84-348b62c7d502">|<img width="499" alt="image" src="https://github.com/mongodb-js/compass/assets/5036933/e8f9843c-6dc4-45f4-bf13-0cbf417cad81">|

fix(connection-info, indexes, web): use clusterName for breadcrumbs; fix spacing in the table

---

packages/compass/src/main/menu.spec.ts
packages/compass/src/main/menu.ts

COMPASS-7301
The issue reported in the ticket is that the code mirror captures the `Cmd+w`, which makes the close tab hotkey not run, however the close window electron hotkey still runs. This can be frustrating when there's something happening in other tabs. This pr mitigates the issue by updating close window to be `Cmd+Shift+w`.

feat(compass): update close window hotkey to be cmd+shift+w to avoid conflict with close tab cmd+w COMPASS-7301

---

packages/connection-form/src/components/connection-form.tsx

fix(connection-form): don't force the modal larger, prevent it from going too big

---

packages/compass-components/src/components/accordion.tsx
packages/connection-form/src/components/advanced-connection-options.tsx
packages/connection-form/src/components/advanced-options-tabs/advanced-options-tabs.tsx
packages/connection-form/src/components/advanced-options-tabs/advanced-tab/advanced-tab.tsx
packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-tab.tsx
packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.tsx
packages/connection-form/src/components/advanced-options-tabs/general-tab/general-tab.tsx
packages/connection-form/src/components/advanced-options-tabs/ssh-tunnel-tab/proxy-and-ssh-tunnel-tab.tsx
packages/connection-form/src/components/advanced-options-tabs/tls-ssl-tab/tls-ssl-tab.tsx
packages/connection-form/src/components/connection-form-modal.tsx
packages/connection-form/src/components/connection-form.tsx
packages/connection-form/src/components/form-help/form-help.tsx

Removes all the workarounds for the connection form sizing and changes them to css instead. Also a new behavior is added that makes the form to stretch to the whole available screen size when in modal to avoid jumps when switching the tabs in the advanced section
<video src="https://github.com/mongodb-js/compass/assets/5036933/a94024b1-f6a5-4d44-ba79-62c4c8c51cda">

chore(connection-form): clean up connection form styles; address modal jumping behavior

---

packages/compass-aggregations/src/components/stage-toolbar/index.tsx

COMPASS-6476
https://github.com/mongodb-js/compass/assets/1791149/f107dbd6-40cd-4a7a-a8f2-6953f64afe46

chore(aggregations): show grabbing cursor when dragging stage COMPASS-6476

---

packages/data-service/src/data-service.ts

Expose the `close` so we can listen on it in VSCode.

feat(data-service): expose close event VSCODE-536

---

packages/compass-generative-ai/scripts/ai-accuracy-tests/ai-accuracy-tests.ts
packages/compass-generative-ai/src/atlas-ai-service.ts

Our current query response validation in Compass strictly checks for if a query exists in the response: https://github.com/mongodb-js/compass/blob/2d41950fa5811e00ed20af1c63352f8f44f8b703/packages/compass-generative-ai/src/atlas-ai-service.ts#L270 
The changes in https://github.com/10gen/mms/pull/98900 made it so that we don't return a query if no query fields were returned. Because of this change we now error in the validation when an aggregation is returned:
```
Error: Unexpected response: expected query to be an object
```
Cloud pr where we fix this: https://github.com/10gen/mms/pull/100505
We missed this as the ai-accuracy-tests do not do this same validation. This pr updates our validation in our accuracy tests to use what we do in our code flow. It also makes the check less strict.

chore(gen-ai): remove strict validation of query response for aggregation generation

---

packages/compass-preferences-model/src/feature-flags.ts
packages/compass-settings/src/components/settings/gen-ai-settings.spec.tsx
packages/compass-settings/src/components/settings/gen-ai-settings.tsx

COMPASS-7931
The setting is still disabled by default, this enables showing it to all users by removing the feature flag.

feat(settings): enable sample documents setting COMPASS-7931

---

package-lock.json
packages/compass-import-export/package.json
packages/compass-import-export/src/export/export-csv.ts
packages/compass-import-export/src/modules/export.spec.ts

chore(import-export): remove production dependency on temp COMPASS-7975

---

packages/compass-explain-plan/src/components/explain-tree/explain-tree-stage.tsx

[COMPASS-7016](https://jira.mongodb.org/browse/COMPASS-7016)
Before | After
--- | ---
Indexes with very long names that do not fit in the explain tree index card go off of the card. Fix allows uses ellipsis to keep name within card, and mousing over the name shows the full name.

fix(index card explain plan): long index names COMPASS-7016

---

.evergreen/functions.yml

Might help to avoid getting rate limited by the github api

chore(ci): disable static analysis report for patches

---

packages/compass-query-bar/src/stores/query-bar-reducer.spec.ts
packages/compass-query-bar/src/stores/query-bar-reducer.ts

Previously you could click on something from the history and it wouldn't open options. This could cause some confusion if a user doesn't see something like a sort or limit applied.
https://github.com/mongodb-js/compass/assets/1791149/8d26e491-5951-4121-b976-29317124f753
Made a thread on slack to discuss: 
Will wait to merge for folks to respond there.

feat(query-bar): expand options when applied from query history with options

---

packages/compass-crud/src/components/insert-document-dialog.tsx

COMPASS-3246
This is a painful bug that's been in Compass for a long time. When inserting a document on the document view, if a user entered an invalid value, like when switching the type from string to Date with an invalid date in the video, an error would be shown which prevents inserting the document or switching the view. This error could never be cleared.
We'll likely revisit this entire insert document experience in the data viewing enhancements epic (and hopefully refactor it a lot 😅 ). Since this fix is a one liner I figured it's worth fixing now.
https://github.com/mongodb-js/compass/assets/1791149/37d4b5f0-499a-4afb-ba7e-bfad658e9b51

fix(crud): keep listeners for insert document validity on document view COMPASS-3246

---

packages/databases-collections-list/src/collections.tsx
packages/databases-collections-list/src/index.spec.tsx

COMPASS-6712
Hides collection stats (except for storage size) for timeseries cards since they are not calculated/calculated correctly by the collection.stats() method.

fix(databases-collections-list): hid inaccurate collection stats for timeseries COMPASS-6712

---

packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-ai.tsx
packages/compass-generative-ai/src/components/generative-ai-input.spec.tsx
packages/compass-generative-ai/src/components/generative-ai-input.tsx
packages/compass-query-bar/src/components/query-ai.tsx

COMPASS-7837
Shows a popover/guide cue when a user generates a query/agg that's without content or empty.
https://github.com/mongodb-js/compass/assets/1791149/52c829b2-2550-4594-950c-e52660a4d06a
Question for folks, and maybe product, is this worth having in the release notes? I was thinking it could be omitted but I'm not sure.

feat(generative-ai): add popover on empty content generated COMPASS-7837

---

scripts/generate-security-test-summary.ts

Prettier replaces `__SUMMARY__` with `**SUMMARY**`, so just accept either.

fix(scripts): account for prettier placeholder replacement

---

packages/compass-web/src/connection-storage.spec.ts
packages/compass-web/src/connection-storage.tsx

This patch fixes `deploymentItem` lookup in the deployment backend response by looking at the correct list of items 😅  [Totally missed](https://github.com/10gen/mms/blob/9e60e9eac35e700e78b9e453a6e880040c4ef19f/client/packages/legacy/core/models/deployment/Deployment.ts#L93-L96) that sharding deployment items are coming from the backend under a different key and only then mapped to `clusters` in the class constructor.
|Before|After|
|---|---|
|![image](https://github.com/mongodb-js/compass/assets/5036933/6f67edcf-73e6-4a99-9f81-a9dabfa0dd86)|![image](https://github.com/mongodb-js/compass/assets/5036933/a84e8dfd-74d7-436d-af38-aba0b39fd8a7)|

fix(web): fix deployment types; resolve deployment item for sharded from sharded and not clusters CLOUDP-253915

---

packages/compass-connections-navigation/src/connections-navigation-tree.spec.tsx
packages/compass-connections-navigation/src/connections-navigation-tree.tsx
packages/compass-connections-navigation/src/item-actions.ts
packages/compass-connections-navigation/src/navigation-item.tsx
packages/compass-connections-navigation/src/tree-data.ts

Fixes:
- changes in preferences weren't applied immediately (something wasn't re-rendering)
Other changes:
- disable shell when preferences readOnly mode is on, or the connection isn't writable (which isn't the same as the connection item being readOnly! we allow the shell when `instance.isDataLake`)

fix: finish readOnly logic COMPASS-7972

---

packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts

Some tests were adding a stage when there was already one there and it only intended to operate on one stage.
Other than that that was never the intended behaviour this also gets around the problem of the page scrolling on smaller displays and the stage selector popover then obscuring the field which then trips up some e2e tests on CI.

chore(e2e): don't add unintentional second stages

---

.github/workflows/codeql.yml

This gives us the ability to run this manually if we need to, but more importantly should also allow us to trigger it for a freshly pushed commit created by a github action programmatically.

chore(ci): add workflow dispatch for codeql.yml

---

packages/compass-preferences-model/src/preferences-schema.ts
packages/compass-settings/src/components/settings/general.tsx
packages/compass/src/main/menu.spec.ts
packages/compass/src/main/menu.ts

COMPASS-6435
Added to general settings tab:
When cmd/ctrl-Q is pressed, a standard message box appears. Clicking 'Cancel' does not change the setting and closes out the dialog, while clicking 'Quit' saves whatever setting was set using the checkbox/settings. If 'Do not ask me again' is saved, quitting using the shortcut will immediately close the app. This can be re-enabled in the general settings tab.

feat(compass): add confirmation dialog when quitting compass COMPASS-6435

---

packages/compass-connections-navigation/src/connections-navigation-tree.tsx

Just noticed this tiny bug, was probably introduced in https://github.com/mongodb-js/compass/commit/8633a8dcd4269359a93a646c14d06f4e730b5360 and is in the latest Compass version
https://github.com/mongodb-js/compass/assets/5196720/3a9a3fb6-6bb2-46db-8423-419fb06a5719

fix: small issue with sidebar tabbing

---

packages/compass/src/main/application.ts

Sometimes the e2e tests get a failed toast which it doesn't expect and then it obscures another toast that the test IS expecting which causes it to flake.
Better to leave auto-updates disabled in e2e tests in CI until we add testing support in [COMPASS-7618](https://jira.mongodb.org/browse/COMPASS-7618). Then the compass initialisation in e2e tests can wait for the relevant toasts and then dismiss them before the tests run.

chore(e2e): Don't setup auto-update in CI until we add tests for it

---

packages/compass-connections-navigation/src/base-navigation-item.tsx
packages/compass-connections-navigation/src/connections-navigation-tree.spec.tsx
packages/compass-connections-navigation/src/connections-navigation-tree.tsx
packages/compass-connections-navigation/src/navigation-item.tsx
packages/compass-connections-navigation/src/virtual-list/use-virtual-navigation-tree.tsx
packages/compass-connections-navigation/src/virtual-list/virtual-list.tsx

This is a problem we identified while finalising the unified sidebar experience that when you tab through the navigation tree, the action buttons are not tabbable. This happens because the action buttons are never rendered and because of which when we tab, they never have a chance to capture the next focus.
Another issue that was only highlighted in the unified sidebar experience was that the active item was not getting highlighted even when navigation changed. Now this is not a problem in main because the the connections list changes all the time which leads to re-render.
Before:
https://github.com/mongodb-js/compass/assets/10037761/6fc035d5-e002-414c-b6cf-68a195086668
After:
https://github.com/mongodb-js/compass/assets/10037761/97a538bb-b788-4419-93f3-3cd809af7f1f

fix(compass-connections-navigation): fix for action button not being tabbable when tabbing through navigation tree

---

.evergreen/compass_package.sh
.evergreen/functions.yml
.github/workflows/start-beta.yml
.github/workflows/start-ga.yaml
.mailmap
packages/compass/.gitignore
packages/compass/package.json
scripts/release.js

- Add our team's official email addresses and github usernames to `.mailmap` (we'll need to be using our mongodb.com email addresses soon anyway according to our DBX repo policy)
- Map the username for a newly triggered GH release to the name and email through the mailmap (and verify it's a mongodb.com address)
- Include it in the Compass package.json when we update it, ~~and include the package.json file in the generated app bundle~~ and use that to submit the information to papertrail
- Kick off CodeQL for the pushed, tagged commit from the release script as well

fix(ci): include releaser name in application artifacts COMPASS-7888

---

packages/data-service/src/data-service.ts

Was [investigating an issue](https://jira.mongodb.org/browse/HELP-60782) where someone reported not having `maxTimeMS` supplied to their Atlas Data Federation aggregation that could have been run in Compass. Figured this is a good thing to log since we do it other places. On a quick manual test this is working as expected:
```
"t":{"$date":"2024-06-17T15:21:46.766Z"},"s":"I","c":"COMPASS-DATA-SERVICE","id":1001000041,"ctx":"Connection 0","msg":"Running aggregateCursor","attr":{"ns":"sampleDB.listingsAndReviews","stages":["$count"],"maxTimeMS":60000}}
```

chore(data-service): add maxTimeMS to aggregationCursor log

---

packages/compass-components/src/components/workspace-tabs/tab.spec.tsx
packages/compass-components/src/components/workspace-tabs/tab.tsx
packages/compass-connections/src/hooks/use-tab-connection-theme.spec.ts
packages/compass-connections/src/hooks/use-tab-connection-theme.ts

as https://www.figma.com/proto/EjkYycHg99awXcKGCPANVR/EXPO-2245%3A-Multiple-connections?page-id=2354%3A24022&node-id=2354-39549&viewport=45%2C422%2C0.65&t=hLhcbFhbVdp9jRM1-1&scaling=contain&content-scaling=fixed&starting-point-node-id=2354%3A35204

chore: active tabs the same colour as the active workspace COMPASS-7958

---

packages/compass-logging/src/provider.ts
packages/compass-shell/src/components/compass-shell/tab-compass-shell.tsx

Drive-by fix for incorrect usage of refs in a few places, spotted when working on something else. The createRef literally just returns a new object every time it's called meaning that for example our logger hook was always recreating the logger on every render

fix(shell, logging): replace createRef with useRef

---

packages/compass-components/src/components/workspace-tabs/tab.spec.tsx
packages/compass-components/src/components/workspace-tabs/tab.tsx

Wasn't working with inactive tabs, animation not smooth.
Follow-up to https://github.com/mongodb-js/compass/pull/5934

chore: revert close button animation

---

packages/compass-components/src/components/workspace-tabs/tab.tsx

chore(compass-components): only put the border on selected themed tabs COMPASS-8025

---

packages/compass-editor/src/editor.tsx

COMPASS-7941
This pr does part of the linked ticket, this makes the line number text not selectable. Leaving the ticket open and will update it as we want the ability to start a code selection from these numbers, which is a more involved change.

fix(editor): update line numbers to not be selectable COMPASS-7941

---

packages/compass-e2e-tests/tests/protect-connection-strings.test.ts

This was fixed in the meantime so I literally just had to remove the skip.

chore(e2e): un-skip protect connection strings e2e tests for multiple connections COMPASS-8029

---

packages/compass-aggregations/src/modules/input-documents.spec.ts
packages/compass-aggregations/src/modules/input-documents.ts

COMPASS-7798
*before*
```json
{"t":{"$date":"2024-06-20T12:39:30.045Z"},"s":"I","c":"COMPASS-DATA-SERVICE","id":1001000181,"ctx":"Connection 0","msg":"Running aggregate","attr":{"ns":"ns removed","stages":["$limit"],"maxTimeMS":null}}
```
*after*
```json
{"t":{"$date":"2024-06-25T16:43:15.010Z"},"s":"I","c":"COMPASS-DATA-SERVICE","id":1001000181,"ctx":"Connection 0","msg":"Running aggregate","attr":{"ns":"NYC.squirrels","stages":["$limit"],"maxTimeMS":60000}}
```

fix(aggregations): use maxTimeMS default on preview docs COMPASS-7798

---

packages/compass-connections/src/hooks/use-connection-repository.ts
packages/compass-connections/src/hooks/use-connections-with-status.ts
packages/compass-e2e-tests/tests/auto-connect.test.ts

This is a hotfix for the connection info not accounting for autoconnect when calculating the active connections list. There is probably a better way to handle this overall, but the focus is to fix the GA right now. I also updated the autoconnect test to make sure that we're checking that the connection is functional

fix(connections): make sure that autoconnect info is provided in connection hooks COMPASS-8044

---

packages/compass-query-bar/src/index.tsx
packages/compass-schema/src/components/coordinates-minichart/coordinates-minichart.jsx
packages/compass-schema/src/components/field.tsx
packages/compass-schema/src/components/minichart/minichart.jsx
packages/compass-schema/src/components/unique-minichart/unique-minichart.jsx
packages/compass-schema/src/components/value-bubble.tsx
packages/compass-schema/src/stores/store.ts

When using "Schema" tab charts and selecting ranges that are rendered too close to each other, it can cause the application to lock up for a very long time as query update and a subsequent re-rendering is syncronous and will happen before the next on change will be processed.
This patch addresses the issue by introducing the debounce around the onChange function that triggers the actual query bar state update. That way the selection still stays snappy and we only trigger a re-render cycle at the very end when user finished selecting.

fix(schema): prevent application from hanging when selecting ranges too fast on the "Schema" tab COMPASS-8048

---

packages/compass-e2e-tests/tests/shell.test.ts

This failed five times in a row in a single variant before succeeding eventually. I'm not sure this will remove the flake, but should reduce the chances as the failure screenshots were actually showing the shell when the test would fail as if the element is not on the screen. Hopefully `waitFor` helps to deal with that

chore(e2e): update the test to reduce the flake

---

packages/compass-connections-navigation/src/base-navigation-item.tsx
packages/compass-connections-navigation/src/navigation-item.tsx
packages/compass-sidebar/src/components/multiple-connections/connections-navigation.tsx
packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx

Expanding a disconnected item is not possible without connecting first. Then, it'll be expanded by default.
Handling this at the sidebar level, so that the NavigationItem doesn't need to know about this connection specific case.

fix: expanding an inactive connection triggers connect COMPASS-8060

---

packages/compass-connections/src/components/connections.tsx
packages/compass-connections/src/stores/connections-store.spec.tsx
packages/compass-connections/src/stores/connections-store.tsx
packages/compass-e2e-tests/tests/connection-form.test.ts
packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx

In the multiple connection world, the duplicate is not created until the user presses `save` or `connect&save`. The action can be cancelled by closing the modal or clicking "cancel".
Side change: Instead of `(copy) (copy)` appendix, the copies now have an incremental `(number)` appendix. Originally I made this change only for the new version, but then I figured it's an improvement that we can roll out right away (and we don't need another "if" in the e2e tests).
Note: The duplicate creation mechanism stays in the connections store even though it's not saved. This follows the connection creation pattern and also keeps the connection related logic in compass-connections

fix: new duplicate connection behaviour for MC (COMPASS-8069)

---

package-lock.json
package.json

We can't immediately update mongosh because of the bug I introduced in browser-repl, so temporarily we override mongodb-redact package so that the static_analysis_report task can continue to work. This is a major bump, but AFAIU there were no breaking changes in the package

fix(ci): temporarily use override to bump mongodb-redact package

---

packages/compass-app-stores/src/stores/instance-store.ts
packages/compass-e2e-tests/tests/instance-sidebar.test.ts
packages/compass-e2e-tests/tests/my-queries-tab.test.ts
packages/compass-sidebar/src/components/legacy/sidebar.tsx
packages/compass-sidebar/src/components/multiple-connections/connections-navigation.tsx
packages/databases-collections/src/components/databases.tsx
packages/databases-collections/src/modules/databases.ts

* I realised that refresh databases wasn't actually doing anything. I just fixed it in this PR
* This un-skips the my queries tests for multiple connections
* I renamed the test file because it isn't actually per-instance
* I just flatted the nested context & multiple beforeEach hooks to fit with the style in this package. When you have a big test file and lots of nested describe/context each with their hooks I find it hard to follow what's actually in play. I also don't like putting too much work in a beforeEach especially in an e2e test because it is just as likely to fail as other test code and then it is the hook that fails and gets screenshotted rather than the test.
* I updated the test that checks that the sidebar's refresh databases button works because it looks like it couldn't …

chore(e2e): Port My Queries tests, fix Refresh Databases COMPASS-8006

---

CONTRIBUTING.md
package-lock.json
package.json

You can't bootstrap monorepo anymore with node 16:
```
npm ERR! engine Not compatible with your version of node/npm: @octokit/auth-token@4.0.0
npm ERR! notsup Not compatible with your version of node/npm: @octokit/auth-token@4.0.0
npm ERR! notsup Required: {"node":">= 18"}
npm ERR! notsup Actual:   {"npm":"9.9.3","node":"v16.20.1"}
```
So I'm updating it to be aligned with what we use in CI. Also some drive-by small changes to CONTRIBUTING

chore: align engines and docs with actually supported version

---

packages/compass-e2e-tests/helpers/commands/connect-with-connection-form.ts
packages/compass-e2e-tests/helpers/commands/connect-with-connection-string.ts
packages/compass-e2e-tests/helpers/commands/disconnect.ts
packages/compass-e2e-tests/helpers/commands/index.ts
packages/compass-e2e-tests/helpers/commands/remove-connection.ts
packages/compass-e2e-tests/helpers/commands/save-connection-string-as-favorite.ts
packages/compass-e2e-tests/helpers/commands/save-favorite.ts
packages/compass-e2e-tests/helpers/commands/shell-eval.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/auto-connect.test.ts
packages/compass-e2e-tests/tests/collection-export.test.ts
packages/compass-e2e-tests/tests/collection-import.test.ts
packages/compass-e2e-tests/tests/collection-rename.test.ts
packages/compass-e2e-tests/tests/connection-form.test.ts
packages/compass-e2e-tests/tests/connection.test.ts
packages/compass-e2e-tests/tests/in-use-encryption.test.ts
packages/compass-e2e-tests/tests/instance-sidebar.test.ts
packages/compass-e2e-tests/tests/oidc.test.ts
packages/compass-e2e-tests/tests/read-only.test.ts
packages/compass-e2e-tests/tests/search-indexes.test.ts

Main change is that the in-use-encryption tests were ported. browser.shellEval() can now handle multiple commands and properly waits for them to be finished.

chore(e2e): Port usage of saving favourites including all of the in-use-encryption e2e tests to multiple connections COMPASS-8003

---

packages/compass-sidebar/src/components/legacy/sidebar-databases-navigation.tsx
packages/compass-sidebar/src/components/use-filtered-connections.spec.ts
packages/compass-sidebar/src/components/use-filtered-connections.ts

This fixes the scenario where both the top level (connection/database) and low level (database/collection) match the filter. Since we cannot know whether the user is searching for the top or low level item, it is safer to assume the top, so that unfiltered children are available.
See https://jira.mongodb.org/browse/HELP-60975
Before:
After:

fix(compass-sidebar): do not filter out low level items when a top level item matches the filter COMPASS-8026

---

packages/compass-e2e-tests/helpers/commands/disconnect.ts
packages/compass-e2e-tests/tests/collection-export.test.ts
packages/compass-e2e-tests/tests/collection-import.test.ts
packages/compass-import-export/src/modules/export.ts
packages/compass-import-export/src/modules/import.ts
packages/compass-import-export/src/stores/export-store.ts
packages/compass-import-export/src/stores/import-store.ts

The e2e tests actually caught the regression. We weren't aborting the import/export so the toast would get all the errors from trying to work with a disconnected dataservice.

chore(e2e): cancel import/export when disconnecting, re-enable tests COMPASS-8008

---

packages/hadron-document/src/element.ts
packages/hadron-document/test/element.test.ts

fix(hadron-document): allow expanding an element that has its type changed to array or object COMPASS-7929

---

package-lock.json
packages/compass-telemetry/src/generic-track.ts

We don't actually send tracking in local dev so nothing shows in logs or anywhere which is a pain when you're just trying to make sure that we don't accidentally send an event too many times.
With this you can see it in the console, at least:
Without having to add a console.log() every time.

chore(compass-telemetry): add debug logging for tracking so we can check it locally

---

.snyk

This PR adds an ignore for SNYK-JS-ELECTRON-7443355 despite having a fix for this in main (https://github.com/mongodb-js/compass/pull/6041) because:
1. Snyk does not yet recognise that Electron update 29.4.5 fixes the mentioned CVE
2. The vulnerability does not apply to us
Have also extended the expiry of vuln related to aggridcommunity.

chore: update snyk policy to ignore one of non-applicable ELECTRON vuln and extend the expity of aggrid-community package

---

packages/compass-query-bar/src/utils/get-query-attributes.spec.ts
packages/compass-query-bar/src/utils/get-query-attributes.ts
packages/my-queries-storage/src/query-storage-schema.ts

A few places use this `getQueryAttributes` function. One of them is when saving a recent query. Without hint defined here we weren't saving this field.

fix(query-bar): save hint in queries

---

packages/hadron-build/lib/target.js

Electron releases for latest versions are currently packaging a mismatched arch version of ffmpeg for macos x64. There is already a fix in progress, but as this completely blocks our CI for now we'll work around this by using ffmpeg from an older release

fix(build): use an older ffmpeg version when packaging

---

packages/compass-editor/src/codemirror/ace-compat-autocompleter.ts
packages/compass-editor/src/codemirror/query-autocompleter-with-history.ts
packages/compass-editor/src/codemirror/query-history-autocompleter.ts
packages/compass-editor/src/editor.tsx

COMPASS-8031
Added icons next to each autocompletion item based on which type of completion it is; clock for query history, rectangular box for base completions.

 feat(compass-editor, compass-query-bar): autocomplete icon COMPASS-8031

---

packages/compass-editor/src/codemirror/query-autocompleter-with-history.test.ts
packages/compass-editor/src/codemirror/query-history-autocompleter.ts
packages/compass-editor/src/editor.tsx
packages/compass-editor/src/index.ts
packages/compass-query-bar/src/components/option-editor.spec.tsx
packages/compass-query-bar/src/components/option-editor.tsx

Added star icon to autocomplete favorite query completions.

feat(compass-editor, compass-query-bar): added star icon to autocomplete favorite queries

---

packages/compass-query-bar/src/components/option-editor.spec.tsx
packages/compass-query-bar/src/components/option-editor.tsx
packages/compass-query-bar/src/components/query-option.tsx

Filter bar is unchanged and will display all saved queries. The additional option editors (i.e. project, sort, collation, etc.) will only display saved queries that contain that specific property.

feat(compass-query-bar): selectively autocomplete query history in additional options COMPASS-8118

---

packages/compass-components/src/components/resizeable-sidebar.tsx
packages/compass-connections-navigation/src/base-navigation-item.tsx
packages/compass-connections-navigation/src/tree-item.tsx

@bsradcliffe and I went through the Figma designs and the sidebar as currently implemented to see why it looked more cramped in the app than in the designs and identified these differences:
* The chevron arrow icon was too big (should be 14px, not 16px but the button should still take up 16px)
* The font size is slightly too big (should be 12px, not 13px)
* Bump the default sidebar width to 300px (was 256px) so there’s less cutoff by default

fix(sidebar): tweak some sidebar sizes after design review COMPASS-8111

---

package-lock.json
packages/compass-components/package.json
packages/compass-components/src/hooks/use-confirmation.tsx
packages/compass-connections/src/components/connection-status-notifications.tsx
packages/compass-connections/src/components/connection-status-toasts.tsx
packages/compass-connections/src/components/legacy-connections.tsx
packages/compass-connections/src/stores/connections-store.spec.tsx
packages/compass-connections/src/stores/connections-store.tsx
packages/compass-e2e-tests/helpers/selectors.ts

This patch adds support for device auth flow to multiple connections. When the `notify` callback is triggered in multiple connections, we show a confirmation modal telling user the url to navigate to and the code to enter:
I added a unit test but didn't manage to create an e2e one, but I tested locally in addition to unit tests by hardcoding allowed flows values in the app (I can't figure out right away how to reconfigure the mock-oidc-provider to only "support" device auth and compass always allows both auth code and device flow (device code being optional and disabled by default), doesn't look like we currently have a way to only allow device auth in Compass for a good reason)

feat(connections): show device auth code in the confirmation modal for multiple connectinos connect flow COMPASS-8140

---

packages/compass-workspaces/src/stores/workspaces.spec.ts
packages/compass-workspaces/src/stores/workspaces.ts

[COMPASS-8113](https://jira.mongodb.org/browse/COMPASS-8113)
Forces a new tab if both the active & the next workspace are of a different connection.
https://github.com/user-attachments/assets/f1bae7cb-2f74-45ad-aa50-e92f78218af8

fix: do not replace tabs of different connections COMPASS-8113

---

packages/compass-connections/src/stores/connections-store.spec.tsx
packages/compass-connections/src/stores/connections-store.tsx
packages/connection-form/src/components/connection-form-actions.spec.tsx
packages/connection-form/src/components/connection-form-actions.tsx

This patch removes multiple-connections only special behavior for connect function that would always save changes to connection, even for already saved connections. For now we're reverting this back to what was happening in single connection mode where already saved connections (favorites or recents) would only update `lastUpdated` and optionally the OIDC auth state and only after successful connection, not before that

chore(connections): align multiple connections saving behavior with single connections mode COMPASS-8133

---

packages/compass/src/app/utils/telemetry.spec.ts
packages/compass/src/app/utils/telemetry.ts

- Return hostname without port
- Fall back to original hostname from uri when resolving srv failed

fix(telemetry): better hostname parsing for telemetry COMPASS-8148

---

packages/compass-collection/src/components/collection-header-actions/collection-header-actions.tsx
packages/compass-sidebar/src/components/multiple-connections/connections-navigation.tsx
packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
packages/databases-collections-list/src/items-grid.tsx

Adding `Shell Open` events, with `entrypoint` of either `sidebar` | `databases` | `collections` | `collection`.

fix: add shell open events with entrypoints COMPASS-8136

---

packages/hadron-build/lib/run.js

When building compass locally (which failed), the process did not throw any useful error due to js trying to access locally scoped `output` instead of outer one.

fix(build): throw error when build fails

---

packages/compass-e2e-tests/helpers/commands/click-visible.ts
packages/compass-e2e-tests/helpers/commands/connect.ts
packages/compass-e2e-tests/helpers/commands/hide-visible-toasts.ts
packages/compass-e2e-tests/helpers/commands/wait-for-animations.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/connection.test.ts
packages/compass-e2e-tests/tests/my-queries-tab.test.ts

Connects twice with different errors, then clicks review on each error toast and makes sure that the modal populates with that connection's info and shows the error.

chore(e2e): add E2E test for multiple connection errors COMPASS-8153

---

packages/compass-e2e-tests/helpers/commands/index.ts
packages/compass-e2e-tests/helpers/commands/remove-connections.ts
packages/compass-e2e-tests/helpers/compass.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/atlas-login.test.ts
packages/compass-e2e-tests/tests/auto-connect.test.ts
packages/compass-e2e-tests/tests/connection.test.ts
packages/compass-e2e-tests/tests/import-export-connections.test.ts
packages/compass-e2e-tests/tests/intercom.test.ts
packages/compass-e2e-tests/tests/logging.test.ts
packages/compass-e2e-tests/tests/no-network-traffic.test.ts
packages/compass-e2e-tests/tests/oidc.test.ts

The connections test file creates a ton of connections and we're just about at the point where virtual scrolling kicks in. browser.removeAllConnections() allows us to remove them all between tests.
Furthermore firstRun now defaults to true so that each test file now gets its own user directory and therefore things like connections, saved queries and so on get reset every time. Only the tests that care about starting compass twice in a row and keeping the user directory have it set to false. This should isolate tests better with the downside being that we're almost always testing the first run use case.

chore(e2e): firstRun: true by default, remove connections

---

packages/compass/scripts/download-csfle.js

In 7.3.4, the server is changing its internal identifier for RHEL 8 from `rhel80` to `rhel8`. Since this was just released, we need to account for it as well in order to un-break our build.

fix(compass): account for server RHEL distro rename

---

packages/compass-connections/src/components/connection-status-notifications.tsx

fix(compass-connections): text-overflow: ellipsis on very long connection names in connection errors COMPASS-8112

---

package-lock.json
packages/atlas-service/package.json
packages/atlas-service/src/main.spec.ts
packages/atlas-service/src/main.ts
packages/compass-utils/src/cancellable-promise.ts
packages/compass/package.json
packages/compass/src/main/application.ts
packages/compass/src/main/auto-update-manager.ts

fix(compass,atlas-service): apply proxy to main thread HTTP calls COMPASS-8165

---

packages/compass-components/src/components/workspace-tabs/tab.tsx
packages/compass-connections/src/hooks/use-tab-connection-theme.spec.ts
packages/compass-connections/src/hooks/use-tab-connection-theme.ts

Ideally it would animate the background, but I can't get that right yet. I think this is an improvement for now, though.
https://github.com/user-attachments/assets/e414c126-d313-4cf0-8570-ea5b9b494ef6

fix(compass-components): keep the colour tabs' background COMPASS-8168

---

packages/compass-e2e-tests/tests/collection-import.test.ts

There used to be a separate error for the batch itself. Now the errors and docs are one to one. Three docs failed, so there are three errors in the log.

fix(e2e): three lines for three errors, not four

---

packages/compass-e2e-tests/helpers/commands/disconnect.ts
packages/compass-e2e-tests/helpers/commands/hide-visible-modal.ts
packages/compass-e2e-tests/helpers/commands/index.ts
packages/compass-e2e-tests/helpers/commands/remove-connections.ts

This is kinda the problem whenever you use something like isDisplayed(). It isn't a stable end state: The modal could still be "animating away", for example.

fix(e2e): deal with the fact that the modal might already be closed

---

packages/connection-storage/src/compass-main-connection-storage.spec.ts
packages/connection-storage/src/compass-main-connection-storage.ts

fix(connection-storage): store `useApplicationLevelProxy` flag to disk COMPASS-8219

---

packages/compass-connections/src/hooks/use-connection-form-preferences.tsx
packages/compass-e2e-tests/tests/oidc.test.ts
packages/compass-e2e-tests/tests/proxy.test.ts
packages/compass-preferences-model/src/feature-flags.ts
packages/compass-settings/src/components/modal.tsx

feat: release feature flag for proxy support COMPASS-8167

---

packages/compass-connections/src/hooks/use-tab-connection-theme.spec.ts
packages/compass-connections/src/hooks/use-tab-connection-theme.ts
packages/compass-connections/src/stores/store-context.tsx

Follow-up to the big connections refactor I just merged, spotted an issue with this hook when working on refactor, but kept the fix out just to limit the scope of previous PR.
The fix itself is pretty straightforward: just make sure that method depends on actual list of data it needs and not on a stable getter. Maybe a good example to keep in mind for how easy it is to mess up state updates when React hooks are used and how vigilant you need to be when specifying dependencies (including making sure that dependencies used will actually update too)

chore(connections): make sure that getThemeOf method gets updated when colors change

---

packages/compass-crud/src/components/change-view/unified-document.ts
packages/compass-crud/test/before-after-fixtures.ts
packages/compass-crud/test/fixture-results/all_types_all_types_changed.json
packages/compass-crud/test/fixture-results/array_changes_add_array_to_array.json
packages/compass-crud/test/fixture-results/array_changes_add_object_to_array.json
packages/compass-crud/test/fixture-results/array_changes_add_simple_value_to_array.json
packages/compass-crud/test/fixture-results/array_changes_remove_simple_value_from_array.json
packages/compass-crud/test/fixture-results/array_changes_simple_array.json
packages/compass-crud/test/fixture-results/nested_object_changes_nested_object_array_array_simple.json
packages/compass-crud/test/fixture-results/nested_object_changes_nested_object_array_simple.json
packages/compass-crud/test/fixture-results/objects_in_arrays_add_number_next_to_object_in_array.json
packages/compass-crud/test/fixture-results/objects_in_arrays_many_items.json
packages/compass-crud/test/fixture-results/objects_in_arrays_object_inside_array_changed.json
packages/compass-crud/test/fixture-results/objects_in_arrays_object_value_nested_in_an_array.json
packages/compass-crud/test/fixture-results/objects_in_arrays_remove_number_next_to_object_in_array.json

Don't know what I was thinking fighting TypeScript there.
There isn't really much we can do as a generic solution for objects nested inside arrays (the diff will still look huge), but at least now it won't look broken.
Only a few lines changed, most of the diff is test fixtures.

fix(compass-crud): in the bulk update preview, convert array indexes from strings to numbers COMPASS-8218

---

packages/compass-connections/src/stores/connections-store-redux.ts
packages/compass-connections/src/stores/connections-store.spec.tsx

This patch adjusts the connect logic a bit to make sure that while we're still not storing any changes to the connection options of already stored connections, but we do store any changes to the favorite info as this seems to be the most common expectation.
It was planned as post GA, but easy enough to do and seems like rolling out the beta just continues to confirm that we might want to have this in GA

chore(connections): autosave favorite info on connect for existing connections COMPASS-8185

---

packages/compass-web/src/connection-storage.spec.ts
packages/compass-web/src/connection-storage.tsx
packages/connection-info/src/connection-info.ts

This just puts instanceSize on connectionInfo.atlasMetadata. Will add a hook that uses it in https://jira.mongodb.org/browse/COMPASS-8213

feat: add connectionInfo.atlasMetadata.instanceSize COMPASS-8236

---

configs/mocha-config-compass/package.json
package-lock.json
scripts/package.json

This removes some noise from the unit tests that was caused by previous version of jsdom we were on not being able to parse certain modern css features like container queries

chore(mocha-config): update jsdom to 24

---

configs/mocha-config-compass/index.js
configs/mocha-config-compass/react.js
configs/mocha-config-compass/register/mute-console-warnings-register.js
packages/compass-query-bar/src/components/query-history/favorite-list.spec.tsx
packages/compass-query-bar/src/components/query-history/recent-list.spec.tsx

Those are still visible in browser devtools console when running the application locally where you can actually track them and address if needed, in unit tests those are mostly generating unnecessary noise that makes it hard to read the output
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/b491a771-fde4-4263-b35e-e9ce725b601e)|![image](https://github.com/user-attachments/assets/6c048d84-a1cf-4151-8a4c-31125d47887d)|

chore(mocha-config): mute unhelpful messages in unit tests

---

packages/compass-editor/src/codemirror/query-autocompleter-with-history.test.ts
packages/compass-editor/src/codemirror/query-autocompleter-with-history.ts
packages/compass-editor/src/codemirror/query-history-autocompleter.test.ts
packages/compass-editor/src/codemirror/query-history-autocompleter.ts
packages/compass-query-bar/src/components/option-editor.tsx
packages/compass-query-bar/src/components/query-history/index.spec.tsx

COMPASS-8241
This pr restricts the query history auto completion items we show when a user is typing in the query bar.
Previously we would fuzzy match any characters in the entire query. That resulted in too many things being shown even when they weren't relevant. Now it'll only do this fuzzy matching when it the query history item passes a preliminary check that looks for if what the user is typing is a field prefix or contains a matching field + value in the query property.
Another part of this is not matching on the labels we provide for various fields. We used to match on the field property titles like 'project' and 'sort', which would produce false positives and more noise. To do this we use the `displayLabel` property of a completion item. Unfortunately this results in us losing the …

fix(query-bar, editor): update query history autocompletion to be more selective COMPASS-8241

---

packages/compass-editor/src/codemirror/query-history-autocompleter.ts
packages/compass-editor/src/editor.tsx
packages/compass-query-bar/src/components/option-editor.tsx

Couple smaller changes in here:
1. When selecting a query history item from the autocomplete, we automatically move the cursor to the end of the editor.
2. Don't provide the autocompletion for a query history item if it matches what's typed.
3. Auto complete option info height reduced:
| - | - |
| ![Screenshot 2024-09-04 at 12 49 12 PM](https://github.com/user-attachments/assets/5d72431a-a826-440b-8381-af5126a913b3) | <img width="764" alt="Screenshot 2024-09-04 at 1 07 12 PM" src="https://github.com/user-attachments/assets/55993d5a-71c8-4650-992c-8ad687b8772e"> |

feat(editor, query-bar): on query history autocomplete move cursor to end of content, small ux updates

---

packages/compass-indexes/src/components/search-index-template-dropdown/index.spec.tsx
packages/compass-indexes/src/components/search-index-template-dropdown/index.tsx
packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.tsx
packages/compass-indexes/src/components/search-indexes-modals/update-search-index-modal.spec.tsx
packages/compass-indexes/src/components/search-indexes-modals/update-search-index-modal.tsx

COMPASS-8235
A bit of a note, this was likely missed/caused by the `isVectorSearchSupported` property being optional on the component. I'm thinking allowing undefined for boolean properties like this is a pattern we should avoid. Probably not worth a lint rule, more of something to look out for.

fix(indexes): check for vector search support when showing edit templates COMPASS-8235

---

packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/index.tsx
packages/compass-components/src/components/item-action-controls.tsx
packages/compass-crud/src/components/delete-data-menu.tsx
packages/compass-crud/src/components/update-data-menu.tsx
packages/compass-generative-ai/src/components/ai-experience-entry.tsx

It admittedly goes pretty far in one step, but the alternative is to only cut some of them short at first and not others and then which ones?

chore: also collapse Add Data and Export Data, add title attributes COMPASS-8231

---

packages/compass-shell/src/components/shell-info-modal/keyboard-shortcuts-table.tsx

Doesn't work anymore. As the shell is now a tab, the controls for tabs apply.

fix: remove outdated shortcut COMPASS-8259

---

package-lock.json
package.json

Due to the vulnerability in current version of dset (3.1.3) used by segment, we are updating dset to the latest patch version.
Without overriding, ran `npm update dset` to update it.

fix(deps): update dset to latest

---

.evergreen/buildvariants-and-tasks.in.yml
.evergreen/buildvariants-and-tasks.yml

A friendly takeover of https://github.com/mongodb-js/compass/pull/5990 incorporating @mcasimir's feedback: https://github.com/mongodb-js/compass/pull/5990#discussion_r1662392749
Updates the build variants used for packaging the app on MacOS to 14 and adds two new test variants for the MacOS 14. We might want to simply remove `test-packaged-app-macos-11-arm` and `test-packaged-app-macos-11-x64` in the future.

chore(ci): build and test packaged app on the newer macos version COMPASS-8090

---

package-lock.json
package.json
packages/compass-web/package.json

fix(deps): override body-parser and bump express COMPASS-8288)

---

packages/compass-connections/src/connection-info-provider.tsx

To make sure that when passed as a dependency, it's not triggerring unnecessary effects

fix(connections): ensure that connectionInfoAccess hook value is stable

---

.depcheckrc
package-lock.json
package.json
packages/compass-e2e-tests/.depcheckrc
packages/compass-explain-plan/.depcheckrc
packages/compass-preferences-model/package.json
packages/compass-web/package.json
packages/hadron-app-registry/.depcheckrc
scripts/package.json

This patch addresses a few dependency / package-lock related issues that are currently in main:
- A recent `express` update for whatever reason caused npm to hoist a bunch of webpack related dependencies, but webpack itself was not hoisted, I missed it when checking the changes in package-lock and this change completely broke the `npm run start / start-web` commands. The fix here is to make sure that `webpack` dependency is also hoisted
-  At the same time, `npm run start-web` is used by our e2e tests to test web, so in theory should sould've showed up in the express update PR already, but on practice the e2e tests for web were silently failing for quite some time already caused by npm unhoisting a different dependency: `devtools-proxy-support`. It is explicitly mentioned in the …

chore(deps) hoist webpack; remove depcheck workarounds; add missing dependency to compass-web COMPASS-8313

---

.snyk

Not applicable to our case and as with other ag-grid issues we can't update to the version with the fix easily

chore(deps): add latest ag-grid vuln to the ignore list

---

packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx

This updates the wording in the tooltip shown when a user hovers a disabled "Search Indexes" control option.

chore(compass-indexes): Update tooltip shown when managing "Search Indexes" is not supported COMPASS-7978

---

packages/compass-indexes/src/components/indexes-table/indexes-table.tsx

I couldn't look at this anymore
before:
after:

chore: don't wrap the indexes table header cells

---

.evergreen/buildvariants-and-tasks.in.yml
.evergreen/buildvariants-and-tasks.yml
.evergreen/functions.yml
packages/compass/scripts/download-csfle.js

Use proper 8.0.x versions where possible and switch the crypt_shared library back to using a `continuous` version.

chore(ci): account for 8.0.0 publish COMPASS-8087

---

packages/compass-e2e-tests/helpers/commands/create-index.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-indexes/src/components/create-index-actions/create-index-actions.spec.jsx
packages/compass-indexes/src/components/create-index-actions/create-index-actions.tsx
packages/compass-indexes/src/components/create-index-modal/create-index-modal.tsx
packages/compass-indexes/src/components/regular-indexes-table/property-field.tsx
packages/compass-indexes/src/modules/create-index.spec.ts
packages/compass-indexes/src/modules/create-index.tsx
packages/compass-indexes/src/modules/regular-indexes.ts

This patch decouples create index form submission from actual index creation process, while still allowing the form to keep the created "in progress" index id in the store if we would ever want to be able to map them together for whatever purpose (for example to be able to re-open the create index form for failed indexes). This makes sure that we don't accidentally close the form when another index finished creating (so resolves COMPASS-6918). We also removing the "In progress" state from this modal in general and closing it right after our client-side validation passed and we submitted index for creation.

chore(indexes): remove in progress state from create index modal; decouple index creation and form submission

---

packages/atlas-service/src/atlas-service.ts
packages/compass-web/scripts/start-electron-proxy.js
packages/compass-web/src/connection-storage.tsx
packages/compass-web/webpack.config.js

One thing I didn't notice when testing this: only serverless should be passing the uniqueId to the backend, other clusters use the metricsId. Also some drive-by fixes:
- sandbox electron proxy logs were not piped anywhere
- polling for connections in web was not working right because we never cleaned up the in-flight promise
- default backend config was not applying correctly in sandbox because the env value was missing

fix(atlas-service): use metricsId for clusterId when doing automation agent requests

---

CONTRIBUTING.md

Small update adding instructions on how to use the React Developer Tools.

chore: add `CONTRIBUTING.md` note on using React Developer Tools

---

packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
packages/compass-indexes/src/components/indexes/indexes.spec.tsx
packages/compass-indexes/src/components/regular-indexes-table/in-progress-index-actions.spec.tsx
packages/compass-indexes/src/components/regular-indexes-table/in-progress-index-actions.tsx
packages/compass-indexes/src/components/regular-indexes-table/index-actions.spec.tsx
packages/compass-indexes/src/components/regular-indexes-table/index-actions.tsx
packages/compass-indexes/src/components/regular-indexes-table/property-field.spec.tsx
packages/compass-indexes/src/components/regular-indexes-table/property-field.tsx
packages/compass-indexes/src/components/regular-indexes-table/regular-index-actions.spec.tsx
packages/compass-indexes/src/components/regular-indexes-table/regular-index-actions.tsx
packages/compass-indexes/src/components/regular-indexes-table/regular-indexes-table.spec.tsx
packages/compass-indexes/src/components/regular-indexes-table/regular-indexes-table.tsx
packages/compass-indexes/src/components/regular-indexes-table/type-field.tsx
packages/compass-indexes/src/components/search-index-template-dropdown/index.spec.tsx
packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.spec.tsx
packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.tsx
packages/compass-indexes/src/modules/regular-indexes.spec.ts
packages/compass-indexes/src/modules/regular-indexes.ts
packages/compass-indexes/src/utils/index-link-helper.ts
packages/compass-indexes/test/fixtures/regular-indexes.ts
packages/compass-indexes/test/helpers.ts
packages/data-service/src/index-detail-helper.ts

Extracted out of https://github.com/mongodb-js/compass/pull/6290
The basic idea is to not merge real indexes and in-progress indexes in the store. That's error prone because you can't really merge them together. All we have to go on is index name and if you override either the in progress details or the real index details it leads to bugs either way. We poll the real details now anyway, so it is eventually consistent as it is. With rolling indexes this just gets worse.
Furthermore, the types aren't really very compatible. We have an index name and little more for in-progress indexes at the moment and for rolling indexes we'll have a name and a type. If we want type and properties for a regular in-progress index we have to infer that based on the input ourselves and in future if we want …

chore(compas-indexes): store real indexes and in-progress indexes as separate lists

---

packages/compass-connections/src/hooks/use-connection-supports.ts
packages/compass-connections/src/index.tsx
packages/compass-connections/src/utils/connection-supports.spec.ts
packages/compass-connections/src/utils/connection-supports.ts

I'd like to check whether the connection supports rolling index creation from within a thunk action creator and right now we only have a hook.

chore(compass-connections): split out connectionSupports into a function that we can use outside of hooks

---

packages/hadron-build/lib/zip.js

This refactores the hadron-build package to use the `ditto` command when producing an archive instead of using `zip` (which currently corrupts the .zip file uploaded to GitHub).

fix(hadron-build): use `ditto` instead of zip to package on MacOS COMPASS-7737

---

.evergreen/functions.yml

This fix the archiving of the all-e2e-logs.tgz which would produce an empty file on MacOS because of incompatibilities in the runtime options of `tar` across platforms.
Here's a[ deep link to the files produced](https://spruce.mongodb.com/task/10gen_compass_main_test_server_macos_11_arm_test_packaged_app_1_patch_8af5d4e18cb47b46518caa3d9f3cfaaafe19b887_66fd2932793fea00072c385c_24_10_02_11_06_27/files?execution=0&sortBy=STATUS&sortDir=ASC) by this PR on a MacOS host - search for and download the "all-e2e-logs.tgz" file to verify the fix.

chore(ci): use "archive.targz_pack" command to archive e2e logs

---

.evergreen/buildvariants-and-tasks.in.yml
.evergreen/buildvariants-and-tasks.yml

Second attempt at https://github.com/mongodb-js/compass/pull/6220 (which had to be reverted in #6230). It was reverted because running the tests were not `patchable` and failed because the host was not logged into a graphical shell.
Here's a patch which sets `patchable: true` to convince yourself this works: https://spruce.mongodb.com/version/66fedc4f7d7d0700078cc466/tasks
A friendly takeover of https://github.com/mongodb-js/compass/pull/5990 incorporating @mcasimir's feedback: https://github.com/mongodb-js/compass/pull/5990#discussion_r1662392749
Updates the build variants used for packaging the app on MacOS to 14 and adds two new test variants for the MacOS 14. We might want to simply remove `test-packaged-app-macos-11-arm` and `test-packaged-app-macos-11-x64` in the future.
Note: To …

chore(ci): build and test packaged app on the newer macos version (2nd attempt) COMPASS-8090

---

packages/compass-components/README.md

Just moving all the relevant parts of https://docs.google.com/document/d/1ZLz_DJYpwTiS_DiPcQMKoLoz2iNxSsMKRTuXXxHb6ak/edit to README instead of a GDoc

chore(components): move component conventions from gdoc to readme

---

packages/compass-connections-navigation/src/item-actions.ts
packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.spec.tsx
packages/connection-form/src/components/connection-form-actions.spec.tsx
packages/connection-form/src/components/connection-form-actions.tsx
packages/connection-form/src/components/connection-form.spec.tsx
packages/connection-form/src/components/connection-form.tsx
packages/connection-form/src/components/connection-string-input.spec.tsx
packages/connection-form/src/components/connection-string-input.tsx
packages/connection-form/src/components/form-help/form-help.tsx

See [figma design](https://www.figma.com/proto/JmNVeRAx398lbu3kNQiuZc/Multiple-connection-UX-tweaks?page-id=0%3A1&node-id=5-1995&node-type=canvas&viewport=25%2C421%2C0.62&t=FN4NntbaFlOMRK7Q-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=5%3A1995&show-proto-sidebar=1) and [slack thread](https://mongodb.slack.com/archives/C05MLSFMUJC/p1728388841356229).

feat(connection-form): allow editing connected connections, but only the name, colour and favorite checkbox COMPASS-8160

---

packages/compass-indexes/src/components/regular-indexes-table/status-field.tsx

thread https://mongodb.slack.com/archives/C07MJS4UT42/p1727959441918739

chore(compass-indexes): remove the icon and tooltip from the rolling index status badge

---

packages/connection-form/src/components/connection-form.spec.tsx
packages/connection-form/src/components/connection-form.tsx

feat(connection-form): show a banner on the connection form explaining why you can't edit the connection COMPASS-8264

---

package-lock.json

During the last mongosh version bump we actually haven't bumped the dependencies to the latest, they got updated in package.json files, but not in the package-lock.json, so correct versions were never installed:
The weirdest part is that even manually trying to install exact version was completely ignored by npm, I'll try to dig a bit more into that because it's a scary thing and very hard to spot when doing package version update, but for not to unblock the release I took the following steps:
- Manually remove any mention of `@mongosh/*` and `@mongodb-js/devtools-*` packages from package-lock.json (but not from package.json)
- Remove all locally installed dependencies and a "hidden" lockfile so that they don't affect lock update
- Run install to update the lock
Taking this steps managed …

chore: force package-lock to update the mismatched dependencies

---

.evergreen/functions.yml
package-lock.json
packages/compass-e2e-tests/package.json
packages/compass/package.json
packages/hadron-build/commands/release.js
scripts/package.json

This is a follow-up to #6348 that fixes two more dependencies (make-fetch-happen and semver) in some workspaces (scripts, compass, and compass-e2e-tests) and adds a check that should make sure that at least we will be able to spot immediately when we run into issues like that in the future

chore: fix more mismatched versions issues and add a check in ci

---

.evergreen/functions.yml
package-lock.json
package.json
packages/compass-components/package.json
packages/compass-components/src/components/combobox/ComboboxMenu/ComboboxMenu.tsx
packages/compass-components/src/hooks/use-theme.tsx
packages/compass-generative-ai/src/components/generative-ai-input.tsx

This patch fixes the mismatched versions issue for the rest of transitive deps and changes the `npm ls` check to validate those too

chore: fix ELSPROBLEMS for all transitive dependencies

---

packages/compass-indexes/src/modules/regular-indexes.ts
packages/compass-indexes/src/modules/search-indexes.ts
packages/compass-telemetry/src/telemetry-events.ts

Like Index Created it will only log if the user kept Compass open until the operation finishes. It won't log anything if a rolling build fails after the job was successfully received. We don't get those failures - the index just disappears from the list and the user gets an email.

chore(telemetry): add "Index Create Failed" to mirror Index Created COMPASS-8100

---

packages/compass-global-writes/src/components/index.tsx
packages/compass-global-writes/src/components/states/sharding.spec.tsx
packages/compass-global-writes/src/components/states/sharding.tsx
packages/compass-global-writes/src/plugin-title.spec.tsx
packages/compass-global-writes/src/plugin-title.tsx
packages/compass-global-writes/src/services/atlas-global-writes-service.ts
packages/compass-global-writes/src/store/index.spec.ts
packages/compass-global-writes/src/store/index.ts
packages/compass-global-writes/src/store/reducer.ts

While the state and UI existed already, this PR completes it with:
- Cancel sharding action (requires confirmation)
- Polling for shardKey or shardingError
- polling starts when sharding state has been detected right away or reached after a successful sharding request
- polling ends when either shardKey or shardingError is retrieved, or when the user cancels the sharding request
- polling is paused when the plugin title is not displayed (this means the user is not in the workspace), and renewed if they come back. note: this is tied to the plugin title and not content because the title includes the unsharded warning
- Simplified integration tests (index.spec.ts - testing redux + service in different scenarios).

feat(compass-global-writes): sharding in progress state COMPASS-8277

---

packages/compass-generative-ai/src/atlas-ai-service.spec.ts
packages/compass-generative-ai/src/atlas-ai-service.ts
packages/compass-generative-ai/src/components/generative-ai-input.spec.tsx
packages/compass-generative-ai/src/components/generative-ai-input.tsx

Currently if folks use the generative ai feature in Compass with a collection with documents with a lot of fields, we'll show an error:
"Sorry, your collections have too many fields to process. Please try 
using this feature on a collection with smaller documents."
PROMPT_TOO_LONG error from mms
This is because we don't want to exceed the token limit of open ai. We recently changed from gpt-3.5-turbo to gpt-4o. The new limit is 128,000 tokens and OpenAI approximates 1 token as ~= 4 english chars, so we updated this field to 4*128,000 = 512000 in the server. Since we want the final validation to be on the server lets do 10x what the server limit is at. The server does some further changes to schema and sample documents so we should let it be the decider. The frontend should only prevent …

fix(compass-generative-ai): Increase the character size restriction for query and aggregation genai COMPASS-8369

---

packages/compass-global-writes/src/components/index.spec.tsx
packages/compass-global-writes/src/components/index.tsx
packages/compass-global-writes/src/components/shard-key-markup.tsx
packages/compass-global-writes/src/components/states/shard-key-correct.spec.tsx
packages/compass-global-writes/src/components/states/shard-key-correct.tsx
packages/compass-global-writes/src/components/states/shard-key-invalid.spec.tsx
packages/compass-global-writes/src/components/states/shard-key-invalid.tsx
packages/compass-global-writes/src/components/states/shard-key-mismatch.spec.tsx
packages/compass-global-writes/src/components/states/shard-key-mismatch.tsx
packages/compass-global-writes/src/services/atlas-global-writes-service.ts
packages/compass-global-writes/src/store/index.spec.ts
packages/compass-global-writes/src/store/reducer.ts

Adding two new screens, handling the invalid and mismatching shard key states. This one was pretty straight-forward. Content taken from current data-explorer, updated to Compass/LG components.

feat(compass-global-writes): invalid and mismatching shard key state COMPASS-8278

---

packages/compass-e2e-tests/helpers/commands/index.ts
packages/compass-e2e-tests/helpers/commands/read-first-document-content.ts
packages/compass-e2e-tests/helpers/commands/read-stage-operators.ts
packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
packages/compass-e2e-tests/tests/collection-ai-query.test.ts
packages/compass-e2e-tests/tests/collection-import.test.ts
packages/compass-e2e-tests/tests/in-use-encryption.test.ts
packages/compass-e2e-tests/tests/read-only.test.ts

Small drive-by clean up, spotted while working on something else: we have all other commands attached to browser instance directly

chore(e2e): move commands to commands folder

---

.evergreen/print-compass-env.sh
packages/data-service/src/connect-mongo-client.spec.ts
packages/data-service/src/data-service.spec.ts

We were running unit tests on 6.0.x in CI and whatever mongodb-runner uses by default locally.

chore: bump the major version we run unit tests on in ci

---

packages/atlas-service/src/main.ts
packages/atlas-service/src/util.ts
packages/compass-generative-ai/src/atlas-ai-service.spec.ts
packages/compass-generative-ai/src/atlas-ai-service.ts
packages/compass-generative-ai/src/provider.tsx
packages/compass-settings/src/components/settings/atlas-login.spec.tsx
packages/compass-settings/src/components/settings/atlas-login.tsx

This wasn't used, and we aren't planning to add it onto the user info, so we can remove it.

chore(atlas-service): remove unused ai enabled boolean

---

packages/compass-settings/src/components/settings/proxy-settings-custom.tsx
packages/compass/src/main/application.ts

fix(proxy): do not lock users out of Compass when using authenticated proxies COMPASS-8382

---

packages/compass-e2e-tests/helpers/commands/connect-form.ts
packages/compass-e2e-tests/helpers/compass.ts
packages/compass-e2e-tests/index.ts
packages/compass-e2e-tests/tests/collection-rename.test.ts

https://jira.mongodb.org/browse/CLOUDP-274595
Enable running compass E2E tests directly against a deployed Atlas environment.
Additionally, enable specifying a test filter as env var to support only running a subset of tests.
Example usage:
```
export CONNECTION_STRING_1='mongodb+srv://<username>:<password>@connection-1.dkur9.mongodb-dev.net/?retryWrites=true&w=majority&appName=connection-1'
export CONNECTION_NAME_1=connection-1
export CONNECTION_STRING_2='mongodb+srv://<username>:<password>@connection-2.dkur9.mongodb-dev.net/?retryWrites=true&w=majority&appName=connection-2'
export CONNECTION_NAME_2=connection-2
export ATLAS_DOMAIN=cloud-dev.mongodb.com
export ATLAS_GROUP_ID=66ce1716209aca269796919b
export COOKIES_FILE=/Users/siyanzhu/compass/packages/compass-e2e-tests/cloud-dev.mongodb.c …
```

chore(e2e): enable e2e tests to run directly against Atlas

---

packages/compass-e2e-tests/helpers/commands/close-shell.ts
packages/compass-e2e-tests/helpers/commands/collection-workspaces.ts
packages/compass-e2e-tests/helpers/commands/connect-form.ts
packages/compass-e2e-tests/helpers/commands/connect.ts
packages/compass-e2e-tests/helpers/commands/connection-workspaces.ts
packages/compass-e2e-tests/helpers/commands/database-workspaces.ts
packages/compass-e2e-tests/helpers/commands/disconnect.ts
packages/compass-e2e-tests/helpers/commands/open-shell.ts
packages/compass-e2e-tests/helpers/commands/remove-connections.ts
packages/compass-e2e-tests/helpers/commands/save-connection-string-as-favorite.ts
packages/compass-e2e-tests/helpers/commands/save-favorite.ts
packages/compass-e2e-tests/helpers/commands/select-connections-menu-item.ts
packages/compass-e2e-tests/helpers/commands/sidebar-connection.ts
packages/compass-e2e-tests/helpers/compass.ts
packages/compass-e2e-tests/helpers/insert-data.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/auto-connect.test.ts
packages/compass-e2e-tests/tests/connection-form.test.ts
packages/compass-e2e-tests/tests/connection.test.ts
packages/compass-e2e-tests/tests/force-connection-options.test.ts
packages/compass-e2e-tests/tests/import-export-connections.test.ts
packages/compass-e2e-tests/tests/in-use-encryption.test.ts
packages/compass-e2e-tests/tests/instance-sidebar.test.ts
packages/compass-e2e-tests/tests/logging.test.ts
packages/compass-e2e-tests/tests/my-queries-tab.test.ts
packages/compass-e2e-tests/tests/oidc.test.ts
packages/compass-e2e-tests/tests/protect-connection-strings.test.ts
packages/compass-e2e-tests/tests/read-only.test.ts
packages/compass-e2e-tests/tests/shell.test.ts
packages/compass-e2e-tests/tests/tabs.test.ts

We already partially removed some single connection code from the app so these tests won't work anyway. I'm doing some clean-up in compass-e2e-tests package, so extra env flags to deal with are a bit in the way, so I'm removing this one that is always `true`
Definitely easier to review with [whitespace diff off](https://github.com/mongodb-js/compass/pull/6393/files?w=1)

chore(e2e): remove TEST_MULTIPLE_CONNECTIONS flag from e2e tests

---

.evergreen/functions.yml
package-lock.json
packages/compass-e2e-tests/package.json
packages/compass/package.json
packages/compass/scripts/electron-rebuild.js
packages/data-service/package.json
packages/hadron-build/commands/release.js
packages/hadron-build/package.json

For some reason after updating node-gyp the build that was passing in https://github.com/mongodb-js/compass/pull/6390 started failing on main, from the logs it seems that the culprit is a dependency on older node-gyp version in electron rebuild. Unclear to me why this didn't show up in the PR branch, so I'm just bumping the version of @electron/rebuild to resolve it (seems like they forked node-gyp to resolve the issue)

chore(deps): update electron/rebuild dependency

---

packages/compass-workspaces/src/provider.tsx
packages/compass-workspaces/src/stores/workspaces.ts
packages/databases-collections/src/modules/create-namespace.ts

feat(global-writes): open global writes tab when creating a collection COMPASS-8280

---

scripts/update-electron.js

Forgot to include this into #6411, now that we have a direct dep on electron-to-chromium, we should update it with electron

chore(scripts): include electron-to-chromium to the list of packages to be updated with electron

---

.github/workflows/bump-packages.yaml
.github/workflows/update-electron.yaml

We still want to follow conventional commit, but we usually don't have tickets for these, adding this label will skip the ticket check

chore(ci): add no-title-validation label to autogenerated PRs

---

.evergreen/functions.yml
.evergreen/start-atlas-cloud-cluster.sh
packages/compass-e2e-tests/helpers/test-runner-context.ts

Small follow up to the new e2e capabilities to make it a bit easier to run these locally if needed. I adjusted the implies check in yargs parsing so that you can keep these env in your shell env config without triggering the implies check when not running the tests for cloud (you still need to explicitly provide the `--test-atlas-cloud` flag to trigger the test and it's still required to provide all the other options in that case, just not otherwise), also added some detailed instructions for what needs to be manually setup before running those, should be helpful also if we ever need to re-do the user creation

chore(e2e): adjust the scripts to make it easier to run atlas cloud e2e tests locally

---

packages/compass-e2e-tests/helpers/compass-web-sandbox.ts

Haven't thought that this screen shows up over time after being dismissed, so the CI is currently failing because the sign in flow can't be finished. This patch adds a check for the dismiss button running in parallel to waiting for the auth request to resolve, so we either resolve when auth is done or this screen appears and we click the button and then wait for the auth
Unless you're trying this locally with your account it's kinda hard to repro for testing purposes, but I ran this tests twice locally against the account like that to make sure that 1) it's dismissed when appears 2) the code is not blocking the sign in when it doesn't appear, and both scenarios worked

fix(e2e): account for a recurring MFA reminder when singing in to cloud ui

---

.evergreen/functions.yml
.evergreen/start-atlas-cloud-cluster.sh

Another follow-up to cloud e2e tests to reduce the amount of manual config required to run these:
- Create db user automatically and delete it afterwards
- Automatically add current ip to the network access
Both are added with an arbitrary delete after of two hours that should be more than enough for our tests so that even if for some reason exit cleanup fails, they'd be eventually removed from the project

chore(e2e): automatically create db user and add ip address to the access list before running tests

---

packages/compass-e2e-tests/tests/atlas-cloud/rolling-indexes.test.ts

Always forget that we need to add these screenshots manually. It haven't failed yet, but it wouldn't be fun to debug if it starts to

chore(e2e): screenshot if failed in rolling-indexes test

---

packages/compass-user-data/src/semaphore.spec.ts
packages/compass-user-data/src/semaphore.ts
packages/compass-user-data/src/user-data.spec.ts
packages/compass-user-data/src/user-data.ts

fix(user-data): use semaphore to limit reads COMPASS-7256

---

packages/compass-editor/src/action-button.tsx
packages/compass-editor/src/actions-container.tsx
packages/compass-editor/src/editor.tsx
packages/compass-editor/src/index.ts
packages/compass-editor/src/types.ts

As a preparation for [COMPASS-4635](https://jira.mongodb.org/projects/COMPASS/issues/COMPASS-4635) this refactors the JSON editor, extracting the actions container into its own component. This refactor brings no additional features or visual changes.

chore(compass-editor): refactor JSON editor actions container into its own component

---

packages/compass-components/src/components/document-list/document-actions-group.tsx
packages/compass-components/src/components/document-list/element.tsx

As a preparation for COMPASS-4635 this solves the first part of the designed proposed in EXPO-2098: Making the expand-all button more compact and trimming padding.

chore(compass-components): less document whitespace

---

packages/compass-crud/src/components/json-editor.tsx
packages/compass-editor/src/action-button.tsx
packages/compass-editor/src/actions-container.tsx
packages/compass-editor/src/editor.tsx

A sub-task of the design proposed in COMPASS-4635 is to add the "expand all" / "collapse all" button to the JSON editor view of documents.
- Update the spacing of the actions container and styles injected by the `JSONEditor` component to use the non-deprecated variants, as well as pull the actions container to span the entire width.
- Add `pointer-events` css properties to avoid capturing clicks on whitespace of the actions container.
- Add a "compact" prop to the editors `ActionButton` component, using [the same hack introduced in #6439](https://github.com/mongodb-js/compass/pull/6439/files/3bc54710e5b07b8a7771973a509af83ef92f1eb6#diff-08b32be8f1f7995a0af322d352a6f5390db3c1c14bcf897bc6c8e595f113ccb2R47-R52). I hope to replace this by [an upstream change to …

feat(editor): expandable json editor

---

packages/compass-global-writes/src/components/example-commands-markup.spec.tsx
packages/compass-global-writes/src/components/example-commands-markup.tsx
packages/compass-global-writes/src/components/index.tsx
packages/compass-global-writes/src/components/shard-zones-description.tsx
packages/compass-global-writes/src/components/shard-zones-descripton.spec.tsx
packages/compass-global-writes/src/components/shard-zones-table.tsx
packages/compass-global-writes/src/components/states/incomplete-sharding-setup.spec.tsx
packages/compass-global-writes/src/components/states/incomplete-sharding-setup.tsx
packages/compass-global-writes/src/components/states/shard-key-correct.spec.tsx
packages/compass-global-writes/src/components/states/shard-key-correct.tsx
packages/compass-global-writes/src/components/states/shard-key-invalid.spec.tsx
packages/compass-global-writes/src/components/states/shard-key-mismatch.spec.tsx
packages/compass-global-writes/src/services/atlas-global-writes-service.ts
packages/compass-global-writes/src/store/index.spec.ts
packages/compass-global-writes/src/store/reducer.ts

When the collection has already been geosharded with one key, it cannot be sharded with another one. Until now, we allowed this because we went from SHARD_KEY_CORRECT -> UNSHARDED. This PR handles the state when collection has already been sharded (shardKey exists), but it is not managed now. The new state is INCOMPLETE_SHARDING_SETUP, and from this state we can only resume sharding. The request is the same, but the key description is taken from the existing key, not user input.
The change looks bigger than it is - `example-commands-markup.tsx` and `shard-zones-description.tsx` are just moved out of `shard-key-correct.tsx`. The bulk of changes is in the reducer, which had to be rearranged a bit to incorporate the new scenario (we haven't realised this possibility exists until later on).

feat(compass-global-writes): incomplete sharding setup COMPASS-8372

---

.github/workflows/check-pr-title.yml

CLOUDP tickets are over current limit and doesn't look like there's a reason to set this so precise

chore(ci): allow for more numbers in tickets

---

packages/compass-global-writes/src/components/index.tsx

Some small fixes for the global-writes tab conatiner:
- WorkspaceContainer component should not be wrapped in anything, the intent is for it to always just take all the availble space in the tab, otherwise the shadow and scroll it renders looks weird and kinda broken
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/6a84d8d1-169d-4ab5-958b-a208e620d654)|![image](https://github.com/user-attachments/assets/e14b0762-b091-45cd-97b7-ee39c422f3a4)|
- Loading spinner was off-center because of the max width for the content it was rendered in, I also removed the vertical centering, we usually do a margin from the top (see CRUD for example) so that on bigger screens it's not showing up too close to the bottom, it looks a bit off and inconsistent with other tabs in the …

chore(global-writes): fix subtab container styles

---

packages/atlas-service/src/atlas-service.spec.ts
packages/atlas-service/src/atlas-service.ts
packages/compass-web/sandbox/index.tsx
packages/compass-web/sandbox/sandbox-atlas-sign-in.tsx
packages/compass-web/scripts/electron-proxy.js

We forgot to copy this logic over from mms when setting up the atlas service fetch methods and because the sandbox was implicitly applying those to every request when proxying we didn't notice this locally. This patch updates the atlas-service to the csrf passing logic and also updates the sandbox so that it closer emulates what happens in cloud. I added some unit tests, and the existing sandbox tests should cover the e2e part

fix(atlas-service): pass csrf tokens with the requests COMPASS-8490

---

packages/compass-components/src/components/document-list/document.tsx
packages/compass-components/src/components/document-list/element.tsx
packages/compass-crud/src/components/readonly-document.tsx

This is the final sub-task of COMPASS-4635 adding an "expand all" / "collapse all" button to the read-only view.
- Make the `ReadonlyDocument` expandable, by registering relevant event listeners on the `doc` updating a local state.
- Pass a callback into the `DocumentActionsGroup` component to render the "expand button".
- Add extra gutter width in the `Element` component when used in a `ReadonlyDocument` to avoid conflicts with the field-level expand/collapse icons.
https://github.com/user-attachments/assets/3cbaa1d1-36b2-40d4-8139-e0bbf74dd320

fix(crud): expandable readonly document COMPASS-4635

---

packages/compass-global-writes/src/components/index.tsx
packages/compass-global-writes/src/components/states/loading-error.spec.tsx
packages/compass-global-writes/src/components/states/loading-error.tsx
packages/compass-global-writes/src/store/index.spec.ts
packages/compass-global-writes/src/store/reducer.ts

This one adds a LOADING_ERROR state. This state is reached whether the loading fails in the initial state (NOT_READY), or during polling (SHARDING). I have considered to simply show the toast during polling and continue with polling attempts. But seeing it in action, I think the toast isn't very clear when there was no user action, so I choose to handle both the same way (LOADING_ERROR and user has to reload). Let me know what you think about it, I'm on the edge about stopping the polling after it fails - it might be a temporary error after all.

fix(compass-global-writes): handle loading error COMPASS-8446

---

package-lock.json
packages/compass-e2e-tests/package.json
packages/compass/package.json

Generate vulnerability report task is failing on [CI](https://spruce.mongodb.com/task/10gen_compass_main_generate_vulnerability_report_generate_vulnerability_report_6731571627cea30007113020_24_11_11_01_00_06/logs?execution=1) and requires to bump cross-spawn to latest in addition to electron update (#6428)

chore(deps): bump cross-spawn

---

docs/tracking-plan.md
packages/compass-connections/src/stores/connections-store-redux.ts
packages/compass-telemetry/src/telemetry-events.ts

- Add two new fields to the "New Connection" event.
- Supply values for these when a new connection gets established.

chore(connections): send active and inactive connections with "New Connection" telemetry event COMPASS-8476

---

packages/compass-components/src/components/item-action-controls.tsx
packages/compass-connections-navigation/src/base-navigation-item.tsx
packages/compass-connections-navigation/src/connections-navigation-tree.tsx
packages/compass-connections-navigation/src/item-actions.ts
packages/compass-connections-navigation/src/navigation-item.tsx
packages/compass-e2e-tests/helpers/commands/connect.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx

- Add a connect action, represented as a `Button` to every disconnected connection item in the sidebar.
- Disable the default action (which was connecting) when clicking the connection in the sidebar as well as removing the visual cue for the interaction (the `cursor: 'pointer'`).
- Update E2E tests to connect by clicking the new button.
- Invert a test which expected clicking an inactive connection to connect.
https://github.com/user-attachments/assets/4743b209-1aed-463e-be3e-c3fe478fe2fa
- Given the intent to eventually extend this "Connect" button with a drop-down, I wonder if the existing `ItemAction` abstraction is the right for this feature or I should introduce another prop to inject a custom component into the `NavigationBaseItem`.

chore(connections-navigation): add connect button to connections in sidebar COMPASS-8381

---

packages/compass-collection/src/components/collection-tab.tsx

fix(compass-global-writes): make global writes tab not appear for readonly and config/local/admin collections COMPASS-8447

---

packages/compass-components/src/components/interactive-popover.tsx
packages/compass-components/src/hooks/use-sort.spec.ts
packages/compass-components/src/hooks/use-sort.tsx

The `useId` hook automatically generates an id when one is not provided, so when a constant value is passed, it does nothing. Also in one case id was not passed correctly at all (as shown by the tests using a meaningless label when selecting an element). This patch fixes both of those issues

fix(components): fix incorrect usage of useid

---

packages/compass/src/setup-hadron-distribution.ts

After the last electron upgrade it stopped working. We should eventually clean up this workaround as part of COMPASS-8269, but this would be an involved process at least requiring us to release mongosh (all releases are blocked at the moment), so this is a contained workaround for now

chore(compass): work around local dev issue with loading worker from a file COMPASS-8504

---

packages/compass-connections/src/index.spec.tsx
packages/compass-connections/src/index.tsx
packages/compass-connections/src/stores/connections-store-redux.ts
packages/compass-connections/src/stores/connections-store.spec.tsx
packages/compass-web/src/connection-storage.tsx

Two small fixes related to compass-web:
- cleanup connections when plugin is deactivated, doesn't really affect compass, but when navigating to other pages in DE, connections stay open CLOUDP-284226
- filter out paused clusters when building a list of connections, we can't really connect to those and they are missing important metadata COMPASS-8510

fix(web, connections): filter out paused clusters; cleanup connections on plugin deactivate COMPASS-8510 CLOUDP-284226

---

.evergreen/functions.yml
.evergreen/start-atlas-cloud-cluster.sh
packages/compass-indexes/src/components/create-index-form/create-index-form.tsx
packages/compass-indexes/src/index.spec.tsx
packages/compass-indexes/src/index.ts
packages/compass-indexes/src/modules/index.ts
packages/compass-indexes/src/modules/regular-indexes.ts
packages/compass-indexes/src/stores/store.ts
packages/compass-indexes/test/setup-store.ts
packages/compass-preferences-model/src/feature-flags.ts
packages/compass-web/sandbox/index.tsx

Will be used for the controlled rollout of the feature in mms

chore(indexes): add feature flag for rolling indexes COMPASS-8507

---

.evergreen/functions.yml
package.json

It doesn't work. Maurizio and Anna both agree that it is ok to remove.
See https://spruce.mongodb.com/task/10gen_compass_main_generate_vulnerability_report_generate_vulnerability_report_673e8614859d330007f853f4_24_11_21_01_00_04/logs?execution=0

chore: remove the code that tries to generate the vulnerability report tickets

---

packages/compass-e2e-tests/helpers/commands/hide-visible-toasts.ts

https://parsley.mongodb.com/test/10gen_compass_main_test_maintained_servers_test_server_60x_community_1_673e8614859d330007f853f4_24_11_21_01_00_04/0/d34d0aa2d775324b8cb563070a9290a7?bookmarks=0,12,17&shareLine=0

chore(e2e): fix for rare e2e test flake

---

packages/compass-preferences-model/src/compass-web-preferences-access.ts

COMPASS-8572
This updates the runtime memory preferences for Compass web, `CompassWebPreferencesAccess`, to allow updating of the `cloudFeatureRolloutAccess` preference. This is updated when the hello endpoint returns that the feature is enabled.

chore(preferences-model): enable updating the cloudFeatureRolloutAccess preference for web COMPASS-8572

---

.github/workflows/authors-and-third-party-notices.yaml

This updates the authors/3rd party notices workflow to use our github app and push to main directly rather than have to go through a PR for every commit.

chore(ci): use a github app to commit to main directly COMPASS-8573

---

.github/workflows/authors-and-third-party-notices.yaml

Had a copy-paste error from mongosh, where */AUTHORS was added, but we don't have those in Compass.

chore(ci): fix 3rd party notices workflow

---

packages/data-service/src/data-service.ts
packages/data-service/src/instance-detail-helper.ts
packages/data-service/src/run-command.ts

There's an old server bug where it could truncate content in the middle of a UTF-8 codepoint: https://jira.mongodb.org/browse/SERVER-24007
This can make compass unusable if it happens for one of the commands that compass fires off when you connect or browse to a collection. It is reasonably safe to just turn off utf8 validation in those cases. We still leave it on when reading/writing documents and therefore users aren't at risk of writing back broken data to their database.

chore(data-service): disable utf8 validation when retrieving metadata compass needs in order to function COMPASS-8517

---

.github/workflows/authors-and-third-party-notices.yaml
.github/workflows/bump-packages.yaml
.github/workflows/merge-bump-packages-pr.yaml
.github/workflows/update-electron.yaml
CONTRIBUTING.md

This is a minor cleanup of gha workflows. It includes the following changes:
- Bump 3rd party actions to the latest version
- Use our github app token instead of the service account
- Cleanup redundant steps or arguments
TODO:

chore(ci): use github app for tokens

---

packages/compass-connections/src/utils/connection-supports.spec.ts
packages/compass-connections/src/utils/connection-supports.ts
packages/compass-web/src/connection-storage.spec.ts
packages/compass-web/src/connection-storage.tsx
packages/connection-info/src/connection-info.ts

https://jira.mongodb.org/browse/COMPASS-8579
Note: I'm not storing the rest of the geoSharding object in connectionInfo, as the `managedNamespace` part is something we can manage in compass-web and could easily become stale. I don't think `selfManagedSharding` can become stale, afaik it's decided when the cluster is created.

fix: avoid global writes for self managed sharding COMPASS-8579

---

.github/workflows/bump-packages.yaml
.github/workflows/update-electron.yaml

https://github.com/mongodb-js/compass/pull/6534 made it so we use the github app token for creating PRs but we hadn't requested permissions for this. I've reached out to IT to update the perms, but in the meantime, reverting to the user token.

chore(ci): use the devtools bot user token for PRs

---

packages/compass-collection/src/components/collection-tab.tsx
packages/compass-preferences-model/src/feature-flags.ts
packages/compass-preferences-model/src/preferences-schema.ts

Although this flag was created, it was never actually used. It was also defined in `InternalUserPreferences` instead of `FeatureFlags`. How did this work before? It was because atlasMetadata is missing for Electron Compass, so instead of the flag the `isGlobalWritesSupported` condition was never met: https://github.com/mongodb-js/compass/blob/77c23bf4da5ca7b5368dc6083d184264e5b95579/packages/compass-connections/src/utils/connection-supports.ts#L15

fix: global writes feature flag COMPAS-8524

---

.evergreen/buildvariants-and-tasks.in.yml
.evergreen/buildvariants-and-tasks.yml

It was strongly suggested that we don't run these on PRs. Running on main should still cover us from introducing unexpected breakage, will just require paying a bit more attention. And the scripts are still usable for running those locally

chore(ci): do not run atlas cloud tests on PRs

---

packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.tsx
packages/compass-components/src/components/interactive-popover.tsx
packages/compass-components/src/components/signal-popover.tsx
packages/compass-query-bar/src/components/query-history-button-popover.tsx
packages/compass-sidebar/src/components/connections-filter-popover.tsx

As a follow-up to this https://github.com/mongodb-js/compass/pull/6486#discussion_r1841958522, I suggest adding a type argument to the `InteractivePopover` to specify the concrete `HTMLElement` used when declaring the type of the `ref` passed through the `trigger` callback.
We can't just pass `React.Ref<HTMLElement>` as that (as an example) isn't possible to pass via `ref` to a `<button />`:
```tsx
const ref = React.useRef<HTMLElement>(null);
return <button ref={ref} />;
```
☝️ yields this TS error related to the `ref` prop:
```
Type 'RefObject<HTMLElement>' is not assignable to type 'LegacyRef<HTMLButtonElement> | undefined'.
Type 'RefObject<HTMLElement>' is not assignable to type 'RefObject<HTMLButtonElement>'.
Type 'HTMLElement' is missing the following properties from type …
```

chore(components): refactor `InteractivePopover` to take a type argument for the trigger element

---

packages/compass-connections-navigation/src/base-navigation-item.tsx
packages/compass-connections-navigation/src/connections-navigation-tree.tsx
packages/compass-connections-navigation/src/navigation-item.tsx
packages/compass-connections-navigation/src/tree-item.tsx

This is a follow-up to #6449.
- Disable the pointer cursor on the right-caret icon shown on disconnected rows of the connection navigation in the sidebar.
- Refactor the way callbacks for expanding / collapsing is passed through the tree.

chore(connections-navigation): disable sidebar right-caret on disconnected connections

---

packages/compass-connections-navigation/src/connections-navigation-tree.tsx
packages/compass-connections-navigation/src/item-actions.ts

- Remove the "Connect" action / button from a connection row in the sidebar, while a connection is being established.
This is a follow-up to https://github.com/mongodb-js/compass/pull/6449.
https://github.com/user-attachments/assets/11dd52d5-bd09-45a9-9244-db3ae124dc14

fix(connections-navigation): don't show connect button while connecting COMPASS-8599

---

packages/compass-components/src/components/document-list/element-editors.tsx
packages/compass-components/src/components/document-list/element.tsx

[COMPASS-8586](https://jira.mongodb.org/browse/COMPASS-8586)
- Fixes the duplicate key error tooltip not showing.
- Fixes the `revert` action not reverting the validity of a field if it updates the field name making it not a duplicate.
- Shows a red error around values that are invalid similar to what we do with keys.
**Error tooltip that is now shown**
**Error validity state of field**
| - | - |
| <img width="443" alt="Screenshot 2024-12-03 at 2 26 17 PM" src="https://github.com/user-attachments/assets/d2a6e537-1fdb-4eaf-be92-204911bf95ae"> | <img width="424" alt="Screenshot 2024-12-03 at 2 02 04 PM" src="https://github.com/user-attachments/assets/d1356f7a-ff7e-4801-8437-a8b9f5da1df7"> |

fix(components): fix element key editor tooltip and revert not updating validity COMPASS-8586

---

packages/compass-generative-ai/src/atlas-ai-service.spec.ts
packages/compass-generative-ai/src/atlas-ai-service.ts
packages/compass-web/sandbox/index.tsx
packages/compass-web/src/connection-storage.tsx
packages/compass-web/src/entrypoint.tsx

COMPASS-8571
Also adds a gen ai feature enablement env variable to sandbox. This is helpful when testing, and we'll use it in the e2e tests (these settings it overrides will be passed from mms).
In mms we can pass in the `settingsModel.get('USER_AUID')` `userAuid` to make this consistent.

chore(generative-ai): use telemetryAtlasUserId in feature enablement check COMPASS-8571

---

package-lock.json
packages/hadron-build/package.json

This commit updates the signing-utils package to the latest version because our Authenticode certificate has nearly expired and we need the latest package version in order to use the new one.

chore(deps): update signing-utils to latest DEVPROD-13204

---

packages/compass-e2e-tests/helpers/compass-web-sandbox.ts

This got missed when updating wdio to 9 as the tests are not running on PRs. I [did a manual patch](https://spruce.mongodb.com/task/10gen_compass_main_test_web_sandbox_atlas_cloud_test_web_sandbox_atlas_cloud_patch_8e96a1e94fa9238a29bf7133f49cf3f8d419bedb_675c2e4490d0680007311ce8_24_12_13_12_53_36/logs?execution=0) to confirm that this fixes the issue, it's green

fix(e2e): add the webdriverclassic option to the atlas cloud login window remote session

---

packages/compass-generative-ai/src/store/atlas-optin-reducer.spec.ts
packages/compass-generative-ai/src/store/atlas-optin-reducer.ts

COMPASS-8681
Previously we would show the input, which would then create an error anytime the user would try to submit as the backend checks for the project setting. This way the modal tells them it's disabled with a link to the setting:

fix(generative-ai): when opted-in and the project setting is disabled show opt in COMPASS-8681

---

packages/compass-serverstats/src/components/top-component.jsx
packages/compass-serverstats/src/stores/top-store.js

COMPASS-8604
Small visual bug on how we show the % of write on the load in the top / hottest collections chart. Javascript related (typescript would catch this sort of thing).
Not easily seen which is probably why it's never been fixed. This bug has probably been in there since it was written 5+ years ago lol.
This is the chart for reference:

fix(serverstats): update top chart write lock percentage of load visual COMPASS-8604

---

packages/compass-aggregations/src/components/stage-toolbar/option-menu-item.tsx
packages/compass-aggregations/src/components/stage-toolbar/option-menu.tsx
packages/compass-components/src/components/workspace-tabs/tab.tsx
packages/compass-components/src/components/workspace-tabs/workspace-tabs.tsx
packages/compass-components/src/index.ts
packages/compass-editor/src/action-button.tsx
packages/databases-collections-list/src/namespace-card.tsx

An alternative to the refactor which happened in https://github.com/mongodb-js/compass/pull/6569#discussion_r1887231014 favoring composition over arrays of props.
I included a change to re-export the `GlyphName` from LG instead of deriving and exporting our own from the "components" package.

chore(aggregations): Refactor aggregations stage toolbar

---

.evergreen/buildvariants-and-tasks.in.yml
.evergreen/buildvariants-and-tasks.yml

(Tried this out in an evergreen patch before: https://spruce.mongodb.com/version/675a5d733c7efa00075f30bb/tasks)

chore(ci): switch to newer `macos-11{,-arm64}-gui` distros COMPASS-8696

---

packages/compass-components/src/components/virtual-list.tsx
packages/compass-components/src/hooks/use-virtual-list-item-observer.ts
packages/compass-crud/src/components/virtualized-document-json-view.spec.tsx
packages/compass-crud/src/components/virtualized-document-json-view.tsx
packages/compass-crud/src/components/virtualized-document-list-view.spec.tsx
packages/compass-crud/src/components/virtualized-document-list-view.tsx

This PR exposes virtual list `listRef` prop and also item index when trying to estimate the item height. Doing this as part of [COMPASS-7567](https://jira.mongodb.org/browse/COMPASS-7567) and this will be eventually used in browser-repl package inside mongosh.

chore(compass-components): expose v-list listRef prop COMPASS-7567

---

packages/compass-components/src/components/actions/dropdown-menu-button.tsx
packages/compass-components/src/components/actions/item-action-button.tsx
packages/compass-components/src/components/actions/item-action-controls.spec.tsx
packages/compass-components/src/components/actions/item-action-controls.tsx
packages/compass-components/src/components/actions/item-action-group.tsx
packages/compass-components/src/components/actions/item-action-menu.tsx
packages/compass-components/src/components/actions/utils.ts
packages/compass-connections-navigation/src/base-navigation-item.tsx
packages/compass-connections-navigation/src/connect-button.tsx
packages/compass-connections-navigation/src/constants.tsx
packages/compass-connections-navigation/src/item-actions.ts
packages/compass-connections-navigation/src/navigation-item.tsx

Follow-up to https://github.com/mongodb-js/compass/pull/6552.
- Replace `&:not(:first-child)` styling to add spacing between item action buttons with the use of flex `gap` on the container element.
- Add strong typing for 3x `onClick` handlers accessing `data-action` attributes on the element being clicked.
- Remove `Actions` generic type parameters where it didn't add additional guarantees
- Provide default type argument for `Actions` generic type to simplify use internally in the `./actions` directory.
- Remove unneeded / extraneous memoization.

chore(compass-components): refactor `ItemActionControls` #2

---

packages/compass/src/index.d.ts
packages/compass/src/main/auto-update-manager.ts

The way autoupdate is unit tested we already override the endpoint anyway, so my attempts there were a bit useless. So I ended up testing this manually with a small custom express server. The little express server will form part of the next step where we use it to test auto-update, so that will be end-to-end tested properly starting in the next PR.

feat(autoupdate): allow setting the autoUpdate endpoint with process.env.HADRON_AUTO_UPDATE_ENDPOINT_OVERRIDE COMPASS-8534

---

packages/compass-web/sandbox/sandbox-atlas-sign-in.tsx

New leafygreen likely changed some styles that made the sign in button stop being visible.
| - | - |
| <img width="428" alt="Screenshot 2025-01-02 at 1 17 24 PM" src="https://github.com/user-attachments/assets/0752804d-99cd-48d1-9b1b-64e2902e4be9" /> | <img width="435" alt="Screenshot 2025-01-02 at 1 17 14 PM" src="https://github.com/user-attachments/assets/93acd0e3-b940-4e14-bd0a-2ffeec2ad78f" /> |

fix(compass-web): update sandbox toast action to make actions visible

---

.github/workflows/codeql.yml
.github/workflows/publish-compass.yaml
.github/workflows/publish-packages.yaml
.github/workflows/start-beta.yml
.github/workflows/start-ga.yaml
.github/workflows/update-electron.yaml

This cleans up a few gha workflows:
1. Format using prettier (best review this with whitespace: off)
2. Bump checkout and setup-node versions to latest
3. Configure token/author in the update-electron workflow
4. Removes a non-existent secret from the start-ga workflow

chore: gha workflow updates

---

packages/compass-e2e-tests/smoke-test.ts

None of my suggested changes are critical and I'd be okay with reverting any of the, if you have a strong preference for the existing code 👍

chore(e2e): Smoke test cli cleanup

---

packages/compass-connections/src/utils/connection-supports.spec.ts
packages/compass-connections/src/utils/connection-supports.ts

Rolling indexes are not available on flex tier. Tested the change with the flex cluster we have on -dev, kinda hard to show, but there is not rolling indexes option at the bottom:

chore(indexes): do not show rolling indexes UI for flex tier clusters COMPASS-8622

---

packages/compass-telemetry/src/index.spec.tsx
packages/compass-telemetry/src/telemetry-events.ts

This patch adds is_compass_web property that is being passed with every tracking event in mms to tracking types to make sure it shows up in the tracking plan

chore(telemetry): add is_compass_web to tracking event types

---

configs/testing-library-compass/src/index.tsx
packages/compass-connections/src/index.tsx
packages/compass-connections/src/stores/connections-store-redux.spec.tsx
packages/compass-connections/src/stores/connections-store-redux.ts
packages/compass-web/sandbox/index.tsx
packages/compass-web/src/entrypoint.spec.tsx
packages/compass-web/src/entrypoint.tsx
packages/compass/src/app/components/home.tsx

With this prop, we will be able to handle showing custom error page instead of a toast on mms side.

feat(compass-web): add onFailToLoadConnections callback COMPASS-8657

---

packages/compass-web/polyfills/net/index.ts
packages/compass-web/scripts/ws-proxy.js
packages/compass-web/src/connection-storage.spec.ts
packages/compass-web/src/connection-storage.tsx

Was debugging a flaky test and tracked it down to CCS currently not supporting streaming monitoring (known limitation for now), we already decided to disable it for now ([see tech design](https://docs.google.com/document/d/1QJeqFtp9HeLRcvlnZZUlLu20Se5nOcehtVm0y_FS9rg/edit?tab=t.0#heading=h.rgnltje0h06s)) opting into the polling monitoring, but never updated compass-web to account for that. This patch aligns this and other options with the tech design, polling being the most important to fix as this causes real issues at the moment

chore(web): align cluster connection options with the design COMPASS-8794

---

.npmrc
package-lock.json

Small clean-up: we enabled this initially when moving to the monorepo a long time ago to avoid some conflicting versions being installed, but over time the need for this option went away, so we can remove it. No versions or modules in package-lock changed, just the dev flag got removed or changed to devOptional in some cases, I don't think it should have much of an effect

chore(monorepo): remove legacy-peer-deps from the npmrc

---

package-lock.json
packages/compass-e2e-tests/.eslintrc.js
packages/compass-e2e-tests/helpers/commands/codemirror.ts
packages/compass-e2e-tests/helpers/commands/scroll-to-virtual-item.ts
packages/compass-e2e-tests/helpers/commands/select-file.ts
packages/compass-e2e-tests/helpers/commands/set-export-filename.ts
packages/compass-e2e-tests/helpers/compass-web-sandbox.ts
packages/compass-e2e-tests/helpers/compass.ts
packages/compass-e2e-tests/helpers/telemetry.ts
packages/compass-e2e-tests/package.json
packages/compass-e2e-tests/tests/auto-connect.test.ts
packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
packages/compass-e2e-tests/tests/intercom.test.ts
packages/compass-e2e-tests/tsconfig-lint.json
packages/compass-e2e-tests/tsconfig.json

The WebdriverIO API allows for execution of serialized JavaScript functions in the browser via the `browser.execute` method. We're currently using this. To get typescript support for this, our tsconfig includes `"dom"` as a `lib`, which has the unfortunate drawback that the types for DOM globals become available to all the code, which is running on Node.js and doesn't have values for these available at runtime.
This is an issue first and foremost because the usefulness of TypeScript degrades fast when you cannot trust it and most recently when I wanted to use the `fetch` implementation built into Node.js, as the DOM's `fetch` declaration overlap and differ slightly.
<details><summary>TLDR; It's not trivial to restrict access to these types</summary>
In situations like this, I've reached …

chore(e2e): Lint for restricted globals in e2e tests

---

packages/compass/src/app/components/update-toasts.tsx
packages/compass/src/app/index.tsx

This also adds logging that will be super helpful in debugging auto-update. Especially during testing. And some data-testids we can use in the tests to address things in the relevant toasts.

feat(compass): show the autoupdate installed toast even when we downgrade COMPASS-8808

---

packages/compass-e2e-tests/smoke-test.ts

Unfortunately default values by-pass yarg's validation: Here's a few suggestions to avoid a type assert and potential runtime issue if `ARCH` or `PLATFORM` environment variables doesn't match the supported values.

chore(e2e): few suggestions to smoke-test.ts

---

packages/compass-e2e-tests/smoke-test.ts

Evergreen sets DEV_VERSION_IDENTIFIER to an empty string for beta/ga builds and we don't want to pass that to hadron build info because it will use `''` and then throw an error when it tries to parse it with semver. Furthermore target.js (used by hadron build info) already uses all sorts of env vars and has all sorts of fallbacks and logic that end up just interfering with what we try and set as a parameter, so rather than try and second-guess that let's rather leave it up to hadron build info to do all that.
see https://spruce.mongodb.com/task/10gen_compass_testing_smoketest_ubuntu_compass_smoketest_compass_8c8e61ee1d97ed7e5d8b9cef01553c57a968bdab_25_01_13_05_05_18/logs?execution=1
This also logs the relevant env vars that target.js might be using as a reminder to us that things are …

fix(e2e): do not pass version to hadron build info - have it figure it out on its own COMPASS-8812

---

.github/workflows/authors-and-third-party-notices.yaml
scripts/generate-tracking-plan.ts

Same as #6546, with the same motivation (specifically the lack of CodeQL SARIF reports for automatically created commits which failed their evergreen CI runs, COMPASS-8789), but with a fix that should prevent automatically recursively creating an infinite number of new commits.

Re-revert: chore(ci): do not apply 'skip actions' to automatically generated commit COMPASS-8789

---

packages/compass-e2e-tests/tests/time-to-first-query.test.ts

I have a suspicion that retry isn't helping and is actually making things worse. Let's see what happens in CI for this PR. We don't have to merge it and we can easily revert it too.

chore(e2e): remove the retry

---

packages/compass-e2e-tests/helpers/compass.ts
packages/compass-e2e-tests/helpers/test-runner-global-fixtures.ts

This is here to make very sure that we're definitely testing  the packaged app when we intend to. Mostly to not trip me up every time I read over that code.

chore(e2e): throw if we're unexpectedly building Compass COMPASS-8615

---

packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts

This test has been flaking a lot due to modal not closing as we press the escape.

fix(e2e-tests): close the focus-mode modal COMPASS-8820

---

packages/compass-crud/src/components/crud-toolbar.tsx
packages/compass-schema/src/components/compass-schema.tsx

COMPASS-8835
| - | - |
| <img width="433" alt="Screenshot 2025-01-15 at 2 08 37 PM" src="https://github.com/user-attachments/assets/b691a739-3c5b-4046-80e5-69a7f5e7b63c" /> | <img width="516" alt="Screenshot 2025-01-15 at 3 01 07 PM" src="https://github.com/user-attachments/assets/8c2a42f6-79cc-4d16-8319-25c4963275b2" /> |
A drive by removing the name Compass for better compass web branding in Atlas (also aligns with the other tabs empty state info links)
| - | - |
| <img width="494" alt="Screenshot 2025-01-15 at 5 19 45 PM" src="https://github.com/user-attachments/assets/f22dc747-627c-45ee-af4c-de202f9c2b14" /> | <img width="420" alt="Screenshot 2025-01-15 at 5 19 29 PM" src="https://github.com/user-attachments/assets/4f46ff96-eddb-477e-a8b5-9894f15b1 …

chore(crud): improve tooltip message, remove in Compass from schema view COMPASS-8835

---

packages/compass-import-export/src/export/export-json.spec.ts
packages/compass-import-export/src/export/export-json.ts

One of the flakes: https://parsley.mongodb.com/evergreen/10gen_compass_main_unit_tests_macos_test_patch_7543fc546fa8176745b6f248458505eef113e0d6_6787dc9065173e0007fc3745_25_01_15_16_04_36/0/task?bookmarks=0,97632,97763&selectedLineRange=L97633&shareLine=97630

fix(compass-import-export): handle export flake COMPASS-8839

---

packages/compass-e2e-tests/tests/time-to-first-query.test.ts

I think this was an oversight when I ported the tests to multiple connections. `await browser.connectWithConnectionString();` will remove the connection if it already exists and add it back which is potentially open to race conditions since it is a bit "best effort" which would explain why it flakes.
The original idea behind those tests is the first one starts up with a fresh new user dir and gets the first run experience with the welcome page and then the second one re-opens Compass with the connection already there and the first run experience already in the past.

chore(e2e): reuse the existing connection for the second test

---

.evergreen/functions.yml
packages/data-service/package.json

To avoid expanding those where they are not used

chore(ci): move e2e secrets to their own anchor

---

.evergreen.yml

When we added automated tasks for generating files in the docs dir, we didn't update evergreen to match. This patch fixes this and adds some more files we can ignore to avoid running CI for no good reason

chore(ci): ignore more files as ci triggers in Evergreen

---

packages/compass-web/src/connection-storage.spec.ts
packages/compass-web/src/connection-storage.tsx

For initial launch we want to make the cluster fetching less strict to make sure that the whole compass-web feature doesn't get disabled if some of the clusters end up in the state we didn't anticipate. This patch changes the connection storage in compass-web to filter out clusters when we were not able to build required metadata for connection to be usable in compass and log errors in case anything unexpected happened.

chore(web): catch and log errors when building connection info instead of throwing COMPASS-8848

---

.evergreen/buildvariants-and-tasks.in.yml
.evergreen/buildvariants-and-tasks.yml
.evergreen/functions.yml
packages/compass-smoke-tests/src/build-info.ts
packages/compass-smoke-tests/src/cli.ts
packages/compass-smoke-tests/src/installers/windows-zip.ts

1. Derive the `appName` passed when running the e2e tests from the build file (field name is TBD for Linux)
2. Implement the Windows ZIP installer (the mac zip installer was included in https://github.com/mongodb-js/compass/pull/6621)
3. Arm CI to execute the smoke tests for Mac and Windows ZIP installers.

feat(smoke-tests): test zip installer for on Windows COMPASS-8710

---

.evergreen/buildvariants-and-tasks.in.yml
.evergreen/buildvariants-and-tasks.yml
.evergreen/functions.yml
package.json

A long time ago we added this task to then be able to automate plugin update testing in mms, as we moved away from using plugins directly in mms and it's just a single dependency that we own upgrades for, this is not really useful anymore (and we never got to setting up the actual tests using these `next` packages in mms in the first place)

chore(ci): remove publish-packages-next task from evergreen

---

.github/workflows/bump-packages.yaml
.github/workflows/update-electron.yaml

This is roughly reverting https://github.com/mongodb-js/compass/pull/6641 by re-adding the author, but fixing the value to be a proper email.

chore(ci): re-enable setting the author of the automated PRs

---

.evergreen/functions.yml
package-lock.json
package.json
packages/compass-e2e-tests/package.json

There is currenly an ELSPROBLEMS error on main caused by the version of puppeteer-core being mismatched with the one specified by webdriver:
```sh
npm ls puppeteer-core                                                                                                                                                                                     1 ↵
mongodb-compass-monorepo@ ./compass
└─┬ compass-e2e-tests@1.28.2 -> ./packages/compass-e2e-tests
├── puppeteer-core@23.10.3
└─┬ webdriverio@9.4.1
└── puppeteer-core@23.10.3 deduped invalid: "^22.3.0" from packages/compass-e2e-tests/node_modules/webdriverio
npm error code ELSPROBLEMS
npm error invalid: puppeteer-core@23.10.3 ./compass/node_modules/puppeteer-core
```
This patch is a fix for that and for the ci task that's supposed to be …

fix(package-lock): downgrade puppeteer-core to align with version required by webdriverio

---

packages/compass-e2e-tests/helpers/compass.ts
packages/compass/src/main/application.ts

Pulling this out of https://github.com/mongodb-js/compass/pull/6629 into its own PR.

chore: setup auto-update when testing auto-update, even in CI.

---

packages/compass-telemetry/src/telemetry-events.ts
scripts/generate-tracking-plan.ts

Small drive-by change to tracking documentation

chore(telemetry): add disclaimer to the doc; update new connection description COMPASS-8807

---

scripts/generate-tracking-plan.ts

Should've tried rendering it first and we don't get the previous before automatic pr actually generates it, difference is 
http://example.com/<version>/foo vs `http://example.com/<version>/foo`

fix(tracking): unformat the url to avoid placeholder disappearing

---

.evergreen/functions.yml
packages/compass-smoke-tests/src/cli.ts
packages/compass-smoke-tests/src/context.ts
packages/compass-smoke-tests/src/execute.ts
packages/compass-smoke-tests/src/installers/types.ts
packages/compass-smoke-tests/src/installers/windows-msi.ts

1. Add a `skipCleanup` to prevent the deletion of the sandbox, useful when debugging.
2. Add a `ExecuteFailure` to allow the caller to access the `status` and `signal` of a failing `execute` call.
3. Implement the Windows MSI installer.
4. Arm CI to execute the smoke tests for the Windows MSI installer.

feat(smoke-tests): test MSI installer for on Windows COMPASS-8707

---

packages/compass-web/src/preferences.tsx

We decided to remove the very small hard timeout for the initial launch and just align the behavior with compass that has a soft 60s timeout

chore(web): remove maxTimeMS from default preferences

---

packages/compass-schema/src/modules/schema-analysis.ts
packages/compass-schema/src/stores/reducer.ts
packages/compass-schema/src/stores/store.spec.ts
packages/data-service/src/data-service.spec.ts
packages/data-service/src/data-service.ts

COMPASS-8854
https://www.mongodb.com/docs/manual/core/read-preference/

feat(schema): run schema analysis with secondaryPreferred when read pref not set COMPASS-8854

---

.evergreen/buildvariants-and-tasks.in.yml
.evergreen/buildvariants-and-tasks.yml
.evergreen/print-compass-env.js
.evergreen/print-compass-env.sh

This is a small change that aligns our testing matrix with plaform support policy and mongosh. I'm hoping this will not have any effect at the moment, but unit tests were running against 7.0.x for a long time now, so some units might break, CI should catch this

chore(ci): explicitly define latest stable server to test against based on maintained versions; remove default fallback version

---

packages/hadron-type-checker/src/type-checker.js

The second parameter is scope, but code with scope has been deprecated (see [bson spec](https://bsonspec.org/spec.html)). BSON supports optional scope still, but it becomes a problem if we add validation (this is how I stumbled upon it), because this becomes the deprecated bson type.
Before:
After:

fix(hadron-type-checker): remove deprecated scope from code COMPASS-8921

---

.evergreen/functions.yml
packages/compass-smoke-tests/src/installers/index.ts
packages/compass-smoke-tests/src/installers/windows-registry.ts
packages/compass-smoke-tests/src/installers/windows-setup.ts

1. Add a new `windows-registry.ts` exporting a `query` function callable to query the windows registry database.
3. Implement the Windows Setup.exe installer.
4. Arm CI to execute the smoke tests for the Windows Setup.exe installer (only running `time-to-first-query` for now).

feat(smoke-tests): test Setup.exe installer for on Windows COMPASS-8706

---

.evergreen/buildvariants-and-tasks.in.yml
.evergreen/buildvariants-and-tasks.yml
.evergreen/functions.yml
packages/compass-smoke-tests/src/installers/index.ts
packages/compass-smoke-tests/src/installers/linux-tar.ts

1. Implement the Linux .tar installer (using the `tar` command and verifying compass `--version` via `xvfb-run`).
2. Arm CI with the Ubuntu build variant to execute the smoke tests for the Ubuntu tar installer (only running `time-to-first-query` for now).

feat(smoke-tests): test tar installer for on Ubuntu COMPASS-8711

---

.evergreen/functions.yml
packages/compass-smoke-tests/src/installers/apt.ts
packages/compass-smoke-tests/src/installers/index.ts
packages/compass-smoke-tests/src/installers/linux-deb.ts

PR stacked on https://github.com/mongodb-js/compass/pull/6684.
1. Implement the Linux .deb installer (using the `apt` command and verifying compass `--version` via `xvfb-run`).
2. Arm CI to execute the smoke tests for the Ubuntu deb installer (only running `time-to-first-query` for now).

feat(smoke-tests): test deb installer for on Ubuntu COMPASS-8712

---

packages/compass-smoke-tests/src/downloads.ts

A quick assertion to make it a bit more apparent when the download fails.

Assert `response.ok` when downloading files

---

.github/workflows/start-beta.yml
.github/workflows/start-ga.yaml

release.js is using the github cli to trigger the codeql workflow for the commit we're releasing from. We could eventually move to use the github app to trigger the codeql workflow automaticall.

chore(ci): grant beta/ga workflows permissions for actions

---

.evergreen/buildvariants-and-tasks.in.yml
.evergreen/buildvariants-and-tasks.yml
.evergreen/functions.yml
packages/compass-smoke-tests/src/installers/index.ts
packages/compass-smoke-tests/src/installers/linux-rpm.ts

1. Implement the Linux .rpm installer (using the `dnf` command as that installs dependencies too and verifying compass `--version` via `xvfb-run`).
2. Arm CI to execute the smoke tests for the RHEL rpm installer (only running `time-to-first-query` for now).

feat(smoke-tests): test rpm installer for RHEL / Rocky linux COMPASS-8713

---

configs/testing-library-compass/src/index.tsx
packages/compass-connections/src/index.tsx
packages/compass-connections/src/provider.ts
packages/compass-connections/src/stores/connections-store-redux.spec.tsx
packages/compass-connections/src/stores/connections-store-redux.ts
packages/compass-connections/src/stores/store-context.tsx
packages/compass-e2e-tests/helpers/commands/connect.ts
packages/compass-e2e-tests/helpers/commands/disconnect.ts
packages/compass-e2e-tests/helpers/commands/remove-connections.ts
packages/compass-e2e-tests/helpers/commands/sidebar-connection.ts
packages/compass-sidebar/src/components/connections-filter-popover.tsx
packages/compass-sidebar/src/components/multiple-connections/connections-navigation.tsx
packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
packages/compass-sidebar/src/components/navigation-items-filter.tsx

This patch updates the sidebar to show the loading state with placeholders list while we're loading connections (both for web and desktop, although loading in desktop from disc is too fast to notice).
To be able to read this state I'm adding a new hook to the compass-connections + to be able to test it I'm changing the logic in the compass-testing-library to explicitly allow to skip sync preloading of connections (in most cases we want them to be preloaded, so I'm making this behavior an opt-in through passing `null`)

feat(sidebar): show loading state when initially loading connections COMPASS-8876

---

packages/compass-sidebar/src/components/multiple-connections/header/sidebar-header.tsx
packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
packages/compass-sidebar/src/plugin.tsx
packages/compass-web/src/entrypoint.tsx

Adding header back for Compass Web with a preview badge for private preview users
COMPASS-8904
Getting a type error on line 206 of compass-web/src/entrypoint.tsx, which I can't figure out why for the life of me. Help appreciated!!

feat(sidebar): show header for Data Explorer COMPASS-8904

---

.github/workflows/test-installers.yml
packages/compass-smoke-tests/src/cli.ts
packages/compass-smoke-tests/src/context.ts
packages/compass-smoke-tests/src/tests/auto-update-from.ts
packages/compass-smoke-tests/src/tests/auto-update-to.ts
packages/compass-smoke-tests/src/tests/time-to-first-query.ts

Since the GHA runners are pristine environments and we run only one package and test per job, the uninstalling and cleanup serve no purpose and is just adding noise.

chore(smoke-tests): skip uninstalling when running on GHA

---

.evergreen/functions.yml
.github/workflows/test-installers.yml
packages/compass-smoke-tests/src/installers/linux-rpm.ts

- Arm the RPM package on GHA running "time-to-first-query" and "auto-update-from" tests using Rocky linux via docker.
Here's a link to a green run: https://github.com/mongodb-js/compass/actions/runs/13342974727.
I've disabled the "[linux_rpm test auto-update-to (compass)](https://github.com/mongodb-js/compass/actions/runs/13338020419/job/37257305037#logs)" tests, as they're waiting for https://github.com/10gen/compass-mongodb-com/pull/122 to deploy.

chore(smoke-tests): Run RPM tests on Rocky linux

---

packages/compass-schema/src/components/coordinates-minichart/constants.js
packages/compass-schema/src/components/coordinates-minichart/utils.js

See https://github.com/10gen/compass-maps-server/pull/17 and https://github.com/10gen/compass-maps-server/pull/18
Also https://www.here.com/docs/bundle/raster-tile-api-developer-guide/page/topics/required-copyright-notice.html

fix(schema): update maps from map tile API v2 to raster tile API v3 COMPASS-8981

---

packages/compass-web/polyfills/net/index.ts
packages/compass-web/scripts/ws-proxy.js

Updating sandbox to follow websocket protocol changes in MMS

test(sandbox): fix sandbox tests after protocol change COMPASS-8976

---

.evergreen/buildvariants-and-tasks.in.yml
.evergreen/buildvariants-and-tasks.yml
.evergreen/create-sbom.sh
.evergreen/functions.yml

Silkbomb 2.0 introduces the augment command which will allow you to upload your sbom to be scanned by OSV and have an augmented SBOM returned with any vulnerabilities in a single step.
Let me know if I'm missing anything or if there is anything else that can be cleaned up or improved. Thanks!

chore(ci): update to silkbomb 2.0

---

packages/compass-schema-validation/src/components/compass-schema-validation.tsx
packages/compass-schema-validation/src/components/sample-documents.tsx

COMPASS-8997
| - | - |
| <img width="850" alt="Screenshot 2025-02-20 at 3 05 15 PM" src="https://github.com/user-attachments/assets/6a900f3c-cda6-4f9c-9d27-cf5edadfc2c9" /> | <img width="874" alt="Screenshot 2025-02-20 at 3 01 36 PM" src="https://github.com/user-attachments/assets/57cd16da-1c22-46dd-bf95-3523a6b04e5c" /> |

fix(schema-validation): document preview overflow styles COMPASS-8997

---

package-lock.json
packages/compass-aggregations/package.json
packages/compass-components/src/components/error-warning-summary.tsx
packages/compass-field-store/package.json
packages/compass-generative-ai/package.json
packages/compass-import-export/package.json
packages/compass-query-bar/package.json
packages/compass-schema/package.json
packages/compass-schema/src/components/compass-schema.tsx
packages/compass-schema/src/components/schema-toolbar/schema-toolbar.spec.tsx
packages/compass-schema/src/components/schema-toolbar/schema-toolbar.tsx
packages/compass-schema/src/constants/analysis-states.ts
packages/compass-schema/src/modules/schema-analysis.spec.ts
packages/compass-schema/src/modules/schema-analysis.ts
packages/compass-schema/src/stores/schema-analysis-reducer.ts
packages/compass-schema/src/stores/store.spec.ts

The new limits are behind the export schema feature toggle. The messaging is similar to the bloated documents insights, the link leads to: [www.mongodb.com/docs/manual/data-modeling/design-antipatterns/bloated-documents](https://www.mongodb.com/docs/manual/data-modeling/design-antipatterns/bloated-documents/?utm_source=compass&utm_medium=product)
Side changes: Error is no longer a separate state, we still show the 'Explore your schema' content. Errors can be dismissed.
Note: You can find bloated documents in Compass Data Sets -> `Schema Advisor` or `validations` db, or MDE Test -> `bloated_documents` db.

fix(compass-schema): complexity and size limits COMPASS-8905 COMPASS-8984 COMPASS-8941

---

.evergreen/buildvariants-and-tasks.in.yml
.evergreen/buildvariants-and-tasks.yml
.evergreen/functions.yml
.github/workflows/test-installers.yml
package-lock.json
packages/compass-smoke-tests/package.json
packages/compass-smoke-tests/src/build-info.ts
packages/compass-smoke-tests/src/cli.ts
packages/compass-smoke-tests/src/dispatch.ts

- Arm Evergreen to run smoke tests by dispatching a workflow run on GitHub actions and awaiting a successful completion.
Ideally, we would simply run `gh workflow run --watch` but that's not supported and blocked by https://github.com/cli/cli/issues/4001.

chore(smoke-tests): dispatch workflow run on GitHub Actions from Evergreen COMPASS-8751

---

package-lock.json
package.json
packages/compass-e2e-tests/package.json
packages/compass-logging/package.json
packages/compass-shell/package.json
packages/compass-shell/src/modules/worker-runtime.ts
packages/compass/package.json
packages/data-service/package.json

Updates and applies the breaking changes from `@mongosh/logging`.

chore(compass-shell): update mongosh logging

---

package-lock.json

A recent dependency update for mongosh packages lost the hoisting at the top in `package-lock.json`. This PR patches that but also (wip: soon) includes fixes for the updated driver dependency.

chore(deps): update driver and patch package-lock.json hoisting for mongosh packages

---

packages/compass-e2e-tests/helpers/compass.ts
packages/compass-e2e-tests/helpers/downloads.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/collection-schema-tab.test.ts
packages/compass-schema/src/components/export-schema-modal.tsx
packages/compass-schema/src/stores/schema-export-reducer.ts
packages/compass-schema/src/stores/store.spec.ts
packages/compass-schema/src/stores/store.ts
packages/compass-telemetry/src/telemetry-events.ts
packages/compass-web/sandbox/index.tsx
packages/compass/src/app/utils/csp.ts

Doing the file download with blob + createObjectUrl solution. Tested in electron and chrome. Including e2e

feat(schema): File download COMPASS-8704

---

.evergreen/functions.yml
.github/workflows/test-installers.yml
packages/compass-smoke-tests/src/cli.ts
packages/compass-smoke-tests/src/dispatch.ts

- Refactor dispatch function to poll for completion and return a status, which can be asserted from the caller.
- ☝️ makes the dispatch command fail earlier (before it would wait for successful completion), allowing someone to manually restart the GHA run.
- Stop printing the help message when the smoke test CLI fails (because it's annoying to have to scroll past on CI).
- Propagate the Evergreen task URL into the GHA job summary, to make increase traceability between the two systems.

chore(smoke-test): fail early and propagate task url

---

packages/compass-connections/src/stores/connections-store-redux.ts
packages/compass-web/src/entrypoint.spec.tsx
packages/connection-form/src/hooks/use-connect-form.ts
packages/connection-form/src/utils/set-app-name-if-missing.spec.ts
packages/connection-form/src/utils/set-app-name-if-missing.ts

See [COMPASS-8591](https://jira.mongodb.org/browse/COMPASS-8591)

feat(connection-form): add connection and anonymous id to app name for atlas connections COMPASS-8591

---

packages/compass-e2e-tests/helpers/commands/set-validation.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/collection-validation-tab.test.ts
packages/compass-editor/src/editor.tsx
packages/compass-schema-validation/src/components/validation-editor.spec.tsx
packages/compass-schema-validation/src/components/validation-editor.tsx
packages/compass-schema-validation/src/modules/edit-mode.spec.ts
packages/compass-schema-validation/src/modules/edit-mode.ts
packages/compass-schema-validation/src/modules/validation.ts
packages/compass-schema-validation/src/modules/zero-state.ts
packages/compass-schema-validation/src/stores/store.spec.ts
packages/compass-schema-validation/src/stores/store.ts
packages/compass-schema/src/components/export-schema-modal.tsx

This is most of COMPASS-8861, I'd like to do the toasts separately as they can be in a separate pr from this work without any conflicts.
Designs: https://www.figma.com/design/CBHJriBQZ2qxMxtnXFgDxJ/EXPO-3174-%3A-Export-Schema-%2B-Validation-Detection?node-id=1309-40813&t=ouDByoHIQallPTXr-1 
<details open>
<summary>Screenshots</summary>
<br>
</details>
We could refactor the store here to have fewer reducers to simplify some of the actions here. Probably not worth making part of this work, but something that is on the mind with these changes. Removing some of the debouncing and cleaning up the fetching of existing validation would be nice as well.

feat(schema-validation): add confirmation modal when applying rules, add explicit editing state COMPASS-8861

---

packages/compass-connections/src/stores/connections-store-redux.ts
packages/connection-form/src/hooks/use-connect-form.ts

Since `adjustConnectionOptionsBeforeConnect` is used in places like VSCode where we may not have the same concept of atlasMetadata, it is better for us to be more direct with our parameters and simply ask for `isAtlas`.

fix(connection-form)!: use a simpler parameter for differentiating Atlas and non-Atlas connections

---

packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/collection-validation-tab.test.ts
packages/compass-schema-validation/src/components/document-preview.spec.tsx
packages/compass-schema-validation/src/components/document-preview.tsx
packages/compass-schema-validation/src/components/sample-documents.spec.tsx
packages/compass-schema-validation/src/components/sample-documents.tsx
packages/compass-schema-validation/src/modules/sample-documents.spec.ts
packages/compass-schema-validation/src/modules/sample-documents.ts
packages/compass-schema-validation/src/stores/store.spec.ts

This one is independent and so it's not behind the feature toggle.
CTA:
Samples:

fix(compass-validation): unified validation preview CTA COMPASS-8862

---

scripts/update-electron.js

chore(release): unblock workflows for update electron COMPASS-9075

---

scripts/find-packages-on-old-config.js
scripts/update-electron.js

We broke compass' scripts/update-electron,js in [June 2023](https://github.com/mongodb-js/devtools-shared/pull/109#pullrequestreview-1505779815), when we removed/replaced forEachPackage, but we never bumped monorepo-tools until [yesterday](https://github.com/mongodb-js/compass/pull/6732) when we finally took in the new code.

fix: switch from forEachPackage to listAllPackages

---

packages/connection-form/src/utils/set-app-name-if-missing.spec.ts
packages/connection-form/src/utils/set-app-name-if-missing.ts

A single `-` can be hard to separate in cases such a vscode where the defaultAppName is `mongodb-vscode` as well as with UUIDs so we use `--` to make this separation clearer.

fix(connection-form): use a double dash for separating appName identifiers COMPASS-8591

---

packages/compass-indexes/src/components/indexes/indexes.tsx
packages/compass-schema/src/components/compass-schema.tsx

fix(compass-web): make banners dismissible COMPASS-8976

---

docs/tracking-plan.md
packages/compass-schema-validation/src/modules/rules-generation.ts
packages/compass-schema-validation/src/stores/store.spec.ts
packages/compass-telemetry/src/telemetry-events.ts

Adding Schema Validation Generated event

feat: add telemetry for rules generation COMPASS-8863

---

packages/compass/src/app/index.tsx
packages/compass/src/main/application.ts

What we're trying to solve: 
When the download is handed over to the browser, a full-fledged browser will show the download progress and success/failure + link to the file.
Example: chrome
Desktop electron doesn't have this, and it feels weird when you click save and nothing happens. So we're adding a minimalistic solution to for browser download success/failure, by listening to the session's `will-download` - see [electron docs](https://www.electronjs.org/docs/latest/api/session#event-will-download). 
- The messaging is generic, because the solution is generic.
- Error message is unfortunately not available.
- No progress, because it's a bit trickier, the schema export is pretty quick, and we didn't want to spend much time on this. Can be a follow up.
Note: if you want to reproduce the …

feat: file download success/failure COMPASS-9095

---

packages/compass-schema/src/components/export-schema-modal.tsx

Fixing the styles for code editor on export schema modal
Before:
The whole editor scrolls, so the actions get hidden down the line.
After:
Only content of the editor scrolls.

fix(compass-schema): sticky copy button COMPASS-9141

---

packages/compass-e2e-tests/helpers/commands/save-aggregation-pipeline.ts
packages/compass-e2e-tests/helpers/selectors.ts

COMPASS-9143
What's I believe was happening is we save the pipeline, then click the create new button before it has updated the state to indicate the save event has completed. This means a confirmation is shown as Compass still believes the pipeline is unsaved. This pr updates the test to wait for the save to complete before clicking to create the new pipeline.
Example flake that this will fix:
https://parsley.mongodb.com/test/10gen_compass_main_test_packaged_app_macos_14_arm_test_packaged_app_3_90c199858e9df2294572932778b19b5aba449048_25_03_06_13_04_15/0/4b58310d107af45f5decda56bb929bc5?bookmarks=0,18&shareLine=0
Screenshot: https://parsley.mongodb.com/test/10gen_compass_main_test_packaged_app_macos_14_arm_test_packaged_app_3_90c199858e9df2294572932778b19b5aba449048_25_03_06_13_04_15/0/4b …

chore(e2e-tests): wait for aggregation name to reduce flakes COMPASS-9143

---

packages/compass-schema-validation/src/components/validation-editor.spec.tsx
packages/compass-schema-validation/src/components/validation-editor.tsx
packages/compass-schema-validation/src/components/validation-selectors.tsx

Forgot about this when implementing the rules generation.
The button is enabled when the validator is empty (either empty string or empty object). Editor to be editable but doesn't have to be in the edit mode (that would be an extra click for the same action). Button is in loading state when the generation is in progress.

fix(compass-schema-validation): add generate button to the editor COMPASS-9145

---

packages/data-service/src/connect.spec.ts
packages/data-service/src/data-service.ts

There's a bug https://jira.mongodb.org/browse/PRODTRIAGE-3102 where readPreferenceTags does not work with config servers. This means that if compass connects to a sharded cluster and then the user specifies something like `readPreferenceTags=nodeType:ANALYTICS` as part of the connection string, Compass won't be able to list the databases&collections which should appear in the sidebar.
The workaround here is to remove the tags for those commands IF we're connected to a sharded cluster AND readPreferenceTags is present.
To test this it is _almost_ enough to just connect to any sharded cluster without any special node tags and then specify readPreferenceTags, but in that case no command will work because there aren't nodes for that cluster. If a node exists with the read preference tag then …

fix: remove readPreferenceTags for database&collection lookups if the cluster is sharded and readPreferenceTags was set COMPASS-9111

---

.evergreen/functions.yml
package-lock.json
packages/hadron-build/commands/upload.js
packages/hadron-build/lib/download-center.js
packages/hadron-build/package.json

This commit adjusts Compass to write release artifacts to a new S3 bucket.
Eventually the old bucket will be removed after we have confirmed that we
can serve artifacts from the new bucket. We also use assume role to access
this bucket instead of static credentials.

feat(release): dual write release artifacts to new bucket COMPASS-9160

---

packages/atlas-service/src/main.spec.ts
packages/compass-e2e-tests/tests/collection-ai-query.test.ts
packages/compass-generative-ai/src/atlas-ai-service.spec.ts
packages/compass-generative-ai/src/atlas-ai-service.ts

COMPASS-9117
We used the access to roll out the feature initially, now that 100% of folks have had it for a while we can remove this as it adds more network requests, and also could prevent someone from using the feature temporarily if they start compass without internet and then connect.

chore(gen-ai): remove gen ai access check, default always on COMPASS-9117

---

packages/compass-schema-validation/src/components/validation-editor.spec.tsx
packages/compass-schema-validation/src/components/validation-editor.tsx
packages/compass-schema-validation/src/modules/validation.spec.ts
packages/compass-schema-validation/src/modules/validation.ts
packages/compass-schema-validation/src/stores/store.spec.ts

COMPASS-9077
https://github.com/user-attachments/assets/febe7169-9a1b-4b91-9c29-203030939fd4

feat(schema-validation): add in progress saving state COMPASS-9077

---

.evergreen/buildvariants-and-tasks.in.yml
.evergreen/buildvariants-and-tasks.yml
.github/workflows/test-installers.yml

mongodb 8.0.6 does not work on macOS version < 14.

fix: use mongodb version 8.0.5 on macOS versions < 14

---

packages/compass-saved-aggregations-queries/.eslintrc.js
packages/compass-saved-aggregations-queries/src/hooks/use-grid-filters.spec.tsx
packages/compass-saved-aggregations-queries/src/index.spec.tsx
packages/compass-saved-aggregations-queries/src/stores/delete-item.ts
packages/compass-saved-aggregations-queries/src/stores/edit-item.ts
packages/compass-saved-aggregations-queries/src/stores/open-item.ts
packages/compass-saved-aggregations-queries/test/fixtures.ts

follow-up to https://github.com/mongodb-js/compass/pull/6817

chore: use switch-exhaustiveness-check, add updatemany to fixtures

---

packages/compass-crud/src/stores/crud-store.ts

Fixing a small issue I stumbled upon - parse errors on array inserts were not caught and displayed. They must've been caught higher up and swallowed, as the modal was just getting stuck at "Inserting Document".

fix: catch parse error on multi insert

---

.github/workflows/authors-and-third-party-notices.yaml

chore(ci): temporarily disable third party update action

---

packages/compass-e2e-tests/tests/collection-documents-tab.test.ts

Lower servers didn't have errInfo

chore: skip errInfo tests on server version < 5

---

packages/compass-e2e-tests/tests/collection-import.test.ts

More failing tests that are were included in the original #6824

fix(e2e): skip more validation details tests

---

packages/compass-schema-validation/src/components/validation-editor.spec.tsx
packages/compass-schema-validation/src/components/validation-editor.tsx
packages/compass-schema-validation/src/components/validation-selectors.tsx
packages/compass-schema-validation/src/modules/validation.ts
packages/compass-telemetry/src/telemetry-events.ts

8.1 supports a new 'errorAndLog' validation action. This adds this to the schema validator UI.
- ~~Documentation is changed or added~~

feat(compass-schema-validator): add validation action option for 'errorAndLog' with 8.1 COMPASS-8983

---

package-lock.json
packages/hadron-build/lib/download-center.js
packages/hadron-build/package.json

This commit adjusts our release process to upload artifacts to the new release bucket using private ACLs. Because users fetch artifacts from our CDN, we are not allowing direct access to this bucket. If we do not set the ACLs to private, our uploads will fail. In order to support this, we had to update to the latest devtools-shared dl-center package.

feat(release): write artifacts to new release bucket with private acls COMPASS-9238

---

packages/compass-components/src/components/bson-value.spec.tsx
packages/compass-components/src/components/bson-value.tsx

The table view for this is not awesome, but we would have to revisit either the principle of showing copy-pastable code in the cells or the driver API to improve that.
](url)

feat: add special handling of vector sub-type COMPASS-8257

---

packages/compass-crud/src/components/table-view/document-table-view.tsx

Small fix - numbering was always starting from 1 for expanded table view, not taking the pagination into account.
Before:
After:

fix(compass-crud): account for pagination in expanded table view COMPASS-9161

---

packages/hadron-build/commands/upload.js

GitHub's REST API returns releases sorted incorrectly, so `1.45.5-beta.9` appears before `1.45.5-beta.10`. We then pick the first non-draft of the relevant channel as the latest one for the manifest on the download centre and end up with .9 and not .10.
This sorts the releases with semver first.
I tested this by just putting the code in a separate file and running it there, printing to the console. Once this is merged we can just re-run the most recent action that used this code and that should update the download centre correctly.

fix: semver sort the releases latest first before picking the first non-draft of the relevant channel

---

packages/compass-crud/src/stores/crud-store.spec.ts
packages/compass-crud/src/stores/crud-store.ts

This has been partially fixed already, but the action button still showed 0. Also changed the initial state just to be safe.
Before:
After:

fix(compass-crud): no 0 default for bulkDelete count COMPASS-8603

---

packages/compass-schema-validation/src/components/sample-documents.tsx

fix: cleanup tooltip COMPASS-9256

---

packages/compass-components/src/components/workspace-tabs/tab.tsx

before:
after:
slack discussion: https://mongodb.slack.com/archives/GDTJXPHD0/p1744142055088759

chore: fix workspace tab tooltip overflow COMPASS-9244

---

packages/compass/src/main/auto-update-manager.spec.ts
packages/compass/src/main/auto-update-manager.ts

As a preparation for a PR adding specific reasons for auto updates being unavailable I'm refactoring the auto updater to return an object with `{ available: false }` instead of `null` when an update is not available.

chore(compass-main): refactor auto-updater to return objects when no update is available

---

.github/workflows/bump-packages.yaml

Another thing that got lost during refactoring

chore(bump-pacakges): fetch history so that script can access it

---

packages/compass-schema-validation/src/components/validation-editor.spec.tsx
packages/compass-schema-validation/src/components/validation-editor.tsx
packages/compass-schema-validation/src/modules/rules-generation.ts

The 'rules are edited, please review before applying' message will be different right after the rules are generated. once the user makes changes, we go back to the 'rules are edited' message.

fix(compass-schema-validation): rules generated message COMPASS-9252

---

package-lock.json
packages/compass/package.json
packages/compass/src/app/components/update-toasts.tsx
packages/compass/src/app/index.tsx
packages/compass/src/main/auto-update-manager.spec.ts
packages/compass/src/main/auto-update-manager.ts
packages/compass/src/main/menu.spec.ts
packages/compass/src/main/menu.ts

- Propagate MacOS product version to the update server (through a query-string param).
- React to the server sending a response of [status 426 (Upgrade Required)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/426) and parse the body of the response to determine any reason for the rejection.
- If the reason is determined to be `'outdated-operating-system'` the updater will transition to a new `OutdatedOperatingSystem` state.
- This will propagate to the UI with a custom alert message (when the update was manually checked) and a toast to inform the user of the outdated operating system. Both with a link to the system requirements: https://www.mongodb.com/docs/compass/current/install/
You can verify the behaviour introduced with this PR by running …

feat(auto-updater): Error when requesting updates from an outdated MacOS machine COMPASS-9081

---

.prettierignore

I've found updating the templates for Yaml files difficult: The commit-hook fails when running Prettier on the file, because it contains non-yaml syntax.

Ignoring template files when running prettier

---

packages/compass-components/src/components/document-list/document-actions-group.tsx
packages/compass-components/src/components/signal-popover.spec.tsx
packages/compass-components/src/components/signal-popover.tsx
packages/compass-crud/src/components/crud-toolbar.tsx
packages/compass-query-bar/src/components/option-editor.tsx
packages/compass-query-bar/src/components/query-bar.tsx
packages/compass-query-bar/src/components/query-option.tsx

design:
https://www.figma.com/design/pFjIikzky8ACkISabtvhrH/CLOUDP-239367--Index-Guidance?node-id=627-17024&t=e30aDEmtJaAdrlkT-0
multiple signals

feat: move the signal from query bar to outside of it CLOUDP-311778

---

packages/compass-indexes/src/components/create-index-form/create-index-form.spec.tsx
packages/compass-indexes/src/components/create-index-form/create-index-form.tsx
packages/compass-indexes/src/components/create-index-modal/create-index-modal.tsx
packages/compass-indexes/src/modules/create-index.tsx

https://jira.mongodb.org/browse/CLOUDP-311780
Added radio boxes for the two flows and content will be different based on which one is clicked 
Control:
Variant:
Index Flow
Query Flow

feat: Add radio boxes for the two flows in create index modal CLOUDP-311780

---

packages/compass-e2e-tests/tests/no-network-traffic.test.ts
packages/compass/src/main/application.ts
packages/compass/src/main/window-manager.ts

COMPASS-8166
We already were disabling the spellcheck when network traffic was disabled, however it looks like it was being disabled after the request for the dictionary would happen. This pr updates when we do the override to happen earlier.
The other change here is ignoring Google's public DNS ip in our no network test as its an expected functionality of chromium:
https://source.chromium.org/chromium/chromium/src/+/main:net/dns/README.md;l=351

fix(compass): disable spellcheck before creating window when no network traffic COMPASS-8166

---

packages/compass-generative-ai/src/components/ai-optin-modal.tsx

chore(generative-ai): update DE gen ai opt in text COMPASS-9078

---

packages/compass-indexes/src/components/create-index-form/index-flow-section.spec.tsx
packages/compass-indexes/src/components/create-index-form/index-flow-section.tsx

https://jira.mongodb.org/browse/CLOUDP-311782
Best viewed with 'hide whitespace' 
Added a tooltip for when the type is not supported:
Default state:
One field:
Two fields:
Three fields:

feat: Add covered and optimal query examples CLOUDP-311782

---

packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.spec.tsx
packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
packages/compass-indexes/src/components/indexes/indexes.tsx

https://jira.mongodb.org/browse/COMPASS-9158
https://github.com/user-attachments/assets/fa12148a-2eb6-4c9c-92c9-671591d2195e

feat(indexes): add Atlas search indexes link when banner dismissed COMPASS-9158

---

packages/compass-aggregations/src/components/pipeline-results-workspace/index.spec.tsx
packages/compass-aggregations/src/components/pipeline-results-workspace/index.tsx
packages/compass-aggregations/src/modules/aggregation.ts
packages/compass-e2e-tests/helpers/commands/set-validation.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts

feat: validation error details aggregation COMPASS-8868

---

packages/compass-data-modeling/src/components/diagram-editor.tsx
packages/compass-data-modeling/src/components/new-diagram-form.tsx
packages/compass-data-modeling/src/components/saved-diagrams-list.tsx
packages/compass-e2e-tests/helpers/commands/workspace-tabs.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/data-modeling-tab.test.ts

test: add data-modeling tab e2e test COMPASS-9305

---

packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts

forgot to do this for the latest tests. older versions of mongo did not include validation error details

chore: skip validation tests for < 5.0

---

packages/compass-preferences-model/src/compass-web-preferences-access.ts
packages/compass-web/src/entrypoint.tsx

https://jira.mongodb.org/browse/CLOUDP-317478
in variant
in control
tested in cloud-dev with redwood running on local

feat: Made early indexes variables update when changed CLOUDP-317478

---

packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
packages/compass-e2e-tests/tests/collection-documents-tab.test.ts

Apparently afterEach() still executes if you skip() in beforeEach() ? Can't think of another reason why this worked for the collection tests but not the aggregation tests.

chore: also skip afterEach()

---

packages/compass-indexes/src/modules/regular-indexes.ts

Matching on internal code patterns (CAPS_UNDERSCORE_WITH_COLON:) and HTTP codes 400-599 anywhere in the string. Wanted to make this more general but the Indexes page was where I saw the 403 error from filter, so followed it up to the regular-indexes modules. 
error without sanitization, in console:

fix(web): Provide an actionable error message on DE errors CLOUDP-313461

---

packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
packages/compass-e2e-tests/tests/collection-import.test.ts

I saw some flakes in the nightly. Not sure if all of these are strictly necessary since maybe in some cases the moment the element appears the text is immediately stable. But I don't think this will hurt. Also not 100% sure if these are the only affected cases.
Example failure: https://spruce.mongodb.com/task/10gen_compass_main_test_packaged_app_macos_14_arm_test_packaged_app_3_681d5391e27c11000732a3de_25_05_09_01_00_01?execution=0&sortBy=STATUS&sortDir=ASC

chore: wait for text to include the expected result

---

package-lock.json
packages/compass-components/package.json
packages/compass-components/src/components/insights-chip.tsx
packages/compass-components/src/components/leafygreen.tsx
packages/compass-components/src/index.ts
packages/compass-crud/src/stores/crud-store.ts
packages/compass-indexes/src/components/create-index-form/create-index-form.spec.tsx
packages/compass-indexes/src/components/create-index-form/create-index-form.tsx
packages/compass-indexes/src/components/create-index-form/query-flow-section.spec.tsx
packages/compass-indexes/src/components/create-index-form/query-flow-section.tsx
packages/compass-indexes/src/components/create-index-modal/create-index-modal.tsx
packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
packages/compass-indexes/src/modules/create-index.spec.ts
packages/compass-indexes/src/modules/create-index.tsx
packages/compass-indexes/src/stores/store.ts

- Add `query` field to Create Index redux store and redux actions
- Publish `open-create-index-modal` events with `query` context
- Read and pass down `query` context from store to components
https://github.com/user-attachments/assets/54a7cf77-a2b6-40bc-904c-73155eaabe26

feat: Open create index modal with query context CLOUDP-311788

---

package-lock.json
packages/compass-vector-embedding-visualizer/components/vector-visualizer.tsx
packages/compass-vector-embedding-visualizer/index.tsx
packages/compass-vector-embedding-visualizer/package.json
packages/compass-vector-embedding-visualizer/plugin.tsx
packages/compass-web/src/entrypoint.tsx
packages/compass/src/app/components/workspace.tsx

Skunkworks: getting the vector embeddings tab on a collection set up and showing a placeholder graph

getting the tab set up

---

packages/compass-preferences-model/src/feature-flags.ts
packages/compass-query-bar/src/components/option-editor.tsx

A cleanup as this feature has been released now for some time, so we can remove this feature flag.

chore(preferences): remove enableQueryHistoryAutocomplete feature flag

---

.github/workflows/test-installers.yml

After the upgrade of Node (which include an update to NPM) we're seeing consistent failures of the install tests because NPM in the new version has a bug related to passing arguments (after the `--`) to the command declared in an NPM script.
This is an attempt to work around the issue by avoiding the use of PowerShell when running the install tests.

Update test-installers workflow to use "bash"

---

packages/compass-web/src/connection-storage.spec.ts
packages/compass-web/src/connection-storage.tsx
packages/compass-web/src/entrypoint.tsx

https://jira.mongodb.org/browse/COMPASS-9367
Fixes clusters showing up duplicated with terminated status
Mainly two issues:
1. The "fallback" logic to v1 causes compass web to forever switch to using V1 after a single failure to call V2. The issue with this, is that sometimes v2 will fail transiently. I don't know what the exact reason is, but one way to reproduce this is to go to Data Explorer, then close your laptop lid, wait a few minutes, then open it again. When you get back to the DE page, you will see that the V2 endpoint call failed once, and now we keep calling V1 forever. I believe this fallback logic was only really needed during the initial rollout anyways, so I've updated the logic to just be a flag now, which decides to either use the new endpoint or not.
2. Following the …

fix: fix terminated cluster states COMPASS-9367

---

.snyk

> I set the expiration based on the platform update project, hoping we'll have a release that disables updates for macos out for longer so that we can actually update electron without affecting too many users. You can probably bump the expiration once more to give more people time to update

chore: ignore two not applicable electron vulnerabilities for longer

---

packages/compass-connections/src/stores/connections-store-redux.ts
packages/compass-connections/src/utils/end-of-life-server.ts
packages/compass-e2e-tests/helpers/compass.ts
packages/compass-preferences-model/src/preferences-schema.tsx

A follow-up to https://github.com/mongodb-js/compass/pull/6888 this updates the e2e tests to disable showing the end-of-life connection modal.
Here's a patch with end-of-life servers: https://spruce.mongodb.com/version/682f8f80b0575500072dec22/tasks

chore(e2e-tests): disable end-of-life connection modal when testing COMPASS-9361

---

packages/compass-smoke-tests/src/installers/linux-deb.ts

This is an attempt at stabalizing the install / smoke tests on Debian.

chore(smoke-tests): try updating the package index first COMPASS-9405

---

packages/compass-e2e-tests/tests/logging.test.ts
packages/data-service/src/data-service.spec.ts
packages/data-service/src/data-service.ts

https://jira.mongodb.org/browse/COMPASS-9404
- Adds a new log message in a catch block. 
- Adds connection id as an attr to connecting, success, and failure

chore(data-service): add a log whenever connecting throws and include connection id COMPASS-9404

---

packages/compass-components/src/components/signal-popover.spec.tsx
packages/compass-components/src/components/signal-popover.tsx
packages/compass-crud/src/components/crud-toolbar.tsx

https://jira.mongodb.org/browse/CLOUDP-319356

feat: revert nudge back to icon on default and expand on hover CLOUDP-319356 

---

packages/compass-workspaces/src/components/workspace-tab-context-provider.tsx
packages/compass-workspaces/src/components/workspaces-provider.tsx
packages/compass-workspaces/src/components/workspaces.tsx

To allow for the tab to render titles based on the internal plugin state we would need to make changes to the workspace plugin structure similar to what we already did for collection subtabs. I'm going to be doing this in separate steps to avoid a big bang PR.
This first step is pretty straightforward: we move all providers that a workspace tab component needs into its own component so that later we can use the same provider component when rendering a custom tab title

chore(workspaces): move all workspace tab providers into a single component COMPASS-9413

---

.evergreen/buildvariants-and-tasks.in.yml
.evergreen/buildvariants-and-tasks.yml
.evergreen/functions.yml

This task ensures that in prs we aren't exceeding the compass-web bundle issue. 
Example pass:
https://spruce.mongodb.com/version/683722a7d818810007e4dd2a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Example fail:
https://spruce.mongodb.com/version/683722820c9e580007465f70/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

test(compass-web): add evergreen task to compile compass web COMPASS-9415

---

packages/compass-shell/src/components/compass-shell/tab-compass-shell.tsx

COMPASS-9418
Likely a leftover from when the shell was the full width at the bottom of the window.
Now it shouldn't overflow in a way that prevents user interaction.
It would be nice if the reviewer tries it out to see if there are any situations I might be missing. Try inputting a lot of text and scrolling, multi-line, etc in the embedded shell area. To me it's looking good but I might be missing a corner case. Doesn't seem like something we can easily test besides manually.

fix(shell): prevent horizontal overflow scroll COMPASS-9418

---

packages/compass-components/src/components/actions/dropdown-menu-button.tsx
packages/compass-components/src/components/actions/item-action-menu.tsx

chore(components): remove focus workaround as it no longer needed COMPASS-6345

---

packages/compass/src/deps/csfle/.gitignore

Started to show up for csfle distribution, should be treated like the downloaded binaries that we also ignore for source control

chore(compass): ignore dot underscore files in source for external compass deps

---

packages/compass-indexes/src/components/create-index-form/index-flow-section.tsx
packages/compass-indexes/src/components/create-index-form/query-flow-section.tsx
packages/compass-indexes/src/components/create-index-modal/create-index-modal-header.tsx

Update the styling of Create Index Modal components to handle dark/light theming
https://jira.mongodb.org/browse/CLOUDP-313986
https://github.com/user-attachments/assets/b4c00b17-1532-465e-bc3e-a41d3fbc9bbb
<! --- https://github.com/user-attachments/assets/65052219-c266-47ce-be54-56da47066b09 -->
https://github.com/user-attachments/assets/1d205ee5-329e-48dd-9afb-5af1d958cec0

feat: Implement dark mode for create index modal in early journey variant CLOUDP-313986

---

packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.tsx
packages/compass-indexes/src/components/search-indexes-modals/update-search-index-modal.spec.tsx

When opening the edit search index modal we overrode the search index type to search regardless of whether the type is search index or vector search index, so the code paths that are supposed to show the vector labels/links were never hit.
Works now and I added some tests:

fix: link to vector search docs when editing vector indexes COMPASS-9435

---

packages/compass/src/main/application.ts

This is to work around "GTK 2/3 symbols detected. Using GTK 2/3 and GTK 4 in the same process is not supported". See https://github.com/electron/electron/issues/46538

fix: set --gtk-version=3 on linux COMPASS-9437

---

packages/compass-editor/src/editor.tsx

Just checking how CI feels about this now, if it's green we can probably just remove it

fix(editor): remove `EDIT_CONTEXT` workaround COMPASS-9131

---

packages/compass-web/webpack.config.js

It's really hard to make webpack to bundle both for target web and use require imports for its internal module system so that when used as a library, another bundler can actually recognize imports in the code. To work around that we add this manual chunk splitting logic for the production build.
Work in progress, I got pretty far with using webpack chunk splitting and forcing it to produce a build targeting web that can be consumed as a library by other bundling tooling (that's basically what we need for mms) instead of this hack, but will need to pause for a little, opening to not lose track of this and just in case if we become totally blocked on this

chore(web): manually split bundle into multiple chunks

---

packages/compass-aggregations/src/modules/index.ts
packages/compass-aggregations/src/stores/store.ts

As reported, Compass would break if you try to use `$out` with a database / collection that we haven't fetched yet, reason being that data service that was being used in the action wasn't actually being passed to the thunk argument and types were written in a way that hid this issue. This patch fixes the types and adds data service to the thunk arg

fix(aggregations): pass dataService to redux thunk arg, fix types COMPASS-9375

---

packages/compass-e2e-tests/tests/in-use-encryption.test.ts

https://parsley.mongodb.com/test/10gen_compass_main_test_packaged_app_macos_14_arm_test_packaged_app_2_6848d513d970620007c94584_25_06_11_01_00_03/0/b44855bdab4267221d132be32f8e5cff?bookmarks=0,8&shareLine=0

fix(e2e): wait for the footer to update with the error

---

packages/compass-indexes/src/components/create-index-fields.tsx
packages/compass-indexes/src/components/create-index-form/index-flow-section.spec.tsx
packages/compass-indexes/src/components/create-index-form/index-flow-section.tsx
packages/compass-indexes/src/components/create-index-form/query-flow-section.tsx
packages/compass-indexes/src/components/create-index-modal/create-index-modal.tsx
packages/compass-telemetry/src/telemetry-events.ts

https://jira.mongodb.org/browse/CLOUDP-323671
- Added/updated links in covered queries section and added analytic event for the new link
- Swapped the order of the fields for ESR examples (swapped last and second to last field)
- Updated the copy from 'optimal' to 'great' since it might not always be optimal due to nuances
1 field 
2 fields
3 fields 
4 fields

feat: Update covered queries with new links, esr order swap, copy change CLOUDP-323671 

---

configs/eslint-config-compass/index.js
configs/eslint-config-compass/package.json
package-lock.json
packages/compass-components/src/components/actions/dropdown-menu-button.tsx
packages/compass-components/src/components/actions/item-action-menu.tsx
packages/compass-components/src/components/document-list/element.tsx
packages/compass-explain-plan/src/components/explain-tree/explain-tree.tsx
packages/compass-generative-ai/src/components/generative-ai-input.tsx
packages/compass-global-writes/src/store/index.spec.ts
packages/compass-import-export/src/modules/export.ts
packages/compass-user-data/src/semaphore.ts
packages/compass-utils/src/cancellable-promise.ts
packages/compass-web/src/entrypoint.tsx
packages/compass/src/main/menu.ts

Just enabling the rule causes a ton of failures for chai expect usage. Not sure why this wasn't failing for us before to be very honest, but this eslint plugin was made specifically so that no unused expression can be still used without issues while still keeping the check for other cases (some legit failures you can see in the fixes I did)

chore(eslint-config): replace no-unused-expressions with chai-friendly version COMPASS-9459

---

packages/compass-crud/src/components/editable-document.tsx
packages/compass-crud/src/components/json-editor.tsx
packages/compass-crud/src/components/table-view/document-table-view.tsx
packages/compass-crud/src/components/table-view/full-width-cell-renderer.tsx

Two re-enabled eslint rules started showing issues only when both landed on main

chore(crud): explicitly not await for store actions in render

---

packages/compass-e2e-tests/tests/collection-import.test.ts

Example flake: https://parsley.mongodb.com/test/10gen_compass_main_e2e_coverage_e2e_coverage_3_455770f91aeb3ada3c69aab607dbef9b941eb56a_25_06_16_15_06_56/0/fb11c9a36e21c777b48967a8a779a46d?bookmarks=0,4&shareLine=0 
Totally open to other fixes ideas, this isn't a full fix, which is called out in the added comment. These changes should should make it flake much less at least.

chore(e2e-tests): update interval on starting import to ensure we disconnect before fully importing

---

packages/compass-e2e-tests/tests/proxy.test.ts
packages/compass-intercom/src/setup-intercom.spec.ts
packages/compass-intercom/src/setup-intercom.ts
packages/compass/src/app/utils/csp.ts

Combined with https://github.com/10gen/compass-mongodb-com/pull/133, merging this will introduce a preflight request to the update server to determine if Compass is allowed to setup the Intercom integration.
TODO: We might want to send the Compass version and OS / arch to that endpoint, in order to be able to selectively respond based on those parameters. But is that a thing that we will reasonably be using?

chore(intercom): Add request to the update server to determine if Intercom integration is allowed COMPASS-9371

---

configs/eslint-config-compass/index.js
packages/compass-aggregations/src/modules/pipeline-builder/pipeline-ai.ts
packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
packages/compass-components/src/components/workspace-container.tsx
packages/compass-telemetry/src/telemetry-events.ts
packages/connection-storage/src/compass-renderer-connection-storage.ts
packages/my-queries-storage/src/pipeline-storage-schema.ts

Another starightforward one, doesn't look like any types were missing anything, but a few duplicates sneaked in to some unions

chore(eslint-config): re-enable no-duplicate-type-constituents rule COMPASS-9459

---

package-lock.json

I'm looking into what's up with the PR that automatically updates eslint and seems like one of the things is that it hoists mongodb-schema on install (that got unhoisted last time we did a version bump), to reduce the noise of the eslint auto patch, I'm hoisting the package in a separate PR

chore(deps): hoist mongodb-schema package

---

configs/eslint-config-compass/index.js
packages/compass-components/src/components/context-menu.tsx
packages/compass-components/src/index.ts
packages/compass-context-menu/src/context-menu-content.ts
packages/compass-context-menu/src/use-context-menu.tsx

I have a use-case for a component which should be able to add multiple groups of menu items.
- Refactor the `registerItems` to take a variable length of arrays of items as arguments.
- Implement a `useContextMenuGroups` hook, similar to `useContextMenuItems` calling into `registerItems`.

Add `useContextMenuGroups` hook

---

packages/compass-components/src/components/context-menu.spec.tsx

Adds some tests to ensure context menu closes in different contexts. Also cleans up some tests by generalizing the items being passed.

test: add closing tests to context menu COMPASS-9386

---

packages/compass-components/src/components/compass-components-provider.tsx
packages/compass-components/src/components/context-menu.tsx
packages/compass-context-menu/src/context-menu-provider.tsx
packages/compass-preferences-model/src/feature-flags.ts
packages/compass/src/app/components/home.tsx

- Introduce a feature flag to gate the context menus

chore(context-menu): context menu feature flag

---

packages/compass-components/src/components/content-with-fallback.spec.tsx
packages/compass-components/src/components/context-menu.spec.tsx
packages/compass-components/src/components/context-menu.tsx

- Use a separate anchor ref instead of nesting the menu under the trigger, to allow it updating its height as expected.
- Force use of a compact menu styling (until we have [LG-5013](https://jira.mongodb.org/browse/LG-5013)).

chore(context-menu): use anchor ref and compact menu

---

packages/compass-components/src/components/workspace-tabs/tab.spec.tsx
packages/compass-components/src/components/workspace-tabs/tab.tsx
packages/compass-components/src/components/workspace-tabs/workspace-tabs.spec.tsx
packages/compass-components/src/components/workspace-tabs/workspace-tabs.tsx
packages/compass-workspaces/src/components/workspaces.tsx
packages/compass-workspaces/src/stores/workspaces.spec.ts
packages/compass-workspaces/src/stores/workspaces.ts

Stacked on #6956
- Add two new context menu actions to workspace tabs:
- duplicate, which will create and activate a tab to the right of the tab
- close all other tabs, which will ... you've guessed it
https://github.com/user-attachments/assets/c387f0ad-5f48-464f-b819-585768b8f785
Any tab with unsaved work will confirm the close by getting selected and displaying a confirmation dialog.
https://github.com/user-attachments/assets/d5845a4b-50d3-4ed0-b7c5-66a3eba5a988
I feel the tooltip is getting in the way of this interaction and while we could solve this in a bespoke way (ex disabling the tooltip component if the context menu `isOpen`), we could disable the underlying UI (using ex [the `pointer-events` CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/poin …

feat(workspaces): context menu on tabs to duplicate and close all other tabs COMPASS-9397

---

scripts/update-dependencies-config.js
scripts/update-dependencies.js

Something I missed in the script and haven't noticed until looking closer at package-lock update in the eslint PR. This patch changes the update script to also adjust overrides if dependencies are listed there

fix(scripts): update overrides when updating packages

---

packages/compass-indexes/src/components/create-index-form/index-flow-section.spec.tsx
packages/compass-indexes/src/components/create-index-form/index-flow-section.tsx

feat: Changing the sort example for 2 index fields CLOUDP-329033

---

packages/compass-indexes/src/modules/create-index.tsx

chore(indexes): change rolling indexes text COMPASS-9519

---

THIRD-PARTY-NOTICES.md
packages/compass-data-modeling/src/components/diagram-editor-toolbar.tsx
packages/compass-data-modeling/src/components/export-diagram-modal.tsx
packages/compass-data-modeling/src/services/export-diagram.tsx
packages/compass-data-modeling/src/store/analysis-process.ts
packages/compass-data-modeling/src/store/diagram.ts
packages/compass-data-modeling/src/store/export-diagram.ts
packages/compass-data-modeling/src/store/index.ts
packages/compass-data-modeling/src/store/reducer.ts
packages/compass-telemetry/src/telemetry-events.ts

chore(data-modeling): move export state to redux and add telemetry COMPASS-9523

---

packages/compass-data-modeling/src/store/analysis-process.ts
packages/compass-telemetry/src/telemetry-events.ts

Adds `Data Modeling Diagram Created` event

fix(compass-data-modeling): add telemetry for diagram created COMPASS-9525

---

packages/compass-data-modeling/src/components/export-diagram-modal.tsx

fix(data-modeling): update subtitle and radio button size COMPASS-9551

---

packages/compass-data-modeling/src/store/diagram.ts
packages/compass-e2e-tests/tests/data-modeling-tab.test.ts

feat(data-modeling): show previous edits when opening the diagram COMPASS-9544

---

packages/compass-components/src/components/document-list/document-edit-actions-footer.tsx
packages/compass-crud/src/components/table-view/full-width-cell-renderer.tsx
packages/compass-crud/src/components/use-document-item-context-menu.spec.tsx
packages/compass-crud/src/components/use-document-item-context-menu.tsx
packages/compass-crud/src/stores/crud-store.spec.ts
packages/hadron-document/src/document-events.ts
packages/hadron-document/src/document.ts
packages/hadron-document/src/editor/date.ts
packages/hadron-document/src/editor/decimal128.ts
packages/hadron-document/src/editor/double.ts
packages/hadron-document/src/editor/index.ts
packages/hadron-document/src/editor/int32.ts
packages/hadron-document/src/editor/int64.ts
packages/hadron-document/src/editor/null.ts
packages/hadron-document/src/editor/objectid.ts
packages/hadron-document/src/editor/standard.ts
packages/hadron-document/src/editor/string.ts
packages/hadron-document/src/editor/undefined.ts
packages/hadron-document/src/element-events.ts
packages/hadron-document/src/element.ts
packages/hadron-document/src/index.ts

It is best to review this PR in individual commits:
fe04ed84e31abf9a2570a07422a1b8f85e25fbc4 - largely a drive-by clean-up of the current event setup by adding more of the values into the `DocumentEvents` constant and cleaning up our export structure.
e7dc505a474d0079f78f6a09365efc51bbde3387 - adds a `DocumentEvents.EditingFinished` event handling to `document-edit-actions-footer.tsx` so its status can be correctly changed when editing is finished through means other than the cancel button. Also moves the action into its own group at the top and renames it.
'Stop editing' when right clicking does not fully stop editing the element. This is because the Editing Actions footer does not change status when editing is finished.
'Stop editing' should also be bumped up into a separate group and …

chore(compass-crud): adjust cancel editing logic COMPASS-9564

---

packages/compass-crud/src/components/json-editor.tsx
packages/hadron-document/src/document.ts
packages/hadron-document/src/element.ts
packages/hadron-document/test/document.test.ts

In the JSON editor ie. the middle one of the three in the Documents tab. Suppose you have this document:
```javascript
{
a: Double(1)
b: Long(1)
object: {
c: Double(1)
d: Long(1)
}
}
```
and you edit it in the JSON editor, it gets serialised as
```json
{
"a": 1,
"b": 1,
"object": {
"c": 1,
"d": 1
}
}
```
so when you save that back it becomes
```javascript
{
a: Int32(1)
b: Int32(1)
object: {
c: Int32(1)
d: Int32(1)
}
}
```
ie. we implicitly change the type of the Double or Long into an Int32 because 1 can safely be represented by a 32bit int.
This change will check the type of a property and if it is now Int32 and it was Double or Long, it will turn it back into a Double or Long when you save. So the document keeps its original "unnecessary" type.
Just to be clear: This only applies to the …

fix: try and preserve Double and Long/Int64 types in the json editor COMPASS-8337

---

packages/compass-web/polyfills/@mongodb-js/devtools-connect/index.ts

Finishing the job done for the rest of compass

fix(compass-web): skip ping on connect for compass web COMPASS-9579

---

packages/hadron-build/commands/upload.js
packages/hadron-build/lib/target.js
packages/hadron-build/test/upload.test.js

We had some users complain about slowness and it turns out they were running the x64 build of Compass on arm64. Looking at the download centre it is obvious why that happens.

fix: rename and reorder the download center links COMPASS-9588

---

packages/compass/src/main/auto-update-manager.ts
packages/hadron-build/commands/upload.js
packages/hadron-build/test/upload.test.js

COMPASS-9596
Drive by updated `M1/M2` mentions to `Apple silicon`. I've seen some other apps do this and it makes it more accurate now that there's up to M4 chips.
More context: 
Version support scope doc: https://docs.google.com/document/d/1xsR4L_sHdFjS1xAx5LEO5AJ1N9vrA17LCucF2Kmxtxo/edit?tab=t.0
Electron version support page for our electron version: https://github.com/electron/electron/blob/v37.2.2/README.md#platform-support  
Download center (where these versions are shown):
https://www.mongodb.com/try/download/compass

chore(download-center): update minimum versions listed in download center COMPASS-9596

---

.evergreen/functions.yml

Another attempt to de-flake these tests, I don't really have much ideas how to debug this more, since last week or so it seems like connecting to clusters is just way slower than it was before that. Bumping timeouts to see if this will help

chore(ci): increase timeout for compass-web with atlas tests again

---

packages/compass-connections/src/stores/connections-store-redux.ts
packages/compass-connections/src/utils/telemetry.spec.tsx
packages/compass-connections/src/utils/telemetry.tsx
packages/compass-telemetry/src/telemetry-events.ts

chore(connections): add error code cause chain to connection failed telemetry COMPASS-9527

---

packages/compass-data-modeling/src/components/import-diagram-button.tsx
packages/compass-data-modeling/src/services/open-and-download-diagram.ts
packages/compass-e2e-tests/tests/data-modeling-tab.test.ts

chore(data-modeling): change file extension COMPASS-9623

---

package-lock.json
packages/compass-telemetry/.eslintrc.js
packages/compass-telemetry/package.json
packages/compass-telemetry/src/experimentation-provider.tsx
packages/compass-telemetry/src/index.ts
packages/compass-web/src/index.tsx

[CLOUDP-333843](https://jira.mongodb.org/browse/CLOUDP-333843)
- Compass defines the CompassExperimentationProvider component and context interface
- Provider will accept useAssignment and assignExperiment utils as props from MMS
To re-use experimentation logic built on top of the Experiment SDK in MMS, we will allow mms to provide required hooks and callback methods to compass through a React-context-based dependency-injection pattern.
Compass will define an CompassExperimentationProvider interface, which MMS will provide the implementation functions for. This follows conventional React dependency injection patterns and allows Compass to define what it needs from MMS for its experimentation architecture.
Compass will define the experimentation provider in the compass-telemetry package …

feat: Compass Experimentation Provider CLOUDP-333843

---

package-lock.json
packages/compass-components/src/components/leafygreen.tsx
packages/compass-data-modeling/src/components/drawer/collection-drawer-content.tsx
packages/compass-e2e-tests/helpers/commands/connect-form.ts
packages/compass-e2e-tests/helpers/commands/get-input-by-label.ts
packages/compass-e2e-tests/helpers/commands/index.ts
packages/compass-e2e-tests/helpers/commands/save-favorite.ts
packages/compass-e2e-tests/helpers/commands/select-option.ts
packages/compass-e2e-tests/helpers/compass.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/package.json
packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
packages/compass-e2e-tests/tests/data-modeling-tab.test.ts
packages/compass-e2e-tests/tests/my-queries-tab.test.ts

Adding an e2e test which covers the relationship management via the side drawer:
- Click on a collection - sidebar opens
- Click on add relationship
- Fill in the form
--> Verify that the relationship is visible (on a collection AND on the diagram)
- Click edit relationship
- Make changes
--> Verify that the relationship has been updated (on a collection AND on the diagram)
- Delete the relationship
--> Verify that the relationship has been removed (from a collection AND from the diagram)
One interaction that we don't cover is the click directly on a relationship edge - which should open the relationship drawer. It would be nice to have this covered with the e2e test. Unfortunately, depending on the initial layout, the edge is too small to be reliably clickable by webdriver io. And moving …

chore: add e2e tests for relationship management COMPASS-9479

---

packages/compass-data-modeling/src/store/diagram.spec.ts
packages/compass-data-modeling/src/store/diagram.ts

This is enabling selection of fields that are nested under an array or a mixed type

fix: add relationship fields items and anyOf support COMPASS-9649

---

packages/compass-components/src/components/context-menu.tsx
packages/compass-context-menu/src/consts.ts
packages/compass-context-menu/src/context-menu-provider.tsx
packages/compass-context-menu/src/index.ts

stopPropagation doesn't work because the eventListener on window gets triggered first due to the capture option. I assume the capture was intentional and shouldn't be removed (correct me if I'm wrong @gagik ), but it's okay because we can just do this - ignore based on the target.
https://github.com/user-attachments/assets/9150cf89-53c7-4f5c-b881-af8319a27d30

fix: scrolling the context menu shouldn't close it COMPASS-9584

---

packages/compass-data-modeling/src/components/diagram-editor-toolbar.spec.tsx
packages/compass-data-modeling/src/components/diagram-editor-toolbar.tsx
packages/compass-data-modeling/src/components/diagram-editor.tsx
packages/compass-data-modeling/src/store/analysis-process.ts
packages/compass-data-modeling/src/store/diagram.ts
packages/compass-data-modeling/src/utils/nodes-and-edges.tsx
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/data-modeling-tab.test.ts

E2E tests diagram - drawer interactions will be a follow up, I'll add a note to test this scenario as well 
https://github.com/user-attachments/assets/4d2c86b6-e15c-42a2-b100-037537d6c9a6

feat(compass-data-modeling): add relationship via dragging COMPASS-9332

---

packages/compass-data-modeling/src/components/drawer/collection-drawer-content.tsx

This patch removes custom wiring between useState / useLayoutEffect / onChange / onBlur callbacks to control the input in favor of a shared hook that we use for another similar field already. Validation is still controlled from the outside for now
@Anemy just wanted to clarify my point: you don't really need to update the hook to also handle the validation (although you definitely can) to already minimize the amount of similar code that can be shared, the amount of extra useEffects and extra wiring will just grow the more new fields we will be adding there

chore(data-modeling): use change on blur hook for collection name for consistency

---

packages/compass-e2e-tests/tests/data-modeling-tab.test.ts

Looking at the following flakes:
https://parsley.mongodb.com/test/10gen_compass_main_test_packaged_app_macos_14_x64_test_packaged_app_2_3883a58f02d467a07462a326fe2559b0cb672010_25_08_19_16_08_15/0/a8352028097e38aa69aa7787580e602d?bookmarks=0,8&shareLine=0
https://parsley.mongodb.com/test/10gen_compass_main_test_packaged_app_rhel_test_packaged_app_2_37f34fac1b921225b14697730c0564ab569113ad_25_08_18_19_43_43/0/f595bc23473e1bb5ae834dd14010291d?bookmarks=0,14&shareLine=0

chore(e2e-tests): wait for data modeling components in tests

---

.github/workflows/update-dependencies.yaml

You can use `${{ matrix.<value> }}` in most job options, but not in `if`, so my initial attempt to make it work for selected values in workflow_dispatch failed. The only way around it is to [build the whole matrix dynamically in another job](https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/run-job-variations#using-an-output-to-define-two-matrices), it's a bit messy, but should work

fix(ci): build matrix value dynamically based on optional dispatch input

---

scripts/update-dependencies.js

Our leafygreen updates currently require this as the peer dependency doesn't get affected by the `overrides` configuration that we added

chore(scripts): allow to pass force flag when updating via script

---

packages/compass-e2e-tests/tests/data-modeling-tab.test.ts

The relationship management tests seems to be flaky in CI. I can't reproduce it locally, and I don't see anything wrong in the screenshot so I'm just adding a couple of waits around where it gets stuck. If nothing else, it might help us locate the problem.

chore: add wait for flaky relationship management test

---

packages/compass-query-bar/src/components/query-history/save-query-form.tsx

Seems like an old bug that was causing a race condition that would sometimes lead to a recent item not being removed when converting it to a favorite one
Draft because we need to add a test also

fix(query-bar): prevent form submit from propagating COMPASS-9637

---

packages/compass-crud/src/stores/crud-store.ts
packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
packages/compass-telemetry/src/telemetry-events.ts

As discussed, we want to add telemetry for this right away (even if the natural option will go away soon)

chore(query-bar): add telemetry for default sort COMPASS-9763

---

packages/compass-data-modeling/src/components/drawer/diagram-editor-side-panel.spec.tsx
packages/compass-data-modeling/src/components/drawer/field-drawer-content.tsx
packages/compass-data-modeling/src/store/apply-edit.ts
packages/compass-data-modeling/src/store/diagram.ts
packages/compass-data-modeling/src/utils/schema-traversal.spec.tsx
packages/compass-data-modeling/src/utils/schema-traversal.tsx
packages/compass-data-modeling/test/fixtures/data-model-with-relationships.json

This is the last functional part (e2e tests and clean up to follow). 
- I'm not sure if we need to store the old field schema, keeping it here because it didn't occur to me to question this in tech design before, Rhys is not here atm, and it's usually easier to ignore than deal with missing data.
- We're doing a cleanup of parts of schema when the new types no longer support them, but we're not warning the user of it.  That means if the user wants to undo a change, it's better to do it with an actual undo, not just change the types back (this won't bring back the types). While some are visible on the diagram (nested fields disappear), others are not (we don't visualise array types, or required fields). I wouldn't skip the cleanup, as we could end up with weird messy schemas, but this …

feat(compass-data-modeling): update field type COMPASS-9659

---

packages/compass-connections/src/components/connection-status-notifications.tsx

COMPASS-9787
* Clicking either `Review` or `Debug for me` now closes the toast. This is because if you click `Review` it opens a modal and modals in combination with toasts are just broken.
* Added `word-break: break-word` so that crazy long "words" in error messages don't break the toast's layout.
before:
after:

fix(compass-connections): connection toast fixes COMPASS-9787

---

packages/compass-assistant/src/compass-assistant-drawer.tsx
packages/compass-assistant/src/compass-assistant-provider.spec.tsx

We had a PR for this which ended up only applying to entry points, so this adds this to the sidebar itself.

chore(compass-assistant): hide the drawer if AI features are disabled

---

packages/compass-assistant/src/index.tsx
packages/compass-assistant/src/prompts.ts
packages/compass-web/src/entrypoint.tsx
packages/compass/src/app/components/home.tsx

We might still change this further and just have two separate instructions prompts so we have more flexibility in editing them, but at least this puts what we have so far together.

chore(compass-assistant): move the two appNameForPrompt values together

---

packages/compass-e2e-tests/tests/in-use-encryption.test.ts

Tested locally like this:
```bash
npm run stop-servers # in case you have some running
MONGODB_RUNNER_VERSION=8.2.0-rc4-enterprise npm run start-servers
DEBUG=hadron*,mongo*,compass*,xvfb-maybe* npm run test -- --disable-start-stop
```
We don't have 8.2 runners in CI yet, but we do test latest-alpha-enterprise which maps to `MongoDB 8.3.0-alpha0-1099-g0f7021e Enterprise` at the time of writing.

chore(compass-e2e): add e2e tests for prefixPreview, suffixPreview, substringPreview QE features COMPASS-9752

---

scripts/update-dependencies-config.js

See COMPASS-9852 for details. For the time being we can lock the update version so that at least update script can keep us on latest electron@37 version in case there are security fixes

chore(scripts): fix electron update version to 37 temporarily

---

configs/testing-library-compass/src/index.tsx
packages/compass-components/src/components/content-with-fallback.spec.tsx
packages/compass-components/src/components/context-menu.spec.tsx
packages/compass-components/src/components/context-menu.tsx
packages/compass-components/src/components/workspace-tabs/tab.spec.tsx
packages/compass-context-menu/src/context-menu-provider.tsx
packages/compass-web/sandbox/index.html

When embedded as the data-explorer, the right click menu is rendered inside a container with `position: relative;`.
When the context menu anchor is positioned absolute, it will be relative to that container.
- Update the anchor to be positioned ["fixed"](https://developer.mozilla.org/en-US/docs/Web/CSS/position#fixed):
> If the position property is `fixed`, the containing block is established by the [viewport](https://developer.mozilla.org/en-US/docs/Glossary/Viewport) (in the case of continuous media) or the page area (in the case of paged media).
- Add a container div with `display: contents` wrapping the `children` of the `ContextMenuProvider`, to which the "root" "contextmenu" listener gets added.
I tested this locally by modifying [the `compass-web` …

fix(context-menu): position anchor and prevent escaping container COMPASS-9673

---

packages/compass-assistant/src/compass-assistant-provider.tsx
packages/compass-assistant/src/prompts.spec.ts
packages/compass-assistant/src/prompts.ts
packages/compass-assistant/test/entrypoints/explain-plan.ts
packages/compass-explain-plan/src/components/explain-plan-modal.tsx
packages/compass-explain-plan/src/stores/explain-plan-modal-store.spec.ts
packages/compass-explain-plan/src/stores/explain-plan-modal-store.ts

Will now distinguish between queries and aggregations in explain plan prompting.

chore(compass-assistant): differentiate between aggregations and queries in explan plan entry point COMPASS-9855

---

packages/compass-assistant/src/compass-assistant-provider.spec.tsx
packages/compass-assistant/src/components/assistant-chat.spec.tsx
packages/compass-assistant/src/components/assistant-chat.tsx

Updates the placeholder text and disclaimer

chore(compass-assistant):  update the placeholder text and disclaimer COMPASS-9836

---

packages/compass-assistant/src/compass-assistant-provider.tsx
packages/compass-assistant/src/components/assistant-chat.spec.tsx
packages/compass-assistant/src/components/assistant-chat.tsx
packages/compass-telemetry/src/telemetry-events.ts

Some improvements to the sources of entry points sent with feedback and when confirming.

chore(compass-assistant): keep track of confirmation and entry point sources

---

packages/compass-data-modeling/src/components/diagram-editor.tsx

This is a good practice in general to help reduce unnecessary re-rendering.
It's also mentioned in react flow's docs: https://reactflow.dev/learn/advanced-use/performance#memoize-functions 
We already do this in the diagramming package: https://github.com/mongodb-js/diagramming/blob/e5edc84fcc4fb6c960333c690cf0e291cd75c6c3/src/components/canvas/canvas.tsx#L146

chore(data-modeling): memoize functions passed to diagramming

---

packages/compass-data-modeling/src/components/diagram-editor.spec.tsx
packages/compass-data-modeling/src/components/diagram-editor.tsx
packages/compass-data-modeling/src/store/diagram.ts
packages/compass-e2e-tests/helpers/selectors.ts
packages/compass-e2e-tests/tests/data-modeling-tab.test.ts

Info banner shows only the first time (when the diagram is newly created) and can be closed.

feat(compass-data-modeling): add info banner COMPASS-9773

---

packages/compass-e2e-tests/tests/atlas-cloud/collection-ai-query.test.ts
packages/compass-generative-ai/src/components/ai-optin-modal.spec.tsx
packages/compass-generative-ai/src/components/ai-optin-modal.tsx
packages/compass-preferences-model/src/compass-web-preferences-access.ts
packages/compass-preferences-model/src/preferences-schema.tsx
packages/compass-web/sandbox/index.tsx
packages/compass-web/sandbox/sandbox-atlas-sign-in.tsx
packages/compass-web/src/preferences.tsx

CLOUDP-346490
Looks like we didn't follow having the `enableGenAISampleDocumentPassing` preference derived `enableGenAISampleDocumentPassingOnAtlasProject` [as it was originally intended](https://docs.google.com/document/d/1to8ghEzI600WxQm08T5nzNfFLkeLDx55EtYxDb4Lvno/edit?tab=t.0#bookmark=id.d6b8bffb4yih).  This pr r. That should simplify things.
This will require we update the preferences we pass in the props to `CompassWeb`:
https://github.com/10gen/mms/blob/8552f2bc333a928a2c161e24a768f14cd60d02c6/client/packages/project/dataExplorerCompassWeb/router.tsx#L401

fix(preferences): use one enableGenAISampleDocumentPassing preference CLOUDP-346490

---

packages/compass-assistant/src/compass-assistant-drawer.tsx
packages/compass-assistant/src/compass-assistant-provider.tsx
packages/compass-assistant/src/components/assistant-chat.tsx
packages/compass-components/src/components/drawer-portal.tsx

[chore: remove dot](https://github.com/mongodb-js/compass/commit/2110486f71c9f89e95abb6ad4c4a144daa339006)
[fix overflowing and centered: use break-word and width: 100](https://github.com/mongodb-js/compass/commit/862febaf6a8714440d5e61542b736203de422195) [COMPASS-9882](https://jira.mongodb.org/browse/COMPASS-9882) [COMPASS-9883](https://jira.mongodb.org/browse/COMPASS-9883)
[chore: scale down the title when making the drawer narrow](https://github.com/mongodb-js/compass/commit/5595f71f4461606d4d6c90e9b2b98ca21d7f649f)
[chore: clear error on chat clear](https://github.com/mongodb-js/compass/pull/7373/commits/561b2fd021ad3902669874a520ffa6585110ffc1) COMPASS-9888

chore(compass-assistant): fix content overflow and resizing of drawer COMPASS-9882 COMPASS-9883 COMPASS-9888

---

packages/compass-assistant/src/components/assistant-chat.spec.tsx
packages/compass-assistant/src/components/assistant-chat.tsx

Adds this to both message sending and entry points as it seems to make sense in both cases. 
TBC by design.

chore(compass-assistant): add auto-scroll to bottom with entry points and message sending COMPASS-9887

---

packages/compass-assistant/src/components/assistant-chat.tsx
packages/compass-components/src/components/compass-components-provider.tsx
packages/compass-components/src/components/drawer-portal.spec.tsx
packages/compass-components/src/components/drawer-portal.tsx
packages/compass-telemetry/src/telemetry-events.ts
packages/compass-web/src/entrypoint.tsx
packages/compass/src/app/components/home.tsx

This adds open / close tracking for all drawer sections whenever you switch between sections (like via the toolbar or hooks) or when you open/close the drawer or when sections disappear.

feat(compass-assistant): track opening and closing the drawer sections COMPASS-9884

---

scripts/create-workspace.js

Small follow-up to restructuring of tsconfig files

chore(scripts): adjust create-workspace script for new tsconfig structure

---

packages/compass-crud/src/components/crud-toolbar.tsx

Given the different size between refresh button and loading spinner, a flicker was visible when switching between states. This PR fixes that flickering.
**Before:**
**After:**
https://github.com/user-attachments/assets/bc26c85b-8b1a-47d8-b53c-eedafd4f54e7
There's still one flickering because when we jump into the loading state, we reset the counter until it's calculated again, causing the page size selector to reflow and the counter to hide/show. Any ideas on how to improve this?

fix(crud-toolbar): flickering in refresh button COMPASS-8138

---

packages/compass-assistant/src/prompts.ts

The prompt for the user to confirm sharing the explain plan lacked the period at the end.
Now it does not anymore.

chore: period at the end of explain plan confirmation prompt

---

packages/compass-assistant/src/compass-assistant-provider.spec.tsx
packages/compass-explain-plan/src/components/explain-plan-modal.spec.tsx
packages/compass-preferences-model/src/feature-flags.ts

This moves the ai assistant feature flag from development to released so that the next beta/ga has the feature enabled.

feat(compass-assistant): move the AI assistant feature from development to released COMPASS-9753

---

.evergreen/buildvariants-and-tasks.in.yml
.evergreen/buildvariants-and-tasks.yml

So that we can mark it as required in PR checks without making the whole publish task required

chore(ci): split static analysis report into its own build variant

---

packages/mongodb-query-util/src/bson-equal.spec.ts
packages/mongodb-query-util/src/bson-equal.ts

fix: don't crash when using bson-equal to compare against null COMPASS-9924

---

configs/eslint-config-compass/index.js
packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/match/match-group-form.tsx
packages/compass-assistant/src/components/assistant-chat.tsx
packages/compass-assistant/src/components/confirmation-message.tsx
packages/compass-components/src/components/actions/item-action-group.tsx
packages/compass-components/src/components/bson-value.tsx
packages/compass-components/src/components/document-list/element.tsx
packages/compass-components/src/components/file-picker-dialog.tsx
packages/compass-components/src/components/file-selector.tsx
packages/compass-components/src/components/icons/logo-icon.tsx
packages/compass-components/src/components/select-list.tsx
packages/compass-components/src/components/workspace-tabs/tab.tsx
packages/compass-connections-navigation/src/with-status-marker.tsx
packages/compass-explain-plan/src/components/explain-tree/tree-layout.tsx
packages/compass-global-writes/src/components/create-shard-key-form.tsx
packages/compass-workspaces/src/components/workspace-tab-context-provider.tsx

Turns on the `@mongodb-js/compass/no-inline-emotion-css` rule from warn to error. Also updates some places we were dynamically passing objects to use constants. Some of it is a probably a bit of overkill, but I don't think it'll hurt.

chore(lint): turn on dynamic css rule, move more styles to constants

---

packages/compass-components/src/components/inline-definition.tsx
packages/compass-workspaces/src/index.spec.tsx
packages/data-service/src/data-service.ts
packages/data-service/src/instance-detail-helper.ts
packages/data-service/src/run-command.ts
packages/database-model/index.d.ts
packages/database-model/lib/model.js
packages/databases-collections-list/src/collections.tsx
packages/databases-collections-list/src/databases.tsx
packages/databases-collections-list/src/index.spec.tsx

This reverts commit e8c45e553f1f9d7bc863d19bbfce7015af3b80a3. (https://github.com/mongodb-js/compass/pull/7357)
Turns out `freeStorage: 1` is a footgun:
> If the instance has a large number of collections or indexes, obtaining free space usage data may cause processing delays. To gather dbStats information without free space details, either set freeStorage to 0 or do not include the field.

Revert "feat(database-collections): add uncompressed data stat field COMPASS-7691 (#7357)"
